### ISSUE TITLE
Alethzero experiences full crash on import of geth json wallet

### ISSUE THREAD

**Issue by emansipater** [ethereum/webthree-umbrella#10]
Tried to import json wallets from geth, which resulted in a full crash.  I understand if geth wallets aren't supported, but there should be _some_ kind of error handling on the file parsing so this (or any other file format error) doesn't crash the whole client.  Version 0.9.92 prerelease binary on ubuntu 14.04

**Comment by bobsummerwill** [comment]
Hey Jeff!
I am triaging.   Seem to remember seeing a PR related to this, which may or may not have made it into the code-base yet.    I will investigate.
Best wishes!

**Comment by bobsummerwill** [comment]
Adding @corsaro1.

**Comment by chriseth** [comment]
Should be fixed now. Please re-open if it is not.
