### ISSUE TITLE
Unable to locate package libjson-rpc-cpp-dev

### ISSUE THREAD

**Issue by SCBuergel** [ethereum/webthree-umbrella#104]
I am following the [build instructions](https://github.com/ethereum/webthree-umbrella/wiki/Building-on-Ubuntu), preparing to build on Ubuntu 15.10 and get the following error when attempting to load packages for the build:

```
Unable to locate package libjson-rpc-cpp-dev
```

When deleting that package from the list I get another error in a package that (I think) is critical:

```
The following packages have unmet dependencies:
 llvm-3.7-dev : Depends: libjsoncpp0 (>= 0.6.0~rc2) but it is not installable
```

**Comment by chriseth** [comment]
Did you do `sudo apt-get install libjsoncpp-dev`? Is `Unable to locate...` an error that follows from an `apt-get install` call?

**Comment by SCBuergel** [comment]
The `Unable to locate...` comes from `sudo apt-get -y install build-essential git cmake libboost-all-dev libgmp-dev libleveldb-dev libminiupnpc-dev libreadline-dev libncurses5-dev libcurl4-openssl-dev libcryptopp-dev libjson-rpc-cpp-dev libmicrohttpd-dev libjsoncpp-dev libargtable2-dev llvm-3.7-dev libedit-dev mesa-common-dev ocl-icd-libopencl1 opencl-headers libgoogle-perftools-dev qtbase5-dev qt5-default qtdeclarative5-dev libqt5webkit5-dev libqt5webengine5-dev ocl-icd-dev libv8-dev libz-dev`

> Did you do `sudo apt-get install libjsoncpp-dev?`

No I did not (though libjsoncpp-dev is part of the long list of packages above). However, now I did run this separately (all ok), but still, when running the entire command I get the same error:

```
# sudo apt-get -y install build-essential git cmake libboost-all-dev libgmp-dev libleveldb-dev libminiupnpc-dev libreadline-dev libncurses5-dev libcurl4-openssl-dev libcryptopp-dev libjson-rpc-cpp-dev libmicrohttpd-dev libjsoncpp-dev libargtable2-dev llvm-3.7-dev libedit-dev mesa-common-dev ocl-icd-libopencl1 opencl-headers libgoogle-perftools-dev qtbase5-dev qt5-default qtdeclarative5-dev libqt5webkit5-dev libqt5webengine5-dev ocl-icd-dev libv8-dev libz-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'zlib1g-dev' instead of 'libz-dev'
E: Unable to locate package libjson-rpc-cpp-dev
```

**Comment by bumbar1** [comment]
It says that package was renamed in 15.10+:

> JSON-RPC dev has been renamed in 15.10, so use the right version:
> 
> sudo apt-get -y install libjsonrpccpp-dev

**Comment by bobsummerwill** [comment]
Thanks, @bumbar1!
Does that work for you, @SCBuergel?
Looks like the instructions show that too now, though they not have done at the time.
