### ISSUE TITLE
Some notes about MIX

### ISSUE THREAD

**Issue by winsvega** [ethereum/webthree-umbrella#105]
So I tried Mix a little bit. Here is some notes:

Screenshots(https://drive.google.com/a/ethdev.com/folderview?id=0B3Yr0ZZNlHv2RjBDN2dyWThuNkU&usp=sharing)

1) 
Start the mix Mix. All windows are empty. 
See a GENESIS BLOCK caption with a button right to it saying "Edit Starting Parameters".
This button is not responding when I click it.

1.a) A little bit up to the Genesis Block caption there are 4 buttons. 
It seems to be inactive but it does not look like so. (it is colored)

1.b)
If i press a \/ button I could get even more of this inactive buttons.

1.c) Then below is a search field. Does not show any results when I try it. 
at least it should respond with something like "not found"

2) 
The bar in the middle with \/ is empty and it opens a window without edges.
Here is a screenshot bademptywindow.png

3) Scenarious managment window could be opened before the project loaded.
this result in empty interface (scenariousManagmentEmpty.png)

I think all those inactive interfaces could be hidden before the actuall initialization.
Otherwise it is unclear for the user why it is not responding and why there are so many inactive unusable buttons.

Edit Starting Parameters Window
4)
Add new account icon (in window Edit Starting Parameters) looks like "Edit existing account" its confusing.

5)
If I press add new account. it will appear in Accounts list and Miner list.
Then if I press delete account. It will be removed only from Accounts list, leaving Miner list with this account
untill I reopen Block Starting Parameters window.

6) 
It is unclear what would exactly be copied to clipboard by button "Copy to Clipboard" that is right next to "Add new account" button.
Perhaps it is better to ask user for a json file to save on that function. (Otherwise private keys would be stored in keyboard buffer)
Also button icons in general has diffrent size (width/height)

It might be good to add a notification popup or something saying. "Account address has been copied to clipboard" 
So the user would felt that this button works.

7) 
Might be good to have (?) popup information clarifying what does spme field means 
Such as Amount in Edit Transaction window. it is unclear that v(unit256) is a function argument, when Amount is not.
But this two fields look like  the same.

8)
Not quite sure what I did but there was a moment when I pressed Add New bloc a couple of times 
then tried to delete a scenario by pressing delete scenario button and nothing happened untill I created another scenario and then switched back to the default scenario.

9)
In history slide down. It is unclear what button Deploy do. 
I pressed it a couple of times and nothing happens. It could be either pressed down or up

10)
So I couls add a couple of empty blocks with no transactions. But I cant edit them or try to insert o move transactions between it.
only rebuild scenario button would delete empty blocks. by the way why?

11)
Button New account right to add block seems to be adding a new account to the genesis block. 
It should be inside Edit Starting Parameters window then.

12)
Window User Account and Contract Account are always empty even after deploy and running a web3 application.
It is unclear what are they used for. 

A suggestion would be to implement a blockchain explorer. So it would be possible to navigate the state and see what are the storage of each contract right now. I see the query was set. And see pending transactions for it. But I cant see how the contract is stored in blockchain. eg. what is exactly the code assigned to the contract. its nonce and balance. and storage.

13) 
There are File->New Project/Open Project.
Where is the Save Project?

**Comment by yann300** [comment]
pr created for this: https://github.com/ethereum/mix/pull/145

**Comment by chriseth** [comment]
@yann300 can this be closed? If not, please create separate issues for all the items.
