### ISSUE TITLE
OS X (Mavericks) - Unable to open Alethone and Alethzero on Mac OSX 10.9.5

### ISSUE THREAD

**Issue by taotech4096** [ethereum/webthree-umbrella#106]
The icon at the dock just "jumps" and then disappears.

**Comment by bobsummerwill** [comment]
Hey @taotech4096,
What version of these tools do you have which this is happening for?
Did you `brew install`, or build your own?
Have you tried rebuilding?

**Comment by taotech4096** [comment]
Hey Bob,
Thanks for your reply. I did brew install... well i followed the instructions but i can´t remember how i did it. (Me=Average user).. How can i check the version of the tools? 
Where can i find the instructions to rebuild it?
Thanks!

**Comment by bobsummerwill** [comment]
No problem!
Here are the instructions - https://github.com/ethereum/webthree-umbrella/wiki/Building-on-OS-X.

You should probably be able to get away with ...

```
brew update
brew upgrade
```

And then https://github.com/ethereum/webthree-umbrella/wiki/QTBUG-50155-workaround

And then ...

```
brew reinstall cpp-ethereum --with-gui
```

**Comment by taotech4096** [comment]
Nice! I will try this steps and let you know how it goes.
Thanks!

**Comment by bobsummerwill** [comment]
Thanks, @taotech4096!

**Comment by bobsummerwill** [comment]
Did you try again since, @taotech4096?

**Comment by taotech4096** [comment]
I tried now to run-  brew update - but i get error message. I just updated to El Capitan.

brew update
Error: The /usr/local directory is not writable.
Even if this directory was writable when you installed Homebrew, other
software may change permissions on this directory. Some versions of the
"InstantOn" component of Airfoil are known to do this.

Any suggestions? Should i unistall homebrew and install it again? could this affect my Mist wallet?

**Comment by taotech4096** [comment]
I was impatient and i uninstall homebrew and install it again. Now Mist doesn´t open... :( 
Could you help me out with this one?

**Comment by bobsummerwill** [comment]
Hey @taotech4096.
So you are actually on Mavericks, aren't you?   Could you updated to Yosemite or El Capitan?

You're in "undefined territory".

**Comment by bobsummerwill** [comment]
So yeah ... I'm afraid you're on an unsupported OS X version.   Please update :-)   Best wishes.
