### ISSUE TITLE
CMake error: No such file or directory: PersonalFace.h.tmp

### ISSUE THREAD

**Issue by 5chdn** [ethereum/webthree-umbrella#109]
i can not compile webthree-umbrella latest `develop` because cmake is missing several `*.tmp` files, here are the logs https://gist.github.com/5chdn/ef04a26216e12885eb5e

i'm on archlinux kernel 4.2.5-1-ARCH x86_64 GNU/Linux. CMake version 3.4.1/Linux.

please check the logs and let me know if you need more details.

**Comment by LefterisJP** [comment]
It builds fine for me. Can you tell me what is the version of your `libjson-rpc-cpp`?

I would suggest using

```
aur/libjson-rpc-cpp-git 20150220-1 [installed: 20150829-1] (2)
    C++ framework for json-rpc 1.0 and 2.0
```

**Comment by 5chdn** [comment]
Indeed, `aur/libjson-rpc-cpp 0.6.0-1` didnt work. the latest `-git [installed: 20150829-1]` version does fix this issue. Thanks for pointing out.

**Comment by bobsummerwill** [comment]
Thanks, @LefterisJP!
