### ISSUE TITLE
AlethOne Crashes while Pool Mining

### ISSUE THREAD

**Issue by psimaster** [ethereum/webthree-umbrella#11]
gpuminer0 :-( Couldn't submit - JSONRPC connectivity problem.

Win 7 64 bit
NVidia GTX 660 TI

**Comment by bobsummerwill** [comment]
Hey @psimaster!
Just triaging bugs.   This is a really old one.
I'm guessing this isn't hindering you anymore, eh?
I'm thinking we just close it, unless you still want to try to get it going again?

**Comment by destenson** [comment]
I am seeing this currently with the latest version v1.2.1 on Windows 10.

**Comment by destenson** [comment]
Please re-open this issue. It is currently occurring for me. Here is a log of the output: [poolmining.log](https://files.zenhub.io/56dd476393fd4909417cd06b)
(uploaded using [**ZenHub.io**](http://www.zenhub.io))

It apparently occurs when submitting a found solution. Half of the time (perhaps more) when it submits a solution, this problem happens and the solution is not received by the server.

**Comment by chriseth** [comment]
@destenson which version of AlethOne is that? I think we at least fixed the following problem:

```
QObject::connect: Cannot queue arguments of type 'eth::EthashProofOfWork::Solution'
(Make sure 'eth::EthashProofOfWork::Solution' is registered using qRegisterMetaType().)
```

if not also the other one.

**Comment by destenson** [comment]
v1.2.1 on Windows 10 from https://build.ethdev.com/cpp-binaries-data/release-1.2.1/Ethereum.exe. I tried with 2 different mining pools with the same results.

3/4 of the way down ethpool.org, it says:

> If you receive frequent "JSON-RPC Problem" errors try to increase your --farm-recheck value.

Perhaps that parameter from ethminer should included in AlethOne as well?

**Comment by destenson** [comment]
When I try to do a post-mortem with Visual Studio, it says:

> Unhandled exception at 0x00007FFCAFEEE6DC (ntdll.dll) in AlethOne.exe: 0xC0000374: A heap has been corrupted (parameters: 0x00007FFCAFF422B0).

The call stack is:

>   ntdll.dll!RtlReportCriticalFailure()   Unknown
>   ntdll.dll!RtlpHeapHandleError()    Unknown
>   ntdll.dll!RtlpLogHeapFailure() Unknown
>   ntdll.dll!RtlpReAllocateHeapInternal()  Unknown
>   ntdll.dll!RtlReAllocateHeap()   Unknown
>   msvcr120.dll!00007ffc914876bb() Unknown
>   AlethOne.exe!00007ff65cedc416() Unknown
>   libcurl.dll!00007ffca8baaad6()  Unknown
>   libcurl.dll!00007ffca8bbc479()  Unknown
>   libcurl.dll!00007ffca8bbb75b()  Unknown
>   libcurl.dll!00007ffca8bc3496()  Unknown
>   libcurl.dll!00007ffca8bc20d5()  Unknown
>   libcurl.dll!00007ffca8bbd3bb()  Unknown
>   libcurl.dll!00007ffca8bbd2d0()  Unknown
>   AlethOne.exe!00007ff65cedc20c() Unknown
>   AlethOne.exe!00007ff65cedc60d() Unknown
>   AlethOne.exe!00007ff65cedc569() Unknown
>   AlethOne.exe!00007ff65ccefaf1() Unknown
>   AlethOne.exe!00007ff65ccf16e3() Unknown
>   AlethOne.exe!00007ff65ccef039() Unknown
>   AlethOne.exe!00007ff65ced86c7() Unknown
>   AlethOne.exe!00007ff65cedb310() Unknown
>   AlethOne.exe!00007ff65cedb05c() Unknown
>   AlethOne.exe!00007ff65cf5de9e() Unknown
>   AlethOne.exe!00007ff65cedbc0f() Unknown
>   AlethOne.exe!00007ff65cf0873b() Unknown
>   AlethOne.exe!00007ff65cf0891d() Unknown
>   msvcp120.dll!00007ffc915cd24c() Unknown
>   msvcr120.dll!00007ffc91444f7f() Unknown
>   msvcr120.dll!00007ffc91445126() Unknown
>   kernel32.dll!00007ffcaee38102() Unknown
>   ntdll.dll!RtlUserThreadStart()  Unknown

Unfortunately, there are no debug symbols. I'll post more details once I am able to make, run and debug my own builds.

**Comment by JCBauza** [comment]
I am having the same issue. I am running Windows 10 and every now and then it crashes and I get a "AlethOne.exe stopped working" message.

**Comment by JCBauza** [comment]
The last thing on the terminal reads "JSON-RPC problem. Probably couldn't connect. Retrying in 2..."

**Comment by philbert** [comment]
I'm using the GUI version of AlethOne 1.1.4 on OS X Yosemite 10.10.5.
Solo Mining seems to work ok but if you click on Pool Mining the application crashes without further explanation why.
I guess there is a log file somewhere that might explain more?

**Comment by bobsummerwill** [comment]
Everybody ... so I'm afraid we're calling time on AlethOne and will be removing it in the near future.

"One Click Miner" was a great aim, but the messy reality with all the GPU variance, etc, is far from that dream.    We don't have the resources to support it anymore.

So I would suggest that you all look at command-line mining, and also look at Genoil's cpp-ethereum fork for the CUDA miner, which seems better maintained than our own ethminer instance.

Sorry.   This doesn't make us happy either :-(
