### ISSUE TITLE
Please update webthree-helper

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#110]
Please can webthree-umbrella be updated to include the following commit?   Thanks!

https://github.com/ethereum/webthree-helpers/commit/88af602

This one is a pig to work around in the cross-builds.

**Comment by LefterisJP** [comment]
I updated all of webthree-umbrella to latest develop. Should also include this commit.

**Comment by bobsummerwill** [comment]
Many thanks!   Welcome back :-)

FYI ... I'm going to be creating another round of PRs in the next day or two.    They should all be pretty simple and mergeable.   I'm guessing based on recent activity that you and @winsvega are the only candidates for merging them right now?   Or @chriseth?

**Comment by bobsummerwill** [comment]
More cross-build clean-up oddments.

**Comment by LefterisJP** [comment]
I can also take a look but generally the rule is that at least 2 people should "approve" PRs before they are merged unless it's a quick build fix or something along those lines.

**Comment by bobsummerwill** [comment]
I think they're all likely to be pretty trivial build fixes.   No C++ edits yet.
