### ISSUE TITLE
Building etherminer from source fails Arch Linux

### ISSUE THREAD

**Issue by CyberCriminal0** [ethereum/webthree-umbrella#111]
While building I get the following error while at the step Building CXX object libethereum/libethashseal/CMakeFiles/ethashseal.dir/Ethash.cpp.o

libethereum/libethashseal/CMakeFiles/ethashseal.dir/build.make:206: recipe for target 'libethereum/libethashseal/CMakeFiles/ethashseal.dir/Ethash.cpp.o' failed
make[2]: **\* [libethereum/libethashseal/CMakeFiles/ethashseal.dir/Ethash.cpp.o] Error 1
CMakeFiles/Makefile2:1263: recipe for target 'libethereum/libethashseal/CMakeFiles/ethashseal.dir/all' failed
make[1]: **\* [libethereum/libethashseal/CMakeFiles/ethashseal.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: **\* [all] Error 2

Any help would be greatly appreciated.

**Comment by LefterisJP** [comment]
Please give bigger output as this provides no actual compile error.

**Comment by oed** [comment]
I have the same problem. Output here: http://pastebin.com/3RNAdyZj

**Comment by 5chdn** [comment]
@oed is on archlinux probably and his comment belongs to #108 issues with recent boost 1.60

@Jheguy2 might face the same issue as #108 since he also claims to run archlinux. boost 1.60 was released several weeks ago. 

please gather in #108 if its the issue.

**Comment by bobsummerwill** [comment]
Looks like this was addressed by other changes.
