### ISSUE TITLE
bug report : release branch crash,  when eth attach connect to 8545

### ISSUE THREAD

**Issue by smartbitcoin** [ethereum/webthree-umbrella#113]
1. how to re-create. 

in ubuntu 15.10,  gcc 5.2
console A:

> ./eth -j 

in another console B:

> eth attach 

then eth in console A crash.
1. why.

EthashClient.cpp 
line 36, 
<code>EthashClient\* dev::eth::asEthashClient(Interface\* _c)</code>
will bypass the initialize of 
<code>mutable std::unordered_map<h256, std::pair<u256, std::chrono::steady_clock::time_point>> m_externalRates={}; </code>
in EthashClient.h.

when eth attach called, 
u256 EthashClient::externalHashrate() const 
function 
call m_externalRates.begin()   , which is not initialized.
1. how to fix.
   you know how!

![image](https://cloud.githubusercontent.com/assets/5984485/12099720/438fc638-b2f8-11e5-8a51-fa15865bcf8a.png)

**Comment by chriseth** [comment]
Most likely fixed by https://github.com/ethereum/libethereum/pull/163

**Comment by smartbitcoin** [comment]
Patched temperory by libethereum b86467cd58605363d689ccd7868fce59cda4303f
