### ISSUE TITLE
Solidity Compiler v1.1 'Error: Successor Block Not Found' 

### ISSUE THREAD

**Issue by CrackerHax** [ethereum/webthree-umbrella#120]
Version: 0.1.1-cb61d09d/Release-Windows/msvc/JIT
Using the latest version of Mix (from windows pre-compiled Ethereum binary) on Windows 10

```
uint hello;
function setHello(uint _hello)
{
    if(_hello > 0)    // If statement causes Successor Block error
        hello = 1;
}
```

**Comment by yann300** [comment]
which is the version of Mix you use? is this from the release?
I tried from develop branch, I don't have any compilation error for this code.

**Comment by CrackerHax** [comment]
Yes from the last pre-compiled binary release (November 2014). Windows 10.

That was not the only problem. The cursor would disappear after every character you typed too. I have since compiled it myself and it works fine though.

**Comment by bobsummerwill** [comment]
Is there much value in keeping this issue open, given that it is reporting specific issues in an old prebuilt binary?

Perhaps we would be better closing this one, in favor of a new issue saying "We could really use a new point release for the C++ client", which may or may not correspond to Homestead.

Just getting to a new (1.2?) release for Homestead probably makes the most sense, and to target stable binary releases for all platforms at that point.

**Comment by chriseth** [comment]
Yes, let us try to produce new binaries quick.
