### ISSUE TITLE
Windows 10 Compiles and Installs Fine but Nothing Runs

### ISSUE THREAD

**Issue by CrackerHax** [ethereum/webthree-umbrella#121]
**\* Resolved: Add cpp-ethereum directory to Avast exclusions. Apparently Avast will only play well with pre-compiled binaries. ***

Following the Windows instructions.. MSVC 2013 with Windows 7 SDK, 64-Bit

Everything compiles fine, installs fine but when I try to run ANY of the executables all I get is an "hourglass" (no console or anything). The process won't even show up in the task manager, but if I try to delete the file, windows says it is in use and cannot be deleted.

**Comment by bobsummerwill** [comment]
These are the instructions:   https://github.com/ethereum/webthree-umbrella/wiki/Building-on-Windows
And this is occurring on a Windows 10 box.
I am just attempting to replicate this issue on a Surface Pro 3.
Thanks for the report, @CrackerHax.   Stay tuned!

**Comment by bobsummerwill** [comment]
@CrackerHax reports that the prebuilt binaries (https://github.com/ethereum/webthree-umbrella/releases/tag/1.0.1) work on the same machine, though they are obviously pretty outdated and less-than-useful now, dating, as they do, back to 18th November 2015.

**Comment by bobsummerwill** [comment]
Did you use Windows 7 or Windows 8 SDK?

I'm inclined to use Windows 8 SDK, and will try that first.

**Comment by CrackerHax** [comment]
I used 7.1

**Comment by bobsummerwill** [comment]
downloading, downloading, downloading!

**Comment by bobsummerwill** [comment]
Did you have to do anything specific with the CMake invocation to make it find the Windows SDK?   Or to point it at the "right one"?

I'm getting ...

```
CMake Error:
    Could not find an appropriate version of the Windows 10 SDK installed on this machine
```

Did you need to do any funky environment variables?   Like in this ... https://cmake.org/pipermail/cmake-developers/2015-September/026513.html?

**Comment by CrackerHax** [comment]
cmake -G "Visual Studio 12 2013 Win64" ..

No I didn't mess with environment variables at all.

**Comment by bobsummerwill** [comment]
OK - I'm there.   So the generation is failing for me because it cannot find any of the external dependencies.   They DO appear to have be installed into a /webthree-umbrella/webthree-helper/install/windows/x64 directory, but the CMake isn't looking there.     Is that where yours were installed to?   Boost, jsoncpp, etc?    Did you need to do anything explicit to point to them, or pass any specific path to get them installed in the right place?

**Comment by bobsummerwill** [comment]
Oh ... looks like current directory was important when running that script, so they might be one level too high up for me.    Are yours in /webthree-umbrella/webthree-helper/extdep/install/windows/x64?

**Comment by CrackerHax** [comment]
Yes, I just ran \webthree-helpers\extdep\getstuff.bat  and it put them in /webthree-umbrella/webthree-helper/extdep/install/windows/x64.  Really everything went smooth for me according to the directions but resulting binaries will not execute properly.

**Comment by bobsummerwill** [comment]
Yes - the SLN generation has worked when I moved them down a level to correct for my mistake.   Open in the IDE now and will start building.

**Comment by bobsummerwill** [comment]
Are you launching the resulting binaries on the command-line, or from within the IDE?
Which is the one you need/want the most, and which I should try first?
Are both the GUI and non-GUI apps broken for you?

**Comment by CrackerHax** [comment]
I tried starting from double clicking icons as well as from console and neither works. I have been testing with command line though since I can actually stop execution if it's a console. If I use an icon I end up with a wild process I cannot stop because it never shows up in task manager.

Yes all the apps are broken for me, even nonGUI.

I need solc and mix most.

I was even able to package the installer but the installer itself will not run either.

**Comment by CrackerHax** [comment]
Oh mannnn. I found the problem....

For some reason Avast is preventing anything from running. I added Program Files/cpp-ethereum/\* to exclusions and everything runs fine. Maybe this should be mentioned in the windows building doc.

**Comment by CrackerHax** [comment]
It's really strange I didn't have this problem with pre-compiled binaries. If I had, it would have been the first thing I checked.

Anyway the new version of Mix is a vast improvement over the November 2014 version. I'm surprised the binaries have not been updated.

**Comment by bobsummerwill** [comment]
Ooh - delightful :-)
Aside - something I spotted in my build log "Qt: Untested Windows version 10.0 detected".
But it is working for you now?
Please feel free to edit the Wiki page to note what you're seeing.   It is open-to-edit for everyone.

At some stage, I imagine that I will do a full sweep on the Windows instructions, like I have the OS X instructions, and basically rebuild them from scratch.    In the meantime, please feel free to add whatever notes you think would help others in your situation.

Glad it is working for you now!

**Comment by CrackerHax** [comment]
I got that message too, but works anyway.
