### ISSUE TITLE
Windows - Debug configuration broken in Windows build

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#123]
Following the https://github.com/ethereum/webthree-umbrella/wiki/Building-on-Windows instructions on my Surface Pro 3 works for Release configuration, but results in numerous errors in the default (and most desirable for development) Debug configuration.

See https://gist.github.com/anonymous/3a0e71d7213ac94dae55

**Comment by bobsummerwill** [comment]
We should at least have good instructions on how to build a workspace for which the Debug configuration works, even if that means that the Release configuration does not.

Most people (like me!) would want to iterate within the Debug configuration, from inside Visual Studio.    That basic scenario is not working "out of the box" right now.

**Comment by bobsummerwill** [comment]
The simplest way to resolve this is probably to do https://github.com/ethereum/webthree-umbrella/issues/183.

**Comment by winsvega** [comment]
I had the same issue but only with evmjit lib. so I added -DEVMJIT=0 when cmake and it worked fine. 

My setup:
Win7x64
MSVS 12.0.40629.00 Update 5

**Comment by bobsummerwill** [comment]
Yes, the clash is with the LLVM prebuilt binaries, which are only used in EVMJIT, so building without EVMJIT side-steps the issue.   We shouldn't need to side-step, though :-)

**Comment by gcolvin** [comment]
So the choice is to do #183, never use the debug runtime, and forgo the (sometimes useful) ability to step into runtime library code while debugging, or to build a debug version of LLVM ourselves?

**Comment by bobsummerwill** [comment]
Yes.   That's exactly it, @gcolvin.

Management of external dependencies for Windows is a bit weird: https://github.com/ethereum/webthree-helpers/blob/develop/extdep/getstuff.bat

Binaries have just been dumped into https://build.ethdev.com/builds/windows-precompiled/ and are then copied to your host machine by running that batch file, which looks to me like it only works for Windows 64-bit.     So the choice on the -MD versus -MDd for them has already been made, prior to them being zipped up.

To address that we would need to create debug ZIPs for them all too, which is likely a fair bit of hassle.   I'm not sure where their content even came from in the first place!   Probably way easier to just force everything to release system libraries for the time being.

You mentioned that you only have 32-bit Windows actually, didn't you, Greg?   XP and Win7.   You might be out of luck right now, because the binaries, again, are prebuilt.

Perhaps you want to make a Github issue to get Windows 32-bit support working?    It shouldn't be too hard, I don't think, though maybe not a priority.   We're already building as 32-bit for at least Linux ARM.

Also, there is a larger question here, of how to manage our external dependencies.   Right now we get them from PPAs, or Homebrew or this network drive or whatever.   Different per platform.   Nightmare.   Especially with rolling packaging managers on OS X and some Linux distros.    An alternative here is for us to add at least some of these external dependencies as git sub-modules into the webthree-umbrella repo, so we lock down on our versioning.    That does then require us to build them from source, but that's probably not so bad.

**Comment by bobsummerwill** [comment]
See also - https://chocolatey.org/ - which is the Windows package manager which it would probably be in our best interest to use for external dependencies, rather than hosting random binaries ourselves.

**Comment by bobsummerwill** [comment]
What was it you were working on with Chocolatey and PowerShell again, @tgerring?

**Comment by tgerring** [comment]
@bobsummerwill Exactly that: a [Windows build script for go-ethereum](https://gist.github.com/tgerring/79f018954aadfb3f406e) which could in-turn be used for Chocolatey.

The actual Chocolatey pushes themself would probably be best integrated with the build servers so new version numbers automagically get `cpush`ed to the Chocolatey repo.

Original go-ethereum issue about improving Windows build instructions ethereum/go-ethereum#1776

**Comment by bobsummerwill** [comment]
Aha - thanks!

**Comment by gcolvin** [comment]
@bobsummerwill I run Windows in VirtualBox for testing stuff on my other project, but don't do much development there if I can avoid it.  Will probably stick with Mac and Xubuntu for now, so Windows isn't a priority for me.

**Comment by bobsummerwill** [comment]
Fair enough, @gcolvin.
If you've only got XP and Win7 then you would be atypical of most users anyway.

**Comment by gcolvin** [comment]
@bobsummerwill  XP On the desktop XP has slightly more market share than 8 or 10 at about 10% each, and 7 rules at about 50%
https://www.netmarketshare.com/operating-system-market-share.aspx?qprid=10&qpcustomd=0

**Comment by bobsummerwill** [comment]
Atypical of the users who are likely to install eth, I mean :-)

Most of those XP installs will be in corporate environments of companies who don't understand or care about the security implications of running such an old and bug-ridden OS.   No offence, Greg!

No doubt that 11% will shrink very, very closely, and most of the Win7 and Win8 user-base are going to get forced to Win10 over time.

If eth works on XP then great, but we don't have the resources to do any extra work to get that going.

Even supporting Win32 is likely of pretty marginal value.

**Comment by gcolvin** [comment]
I agree that building on XP is not important, but I expect that with 50% of the market Windows 7 will hang on for a long time.  So building there has value if we want people building on Windows.  I'll volunteer at some point if we think that is a good use of my time.

**Comment by bobsummerwill** [comment]
Yes, I think that Windows 7 is a reasonable min-spec.

Looking at http://52.28.164.97/job/project-build/3209/label=windows-slave/consoleFull ...

It appears that our Windows build machine is using Visual Studio 2013 (with .NET 4.0), and using Windows SDK 8.1.    So probably running Windows 8.1.   And it is a 64-bit install, I think.

**Comment by Toadsfather** [comment]
Hi all
Please forgive the intrusion. I am a Windows C++/C#/WPF?ASP.Net/HTM5 dev and have been looking to get involved in ethereum/blockchain in some way and reading up on the technology in general for a while now. I noticed there seems to little support for Win10 in the apps? is that a reasonable observation? I downloaded Mix binary onto my Surface and noted it wasn't scaling correctly for high DPI devices such as the SurfacePro4 (although it ran absolutely fine!). Would a "good first task" be too look at that issue?? Just keen to contribute really, allbeit in a tiny way at this stage. Just thinking how I can apply my skills to good effect. Other suggestions on things to look at would be very welcome of course. My original background is C++/MFC apps from the 90s :-)
Cheers
SteveB

**Comment by bobsummerwill** [comment]
Hey @Toadsfather,

Your conclusion would be correct.    Our Windows builds in general are a little unloved, and could definitely use some extra eyes and loving care and attention.    Anything you could do to help would be much appreciated.     That is apparent in this specific issue, where something as simple as getting clean builds for debug and release is not currently being achieved :-)   I believe we have warnings too.   And yeah, no doubt there are lots of little UX flaws, as you highlight.

Please feel free to jump in, and see what you can do to help!

I have a Surface Pro 3 with Windows 10, but most of my day-to-day work is on OS X (and cross-builds - http://github.com/doublethinkco/webthree-umbrella-cross).   Most of the developers are normally Linux hosted, to the best of my understanding.

**Comment by Toadsfather** [comment]
Hi Bob

Thanks for your reply/welcome/encouragement to contribute. I will download the code and embark on the learning curve!

I’m a little bit rusty on C++ development (day job is mostly C# these days) so will proceed with great caution, but I’m guessing it’s just surface rust:-)

Thanks again, may well be in touch to forum with questions at some point...

Steve

On 24 Feb 2016, at 18:36, Bob Summerwill <notifications@github.com<mailto:notifications@github.com>> wrote:

Hey @Toadsfatherhttps://github.com/Toadsfather,

Your conclusion would be correct. Our Windows builds in general are a little unloved, and could definitely use some extra eyes and loving care and attention. Anything you could do to help would be much appreciated. That is apparent in this specific issue, where something as simple as getting clean builds for debug and release is not currently being achieved :-) I believe we have warnings too. And yeah, no doubt there are lots of little UX flaws, as you highlight.

Please feel free to jump in, and see what you can do to help!

I have a Surface Pro 3 with Windows 10, but most of my day-to-day work is on OS X (and cross-builds - http://github.com/doublethinkco/webthree-umbrella-crosshttps://github.com/doublethinkco/webthree-umbrella-cross). Most of the developers are normally Linux hosted, to the best of my understanding.

**Comment by bobsummerwill** [comment]
No problem, @Toadsfather!

So @gcolvin just joined the Ethereum C++ last week, and is on a learning journey which will no doubt be similar to yours as well :-)

Having both of your fresh eyes on https://github.com/ethereum/webthree-umbrella/wiki/Building-on-Windows would be very helpful.    Please do update as required as you are guinea-pigging!

I have poured a lot of time and effort into https://github.com/ethereum/webthree-umbrella/wiki/Building-on-OS-X, and into trying to fix issues in the OS X build process behind that, but I have hardly spent any time on the Windows build yet.     As @chriseth pointed out on http://ethernodes.org/network/1, nearly 50% of the nodes in the Ethereum network are running on Windows (though nearly all will be Geth), but that is telling us that our install base has a high demand for reliable Windows support, and we're not currently meeting that need very well.     Obviously just addressing bugs and getting the install setup as easy is possible is important.      And we should look to revive Chocately installs too.

**Comment by Toadsfather** [comment]
Ok, so I've actually spent a few hours today following the windows build instructions. Clean machine and absolutely no knowledge of eretheum beyond reading the whitepapers and watching a few videos. I was expecting loads of issues (mainly from past experiences from joining unfamiliar projects), however it actually went fairly well; so credit to those who put the instructions together :+1: 
Unfortunately I have run into a couple of issues which are resulting in no build. Before detailing those issues, as a fyi I was building on a Win7 64bit box within a corporate env behind a firewall so I had to config Git to use the internet proxy; perhaps a mention of that possibility in the instructions could be a time saver (minor point tho). Ok, so the key issues I have been unable to resolve yet on my own (so would really appreciate some help?!) are ....

(1) Before running the cmake command to create the sln/vcproj files by following this section in the instructions:

```
cd C:\webthree-umbrella
C:\webthree-umbrella> mkdir build
C:\webthree-umbrella> cd build
C:\webthree-umbrella\build> cmake -G "Visual Studio 12 Win64" .. # for cmake 2.8.12, or ...
C:\webthree-umbrella\build> cmake .. # for cmake 3.x, or ...
C:\webthree-umbrella\build> cmake -G "Visual Studio 12 2013 Win64" .. # for cmake 3.x x64 build
```

cmake failed to run complaining it couldn't find the cmakelist.txt  file when I ran it from the newly created build dir. When I ran it from the parent dir, webthree-umbrella, is seemed to start ok and chugged away for a few moments then stopped reporting the error described at (2) below.

(2) Whilst "Configuring alethzero" cmake reported this isssue:

```
CMake Error at webthree-helpers/cmake/UseQt.cmake:6 (find_package):
  By not providing "FindQt5Core.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5Core", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5Core"
  (requested version 5.4) with any of the following names:

    Qt5CoreConfig.cmake
    qt5core-config.cmake

  Add the installation prefix of "Qt5Core" to CMAKE_PREFIX_PATH or set
  "Qt5Core_DIR" to a directory containing one of the above files.  If
  "Qt5Core" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  webthree-helpers/cmake/EthDependencies.cmake:105 (eth_apply)
  alethzero/libaleth/CMakeLists.txt:22 (eth_use)`
```

(3) The projects which failed to build all reported this error:

```
_"C:\dev\Test\Eth\webthree-umbrella\CMakeFiles\CMakeTmp\cmTC_bad80.vcxproj" (default target) (1) ->

(ClCompile target) -> 

**  C:\dev\Test\Eth\webthree-umbrella\CMakeFiles\CMakeTmp\CheckSymbolExists.c(8): error C2065: 'CL_VERSION_2_0' : undeclared identifier [C:\dev\Test\Eth\webthree-umbrella\CMakeFiles\CMakeTmp\cmTC_bad80.vcxproj]_**
```

Looks like a missing include perhaps?

Forgive the stupid questions / obvious errors in how followed instructions! Thanks in adv.

Steve

**Comment by bobsummerwill** [comment]
(1) Hmm.   That missing CMakeLists.txt one is strange.    The CMake process obviously needs to POINT at the root directory, but I believe it is conventional to invoke that from within the build directory because that current directory is where the output files will spew to.

(2) That means that CMake cannot an appropriate Qt5 version.    I believe it just searches on your path.   If you look in the CMake folder inside webthree-helpers, you will see this - https://github.com/ethereum/webthree-helpers/blob/develop/cmake/UseQt.cmake - which is the bit which is failing.   CMake appears to have two phases - Find and Use.    The Find scripts look in registry or path or in other ways and locate installed software.    I think Qt5 might actually ship with CMake scripts for itself, or it might be built-in detection in CMake.   You'll have to have a Google for that.

(3) Hmm.   Somebody else hit something a little like that.    Which version of CMake are you using?   See https://github.com/ethereum/webthree-umbrella/issues/249.   If you are using 3.5, that might be the problem.   There is at least one regression.   I've not nailed THAT one down yet, but there is cause for caution.

**Comment by Toadsfather** [comment]
Thanks Bob. I will advise back. I'm doing this on my office based machine initially so will let you know tomorrow how it goes. Appreciate your assistance - given me a couple of pointers.  I was using cmake 3.4.3 (saw the warning not to use 3.5!)

Cheers.

On 25 Feb 2016, at 18:50, Bob Summerwill <notifications@github.com<mailto:notifications@github.com>> wrote:

(1) Hmm. That missing CMakeLists.txt one is strange. The CMake process obviously needs to POINT at the root directory, but I believe it is conventional to invoke that from within the build directory because that current directory is where the output files will spew to.

(2) That means that CMake cannot an appropriate Qt5 version. I believe it just searches on your path. If you look in the CMake folder inside webthree-helpers, you will see this - https://github.com/ethereum/webthree-helpers/blob/develop/cmake/UseQt.cmake - which is the bit which is failing. CMake appears to have two phases - Find and Use. The Find scripts look in registry or path or in other ways and locate installed software. I think Qt5 might actually ship with CMake scripts for itself, or it might be built-in detection in CMake. You'll have to have a Google for that.

(3) Hmm. Somebody else hit something a little like that. Which version of CMake are you using? See #249https://github.com/ethereum/webthree-umbrella/issues/249. If you are using 3.5, that might be the problem. There is at least one regression. I've not nailed THAT one down yet, but there is cause for caution.

##

**Comment by Toadsfather** [comment]
Ok, so the key issue (2) was due to the zip which contained qt was corrupt on arrival on my machine only a couple of directories were present in the archive. Re-downloaded, much bigger archive, alethzero cmake worked immediately after extracting the complete qt archive, now have all the proj files :-)

**Comment by bobsummerwill** [comment]
Excellent - so you have a SLN with everything it in?    But haven't started the build yet?

Probably worth refreshing your git clone too, if you pulled prior to Feb 24th, where I updated the umbrella with a week's worth of changes.

Did you fork into your own repo, then clone to your machine?     Are you git-savvy, @Toadsfather?

**Comment by gcolvin** [comment]
Is this issue still open @bobsummerwill ?  A squeaky clean build may solve your problem, as it did for @Toadsfather

**Comment by bobsummerwill** [comment]
The issue is still open, yes.
We still have the clash of windows runtime libraries which mean Debug builds get build errors.
@Toadsfather's setup issues were an aside.

Or are you saying that you have a working Windows Debug build on your machine somehow, @gcolvin ?

**Comment by gcolvin** [comment]
No, I haven't tried to build this yet, just wanted to be sure.  Two or three down my FIFO.

**Comment by bobsummerwill** [comment]
Right.   The core issue remains, which is a mixture of -MD and -MDd compile settings in the Debug config.   Prebuilt binaries are always -MD, so don't work for Debug config.    To get a working build we need to get them to match - ie. force Debug to -MD as well for the quick win.

**Comment by Toadsfather** [comment]
Apologies for late reply…

No I didn’t fork into my own repo yet - I just followed the Windows build instructions as-is. I will do though.

No I’m afraid I’m not particularly git-savy - all my commercial projects have been svn or TFS.
I’ll get up to speed - hopefully won’t take too long.

The build creates all the VS projects ok  - but it’s not building…looks like it can’t find some includes. I’m running through the process again on my machine at home, to make sure I didn’t miss anything wrt initial setup. I noticed after getting the latest on 1 March a lot of build errors disappeared.

On 26 Feb 2016, at 17:55, Bob Summerwill <notifications@github.com<mailto:notifications@github.com>> wrote:

Excellent - so you have a SLN with everything it in? But haven't started the build yet?

Probably worth refreshing your git clone too, if you pulled prior to Feb 24th, where I updated the umbrella with a week's worth of changes.

Did you fork into your own repo, then clone to your machine? Are you git-savvy, @Toadsfatherhttps://github.com/Toadsfather?

**Comment by Toadsfather** [comment]
Ok, I did a fresh fetch and suddenly down to 909 link errors in DEBUG mode. 

The following is the result of my observations:

All of these 909 errors were the same pair of errors duplicated across all projects for each static lib linker tried to import. As @bobsummerwill says above it looks to be an /MD <-> /MDd mismatch between the static libs in 
~\webthree-umbrella\webthree-helpers\extdep\install\windows\x64\lib and the projects in the solution. This mismatch manifests itself as:
`

```
error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in JIT.obj  C:\dev\webthree-umbrella\libethereum\evmjit\libevmjit\LLVMCore.lib(Module.obj)  evmjit
Error   3   error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in JIT.obj  C:\dev\webthree-umbrella\libethereum\evmjit\libevmjit\LLVMCore.lib(MetadataTracking.obj)    evmjit

```

`
Do we know why the static libs imported by projects within the cpp ethereum are mismatched in this way? 

When I build using the "RelWithDebInfo" there are no mismatches (but 22 warnings).

Is RelWithDebInfo the "standard" build config for development?

Sorry if I'm missed some documentation somewhere on this - pls point me in right direction if there is. Just finding my way around here :-)

@Toadsfather

**Comment by bobsummerwill** [comment]
Hey @Toadsfather!   Thanks for hacking away at this.

"Do we know why the static libs imported by projects within the cpp ethereum are mismatched in this way?

YES!   It's because the external dependencies on Windows are done a really, really horrible way.   OS X is using Homebrew.   Ubuntu is using PPAs.    Windows does now have NuGet and Chocolatey, but we are using them.    Instead we have getdeps.bat, which just pulls some random pre-built binaries from this network directory.    Somebody made them at some point:

```
https://build.ethdev.com/builds/windows-precompiled/
```

There are 32-bit and 64-bit binaries there, but ONLY release binaries.    Hence the mismatch.    We're using prebuild release binaries for all configurations.    That works for RelWithDebInfo and Release but breaks for Debug.     The best solution would be for those prebuilt binaries to contain debug and release variants and for the CMake output to use those.

Maybe we will be able to get there some day, but that day isn't today.

Please could you stick those 22 warnings in a gist?   We should fix those.   But I assume they don't stop a binary from being generated, right?    See also https://github.com/ethereum/webthree-umbrella/issues/219 (TODO).

SO ... I think the pragmatic way to get Debug working is to find how to change the CMake settings so that Debug gets forced to /MD.

**Comment by Toadsfather** [comment]
@bobsummerwill, I understand. Thks for the clear explanation :+1: 

Down to 17 warnings after manually setting the VCINSTALLDIR env correctly on my machine - not entirely sure why this was necessary tbh. Most of the warnings appear to be unreferenced locals, nothing particularly noteworthy I think...

I put them in a gist anyway:
https://gist.github.com/Toadsfather/3fc3d0648c0f5f3ff90d

I need to get a bit more familiar with github tbh (finally getting round to it, I'm mildly embarrassed to admit) , so will do that over next couple of days..then I look fwd to contributing a bit more :-)

**Comment by bobsummerwill** [comment]
Thanks, @Toadsfather!

I just fixed the markdown on your message above for the gist URL which had (url) after it.   Just the plain URL works fine.

Yeah - those all look very fixable, don't they?   We would grateful receive your pull requests (when you work out how to do them!)     No need to be embarrassed.   I only learnt my git-foo in the last couple of years, and am still quite a novice.

Best wishes.

**Comment by debris** [comment]
I'm not sure if anyone remembers, but there is a build script for external dependencies. https://github.com/ethereum/cpp-dependencies If might be helpful if you want to alter their configuration.

**Comment by bobsummerwill** [comment]
Thanks for the tribal knowledge, @debris!   I was certainly not aware of them.

Welcome back, by the way.   Good to see you around!

**Comment by chfast** [comment]
Debug builds has been fixed with https://github.com/ethereum/webthree-helpers/pull/183.

**Comment by bobsummerwill** [comment]
Hurrah - thanks, @chfast!
