### ISSUE TITLE
Ubuntu - not such file or directory - libweb3jsonrpc/DBFace.h.tmp

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#124]
@martchouk said the following on the closed #117 issue, but that was a rambling multi-bug covering lots of issues, where this is a discrete issues, on Ubuntu, on OS X, so I've pull that here for clarity.

The same issue seems to exists for build on Ubuntu as well.
[ 54%] Built target webthree
[ 54%] Built target solidity_BuildInfo.h
[ 62%] Built target solidity
CMake Error at /home/andrei/git/webthree-umbrella/webthree-helpers/cmake/scripts/jsonrpcstub.cmake:56 (file):
file failed to open for reading (No such file or directory):

/home/andrei/git/webthree-umbrella/webthree/libweb3jsonrpc/DBFace.h.tmp

make[2]: **\* [db.jsonstub] Error 1
make[1]: **\* [webthree/libweb3jsonrpc/CMakeFiles/db.jsonstub.dir/all] Error 2
make: **\* [all] Error 2

This will be related to the libjson-rpc-cpp package.   The same thing has shown on Arch as well - see https://github.com/ethereum/webthree-umbrella/issues/109.

**Comment by bobsummerwill** [comment]
My blind guess is that upgrading/reinstalling jibjson-rpc-cpp will get you in a happy place.   From what I can see, the error above occurs when that package is not installed correctly, so those generated files don't get generated, and then the build falls over at the next step.

That is sucky error reporting, if it's the case.    The failed generation step should be caught and flagged.   I've not tried to track down where that is yet, though.

Happy hunting, let me know if you have any success (or failure!)

**Comment by bobsummerwill** [comment]
@martchouk Are you still broken?   If not, or you're doing other stuff now, I'll close this.

**Comment by martchouk** [comment]
I switched to ubuntu repo instead of self-compiling and happy to have a working setup. Thank you

**Comment by bobsummerwill** [comment]
Great!   Have fun.
