### ISSUE TITLE
Test suite: branch/tag "release" doesn't exist

### ISSUE THREAD

**Issue by tuxayo** [ethereum/webthree-umbrella#125]
On the [build doc](https://github.com/ethereum/webthree-umbrella/wiki/Linux--Generic-Building), after cloning the tests, there is `git checkout release` but there is currently no such branch/tag.

**Comment by bobsummerwill** [comment]
Which branch of the tests repo should be recommended in this document, @winsvega?   Thanks!

**Comment by winsvega** [comment]
develop.
Tests tend to update pretty often. We better keep one branch and keep it updated with latest tests.

**Comment by bobsummerwill** [comment]
Thanks for the clarification and doc fix, @winsvega.

Thanks for the report, @tuxayo.   Closing this now!
