### ISSUE TITLE
How to unlock account over RPC?

### ISSUE THREAD

**Issue by Crypto2** [ethereum/webthree-umbrella#126]
Whenever my scripts try to send payments with sendTransaction they fail with INVALID_PARAMS because it's prompting for the account password. I'll then have to restart eth in console mode and do a dummy transaction and type in the password then RPC works fine.

This is my current command line running eth in the background: eth --upnp off --listen-ip my_ip -d ./data/ -j -m off --master master_password --json-admin json_rpc_password -r 52.16.188.185:30303 --bootstrap -v 8 --unsafe-transactions &

I've tried loading all the account passwords with the eth_notePassword RPC call and passing them all with --password parameters but no luck there. All the accounts were created with the admin_eth_newAccount() RPC call. I see geth has like personal.unlockAccount() but it seems like eth doesn't?

**Comment by chriseth** [comment]
This is the result of a design limitation in the JsonRPC server: All requests are currently answered in a synchronous way, so the JsonRPC thread cannot wait for the "foreground" thread to ask for the password to unlock the key. We will address that in the future.

Furthermore, we should also support unlocking keys in the way it is done in mist, eth seems to not support it for now.

**Comment by Crypto2** [comment]
What's weird is it used to work fine, I think it stopped working after there was an eth update (using the ubuntu PPA.) Seems like there should be a way to unlock an account via RPC or send the account pass along with the eth_sendTransaction call or something.

**Comment by smartbitcoin** [comment]
my experience is like if you keep the eth terminal open ,  and eth attach from another terminal , the original eth terminal will prompt your accept for those send transaction and you can choose "always" accept, then it works fine.

**Comment by Crypto2** [comment]
The --unsafe-transactions parm seems to handle that; it's just asking for the account passwords instead of unlocking them automatically like it seemed to do by itself before since my scripts worked until recently.

**Comment by Crypto2** [comment]
It looks like eth supports personal_unlockAccount now, so to any future readers with these issues use personal_unlockAccount(acct, pass, seconds_to_unlock_for) and --unsafe-transactions and you should be good to go for RPC use (barring any future changes.)

**Comment by JMLX42** [comment]
When I run `eth --unsafe-transactions` I get `Invalid argument: --unsafe-transaction`. What am I missing ?

**Comment by Crypto2** [comment]
You may be using an older version of eth (or newer if they've since removed it, things seem to be in flux a lot.) Also make sure you use --unsafe-transactions and not --unsafe-transaction

**Comment by JMLX42** [comment]
OK I solved my problem by using in-the-browser accounts (https://github.com/promethe42/ethereumjs-accounts) to sign transactions (https://github.com/promethe42/hooked-web3-provider).

**Comment by Crypto2** [comment]
And of course, update eth and personal_unlockAccount no longer exists; ugh. What are you guys doing, this is core RPC functionality breaking all the time.

**Comment by bobsummerwill** [comment]
I assume you are seeing this following updating to 1.2.2, @Crypto2?
(https://github.com/ethereum/webthree-umbrella/releases/tag/v1.2.2)

Changes were made in that release to align the account management support in eth with that in geth.   I think that affected JSON-RPC too, but I wasn't involved with those changes myself.

These changes were made to move us towards a place where geth, eth and the other clients can become more "plug-compatible".   I'll let somebody else chip-in with more details on these changes.

But yeah - you might need to change these calls to match geth's API.    Sorry for the disruption :-(

**Comment by Crypto2** [comment]
Thanks, I did figure it out in the end. There is a new command line option added called --admin-via-http that you have to use for personal_unlockAccount to work (the error message may want to be changed to reflect that since it just says that the method doesn't exist versus something like you have to enable admin functions to use this or something like that.)

Just for anyone reading this thread and want a TLDR: now to send Ether you need 3 separate switches enabled, --unsafe-transactions, --admin-via-http, and --json-admin with a password.

As I understand it --json-admin is under consideration for removal and replacement by having the password in a generated file that changes on each eth restart, which personally I don't like just because eth and the programs accessing the RPC interface may not be on the same system and/or have permissions to access the eth data folder.

**Comment by chriseth** [comment]
@Crypto2 Please take care, if you enable `--admin-via-http` in connection with `--unsafe-transactions` anyone that can connect to your http-json-rpc port can send transactions from accounts that do not have their own password. Since the http connection is not encrypted, even if your accounts are password protected and you unlock them with unlockAccount, anyone who can listen to your connection can use your accounts.

**Comment by chriseth** [comment]
Closing this issue again because I think the question in the title ("how to unlock accounts via RPC") was answered - connect via ipc and unlock the account in exactly the same way as described for geth.

**Comment by mattotodd** [comment]
@chriseth -  ipc assumes you are connecting via the same machine.  what if you want to use RPC?

**Comment by Crypto2** [comment]
I don't know if my info from my last post is still accurate or not, we have since moved to geth. Would recommend you switch to geth or parity as well since they are the most supported.
