### ISSUE TITLE
eth --help option

### ISSUE THREAD

**Issue by winsvega** [ethereum/webthree-umbrella#127]
Need to make eth --help option to look as great and readable as geth --help option
https://github.com/ethereum/go-ethereum/wiki/Command-Line-Options

**Comment by smartbitcoin** [comment]
it's better to re-write it by using some lib like boost-options.   now the code if ... else if ... just too error -prone.

**Comment by bobsummerwill** [comment]
This issue was moved to ethereum/cpp-ethereum#3090
