### ISSUE TITLE
Error: No such file or directory - test/testeth

### ISSUE THREAD

**Issue by ghost** [ethereum/webthree-umbrella#13]
Moved here from [cpp-ethereum](https://github.com/ethereum/cpp-ethereum/issues/2980)

==> Installing cpp-ethereum from ethereum/homebrew-ethereum
==> Downloading http://52.28.164.97/job/ethbinaries-build/label=macosx_slave/16/artifact/webthree-umbrella/bu

curl: (22) The requested URL returned error: 403 Forbidden
Error: Failed to download resource "cpp-ethereum"
Download failed: http://52.28.164.97/job/ethbinaries-build/label=macosx_slave/16/artifact/webthree-umbrella/build/cpp-ethereum-1.0rc2.yosemite.bottle.16.tar.gz
Warning: Bottle installation failed: building from source.
==> Cloning https://github.com/ethereum/webthree-umbrella.git
Updating /Library/Caches/Homebrew/cpp-ethereum--git
==> Checking out branch develop
Warning: EVMJIT needs the latest version of LLVM (3.7 or above), currently
only available with --HEAD. If an older version was already installed
or it did not install automatically, make sure to install it with
`brew install llvm --HEAD --with-clang`
==> cmake -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/cpp-et
==> make
==> make install
Error: No such file or directory - test/testeth

**Comment by prophet10x** [comment]
my error is slightly different

brew install cpp-ethereum --with-gui
==> Installing cpp-ethereum from ethereum/homebrew-ethereum
==> Cloning https://github.com/ethereum/webthree-umbrella.git
Updating /Library/Caches/Homebrew/cpp-ethereum--git
==> Checking out branch develop
Warning: EVMJIT needs the latest version of LLVM (3.7 or above), currently
only available with --HEAD. If an older version was already installed
or it did not install automatically, make sure to install it with
`brew install llvm --HEAD --with-clang`
==> cmake -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL_PR
==> make
==> make install
Error: No such file or directory - test/testeth

**Comment by LefterisJP** [comment]
The problem was definitely:

```
 Downloading http://52.28.164.97/job/ethbinaries-build/label=macosx_slave/16/artifact/webthree-umbrella/bu
```

Nothing should be downloaded from Jenkins directly. I changed the script's URL to try the proper build.ethdev.com url. Can you guys try again and see if it works right now?

**Comment by timsuchanek** [comment]
@LefterisJP I really would like to change the url, but have no idea how. Can you help me?

**Comment by timsuchanek** [comment]
Ok, I got it, I went to `/usr/local/Library/Taps/ethereum/homebrew-ethereum` and changed the url to build.ethdev.com.

The following url is now requested:

`https://build.ethdev.com/job/ethbinaries-build/label=macosx_slave/31/artifact/webthree-umbrella/build/cpp-ethereum-1.0rc2.yosemite.bottle.31.tar.gz`

But not found :/
Any idea?

**Comment by timsuchanek** [comment]
Ok, I now got it working.
Go to  `/usr/local/Library/Taps/ethereum/homebrew-ethereum` and do `git pull`
Then `git checkout 9cb9149cb2a924bccc3d2152daa4cbf85fc43179`
Then `brew install cpp-ethereum` works fine again ;)

**Comment by LefterisJP** [comment]
Hmmm this does not sound right. You will be getting quite an old version and also from the old url, since the commit you mentioned is this: https://github.com/ethereum/homebrew-ethereum/commit/9cb9149cb2a924bccc3d2152daa4cbf85fc43179

It is not fixed yet. Let me take a further look .. the url in the homebrew recipe seems to not have changed.

**Comment by prophet10x** [comment]
with --verbose i get this after running brew install cpp-ethereum --with-gui

-- ===========================================================================
-- ===========================================================================
-- Analyzing app='/tmp/cpp-ethereum20151002-38973-vlc88p/mix/Mix.app'
-- bundle='/tmp/cpp-ethereum20151002-38973-vlc88p/mix/Mix.app'
-- executable='/tmp/cpp-ethereum20151002-38973-vlc88p/mix/Mix.app/Contents/MacOS/Mix'
-- valid='1'
-- executable file 1: /tmp/cpp-ethereum20151002-38973-vlc88p/mix/Mix.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/Helpers/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess
-- executable file 2: /tmp/cpp-ethereum20151002-38973-vlc88p/mix/Mix.app/Contents/MacOS/Mix
-- verified='1'

## -- info='Verified 2 executable files in '/tmp/cpp-ethereum20151002-38973-vlc88p/mix/Mix.app''

-- verified='1'

## -- info=''

Error: No such file or directory - test/testeth

**Comment by prophet10x** [comment]
total output in verbose 

https://docs.google.com/document/d/1M0oQpcEHHeTBEW3xrdd2mOLSe4gXmIdjC6nOKBR__6c/edit?usp=sharing

**Comment by LefterisJP** [comment]
@timsuchanek: Can you try again but with the latest develop of homebrew-ethereum checked out?

**Comment by timsuchanek** [comment]
@LefterisJP Ok, I tried it with the newest version from the `homebrew-ethereum` from its master branch (`homebrew-ethereum` has no `develop` branch, if that's what you meant.)

This is the error output I get: 

``` sh
/u/l/L/T/ethereum (master) $ brew reinstall cpp-ethereum
==> Reinstalling ethereum/ethereum/cpp-ethereum with --with-evmjit
==> Cloning https://github.com/ethereum/webthree-umbrella.git
Updating /Library/Caches/Homebrew/cpp-ethereum--git
==> Checking out branch develop
Warning: EVMJIT needs the latest version of LLVM (3.7 or above), currently
only available with --HEAD. If an older version was already installed
or it did not install automatically, make sure to install it with
`brew install llvm --HEAD --with-clang`
==> cmake -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL_PREFIX=/usr/lo
==> make
Last 15 lines from /Users/timsuchanek/Library/Logs/Homebrew/cpp-ethereum/02.make:
#define cwarn clog(dev::WarnChannel)
              ^
/tmp/cpp-ethereum20151003-89114-ivqn2c/libweb3core/libdevcore/Log.h:266:55: note: expanded from macro 'clog'
#define clog(X) DEV_STATEMENT_ONCE() if (X::debug) {} else dev::LogOutputStream<X, true>()
                                                      ^
[ 17%] Building CXX object libweb3core/libdevcore/CMakeFiles/devcore.dir/TrieHash.cpp.o
cd /tmp/cpp-ethereum20151003-89114-ivqn2c/libweb3core/libdevcore && /usr/local/opt/llvm/bin/clang++  -stdlib=libc++  -DETH_FRONTIER -DETH_TRUE -Ddevcore_EXPORTS -std=c++11 -Wall -Wno-unknown-pragmas -Wextra -DSHAREDLIB -fPIC -fstack-protector-strong -Wstack-protector -DSTATICLIB -O3 -DNDEBUG -DETH_RELEASE -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.10 -fPIC -isystem /usr/local/include/jsoncpp -I/tmp/cpp-ethereum20151003-89114-ivqn2c/libweb3core -I/tmp/cpp-ethereum20151003-89114-ivqn2c/libweb3core/include -I/tmp/cpp-ethereum20151003-89114-ivqn2c -I/tmp/cpp-ethereum20151003-89114-ivqn2c/include -I/tmp/cpp-ethereum20151003-89114-ivqn2c/gen -isystem /usr/local/include -I/tmp/cpp-ethereum20151003-89114-ivqn2c/libweb3core/gen    -o CMakeFiles/devcore.dir/TrieHash.cpp.o -c /tmp/cpp-ethereum20151003-89114-ivqn2c/libweb3core/libdevcore/TrieHash.cpp
1 warning generated.
[ 17%] Building CXX object libweb3core/libdevcore/CMakeFiles/devcore.dir/Worker.cpp.o
cd /tmp/cpp-ethereum20151003-89114-ivqn2c/libweb3core/libdevcore && /usr/local/opt/llvm/bin/clang++  -stdlib=libc++  -DETH_FRONTIER -DETH_TRUE -Ddevcore_EXPORTS -std=c++11 -Wall -Wno-unknown-pragmas -Wextra -DSHAREDLIB -fPIC -fstack-protector-strong -Wstack-protector -DSTATICLIB -O3 -DNDEBUG -DETH_RELEASE -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.10 -fPIC -isystem /usr/local/include/jsoncpp -I/tmp/cpp-ethereum20151003-89114-ivqn2c/libweb3core -I/tmp/cpp-ethereum20151003-89114-ivqn2c/libweb3core/include -I/tmp/cpp-ethereum20151003-89114-ivqn2c -I/tmp/cpp-ethereum20151003-89114-ivqn2c/include -I/tmp/cpp-ethereum20151003-89114-ivqn2c/gen -isystem /usr/local/include -I/tmp/cpp-ethereum20151003-89114-ivqn2c/libweb3core/gen    -o CMakeFiles/devcore.dir/Worker.cpp.o -c /tmp/cpp-ethereum20151003-89114-ivqn2c/libweb3core/libdevcore/Worker.cpp
[ 17%] Linking CXX shared library libdevcore.dylib
cd /tmp/cpp-ethereum20151003-89114-ivqn2c/libweb3core/libdevcore && /usr/local/Cellar/cmake/3.3.2/bin/cmake -E cmake_link_script CMakeFiles/devcore.dir/link.txt --verbose=1
/usr/local/opt/llvm/bin/clang++  -stdlib=libc++ -std=c++11 -Wall -Wno-unknown-pragmas -Wextra -DSHAREDLIB -fPIC -fstack-protector-strong -Wstack-protector -DSTATICLIB -O3 -DNDEBUG -DETH_RELEASE -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.10 -dynamiclib -Wl,-headerpad_max_install_names  -L/usr/local/opt/v8-315/lib -L/usr/local/opt/curl/lib -L/usr/local/opt/readline/lib -L/usr/local/lib -Wl,-headerpad_max_install_names -L/usr/local/opt/llvm/lib -o libdevcore.dylib -install_name /tmp/cpp-ethereum20151003-89114-ivqn2c/libweb3core/libdevcore/libdevcore.dylib CMakeFiles/devcore.dir/Base64.cpp.o CMakeFiles/devcore.dir/Common.cpp.o CMakeFiles/devcore.dir/CommonData.cpp.o CMakeFiles/devcore.dir/CommonIO.cpp.o CMakeFiles/devcore.dir/CommonJS.cpp.o CMakeFiles/devcore.dir/FileSystem.cpp.o CMakeFiles/devcore.dir/FixedHash.cpp.o CMakeFiles/devcore.dir/Guards.cpp.o CMakeFiles/devcore.dir/Hash.cpp.o CMakeFiles/devcore.dir/Log.cpp.o CMakeFiles/devcore.dir/MemoryDB.cpp.o CMakeFiles/devcore.dir/RangeMask.cpp.o CMakeFiles/devcore.dir/RLP.cpp.o CMakeFiles/devcore.dir/SHA3.cpp.o CMakeFiles/devcore.dir/StructuredLogger.cpp.o CMakeFiles/devcore.dir/TransientDirectory.cpp.o CMakeFiles/devcore.dir/TrieCommon.cpp.o CMakeFiles/devcore.dir/TrieDB.cpp.o CMakeFiles/devcore.dir/TrieHash.cpp.o CMakeFiles/devcore.dir/Worker.cpp.o /usr/local/lib/libjsoncpp.dylib /usr/local/lib/libjsoncpp.dylib /usr/local/lib/libleveldb.dylib /usr/local/lib/libboost_thread-mt.a /usr/local/lib/libboost_random-mt.a /usr/local/lib/libboost_filesystem-mt.a /usr/local/lib/libboost_system-mt.a -lpthread
[ 17%] Built target devcore
make: *** [all] Error 2

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/ethereum/homebrew-ethereum/issues


```

Then I thought, ok maybe the LLVM is not installed properly.
So I tried this:

``` sh

/u/l/L/T/ethereum (master) $ brew reinstall llvm --HEAD --with-clang
==> Reinstalling llvm with --with-clang
==> Cloning http://llvm.org/git/llvm.git
Updating /Library/Caches/Homebrew/llvm--git
==> Checking out branch master
==> Cloning http://llvm.org/git/libcxx.git
Updating /Library/Caches/Homebrew/llvm--libcxx--git
==> Checking out branch master
==> Cloning http://llvm.org/git/clang.git
Updating /Library/Caches/Homebrew/llvm--clang--git
==> Checking out branch master
==> Cloning http://llvm.org/git/clang-tools-extra.git
Updating /Library/Caches/Homebrew/llvm--clang-tools-extra--git
==> Checking out branch master
==> cmake -G Unix Makefiles /private/tmp/llvm20151003-90598-1ljun8s -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/llvm/HEAD -DCMAKE_BUILD_
==> make
Last 15 lines from /Users/timsuchanek/Library/Logs/Homebrew/llvm/02.make:
make[2]: *** [NATIVE/bin/clang-tblgen] Error 2
make[1]: *** [tools/clang/utils/TableGen/CMakeFiles/CLANG-tablegen-host.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Building CXX object utils/TableGen/CMakeFiles/obj.llvm-tblgen.dir/TableGen.cpp.o
[120%] Built target LLVMSupport
[120%] Building CXX object utils/TableGen/CMakeFiles/obj.llvm-tblgen.dir/X86DisassemblerTables.cpp.o
[120%] Building CXX object utils/TableGen/CMakeFiles/obj.llvm-tblgen.dir/X86ModRMFilters.cpp.o
[120%] Building CXX object utils/TableGen/CMakeFiles/obj.llvm-tblgen.dir/X86RecognizableInstr.cpp.o
[120%] Building CXX object utils/TableGen/CMakeFiles/obj.llvm-tblgen.dir/CTagsEmitter.cpp.o
[120%] Built target obj.llvm-tblgen
Scanning dependencies of target llvm-tblgen
[120%] Linking CXX executable ../../bin/llvm-tblgen
[120%] Built target llvm-tblgen
[ 12%] Built target LLVM-tablegen-host
make: *** [all] Error 2

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
llvm: add more components https://github.com/Homebrew/homebrew/pull/44250
llvm 3.7.0 https://github.com/Homebrew/homebrew/pull/43499
rust: Add --with-llvm option https://github.com/Homebrew/homebrew/pull/44138
llvm formula's clang++ fails with -L $(brew --prefix llvm)/lib https://github.com/Homebrew/homebrew/issues/42957
ocaml will never be detected by llvm during configuration https://github.com/Homebrew/homebrew/issues/43335
llvm --with-clang --with-lldb fails to build https://github.com/Homebrew/homebrew/issues/42041
MacOS.(gcc|clang|llvm)_version can return nil https://github.com/Homebrew/homebrew/issues/18781

```

I have OSX Yosemite installed with 10.10.5 (14F27).
It's a fresh installation.

One question: I'm currently going through the tutorials and
`registrar.addr("nameYouWant")` returns `invalid address`.

Do you know why that command fails?

Thanks thanks! I'm on a hackathon and really need this to get working :)

**Comment by LefterisJP** [comment]
Hmm so there is indeed another issue too. We require llvm 3.7, but it seems that the homebrew llvm 3.7 recipe [has not yet been merged](https://github.com/Homebrew/homebrew/pull/43499).

I am afraid that until that is merged, you will need to [build manually](https://github.com/ethereum/webthree-umbrella/wiki/Building-on-MacOS#manual-build) and specify `-DEVMJIT=0` as an extra cmake option in order to avoid the llvm dependency. I would recommend this if you need this right, right now (you said you are in a hackathon).

As for general questions about the project , let's not hijack an issue. Many of us are active in [gitter](https://gitter.im/ethereum/cpp-ethereum). You are more than welcome to join and ask questions :)

**Comment by chfast** [comment]
I suspect the only working version 3.7+ of LLVM in homebrew is currently `llvm --head` that will build 3.8 SVN version from source.

**Comment by debris** [comment]
fixed in https://github.com/ethereum/webthree-helpers/pull/61
