### ISSUE TITLE
Error compiling windows

### ISSUE THREAD

**Issue by ramvi** [ethereum/webthree-umbrella#131]
Ref issue  #129, after changing all

``` cpp
#if WIN32
#ifdef _WIN32
#ifndef WIN32
```

to `#if defined(_WIN32)` the compiler still can't compile due to a missing `sys/un.h` in `UnixSocketServer.h`

The whole file is wrappet in a `#if defined(_WIN32)`, so it shouldn't really care, but it does.

Win7 x64 and [everything from the guide installed](https://github.com/ethereum/webthree-umbrella/wiki/Building-on-Windows)

**Comment by LefterisJP** [comment]
Can you also print the build log where the error happens, and also the specs of your Windows System?

**Comment by bobsummerwill** [comment]
OK - I see the issue :-)   It's a 64-bit versus 32-bit thing.

`_WIN32` is **only** defined when building Windows for 32-bit.    @ramvi is building 64-bit, so `_WIN64` will be defined, but NOT `_WIN32`.

So I assume that we have a series of conditionals which are only working correctly for Windows 32-bit and are broken for Windows 64-bit.

**Comment by ramvi** [comment]
That's the only instance that creates problems. Commented out the header and it's corresponding cpp-file and it compiles

**Comment by bobsummerwill** [comment]
Or not!   `_WIN32` - "Defined for applications for Win32 and Win64. Always defined.".    Bah!

**Comment by winsvega** [comment]
latest develop compiles fine on win7x64
