### ISSUE TITLE
eth stalls with setTimeout not available in this environment

### ISSUE THREAD

**Issue by jch9678** [ethereum/webthree-umbrella#132]
Windows 10
Athlon II x4
8gb ram

I've had  0.9.4 since August 2015 and haven't used it since then, I decided to give eth (and alethzero) another try with 1.0.1.  I first installed to a directory on my desktop, then I installed it in program files alongside .9.4 (in different directories).  I'm able to type my password in Alethzero but then it stalls and is unresponsive, I'm also able to type my password in eth then I get a setTimeout notification and eth stalls.  The cursor blinks but I can't type anything in it (I started it with eth -i)

**Comment by LefterisJP** [comment]
Hello LefterisJP from IRC here. Thanks for opening the bug report. Would it be possible to try and get a debug build from source in your system to see what could be wrong?

[Building on Windows Guide](https://github.com/ethereum/webthree-umbrella/wiki/Building-on-Windows)

**Comment by jch9678** [comment]
Sure. I'll give it a shot. Happy to help. It's late evening here but I'll
see if I can take a look a little later.

**Comment by chriseth** [comment]
Closing as we will remove the console soon (the new environment has setTimeout).

**Comment by jch9678** [comment]
I may have some eth stuck in my alethzero, will this affect me being able to retrieve them?  I don't know the addresses because I can't get alethzero to work.

**Comment by chriseth** [comment]
You will be able to use eth together with Mist / EthereumWallet and all the accounts you had in alethzero should be visible there.

**Comment by MicahZoltu** [comment]
@chriseth I ran into this too.  What is the recommended workaround?  You mentioned "the new environment", what environment is this?  The front page still suggests eth++ as the powertool and geth as the almost-power tool.  Is there another one?

**Comment by bobsummerwill** [comment]
Hey @Zoltu,

I don't have the context to know who mentioned "new environment" or what they meant.   Where did that happen?  Got a link?

With regard to removal of the console, what @chriseth is talking about is our plan to remove the Javascript console from eth imminently, because we've improved geth -> eth interoperability to the point where you can `geth attach` to a running eth node.   We're stripping eth down of functionality which is redundant with geth.

See https://blog.ethereum.org/2016/02/12/ethereum-dev-update-c-roadmap/ and https://blog.ethereum.org/2016/01/07/2394/.

So yeah, the answer is "don't worry, you won't lose your ether".

**Comment by jch9678** [comment]
My issue was that I have geth installed and used that mainly but I installed alethzero to test it out.  I was solo-mining with geth but I should've been hitting a lot of blocks back in august but they weren't showing up in geth.  I was thinking that they may have been mined to the addresses that alethzero produced but since I can't get it running, I can't check their balances (because I don't know the addresses).  I think geth and alethzero (eth) use different 'default' addresses correct?  Hopefully I won't lose my ether on a machine with both geth and eth installed?

**Comment by bobsummerwill** [comment]
@chriseth will probably have a better answer than me on your addresses question.

**Comment by chriseth** [comment]
@jch9678 eth and geth use different locations to store their keys, so it is certainly possible that your ether is just stored in a key in the eth keystore. You will soon be able to just use the ethereum wallet together with eth. If you want to try, it might even already work. Just start `eth` (without any options), keep it running and then open the mist wallet. I think you should at least be able to see your balance. For sending ether you might have to wait another week or so.

**Comment by jch9678** [comment]
ok thanks @chriseth I don't have any experience with the Mist wallet.  So I can just install the mist wallet (not even sure if it's an install) over my existing geth, eth, and alethzero etc. 'installations' and my keystore's will remain intact for geth and eth?  Just want to make sure before I attempt.  I've tried to back up the keystores but some of the documentation is contradictory.  geth is pretty straightforward but eth not so much.

edit: Is this the latest Mist wallet? https://github.com/ethereum/mist/releases/tag/0.4.0

**Comment by chriseth** [comment]
You will not install it "over" anything, it will not delete any data. Depending on your platform, the wallet might contain a geth and a c++-ethereum node, but will not overwrite anything on installation, these nodes will just re-use your existing key data.

To access you eth keys, you need to have eth running before you start mist/the wallet (or select c++-ethereum in the menu, but that will not work on all platforms).

**Comment by jch9678** [comment]
Thank you, I've started eth and it is doing a "SLOW IMPORT" and the splashscreen of Ethereum Wallet says "Ethereum node needs to sync, please wait..."  "Downloading block 1,053,849 of 1,062,022."

I don't think I have many connections, is there a way to check in eth?  Something like geth attach but for eth?  If I don't have many connections, is there a way to add nodes?  

I know this probably isn't the preferred place for support so I appreciate the help you guys have given me.

edit: It looks like eth has stalled, it has not imported anything for 1.5 hours.

**Comment by chriseth** [comment]
There should be a "skip" link and you should be able to still see your balances and even transfer some money. We will release a new version next week that supports exactly `geth attach` and also something similar that does not need geth.

**Comment by formula300** [comment]
what did you want to say? node? 30 seconds...
hahaha bad JOKE!

**Comment by formula300** [comment]
this english ist das sheet! people of people!

**Comment by formula300** [comment]
coca ZULU!

**Comment by formula300** [comment]
please do not build program with stupid therms as "set up"
windows develloper's has stupid commandline
