### ISSUE TITLE
OS X - Homebrew: dyld: Library not loaded: /usr/local/lib/libmicrohttpd.10.dylib (nearly all Yosemite, one El Capitan)

### ISSUE THREAD

**Issue by davalb** [ethereum/webthree-umbrella#133]
I just installed ethereum with `brew install cpp-ethereum`on a macbook pro with OsX Yosemite. I get this error when I try to run eth on the commandline with `eth console`:

```
dyld: Library not loaded: /usr/local/lib/libmicrohttpd.10.dylib
  Referenced from: /usr/local/bin/eth
  Reason: image not found
Trace/BPT trap: 5
```

Indeed the file in question is not present. Instead I have this file: `/usr/local/lib/libmicrohttpd.12.dylib`. 
Help very much appreciated, thank you!

**Comment by bobsummerwill** [comment]
Hey, @davalb!

Looks like the known issue shown in the Troubleshooting section at the bottom of:

https://github.com/ethereum/webthree-umbrella/wiki/Building-on-OS-X

Please can you attempt https://github.com/ethereum/webthree-umbrella/wiki/homebrew-47806-workaround, and report back if that did NOT get you fixed?   Thanks!

**Comment by davalb** [comment]
Hi @bobsummerwill 

This is exactly the issue I am experiencing, but for some reason the proposed solution doesn't work for me.  I did the following:

```
rm /Library/Caches/Homebrew/libjson-rpc-cpp-0.5.0.yosemite.bottle.tar.gz 
brew uninstall libjson-rpc-cpp
brew install libjson-rpc-cpp
brew uninstall cpp-ethereum
brew install cpp-ethereum
```

Afterwards I still get the `dyld: Library not loaded: /usr/local/lib/libmicrohttpd.10.dylib` error

**Comment by bobsummerwill** [comment]
Hmm.   Have you done:

```
brew update
brew upgrade
```

As well, prior to these steps?   You might have outdated formulas.

**Comment by davalb** [comment]
Yes, I did. To be sure I just repeated everything with `brew update && brew upgrade` as first steps. I still have the problem.

**Comment by bobsummerwill** [comment]
Oh dear ... that is rather ugly.    Any thoughts, @area?

**Comment by area** [comment]
I'd guess it's the fact that @davalb is on OSX Yosemite, not El Capitan.

EDIT: Yeah, the Yosemite bottle still links to the wrong library. I can't remember if building from source was a workaround for this, but maybe try:

```
brew uninstall libjson-rpc-cpp
brew install -s libjson-rpc-cpp
```

**Comment by bobsummerwill** [comment]
Ah!   Good call, @area.   That might well be it.

@davalb Please could you try that?   If that turns out to be the case then we should log another ticket with the Homebrew team about this, or just comment on the original issue to request a re-bottle.

**Comment by davalb** [comment]
I tried 

```
brew uninstall libjson-rpc-cpp
brew install -s libjson-rpc-cpp
```

but the error persists. I have subscribed to the other ticket @area opened. As soon as there is some development, I will try installing ethereum again. Thanks for all the help

**Comment by bobsummerwill** [comment]
Oh dear, @davalb.    How very annoying!    I'm sorry that our "ready fix" wasn't such a "ready fix".

**Comment by maximilianh** [comment]
Same problem here, also on yosemite. Recompile of libjson-rpc-cpp did not help. Would recompile of cpp-ethereum work?

**Comment by dth88** [comment]
Same issue, none of the fixes helped.

**Comment by bobsummerwill** [comment]
Hokey dokey.   I will dig into this when I get a chance.    Thanks for the updates, guys.
Working through Qt issue first - https://github.com/ethereum/homebrew-ethereum/issues/52.

**Comment by bobsummerwill** [comment]
You are on Yosemite too, right, @dathbezumniy?   Just to confirm?

**Comment by dth88** [comment]
yes

2016-02-10 19:27 GMT+06:00 Bob Summerwill notifications@github.com:

**Comment by bobsummerwill** [comment]
Thanks for the confirmation, @dathbezumniy!

**Comment by programonauta** [comment]
Hi, I'm trying to install eth on Yosemite, and facing the same issue.

**Comment by programonauta** [comment]
I don't know if it could help,

But trying to build from source following the instructions at: https://github.com/ethereum/webthree-umbrella/wiki/Building-on-OS-X

I got this error, when run 
`LLVM_DIR=/usr/local/Cellar/llvm/HEAD/share/llvm/cmake cmake ..`

```
CMake Error at libethereum/evmjit/CMakeLists.txt:23 (find_package):
  Could not find a package configuration file provided by "LLVM" with any of
  the following names:

    LLVMConfig.cmake
    llvm-config.cmake

  Add the installation prefix of "LLVM" to CMAKE_PREFIX_PATH or set
  "LLVM_DIR" to a directory containing one of the above files.  If "LLVM"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "/Users/ricardo/webthree-umbrella/build/CMakeFiles/CMakeOutput.log".
```

**Comment by bobsummerwill** [comment]
Hey @programonauta!
Looks like they changed the path for those CMake files are some stage.
I just updated https://github.com/ethereum/webthree-umbrella/wiki/Building-on-OS-X.

So it should actually be :

`LLVM_DIR=/usr/local/Cellar/llvm/HEAD/lib/cmake cmake ..`

Does that work for you?

**Comment by programonauta** [comment]
@bobsummerwill, I'm not with my Yosemite right now, as soon as I can test, I'll let you know.

**Comment by programonauta** [comment]
@bobsummerwill,

I tried to run it again, but it missing another cmake file

```
CMake Error at webthree-helpers/cmake/UseQt.cmake:30 (find_package):
  By not providing "FindQt5DBus.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5DBus", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5DBus"
  (requested version 5.4) with any of the following names:

    Qt5DBusConfig.cmake
    qt5dbus-config.cmake

  Add the installation prefix of "Qt5DBus" to CMAKE_PREFIX_PATH or set
  "Qt5DBus_DIR" to a directory containing one of the above files.  If
  "Qt5DBus" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  webthree-helpers/cmake/EthDependencies.cmake:105 (eth_apply)
  alethzero/libaleth/CMakeLists.txt:22 (eth_use)
```

**Comment by programonauta** [comment]
@bobsummerwill 

BTW, I think it's better open another issue, because this one is about an error on `brew install cpp-ethereum`.

And I brought an error on building on OSX.
What do you think about?

**Comment by bobsummerwill** [comment]
Yes to "new issue", please, @programonauta.   I'll reply here, but please let's move to a new bug if you need more after this ...

The D-Bus issue you are seeing means that your Qt5 install was installed without DBus support.

```
brew uninstall --force qt
brew uninstall qt5
brew install --with-d-bus qt5
brew linkapps qt5
```

**Comment by programonauta** [comment]
@bobsummerwill, I opened issue #205

**Comment by jesuscript** [comment]
@davalb I have the same issue (libmicrohttpd) on El Capitan

**Comment by bobsummerwill** [comment]
Ooh, that is interesting, @jesuscript.   Thanks for the info!

**Comment by bobsummerwill** [comment]
@davalb, @maximilianh, @dathbezumniy, @programonauta, @jesuscript, @area:

Are you guys all still without working Homebrew installs of `eth`?    Just working on this issue again right now, and seeing another issue which is very, very similar:

```
Bobs-Air:webthree-umbrella bob$ eth -V
dyld: Library not loaded: /usr/local/opt/jsoncpp/lib/libjsoncpp.0.dylib
  Referenced from: /usr/local/bin/eth
  Reason: image not found
Trace/BPT trap: 5
```

All of these issues seem to cause by "stale" bottles for prebuilt binaries which we depend on.

Just wanted to check that you are all still gated?   Thanks!

**Comment by maximilianh** [comment]
I've switched to geth, which is working fine.

**Comment by programonauta** [comment]
@bobsummerwill, I tried this on my Yosemite:

```
MacMiniBrandNet:webthree-umbrella ricardo$ eth -V
eth version 1.2.2
eth network protocol version: 63
Client database version: 12041
Build: Darwin/appleclang/JIT/.
```

**Comment by bobsummerwill** [comment]
Hey @maximilianh.   That works :-)
@programonauta Excellent.  That's what we want to see.   Thanks for letting me know.

**Comment by bobsummerwill** [comment]
I think we're good now, so I will close this.    Will open new issue(s) as required if there is still work to do.

**Comment by wenhuizhang** [comment]
hi, any one has idea why dyld does not exist on Mac OS? and not in brew taps repo either
