### ISSUE TITLE
JSONCPP issues when building cpp-ethereum.sln

### ISSUE THREAD

**Issue by hansvde** [ethereum/webthree-umbrella#134]
I am following https://github.com/ethereum/webthree-umbrella/wiki/Building-on-Windows,  but it don't get it up and running. Who can help me. I have following errors: 

-- Found jsoncpp: C:/Program Files/jsoncpp-master
-- JsonCpp headers: C:/Program Files/jsoncpp-master
-- JsonCpp lib   : optimized;C:/Program Files/jsoncpp-master/src/lib_json;debug;JSONCPP_LIBRARY_DEBUG-NOTFOUND
-- Could NOT find leveldb (missing:  LEVELDB_INCLUDE_DIR LEVELDB_LIBRARY)
-- Could NOT find leveldb (missing:  LEVELDB_INCLUDE_DIR LEVELDB_LIBRARY)
-- LevelDB headers: LEVELDB_INCLUDE_DIR-NOTFOUND
-- LevelDB lib   : optimized;LEVELDB_LIBRARY-NOTFOUND;debug;LEVELDB_LIBRARY_DEBUG-NOTFOUND
-- Could NOT find leveldb (missing:  LEVELDB_INCLUDE_DIR LEVELDB_LIBRARY)
-- Could NOT find leveldb (missing:  LEVELDB_INCLUDE_DIR LEVELDB_LIBRARY)
CMake Error at webthree-helpers/cmake/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find CryptoPP (missing: CRYPTOPP_INCLUDE_DIR CRYPTOPP_LIBRARY)
  (Required is at least version "5.6.2")
Call Stack (most recent call first):
  webthree-helpers/cmake/FindPackageHandleStandardArgs.cmake:374 (_FPHSA_FAILURE_MESSAGE)
  webthree-helpers/cmake/FindCryptoPP.cmake:107 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  webthree-helpers/cmake/UseCryptopp.cmake:2 (find_package)
  webthree-helpers/cmake/EthDependencies.cmake:105 (eth_apply)
  libweb3core/libdevcrypto/CMakeLists.txt:8 (eth_use)

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
C:/webthree-umbrella/libweb3core/libdevcore/LEVELDB_INCLUDE_DIR
   used as include directory in directory C:/webthree-umbrella/libweb3core/libdevcore
C:/webthree-umbrella/libweb3core/libdevcrypto/LEVELDB_INCLUDE_DIR
   used as include directory in directory C:/webthree-umbrella/libweb3core/libdevcrypto
JSONCPP_LIBRARY_DEBUG
    linked by target "devcore" in directory C:/webthree-umbrella/libweb3core/libdevcore
    linked by target "devcore" in directory C:/webthree-umbrella/libweb3core/libdevcore
    linked by target "devcrypto" in directory C:/webthree-umbrella/libweb3core/libdevcrypto
LEVELDB_LIBRARY (ADVANCED)
    linked by target "devcore" in directory C:/webthree-umbrella/libweb3core/libdevcore
    linked by target "devcrypto" in directory C:/webthree-umbrella/libweb3core/libdevcrypto
LEVELDB_LIBRARY_DEBUG
    linked by target "devcore" in directory C:/webthree-umbrella/libweb3core/libdevcore
    linked by target "devcrypto" in directory C:/webthree-umbrella/libweb3core/libdevcrypto

-- Configuring incomplete, errors occurred!
See also "C:/webthree-umbrella/build/CMakeFiles/CMakeOutput.log".

**Comment by LefterisJP** [comment]
Did you run [this step](https://github.com/ethereum/webthree-umbrella/wiki/Building-on-Windows#1-getting-dependencies):

```
cd C:\<THEPATHTOWHEREYOUCLONEUMBRELLA>\webthree-helpers\extdep
getstuff.bat 
```

**Comment by hansvde** [comment]
apparently it only downloaded the programs and didn't install it. Must have missed this. Now it ok. Many thanks
