### ISSUE TITLE
Installer not creating Desktop icon or Startup shortcuts (Win10)

### ISSUE THREAD

**Issue by lohuissven** [ethereum/webthree-umbrella#138]
Hi, the installer is not creating any desktop or startup shortcuts. Only folder in C:\ is created "C:\Program Files\Ethereum 1.0.1" with in there a uninstaller and 'Release' folder. In the release folder a list of files. Now playing to see what combination or what .exe is needed to make it work.

**Comment by gmdeo** [comment]
Same Problem here - though on older 32 bit vista

**Comment by bobsummerwill** [comment]
@gmdeo Vista?   Eeek.   You really need to upgrade your OS :-)

Barring the desktop shortcuts, the executables are working for you on Vista, though?

I don't think we've got any clear line on "min spec", but running anything older than Windows 7 is a real security liability.

**Comment by gmdeo** [comment]
@bobsummerwill thanks. Yeah. 
Also had same problem with the installer on 64bit windows 8.1.. Haven't got round to bringing it up to 10,but sounds like OP had same issue on 10.

**Comment by bobsummerwill** [comment]
Yes ... we don't appear to have many people using the Windows build, so it is somewhat unlovely, I am afraid.     I only did my first Windows build a few days back.

**Comment by gmdeo** [comment]
@bobsummerwill would you then suggest I hold off for a bit?

**Comment by bobsummerwill** [comment]
Well, in as much as that I doubt that moving to a newer Windows version would resolve this issue :-)

But certainly using Windows 8.1 or Windows 10 would bring you more in line with everybody else, and make it less likely you will hit unique issues.

**Comment by bobsummerwill** [comment]
Installer has been removed.
