### ISSUE TITLE
Mining suddenly stopped

### ISSUE THREAD

**Issue by ghost** [ethereum/webthree-umbrella#14]
Moved here from [cpp-ethereum](https://github.com/ethereum/cpp-ethereum/issues/2979)

While running mining node with 150 workers - node mined few blocks and then stucked, i saw it was generating valid getwork and receiving with submitHashrate, but it couldn't solve block for 12hours, while it's regularly solving at least one block per 1 hour, i thought it was bad luck, but i have reproduced this again.

**Comment by bobsummerwill** [comment]
Hey @karek314!
I know this is super-old and was never answered.   I'm just triaging through issues.
Are you still doing any eth mining?   See any value in trying to replicate?
What version was this with?
If no value, let's just close it.
