### ISSUE TITLE
windows debug evmjit compile error

### ISSUE THREAD

**Issue by winsvega** [ethereum/webthree-umbrella#140]
WIN7x64 everything builds fine except evmjit under debug with the following errors:

Error   1   error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in JIT.obj  E:\Ethereum\webthree-umbrella\build\libethereum\evmjit\libevmjit\LLVMCore.lib(MetadataTracking.obj) evmjit
Error   2   error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in JIT.obj  E:\Ethereum\webthree-umbrella\build\libethereum\evmjit\libevmjit\LLVMCore.lib(MetadataTracking.obj) evmjit

**Comment by bobsummerwill** [comment]
Closed as dupe of https://github.com/ethereum/webthree-umbrella/issues/123.
