### ISSUE TITLE
Windows Server 2012 R12 on AWS GPU-Based Instance

### ISSUE THREAD

**Issue by moamin77** [ethereum/webthree-umbrella#141]
Hi,

I've tried to set the AlethOne on Windows Server 2012R12 base on AWS instance g2.2X.large (GPU based); the following issues appear in sequence:
1- The missing DLL files issue; I've to copy them manually to the same folder as the Alethone.exe & retried...it worked
2- Though the selected folder for the AlethOne installation is chosen to be on a separate Disk partition (other than C); the synced blocks & everything else kept to be saved on the C drive eating it totally (how could that path be changed?)
3- When the sync is done & the miner was preparing to get started; it hanged completely giving the same error message of "noACL-platform found"....I installed the Nivida drivers & restarted the VM with no use....same error!

Thanks in advance for the help/support

**Comment by bobsummerwill** [comment]
AlethOne is discontinued, so this will never be addressed.   Sorry!
