### ISSUE TITLE
Remove command-line applications which we don't plan to support

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#142]
We had talked about dropping flu and ext, because we don't plan to support them.
Shall we just delete them?
Another other "fluff" which it would make sense to trim from the repository?

CC @smartbitcoin - and see also https://github.com/ethereum/webthree-umbrella/issues/137 for the start of some static analysis of the workspace.

**Comment by chriseth** [comment]
flu shall be integrated into eth, but we can keep the actual binary for now.

**Comment by bobsummerwill** [comment]
Pondering removal of AlethFive and AlethZero for Homestead.
Thoughts, @chriseth?

This long-standing stinker - https://github.com/ethereum/webthree-umbrella/issues/265 - is only in AlethFive, and I'm thinking that it might be easier just to remove AlethFive and AlethZero now.   Might invalidate some other bugs too, like https://github.com/ethereum/webthree-umbrella/issues/217.

**Comment by bobsummerwill** [comment]
@chriseth on gitter -  if you want, you can investigate whether flu can do stuff that eth cannot.

Will do!

**Comment by chriseth** [comment]
Please remove alethfive and flu, but keep alethone, alethzero.
I just checked and it seems that the only thing flu has that eth does not have is a benchmarking mode (measuring transactions per second with disabled ethash). I would prefer writing a simple nodejs-rpc-script for such a benchmark.
