### ISSUE TITLE
Cannot set JSON-RPC password on CLI

### ISSUE THREAD

**Issue by got3nks** [ethereum/webthree-umbrella#145]
$ eth --version
eth version 1.0.0
eth network protocol version: 61
Client database version: 12041
Build: Linux/g++/int/Release

Client mode (default):
    -j,--json-rpc  Enable JSON-RPC server (default: off).
    --admin <password>  Specify admin session key for JSON-RPC (default: auto-generated and printed at start-up).

$ eth -j --admin passphrase
Invalid argument: --admin

**Comment by chriseth** [comment]
This is not supported by geth, so we might also drop this feature.

**Comment by got3nks** [comment]
So there's no way to configure a JSON-RPC password? Or am I missing something?

**Comment by chriseth** [comment]
There should be, but it seems it is broken. As we will remove this functionality soon, this bug will not be fixed.
