### ISSUE TITLE
Error: URL using bad/illegal format or missing URL

### ISSUE THREAD

**Issue by Xploit3r** [ethereum/webthree-umbrella#148]
The web3.eth commands do not work from the console on Win 7 with Ethereum version 1.0.1. I see "URL using bad/illegal format or missing URL" against a lot of values
does anyone know why this happens and how can I get it working? I ran "eth console" in one instance of command prompt. It is synchronized upto 924668 block number. Now, I opened a new instance of command prompt and typed in, "eth attach" to interact with the already running ethereum client. However, the web3.eth commands are giving error messages.

as an example, here is the output for web3.eth.blockNumber command

`web3.eth.blockNumber
(shell):5766: URL using bad/illegal format or missing URL
var result = this.provider.send(payload);
^
←[31mError: ←[0mUncaught URL using bad/illegal format or missing URL←[0m`

Please help resolve this issue.

Note: I installed Ethereum on Windows using the precompiled binary here: https://github.com/ethereum/webthree-umbrella/release

**Comment by chriseth** [comment]
@yann300 you are currently looking into this, right?
