### ISSUE TITLE
eth should accept manually added peers with private ip addresses

### ISSUE THREAD

**Issue by chriseth** [ethereum/webthree-umbrella#150]
Private ip addresses should be rejected if they are received via some automatic mechanism (because we can assume that they are behind NAT in some other network), but if they are added manually via addPeer, eth should connect to them.

**Comment by winsvega** [comment]
ok. so it seems that eth already accept private addresses if added with addPeer

**Comment by chriseth** [comment]
Great, that was my impression from the latest tests. So this can be closed?

**Comment by winsvega** [comment]
but does eth reject private addresses ? 
I guess it wont add a Peer if it can't connect to it anyway.

**Comment by chriseth** [comment]
If you can use addPeer to connect to another node via a private IP address in the same network, this issue can be closed.

**Comment by chriseth** [comment]
Confirmed working.
