### ISSUE TITLE
eth uses a lot of cpu when "idle"

### ISSUE THREAD

**Issue by chriseth** [ethereum/webthree-umbrella#151]
When fully synced and not mining, eth still maxes out one core.

It seems that `Client::syncTransactionQueue` is called quite often from `Client::doWork`, even if no new transactions arrive, probably because there is a bug related to the flag `m_syncTransactionQueue`, which seems to be reset to `true` as part of the `syncTransactionQueue` call.

Another thread that is always quite active is the RLPX handshake, especially the signature verification seems to use a lot of CPU cycles. This can be solved by moving from CryptoPP to secp256k1, go-ethereum did the same move in the past.

**Comment by smartbitcoin** [comment]
I do a fresh build from 1.1.2,  fully sync ,  can't recreate those high CPU usage yet.  CPU is like  < 1% all the time. 
Any hint how to burn the CPU to high usage from eth?

**Comment by smartbitcoin** [comment]
can't recreate those high CPU usage scenario.  close it just for now.

**Comment by bobsummerwill** [comment]
Moved to https://github.com/ethereum/cpp-ethereum/issues/3224
