### ISSUE TITLE
How are we generating Homebrew bottles?

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#153]
Hey @LefterisJP,

I don't see where the Homebrew bottling is happening for webthree-umbrella.

eth-jenkins-bot is commiting updates to:

https://github.com/ethereum/homebrew-ethereum/commits/master/cpp-ethereum.rb

But I don't see where in the Jenkins setup that is happening.

Specially, we're missing bottles for El Capitan (see https://github.com/ethereum/homebrew-ethereum/issues/45#issuecomment-178372789), but I don't even see where the bottles for Yosemite are coming from :-)

**Comment by chriseth** [comment]
Jenkins creates the bottles. My guess is that it cannot cross-create bottles.

**Comment by bobsummerwill** [comment]
We would need two OS X machines within Jenkins for sure.

What I am missing is where in the Jenkins setup the bottle creation is happening.    I can't see where it is happening.

**Comment by LefterisJP** [comment]
It's happening in the release build script and it calls those: 

https://github.com/ethereum/webthree-helpers/tree/develop/homebrew

Don't remember many of the details, and not sure if it was ever working properly. We did it with @debris but as I have no OSX machine I never tested it.

**Comment by bobsummerwill** [comment]
OK ... understood and fixed.
