### ISSUE TITLE
release tar ball does not contain webthree-helpers

### ISSUE THREAD

**Issue by 5chdn** [ethereum/webthree-umbrella#158]
the latest release 1.1.2 tarball does not contain webthree-helpers, only an empty directoy.

this is an issue trying to compile the source code. i have to manually clone the webthree helpers and copy the files in there. 

```
webthree-umbrella-1.1.2/build $ cmake ..
CMake Error at CMakeLists.txt:13 (include):
  include could not find load file:

    EthPolicy

CMake Error at CMakeLists.txt:14 (eth_policy):
  Unknown CMake command "eth_policy".

-- Configuring incomplete, errors occurred!
```

is it possible you could include webthree-helpers in the release?

**Comment by chriseth** [comment]
As far as I know, github does not have an option to include the git submodules in the source tarball. You have to use git for building. It is explained here: https://github.com/ethereum/webthree-umbrella/wiki - make sure to checkout release (now) or v1.1.2 (after the next release) on webthree-umbrella.

**Comment by 5chdn** [comment]
ok, will stay on the git track for now. thanks
