### ISSUE TITLE
Implement modules RPC function

### ISSUE THREAD

**Issue by chriseth** [ethereum/webthree-umbrella#161]
It seems that implementing the "modules" RPC method should be the only thing needed to get "geth attach" working with an eth backend node.

Documentation about the method: https://github.com/ethereum/go-ethereum/wiki/Go-ethereum-management-API's

To be implemented in ModularServer.h

We have to check that we do not expose the admin interface via rpc unless requested (the output of the "modules" function should tell which interfaces are exposed).

**Comment by bobsummerwill** [comment]
Given that we are now implementing the admin API too, should there be an EIP to "promote" the admin API to be an (optional) official API across all clients?
