### ISSUE TITLE
Docs needed for - simple nodejs admin console as replacement for eth console

### ISSUE THREAD

**Issue by chriseth** [ethereum/webthree-umbrella#163]
We should deprecate the v8 console inside eth and provide a very simple nodejs application that can connect via ipc.
This should provide a basic console:

```
var Web3 = require('web3');
var repl = require('repl');
var net = require('net');

console.log("Connecting to node...");
web3 = new Web3(new Web3.providers.IpcProvider('/home/user/.ethereum/geth.ipc',net));
web3.eth.getBlockNumber(function(err, number) {
    console.log("Connection successful.");
    console.log("Current block number: " + number); 
    console.log("Entering interactive mode.");
    var replServer = repl.start({});
});
```

To be added: Smarter detection of the ipc socket location, commandline arguments, fallback to http, admin interface.

Some help: https://github.com/ethereum/mist/blob/master/modules/ipc/getIpcPath.js
https://github.com/ethereum/mist/blob/master/modules/web3Admin.js

**Comment by chriseth** [comment]
Created application here: https://github.com/ethereum/ethereum-console
Would someone please update our documentation?
We will remove the console for 1.3.0

**Comment by bobsummerwill** [comment]
Thanks - I will document.

**Comment by chriseth** [comment]
Documentation might already be in the homestead guide. let's check and close in case.

**Comment by chriseth** [comment]
@yann300 this is basically the same thing as the other story I just assigned to you :-)

**Comment by yann300** [comment]
PR https://github.com/ethereum/homestead-guide/pull/183
