### ISSUE TITLE
Light client protocol

### ISSUE THREAD

**Issue by chriseth** [ethereum/webthree-umbrella#176]
Bob plans to do this work himself, if nobody else steps up!

See [doublethinkco Milestone 3 - Light Client Phase 1](https://github.com/doublethinkco/webthree-umbrella-cross/milestones/Milestone%203%20-%20Light%20Client%20Phase%201)

**Comment by bobsummerwill** [comment]
[doublethinkco Milestone 3 - Light Client Phase 1](https://github.com/doublethinkco/webthree-umbrella-cross/milestones/Milestone%203%20-%20Light%20Client%20Phase%201)

**Comment by bobsummerwill** [comment]
This issue was moved to ethereum/cpp-ethereum#3101
