### ISSUE TITLE
AlethOne: password delay

### ISSUE THREAD

**Issue by chriseth** [ethereum/webthree-umbrella#179]
Upon startup in all nodes, there is a delay after entering the master key for a newly generated keystore - probably because of the KDF.
This is especially annoying for AlethOne, because we do not really get a feedback what is happening.

**Comment by winsvega** [comment]
for how long? 
In debug build I have a delay when entering a password for the first time of about 5-6 sec.
not really annoying

**Comment by chriseth** [comment]
The problem is that there is no indication that it could take 5-6 seconds. We should display some dialog window there. If this turns out to be more complicated, let us just close this issue.
