### ISSUE TITLE
Delegate compiling of IPC transfer mechanism to build system

### ISSUE THREAD

**Issue by chriseth** [ethereum/webthree-umbrella#187]
Wishlist for code cleanup. 

The IPC transfer mechanism's compiling, which is either Unix Sockets or named pipes in Windows should be cleaned up. 

Right now both [UnixSocketServer.cpp](https://github.com/ethereum/webthree/blob/develop/libweb3jsonrpc/UnixSocketServer.cpp) and [WinPipeServer](https://github.com/ethereum/webthree/blob/develop/libweb3jsonrpc/WinPipeServer.cpp) are wrapped in conditional #ifndef. That's not the way to go.

The OS specific compiling should be delegated to the build system . There should be a conditional in cmake which would include the appropriate file for compiling depending on the OS.

**Comment by bobsummerwill** [comment]
This issue was moved to ethereum/cpp-ethereum#3103
