### ISSUE TITLE
Attribution

### ISSUE THREAD

**Issue by chriseth** [ethereum/webthree-umbrella#189]
Fix attributions in about and help pages

**Comment by bobsummerwill** [comment]
Yeah - I see that there are inconsistencies in these, and lots of cut-and-paste code.

Also neither of these formulations are great:
- By Gav Wood and the Berlin ÐΞV team, 2014, 2015.\nSee the README for contributors and credits.
- Code by Gav Wood et al, (c) 2013, 2014, 2015

Does the Ethereum Foundation holds the copyright?   It probably should, shouldn't it?

**Comment by bobsummerwill** [comment]
How does the Linux Kernel do credits/attribution?

**Comment by bobsummerwill** [comment]
So we now have:

https://github.com/ethereum/alethzero/blob/develop/alethzero/AlethZero.cpp#L200
    By the Berlin ÐΞV team, 2014, 2015, 2016.
And
https://github.com/ethereum/libethereum/blob/develop/ethminer/MinerAux.h#L80
    Ethereum (++)
    Code by Berlin ÐΞV team, (c) 2013, 2014, 2015, 2016.

Which is better, but still location-specific.    How about "Ethereum C++ contributors", or "cpp-ethereum contributors" ?

Are we going to do a scoot through on all the @author fields too?   Those are just noise, with the exception of ones in third-party code which had those already, like code from Bitcoin, etc.

**Comment by chriseth** [comment]
Right, cpp-ethereum contributors sounds good and fits the license headers in the individual files (which say "this is part of cpp-ethereum"). This is only about text visible in the UI or cmdline interface, not about e.g. author fields in source files.

**Comment by bobsummerwill** [comment]
Right.

Want to split out a separate issue for author attribution in source code?   So we can close this ASAP, and   look at the rest of the source code as another pass?

Have you seen https://github.com/ethereum/go-ethereum/blob/master/AUTHORS?    I like the simplicity of their approach a lot.

**Comment by chriseth** [comment]
Let's not care about authors in the files. Some document says that they just list the initial author or maintainer. The actual authors are stored in the git history. I don't think that go-ethereum's AUTHORS file is up to date, there is only one revision of it.

**Comment by bobsummerwill** [comment]
Works for me.    So the only "list" we maintain is in the README?   Actually multiple READMEs.

**Comment by LianaHus** [comment]
the Pr's are already merged, I think we can close the issue
