### ISSUE TITLE
Ethminer blocks found sent to 0x0000000000000000000000000000000000000000

### ISSUE THREAD

**Issue by billprescott** [ethereum/webthree-umbrella#190]
Hi

Even though I have a valid unlocked coinbase in my keystore and geth is showing this address, ethminer is finding blocks but they are being credited to 0x0000000000000000000000000000000000000000.

geth,.log says.

I0210 05:28:36.776156 miner/worker.go:349] ð¨  Mined block (#978936 / 6806d574). Wait 5 blocks for confirmation. 

No message after that, it just continues mining. I would expect that if it was not accepted it would become stale "Uncle" ?

This has happened 5 times over the last 5 days.

Could this be a bug?

thanks

**Comment by bobsummerwill** [comment]
You mention geth on several occasions, @billprescott, which is the go client.
This repo is the C++ client.
If this is a geth issue, please could you close this ticket and log a new one at http://github.com/ethereum/go-ethereum, please?   Best wishes.

**Comment by billprescott** [comment]
Is it not ethminer that works with geth? Not sure where the issue is? Happy to create a case for geth as well.

**Comment by fjl** [comment]
This was an issue with geth from the develop branch. It is fixed.

**Comment by bobsummerwill** [comment]
Thanks, @fjl :-)

So I'll close this issue if this is/was a geth issue, @billprescott.   Hope you get your miner going soon.   Best wishes.

**Comment by billprescott** [comment]
Ok thanks.
