### ISSUE TITLE
Mac OS Yosemite, unexpected crash of all three apps.

### ISSUE THREAD

**Issue by dth88** [ethereum/webthree-umbrella#191]
am i missing something? it just crashes on startup

**Comment by bobsummerwill** [comment]
Hey there, @dathbezumniy!

Did you install via Homebrew or build your own from source?   Or get them via https://ethereum.org/cli?

Any information which can help narrow this down would be very useful.

**Comment by bobsummerwill** [comment]
And the three apps being AlethZero, AlethOne and Mix?

**Comment by dth88** [comment]
got all of them from recent release https://github.com/ethereum/webthree-umbrella/releases

**Comment by dth88** [comment]
beforehand tried to install with homebrew but no luck, got into dylb problem and couldnt fix it

**Comment by chriseth** [comment]
Might be a duplicate of #160

**Comment by chriseth** [comment]
Could you please try if the latest release (1.1.3) still has this problem?

**Comment by bobsummerwill** [comment]
Closing, because there is a more recent identical issue - https://github.com/ethereum/webthree-umbrella/issues/362.
