### ISSUE TITLE
eth -r remoteIP:port not working

### ISSUE THREAD

**Issue by smartbitcoin** [ethereum/webthree-umbrella#192]
from eth command line  -r ( or --remote ) not working for adding a remote node.

**Comment by winsvega** [comment]
1) do you type it like this?
eth -r xxx.xxx.xxx.xxx --port xxxxx 

2) do you run eth behind NAT ?

**Comment by chriseth** [comment]
@winsvega there is no code that parses the port. Do you want to implement it?

**Comment by winsvega** [comment]
https://github.com/ethereum/webthree/blob/775e1181be14f53d8de8e95087708404175089d1/eth/main.cpp#L449

https://github.com/ethereum/webthree/blob/775e1181be14f53d8de8e95087708404175089d1/eth/main.cpp#L1244

**Comment by chriseth** [comment]
@winsvega this is not about `--port`, it is about `-r`. `-r` should check whether the argument ends in `:<number>` and assign that number to `remotePort`, the rest to `remoteHost`.

**Comment by winsvega** [comment]
I see. I could do this. But I have problems with eth console so I would need someone to review and test

**Comment by winsvega** [comment]
btw 
eth -r xxx.xxx.xxx.xxx --port xxxxx

wont work for me

**Comment by winsvega** [comment]
https://github.com/ethereum/webthree/pull/123
