### ISSUE TITLE
Clear up licensing

### ISSUE THREAD

**Issue by chriseth** [ethereum/webthree-umbrella#197]
Fix file headers according to https://github.com/ethereum/wiki/wiki/Licensing

**Comment by bobsummerwill** [comment]
Is this referring to missing licensing text on various files in the repos?

Or referring to some ambiguity about the status of the licence used?   We flipped from GPL to MIT, right?

**Comment by chriseth** [comment]
We changed some parts to MIT, but it is not yet reflected in the file headers.

**Comment by bobsummerwill** [comment]
In progress and covered in other issues.
