### ISSUE TITLE
Unknown CMake command "eth_policy"

### ISSUE THREAD

**Issue by bumbar1** [ethereum/webthree-umbrella#198]
Trying to build the latest release/develop branch, I get error:

```
# cmake -DGUI=0 -DTESTS=0 -..
CMake Error at CMakeLists.txt:13 (include):
  include could not find load file:

    EthPolicy


CMake Error at CMakeLists.txt:14 (eth_policy):
  Unknown CMake command "eth_policy".


-- Configuring incomplete, errors occurred!
```

**Comment by chriseth** [comment]
This might be a duplicate of #158 - did you check out all the submodules?

**Comment by bumbar1** [comment]
Forgot to recursive clone the repo. Builds fine.

**Comment by bobsummerwill** [comment]
Maybe we can improve the error message here?
https://github.com/ethereum/webthree-umbrella/issues/202
