### ISSUE TITLE
Easy way to start with NoProof and private network

### ISSUE THREAD

**Issue by LefterisJP** [ethereum/webthree-umbrella#199]
Provide an easy way to start an eth node with NoProof engine and custom network.

**Comment by smartbitcoin** [comment]
Agree with that.  but one thing need to be done first .   the fluidity have a benchmark model which can be used for testing TPS.   We need move those functions into the bench project.

**Comment by bobsummerwill** [comment]
I agree.   We need to manage scope, after harvesting any goodness from flu.

See also https://github.com/ethereum/webthree-umbrella/issues/142.

**Comment by chriseth** [comment]
@LefterisJP what is the actual problem? As far as I understad:
- fix connectivity to private ip addresses (just create an issue for that)
- fix the way how the genesis-json is provided

Apart from that, I would really like to add `--dev`, as geth has which creates a random test chain with tiny difficulty.

**Comment by LefterisJP** [comment]
@chriseth A lot of things don't work due to the private chain functionality being half-moved to eth.

Last time I tried to create a private chain with custom genesis json with eth it was impossible.

Having a --dev flag would be highly useful for debugging and developing. :+1:

**Comment by bobsummerwill** [comment]
This issue was moved to ethereum/cpp-ethereum#3104
