### ISSUE TITLE
libp2p libdevcrypto  should not depends on test or have any link into test folder

### ISSUE THREAD

**Issue by ghost** [ethereum/webthree-umbrella#20]
Moved here from [cpp-ethereum](https://github.com/ethereum/cpp-ethereum/issues/2973)

test/JsonSpiritHeaders.h  need move into a common place since it was hard included in libp2p and libdevcrypto etc.

this is a bad coding practice to make a library build depends on head file in test directory.

**Comment by debris** [comment]
it was fixed during repo reorganization. json spirit headers are now placed in [utils directory](https://github.com/ethereum/webthree-helpers/tree/develop/utils)
