### ISSUE TITLE
OS X - Lock into LLVM 3.7.1 for Homebrew

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#201]
While working on the OS X build, we've had various reliability issues with LLVM.

https://github.com/ethereum/libethereum/pull/184

We're using HEAD, which is utterly unstable from day-to-day, even more so that our other rolling dependencies.

I tried to use 3.7.1 a week or two back, using `homebrew install llvm37`, but it fell over because of CMake changes.   Looks like the CMake files just moved directory, so maybe this is an easy fix, and we can lock this one dependency down?

See https://github.com/ethereum/webthree-umbrella/issues/89#issuecomment-183201570.

**Comment by LefterisJP** [comment]
Our stuff work with llvm 3.7 for sure. I don't know how homebrew works but if it has rolling releases beware, llvm 3.8 is about to be released.

**Comment by bobsummerwill** [comment]
It is ONLY rolling releases, @LefterisJP :-)   Big stability problem.

https://github.com/ethereum/webthree-umbrella/wiki/Building-on-OS-X
https://github.com/ethereum/webthree-umbrella/issues/118

Given that there has been the 3.7.1 release, attempting to lock back to that seems rational, to me at least, though I'm not sure what LLVM versions we're using on Windows and the various Linux distros.

**Comment by bobsummerwill** [comment]
Done with https://github.com/ethereum/libethereum/pull/194
