### ISSUE TITLE
Move "turboethereum guide" to docs folder in webthree-umbrella

### ISSUE THREAD

**Issue by chriseth** [ethereum/webthree-umbrella#210]
Source is here: https://github.com/ethereum/guide

**Comment by bobsummerwill** [comment]
So this is a gitbook.   Where is the source repo?
Is it a private repo under gavofyork's account?

WRT the Homestead docs, I was thinking it would be appropriate for us to update the TurboEthereum docs.

**Comment by chriseth** [comment]
Updated.

**Comment by bobsummerwill** [comment]
Done.
Will continue slewing content OUT of this, tracking working in  https://github.com/ethereum/webthree-umbrella/issues/250.
