### ISSUE TITLE
Arch Linux - Build fails

### ISSUE THREAD

**Issue by markusmazurczak** [ethereum/webthree-umbrella#212]
I am not able to build ethereum under Arch Linux (not release branch nor develop branch).
I am running an Arch Server with kernel 
`4.3.3-3-ARCH #1 SMP PREEMPT Wed Jan 20 08:12:23 CET 2016 x86_64 GNU/Linux`

I am using V8 from the [Arch AUR Repo](https://aur.archlinux.org/packages/v8/).

During make the following error occures:

> Scanning dependencies of target mix_BuildInfo.h
> [  5%] Built target mix_BuildInfo.h
> [  5%] Building CXX object libethereum/evmjit/libevmjit/CMakeFiles/evmjit.dir/JIT-c.cpp.o
> /data/ethereum/webthree-umbrella/webthree/libjsengine/JSV8Printer.cpp: In member function ‘virtual dev::eth::JSString dev::eth::JSV8Printer::prettyPrint(const dev::eth::JSV8Value&) const’:
> /data/ethereum/webthree-umbrella/webthree/libjsengine/JSV8Printer.cpp:40:29: error: ‘New’ is not a member of ‘v8::String’
>   v8::Localv8::String pp = v8::String::New("prettyPrint");
>                              ^
> /data/ethereum/webthree-umbrella/webthree/libjsengine/JSV8Printer.cpp:42:76: error: no matching function for call to ‘v8::Localv8::Value::New(v8::Handlev8::Value&)’
>   v8::Localv8::Value values[1] = {v8::Localv8::Value::New(_value.value())};
>                                                                             ^
> In file included from /data/ethereum/webthree-umbrella/webthree/libjsengine/JSV8Engine.h:27:0,
>                  from /data/ethereum/webthree-umbrella/webthree/libjsengine/JSV8Printer.h:26,
>                  from /data/ethereum/webthree-umbrella/webthree/libjsengine/JSV8Printer.cpp:24:
> /usr/include/v8.h:303:29: note: candidate: static v8::Local<T> v8::Local<T>::New(v8::Isolate_, v8::Local<T>) [with T = v8::Value]
>    V8_INLINE static Local<T> New(Isolate_ isolate, Local<T> that);
>                              ^
> /usr/include/v8.h:303:29: note:   candidate expects 2 arguments, 1 provided
> /usr/include/v8.h:304:29: note: candidate: static v8::Local<T> v8::Local<T>::New(v8::Isolate_, const v8::PersistentBase<T>&) [with T = v8::Value]
>    V8_INLINE static Local<T> New(Isolate_ isolate,
>                              ^
> /usr/include/v8.h:304:29: note:   candidate expects 2 arguments, 1 provided
> /usr/include/v8.h:335:29: note: candidate: static v8::Local<T> v8::Local<T>::New(v8::Isolate_, T_) [with T = v8::Value]
>    V8_INLINE static Local<T> New(Isolate\* isolate, T\* that);
>                              ^
> /usr/include/v8.h:335:29: note:   candidate expects 2 arguments, 1 provided
> webthree/libjsengine/CMakeFiles/jsengine.dir/build.make:71: recipe for target 'webthree/libjsengine/CMakeFiles/jsengine.dir/JSV8Printer.cpp.o' failed
> make[2]: **\* [webthree/libjsengine/CMakeFiles/jsengine.dir/JSV8Printer.cpp.o] Error 1
> CMakeFiles/Makefile2:2880: recipe for target 'webthree/libjsengine/CMakeFiles/jsengine.dir/all' failed
> make[1]: **\* [webthree/libjsengine/CMakeFiles/jsengine.dir/all] Error 2
> make[1]: **\* Waiting for unfinished jobs....

**Comment by bobsummerwill** [comment]
Hey there!

I think your V8 is too new.   We're using 3.15 successfully on OS X.

There was another ticket talking about this exact issue, but I can't find it right now.   @LefterisJP?   How can Markus install an older V8?

Do the https://github.com/ethereum/webthree-umbrella/wiki/Building-on-ArchLinux instructions need updating, based both on V8 and json-rpc-cpp issues?

**Comment by bobsummerwill** [comment]
Hey @markusmazurczak!   You still there?  I'll close this soon if you aren't still blocked.

**Comment by LefterisJP** [comment]
I am using 3.15 v8 too. From [here](https://aur.archlinux.org/packages/v8-3.15/). @markusmazurczak please use that one and your problem should be solved.

**Comment by bobsummerwill** [comment]
Thanks for the link, @LefterisJP.

Good luck, @markusmazurczak.   If you continue to have build issues, please open a new issue, and we'll try to keep you moving.   Thanks.
