### ISSUE TITLE
Remove bad block sentinel from libethereum

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#215]
There is the skinniest of skinnest dependency on JsonRpc within libethereum which "smells" a bit to me:

```
    jsonrpc::HttpClient client(m_sentinel);
    Sentinel rpc(client);
    try
    {
        rpc.eth_badBlock(report);
    }
```

Looks like it would be better served using some kind of listener interface, to break the implementation dependency on JsonRpc within libethereum, considering that is the ONLY libethereum -> "web" dependency.

**Comment by chriseth** [comment]
We might remove this alltogether, let me check.

**Comment by chriseth** [comment]
Yes, please remove this whole thing.

**Comment by bobsummerwill** [comment]
Even better!
