### ISSUE TITLE
JSON-RPC sendTransaction asking for prompt

### ISSUE THREAD

**Issue by got3nks** [ethereum/webthree-umbrella#216]
Hello, when I try to send a transaction through JSON-RPC's eth_sendTransaction I get a prompt on the eth client to process the transaction:

ÐApp is attempting to send ... to a recipient ... with additional network fees of up to ...
Maximum total cost is ....
Enter yes/no/always (always to this address):

Is there a way to disable the prompt, so that I can send transactions automatically?

Thanks.

**Comment by LefterisJP** [comment]
as @arkpar stated in gitter add the `--unsafe-transactions` argument
