### ISSUE TITLE
OS X - Try to eliminate --with-d-bus from our Qt usage

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#217]
Do we actually NEED Qt --with-d-bus?

Our CMake files are enforcing that, but nobody has been able to identify whether or not we actually need to use that non-default Qt variant.

We should try removing that scaffolding from our build system, and see if we can still build-and-link.   If we can then we should eliminate that stuff, and remove the option from our Homebrew formula.   Then we can use the bottles, and save (on my machine) 9 hours of building from source!

**Comment by chriseth** [comment]
alethzero seems to need it, alethone seems to not need it.

**Comment by bobsummerwill** [comment]
That analysis is on the basis of the existing build files, right, @chriseth?

Not on actually trying to strip it out, and seeing what happens, which is what I think we really need to do, because the dependency is probably indirectly, in one of the libraries we are using or similar.   At least, nobody has so far found any of OUR code which is using DBus directly.

**Comment by chriseth** [comment]
source of analysis: `ldd <binary>`

**Comment by bobsummerwill** [comment]
Aha.    But that would still be the case even if no symbols were actually used, wouldn't it?

**Comment by bobsummerwill** [comment]
All Qt is gone, so done!
