### ISSUE TITLE
Make randomness thread-safe

### ISSUE THREAD

**Issue by chriseth** [ethereum/webthree-umbrella#218]
At some places, we use rand() and other randomness functions. We should perhaps create one randomness generator seeded from /dev/urandom and make access to it thread-safe.
Only where cryptographic randomness is needed, we should access /dev/urandom (boost::random_device), otherwise it might be possible to deplete entropy required for actual cryptography.

**Comment by bobsummerwill** [comment]
This issue was moved to ethereum/cpp-ethereum#3105
