### ISSUE TITLE
Warnings-as-errors on all platforms

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#219]
We appear NOT to have warnings-as-errors, at least on OS X, and maybe on other platforms.

We should fix any remaining errors and enable warnings-as-errors.   Maintaining a "no warnings at all times" policy is the single simplest thing I've found in my career to improve code quality and to address "broken windows".

**Comment by chriseth** [comment]
This will not work for clang and Mix because Qt headers have some annoying warnings, they would have to be disabled on a per-header basis.

**Comment by bobsummerwill** [comment]
Right.    I've had to do that before.   It's not so bad.

Think of it as a warnings-condom :-)

**Comment by bobsummerwill** [comment]
DONE!
