### ISSUE TITLE
Disable unreliable Whisper tests

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#220]
While we aren't actively working on Whisper, it is probably a net-negative to have unreliability in our tests, and it would be better to just remove these unreliable tests for the time being.

They can be re-added when we are actively working on Whisper again.

**Comment by chriseth** [comment]
The reason for the test failures might be network port clashes with other test runs (or the same) on the same machine. Network ports in tests should always be randomized.

An example test log can be found here: https://gist.github.com/chriseth/73e9f6a2d57fbda60ef0

**Comment by bobsummerwill** [comment]
Interesting.   Which tests in particular are the unreliable ones?
Have you seen these, @winsvega ?

**Comment by chriseth** [comment]
This here happens quite often: https://gist.github.com/chriseth/73e9f6a2d57fbda60ef0

**Comment by bobsummerwill** [comment]
Right - thanks for the link.

**Comment by chriseth** [comment]
@LianaHus Is this done?

**Comment by LianaHus** [comment]
most of them yes are disabled.

**Comment by LianaHus** [comment]
I'm not sure if we need to disable of of them from the build

**Comment by chriseth** [comment]
Ok, I will close this for now, thanks!
