### ISSUE TITLE
Support geth keys

### ISSUE THREAD

**Issue by chriseth** [ethereum/webthree-umbrella#221]
We should use the same location and key file format as geth uses with an additional fallback at our old location and auto-import the keys to the geth location.

**Comment by winsvega** [comment]
**eth keys** are located at 

```
.web3/keys 
```

and has format of 

```
643e04fb-a9ee-6cd6-3c42-f302621358ed.json

{
    "address" : "eff6c63f5a01b9c21b135b14ecd903bead4f5037",
    "crypto" : {
        "cipher" : "aes-128-ctr",
        "cipherparams" : {
            "iv" : "d21eb60f79478fb3468089974ad4b60c"
        },
        "ciphertext" : "1e40c8874c9d12f318a63fcffea49165bac4964ff57bbfe23bdc6113b6594bd6",
        "kdf" : "scrypt",
        "kdfparams" : {
            "dklen" : 32,
            "n" : 262144,
            "p" : 1,
            "r" : 8,
            "salt" : "8f3ad2d4b778d879fc966383ad1566eeaaa8af2373fda80a631036ceb49d25e9"
        },
        "mac" : "f1559205648af50a4f15321408e3ce3d2abfc2e9621a97f186ba7f0a2aae0a34"
    },
    "id" : "643e04fb-a9ee-6cd6-3c42-f302621358ed",
    "version" : 3
}
```

**geth keys** are stored at 

```
.ethereum/keystore
```

and has format of 

```
UTC--2016-03-07T11-43-32.506692689Z--427db35174ccf39e27d447a563f27b0014902ee3

{"address":"427db35174ccf39e27d447a563f27b0014902ee3","Crypto":{"cipher":"aes-128-ctr","ciphertext":"27f5a0987cc9ab912fb3c1e57d4a5b889e718404c530594c683e89f17d58d687","cipherparams":{"iv":"8f469700627a1f901d4a14c214e492d1"},"kdf":"scrypt","kdfparams":{"dklen":32,"n":262144,"p":1,"r":8,"salt":"8a4706a47d283b2821b701d9fb469395640e799b2397e3792ca7a6ae3612a03d"},"mac":"5ea13a9e959149ef36b5c96fadb4b3dfd8beb5ae4740c903c37015a28e7015d4"},"id":"9d621576-e9ef-47e2-ae8f-08b5893dbef8","version":3}
```

**Comment by winsvega** [comment]
so **eth** should add new keys to .ethereum/keystore in geth format. and also open old keys from .web3/keys

should eth reimport old keys from .web3/keys  into .ethereum/keystore  and convert it to geth format? 

 @yann300, was there some work done with old keys? there was a  warning about keys and it's format in eth.

**Comment by chfast** [comment]
Is there any standard/EIP about key file format? If not, should we propose one?

The file name geth is using is quite weird.

**Comment by chriseth** [comment]
There should be a standard for the contents. Filename format should not be relevant.

**Comment by bobsummerwill** [comment]
Did we address this, @chriseth?

**Comment by chriseth** [comment]
@winsvega can you try? Create a key in geth, copy to cpp-ethereum and see whether it is there.

**Comment by winsvega** [comment]
chcked this out. it works with geth keys.
