### ISSUE TITLE
Roll cpp-ethereum ARM binaries into PPA so they are available via apt-get

### ISSUE THREAD

**Issue by phonikg** [ethereum/webthree-umbrella#228]
I understand it may be a lower priority item, but I believe this is possible, especially by automating the x-compile work that doublethink.co has done.

**Comment by bobsummerwill** [comment]
From go-ethereum gitter ...

caktux: the ARM builds have been enabled for a while on Launchpad, so it's just a matter of getting cpp's debian configs in order, wherever those are now

**Comment by bobsummerwill** [comment]
This issue was moved to ethereum/cpp-ethereum#3111
