### ISSUE TITLE
ethkey should be able to inspect even without any wallet

### ISSUE THREAD

**Issue by LefterisJP** [ethereum/webthree-umbrella#229]
I would like to be able to inspect a key even without having a wallet path set. This used to work in the past but now it does not seem to work.

``` sh
./ethkey inspect --show-me-the-secret ~/.web3/keys/XXX.json

Couldn't open wallet. Does it exist?
```

Seems that Keymanager needs some rework [here](https://github.com/ethereum/libethereum/blob/develop/ethkey/KeyAux.h#L870) and probaly the password reading function path [here](https://github.com/ethereum/libethereum/blob/develop/ethkey/KeyAux.h#L841).

@chriseth any ideas?

**Comment by chriseth** [comment]
KeyManager is a higher-level interface over SecretStore. SecretStore can access a directory of key files (usually `~/.web3/keys/`) (or individual key files) and KeyManager stores additional information about those files in a json file in `~/.ethereum/keys.info`.

`ethkey` already has support for direct access to keys, but it refuses to operate if this configuration file for the KeyManager is not present.

**Comment by smartbitcoin** [comment]
I don't see any reason inspect mode need a wallet.  so we can simple patch it to make it works.  @chriseth , please confirm if you like the idea to inspect a key without wallet store.

**Comment by chriseth** [comment]
@smartbitcoin yes, ethkey should work without a wallet file. In fact, if possible (probably in multiple stages), even `eth` should be able to use keys that are not part of a wallet file.

**Comment by smartbitcoin** [comment]
patched by https://github.com/ethereum/libethereum/commit/3f15f0513a598dfea395d5b7a65e1be5c7e5b9fe
