### ISSUE TITLE
Mix Non-Responsive on Windows 10

### ISSUE THREAD

**Issue by taoteh1221** [ethereum/webthree-umbrella#230]
On Windows 10 I have fully synced the blockchain with AlethZero, and then fired up Mix. Mix is either unresponsive from the start (freezes the second it loads), or as soon as I go to resize the editing window it freezes. Have let it sit for a few minutes, and it still remains frozen. Here is the terminal screen contents minus the RPC requests:

> qrc:///QtQuick/Controls/Private/ScrollBar.qml:98:46: Unable to assign [undefined] to bool
> qrc:/QtQuick/Controls/TextArea.qml:728:24: Unable to assign [undefined] to QColor
> qrc:///QtQuick/Controls/Styles/Base/TextFieldStyle.qml:75: TypeError: Cannot read property '__contentHeight' of null
> qrc:///QtQuick/Controls/Styles/Base/TextFieldStyle.qml:75: TypeError: Cannot read property '__contentHeight' of null
> qrc:///QtQuick/Controls/Styles/Base/TextFieldStyle.qml:72:42: Unable to assign TextArea_QMLTYPE_168 to TextField_QMLTYPE_55
> qrc:///QtQuick/Controls/Private/ScrollBar.qml:95: TypeError: Cannot read property of null
> qrc:///QtQuick/Controls/Private/ScrollBar.qml:95: TypeError: Cannot read property of null
>   i  19:16:50.193|main  Killing blockchain & extras database (WithExisting::Kill).
>   i  19:16:50.233|main  Killing state database (WithExisting::Kill).
> qml: poi

**Comment by bobsummerwill** [comment]
Moved to https://github.com/ethereum/mix/issues/244.
