### ISSUE TITLE
Clarify expected Workflow

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#237]
Let's review https://github.com/ethereum/webthree-umbrella/wiki/Workflow and update it to reflect what we are actually doing NOW.

**Comment by chriseth** [comment]
Updated the wiki page. Please check and close this issue if appropriate.

**Comment by bobsummerwill** [comment]
OK - I gave it some edits too.
I assume that we'll be slewing alethzero issues into webthree-umbrella too?

Are we still using Pivotal Tracker for anything, or can we kill that now?

**Comment by chriseth** [comment]
PT is used for Solidity. It has a gigantic backlog sorted by priorities that would be hard to import.

**Comment by bobsummerwill** [comment]
Right.

Somehow, I was confusing issue tracking tools and documentation tools.

Solidity is where readthedocs started being used.   I had somehow conflated that with Waffle in my mind.
