### ISSUE TITLE
eth segfault EthashClient.cpp line39

### ISSUE THREAD

**Issue by winsvega** [ethereum/webthree-umbrella#239]
```
EthashClient* dev::eth::asEthashClient(Interface* _c)
{
    if (dynamic_cast<Ethash*>(_c->sealEngine()))
>>>>>   return &dynamic_cast<EthashClient&>(*_c);
    throw InvalidSealEngine();
}
```

Have a segfault in eth on this line. So what I did. 
1) run eth for some time
2) run eth attach and type web3 into the console  (everything works)
3) close eth through ctrl+c
4) run eth again for some time
5) run eth attach and type web3  (this time it wont work with segfault on line39) 

changing / deleting datadirectory won help... strange.

**Comment by chriseth** [comment]
Is this actually a segfault or rather an exception? Are you at develop with all subrepos?

**Comment by winsvega** [comment]
std::bad_cast  exception
let me check that every single repo is synced with develop

**Comment by winsvega** [comment]
umbrella/webthree/eth/main.cpp: In function ‘int main(int, char**)’:
umbrella/webthree/eth/main.cpp:995:19: error: ‘class dev::eth::Client’ has no member named ‘setSentinel’
  web3.ethereum()->setSentinel(sentinel);

this path is outdated to the latest develop

**Comment by chriseth** [comment]
This is certainly outdated. `setSentinel` was removed.
