### ISSUE TITLE
OS X - Homebrew "release-build" is, I think unnecessary (or incorrect)

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#242]
We have Jenkins homebrew automation triggered for both the develop and release branches of webthree-umbrella, and they both update the same Homebrew formula file.   They were stomping each other until I fixed that a few days ago with an edit to a .sh script within Jenkins.

Now they're not stomping anymore, but I think that having both is at least unnecessary and possibly incorrect.

Here is what they update:

https://github.com/ethereum/homebrew-ethereum/blob/master/cpp-ethereum.rb

And looking at commits to the umbrella today, for the 1.1.4 release, we see this commit to develop, which happened 5 hours ago, and the corresponding update to the generated Formula which happened 4 hours ago:

https://github.com/ethereum/webthree-umbrella/commit/413f6246a4c236fba2197c006552a79112fd5308

https://github.com/ethereum/homebrew-ethereum/commit/5184485df88e47af574f73f9abf363f55ea3f1c5#diff-9cb658cb589c7349fc3d30f9fa09cb18

And then release was updated 3 hours ago with the same changes, as 1.1.4 was released, which led to Formula changes two hours ago:

https://github.com/ethereum/webthree-umbrella/commit/998f43e88dc9bcb402b558a24fbd8f0b474b1a7e

https://github.com/ethereum/homebrew-ethereum/commit/936e98c924d9c5f636204002ecaed97b15264e84#diff-9cb658cb589c7349fc3d30f9fa09cb18

The only thing which is changing here is the revision number and hashes.    Both of the generated Formulas point to the "develop" branch for the Git repo (incorrectly in the case of the release build).

Both have the same `if build.include? "successful"` conditional, switching between the specific (and correct) sha1 hash for the repo at that stage and between an unconditional "develop@HEAD" clone.

Q - How does that "build successful" condition work?   Would this Formula even get updated if the build had failed?   Perhaps that is a remnant of the previous buildbot integration, which doesn't make sense anymore?

Q - Do we even need or want release branch builds to come here?    Or only develop branch ones?   Is there an expectation that there are multiple modes within this Formula, so we can request the latest successful development version, or the stable release?     What exactly does `brew install cpp-ethereum --devel` do?

https://github.com/ethereum/webthree-umbrella/pull/241

**Comment by chriseth** [comment]
Cannot assess priority and size of this, @bobsummerwill  Is this about using the develop or release tag of the repository?

**Comment by bobsummerwill** [comment]
From what I can see, the Homebrew "release-build" target in Jenkins is only getting fired every few weeks (whenever we flush release), and prior to a recent fix I had to do in Jenkins, it was actually stomping artifacts.

My suspicion is that we don't actually need this target at all, because Homebrew doesn't have "two channels" to publish to anyway.

**Comment by bobsummerwill** [comment]
Jenkins stuff.    Not a problem anymore.
