### ISSUE TITLE
cpp-ethereum eth++ exit command not working

### ISSUE THREAD

**Issue by nikhilshekhawat** [ethereum/webthree-umbrella#243]
web3.admin.exit()
false

**Comment by bobsummerwill** [comment]
So @chriseth.   I imagine we want to just close this as won't fix, eh?

@nikhilshekhawat The plan is to remove the javascript console from eth imminently, because we have got "geth connect" working to connect to an eth node.    Maintaining the JS console just isn't worthwhile.

**Comment by nikhilshekhawat** [comment]
thanks for the answer @bobsummerwill .

**Comment by bobsummerwill** [comment]
No problem!

**Comment by chriseth** [comment]
This is a functionality that is advertised in the rpc interface, so it either be fixed or removed.
