### ISSUE TITLE
Windows 8.1, VS2012 - CMake-3.5 exposes missing boost_atomic library in our boost-1.55.00 binary

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#249]
See http://public.kitware.com/pipermail/cmake/2016-February/062817.html where I have reported a possible regression in CMake-3.5 (which is still at RC2 stage).   Hopefully we can pin this down and get it fixed before the 3.5 release, if it is a real issue.

We don't really have all the information we need right now, so might need the OP to replicate the issue or attempt to replicate it ourselves to get more information.

This was originally reported by @milyInzhoop in https://github.com/ethereum/webthree-umbrella/issues/235.

**Comment by bobsummerwill** [comment]
Actually, I think that https://github.com/ethereum/webthree-umbrella/files/136058/console.txt is actually sufficient.

**Comment by bobsummerwill** [comment]
Followed up http://public.kitware.com/pipermail/cmake/2016-February/062818.html

**Comment by bobsummerwill** [comment]
Adding @winsvega

**Comment by bobsummerwill** [comment]
So we missed the window for getting this resolved before they released CMake-3.5, but it was a regression which was reported and MAY have been fixed.

We need to re-test against the RTM 3.5 release, and if it is still broken then we need to follow up on the logged issue, and work with them to get it fixed for future CMake releases.

**Comment by bobsummerwill** [comment]
So it turns out this is not a regression.   It's actually an enhancement added to the FindBoost.cmake module in CMake-3.5.0 which automatically adds implicit dependencies.   boost_atomic is an implicit dependency of boot_thread.

The bug in on our side, in our prebuilt boost-1.55.00 x64 binaries which do not contain that library.

So the bug is in https://builds.ethereum.org/builds/windows-precompiled/boost-1.55.0-x64.tar.gz.

We should update to a newer boost version on Windows anyway, and should fix this at the same time.

**Comment by debris** [comment]
https://github.com/ethereum/cpp-dependencies/pull/2 should fix it

**Comment by chfast** [comment]
I have built and tested boost 1.60 on Windows, but for Visual Studio 2015.

**Comment by bobsummerwill** [comment]
And I'm getting this right now in Appveyor:
https://ci.appveyor.com/project/bobsummerwill/cpp-ethereum/build/1.0.42

So to use Appveyor (which comes with CMake 3.5), we'll either need the Windows binaries in the current location to be updated so they are built with atomic, or we need your larger changes to be committed.

**Comment by chfast** [comment]
Fixed for Visual Studio 2015 / boost 1.61.

**Comment by bobsummerwill** [comment]
AWESOME!   Thanks, @chfast.
