### ISSUE TITLE
Update README - Simplify naming prior to Homestead

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#250]
So I would like to propose that we simplify our naming prior to Homestead, because the current raft of different names for elements of the C++ codebase are confusing enough for people who are already using the codebase, let alone people who are joining the eco-system fresh.
- [x] Sanitize all README files
- [x] Sanitize https://github.com/ethereum/webthree-umbrella/wiki
- [X] Sanitize https://github.com/ethereum/webthree-umbrella/releases

Reorganizing our repositories is a more involved task, but also makes sense to do, but AFTER Homestead.    I will create a separate Github issue to track that proposal.

Names to be eliminated, because they aren't useful or required:
- TurboEthereum
- ++eth (just use eth)
- Ethereum (++)
- Fluidity/flu (functionality will be rolled back into eth)
- webthree
- Any mention of "C++ suite"
- Hardcode Ethereum
- Ethereum Devkit

What are we left with?
- cpp-ethereum - Ethereum C++ command-line client and utility tools
- mix - IDE
- solidity - Smart contract compiler
- AlethOne - one click miner
- AlethZero - for now

**Comment by obscuren** [comment]
> AlethZero - one click miner

I think you mean AlethOne?

> What are we left with?

Do these go in to separate repositories or all in to one? FWIW I'd suggest to move all 4 in to separate repositories and make them depend on `cpp-ethereum`  (maybe 3, include AO in to `cpp-ethereum`). 

Anyways :pray: :+1:

**Comment by bobsummerwill** [comment]
I did mean AlethOne.   Updated above, thanks, @obscuren.

Repositories certainly need consolidation.   I've made a new issue to track that now - https://github.com/ethereum/webthree-umbrella/issues/251

**Comment by chriseth** [comment]
@bobsummerwill I think the general proposal has reached consensus. If there is actual work to be done, please do it now. Otherwise, close this issue.

**Comment by bobsummerwill** [comment]
Will do.

I'll have a look around today and see if I can enumerate to TODOs here, and then use this issue to track the work through the rest of the week.    Mainly docs, readmes, Wiki, Homestead guide, etc, I think, and some code-changes, like the client-identification.

**Comment by bobsummerwill** [comment]
- [ ] Sanitize all README files
- [ ] Sanitize https://github.com/ethereum/ethereum-org
- [ ] Sanitize https://github.com/ethereum/webthree-umbrella/wiki
- [ ] Sanitize https://github.com/ethereum/webthree-umbrella/releases
- [ ] Pull all useful gitbook content into homestead-guide or Wiki
- [ ] Write a blog.ethereum.org post about the naming changes, and plans for repo simplification
