### ISSUE TITLE
Proposal - UPDATED - Jump our versioning to v1.2 for the Homestead release

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#253]
Maybe we should repurpose "v1.2" as the Homestead release?   Or even jump our versioning to "v2.0", considering that this is a hard-fork?

I think that 1.1.5 as a Homestead release number is confusing to end-users.    We've moved across a tiny range of numbers in the last few months.

Calling the Homestead release "2.0" at the same time as we clean up our naming would make sense to me.   It is somewhat of a rebirth in a number of ways for the team, where we start on the next chapter of our story together.

See also https://github.com/ethereum/webthree-umbrella/issues/250.

**Comment by bobsummerwill** [comment]
@obscuren says ... "I highly advice against that. It’s confusing to ethereum 2.0. We opted out of that for the same reason"

UPDATED - So maybe v1.2?   Title updated.

**Comment by chriseth** [comment]
Yes, we can make it 1.2. Let's rename the milestones and increase their numbers.

**Comment by chriseth** [comment]
Oh and homstead might not include all features we are currently working on, depending on their stability.

**Comment by bobsummerwill** [comment]
Good stuff!
