### ISSUE TITLE
AlethOne: Disable blockchain download in pool mode

### ISSUE THREAD

**Issue by winsvega** [ethereum/webthree-umbrella#254]
If alethone could be used as a node it should have option to set up datadir for it's node. 
also would be good to be able to disable blockchain download if alethone is used as a pool miner.

**Comment by chriseth** [comment]
Please keep in mind that AlethOne is intended to provide as few options as possible. It is a one-click miner, there should only be one button. Blockchain download should be disabled automatically and not as an option.

**Comment by bobsummerwill** [comment]
I don't think it makes sense for us to do any work on this.
Reopen if you disagree, guys!
