### ISSUE TITLE
OpenDataBase test fails on windows

### ISSUE THREAD

**Issue by winsvega** [ethereum/webthree-umbrella#255]
The test when a blockchain class open the same database twice (and expect AlreadyOpen exception)
fails on windows 7x64. It hang forever in function 

ldb::DB::Open(o, chainPath + "/blocks", &m_blocksDB);

which is located at libethereum/BlockChain.cpp line 223

The test itself is BlockChainSuite\opendb
it opens a default blockchain, mine one block into it and then tries to open another blockchain with the same temp directory and WithExisting::Verify flag set.

**Comment by winsvega** [comment]
on windows if levelDB has already been opened  there is a LOCK file in db's directory. 
if then call ldb::DB::Open() on this directory again with LOCK file present it would hang forever

**Comment by chriseth** [comment]
So the problem is that an earlier test does not properly close the database?

**Comment by winsvega** [comment]
no. that is not the problem. it is actual test. this test would intentionally try to open the same database twice. so in second time it should get an exception. 
but on windows this cause a bug in levelDB. 

thus imagine a situation if for some reason blockchain levelDB .LOCKFILE left undeleted - this would result in database unable to be open and eth will not throw exception and just hang forever

**Comment by chfast** [comment]
As leveldb does not support Windows locking files on Windows might be tricky.

**Comment by bobsummerwill** [comment]
Yeah ... rocksdb might help us in this respect too?
