### ISSUE TITLE
bcBasicInsert test fails on Windows

### ISSUE THREAD

**Issue by winsvega** [ethereum/webthree-umbrella#256]
Todo:
- fix static registration of seal engines

Original description:

on line 161 of BlockChainInsert.cpp
TestClient tcFull(me.secret());

fails with father exception at libethcore\SealEngine.h line 76

void setChainParams(ChainOperationParams const& _params) { m_params = _params; }

in operator m_params = _params;

connects to: #341

**Comment by winsvega** [comment]
https://github.com/ethereum/libethereum/blob/develop/libethereum/ChainParams.cpp#L107

need a check for null pointer. 

but why is it null on win64 in the first place....

---

the problem is that MSVS does not execute static declarations from https://github.com/ethereum/libethereum/blob/develop/libethcore/BasicAuthority.cpp (if no functions are called from that) and thus does not add BasicAuthority to the factory.

**Comment by chriseth** [comment]
Can you check what the seal engine name is in that context?

**Comment by winsvega** [comment]
ok. so 
1) 
https://github.com/ethereum/libethereum/blob/develop/libethereum/ChainParams.cpp#L107  needs a check for null pointer.

2)
MSVS compiler never gets to this line 
https://github.com/ethereum/libethereum/blob/develop/libethcore/BasicAuthority.cpp#L32
unless I define something from BasicAuthority.h (just #include is not enough) 

3)
thus SealEngineRegistrar have no BasicAuthority registered

**Comment by chriseth** [comment]
ChainParams changed dramatically in the meantime. Can you re-check? Thanks!

**Comment by winsvega** [comment]
the problem is that MSVS does not execute static declarations from https://github.com/ethereum/libethereum/blob/develop/libethcore/BasicAuthority.cpp (if no functions are called from that) and thus does not add BasicAuthority to the factory.
