### ISSUE TITLE
check permissions for ipc socket

### ISSUE THREAD

**Issue by chriseth** [ethereum/webthree-umbrella#259]
We should check whether there are any security issues with the ipc socket. It should only be accessible from the user that created the socket and it should not be possible to read communications by other processes that go over that socket.
The situation where the socket file already exists should also be considered and of course the different platforms (linux, macos, windows).

**Comment by bobsummerwill** [comment]
Please could you elaborate on this?
Pretty please, @chriseth?  :-)

**Comment by bobsummerwill** [comment]
This issue was moved to ethereum/cpp-ethereum#3115
