### ISSUE TITLE
Testing mode for eth

### ISSUE THREAD

**Issue by chriseth** [ethereum/webthree-umbrella#260]
For various use cases (mostly testing, but also private chains), it is beneficial to put eth into a mode where ethash is disabled ("NoProof" mode) but also timestamp verification is not done which allows us to produce blocks in sub-second time.

Furthermore, especially for testing, we should have RPC endpoints to
- rewind the chain
- mine exactly one block
- set the timestamp for the current block
- (potentially) set the block number of the current block without mining all the previous blocks
- change genesis block via json-rpc to modify account balances

Issues still to be resolved:
- [x] eth takes too much cpu, it should wait if there is nothing to seal, but wait up immediately
- [x] future blocks are ignored
- [ ] document

**Comment by winsvega** [comment]
> (potentially) set the block number of the current block without mining all the previous blocks

what should be with block parent hash in this case?

> change genesis block via json-rpc to modify account balances

this would require to reimport all blocks in the chain

in which section this functions should better be? 
I suppose admin_eth

**Comment by chriseth** [comment]
Changing the block number is probably not too useful, so we can leave that out. Modifying the timestamp is much more important.

If the genesis block is changed to modify account balances, the blockchain is just reset to the genesis block.

I think these functions should go into the `debug` section of rpc, or perhaps even create a new one called `test`.

**Comment by chriseth** [comment]
We should write documentation about the new rpc endpoints.

**Comment by winsvega** [comment]
https://github.com/ethereum/homestead-guide/pull/262

**Comment by bobsummerwill** [comment]
Done!
