### ISSUE TITLE
eth crash in RLPxHandshake

### ISSUE THREAD

**Issue by winsvega** [ethereum/webthree-umbrella#261]
Diagnosis: `RLPXHandshake::m_io` is null at the wrong point in time.
Suggested quick fix: check pointer before each dereference and go into error state if null.

crypto++ secblock.h  line 249

```
        : m_size(t.m_size) {m_ptr = m_alloc.allocate(m_size, NULL); memcpy_s(m_ptr, m_size*sizeof(T), t.m_ptr, m_size*sizeof(T));}
```

running eth with custom datadir set
with geth attach
on Ubuntu x64

**Comment by bobsummerwill** [comment]
What was the crash, @winsvega?   null pointer reference?   other?

**Comment by winsvega** [comment]
this = 0x00

RLPXFrameCoder.cpp
line 227 

```
void RLPXFrameCoder::updateIngressMACWithFrame(bytesConstRef _cipher)
{
    m_ingressMac.Update(_cipher.data(), _cipher.size());
```

**Comment by bobsummerwill** [comment]
Please could you add large chunks of context, @winsvega?   Thanks!

**Comment by winsvega** [comment]
1) running command eth which is built with debug

```
eth -d "/media/www/STUFF/Ethereum/testnet/ethnode1/datadir" 
```

2) running commang geth

```
geth attach
```

3) eth is syncing with 5-7  peers of main network at ~650000 block
then in 1-2 minutes it fails with segfault exception on RLPXFrameCoder.cpp line 227 (libweb3core/libp2p)

```
void RLPXFrameCoder::updateIngressMACWithFrame(bytesConstRef _cipher)
{
    m_ingressMac.Update(_cipher.data(), _cipher.size());
```

debug shows that `this` pointer is 0x0 (qtCreator on Ubuntu 14_04x64)

**Comment by winsvega** [comment]
update:
geth attach is irrelevant to this problem

https://github.com/ethereum/libweb3core/blob/develop/libp2p/RLPxHandshake.cpp#L363 

m_io is null at this point

**Comment by chriseth** [comment]
Was able to reproduce it in AlethOne.
As a first fix, we might just guard each dereference of `m_io` by a check (this is networking code where performance is not a big issue and "failing" means just dropping a single connection, why aren't such checks in place anyway?) and go into error mode if it is null.

**Comment by winsvega** [comment]
https://github.com/ethereum/libweb3core/pull/57
