### ISSUE TITLE
[CLI] Good mining beneficiary but wrong transaction signer

### ISSUE THREAD

**Issue by gmarti** [ethereum/webthree-umbrella#262]
using v 1.1.4, i try to use eth to mine on windows 10, but i have problem with "transaction signer" is not the same as "mining beneficiary"

`eth --frontier -i -v 1 -a <myaddress> --client-name "myName" -x 50 -m on -G`

Mining Beneficiary: OK
Transaction Signer: XE50000000000000000000000000000000 (00000000-0000-0000-0000-000000000000 - 00000000)

**Comment by bobsummerwill** [comment]
Incorrect command-line settings.   Glad it is working for you now!
