### ISSUE TITLE
Remove v8 and with it console and natspec

### ISSUE THREAD

**Issue by chriseth** [ethereum/webthree-umbrella#264]
We want to get rid of v8 as a dependency for eth. For that we have to remove the interactive console and the natspec evaluator.

**Comment by winsvega** [comment]
Could you be more specific? 

By removing v8 you mean disables this lines here
https://github.com/ethereum/webthree/blob/develop/eth/main.cpp#L900

and here 
https://github.com/ethereum/webthree/blob/develop/eth/main.cpp#L1356

?

I feel like it would result in ethereum-console not able to connect to eth

**Comment by chriseth** [comment]
Yes, the whole console should also be removed. It also include some javascript files, please also delete them.
So the idea is to open an ipc server by default (json-rpc-http server on request), but no interactive console as part of eth. If you want to have an interactive console, you can use github.com/ethereum/ethereum-console

**Comment by winsvega** [comment]
so libjsconsole could be removed entirely?

**Comment by bobsummerwill** [comment]
Yes, @winsvega.    libjsconsole, libjsengine, V8, the lot!

**Comment by bobsummerwill** [comment]
So most of this is now done, but the natspec is still there, @chriseth.    I've leave you or @winsvega to chop that out.     I also noticed that there is a jsConsole control in alethzero.    Not totally sure if that is related or unrelated?    Anyway - over to you guys!

**Comment by chriseth** [comment]
Yes, actually I noticed that we can keep natspec, because it is a templated library that does not forcefully use v8 and e.g. in alethzero uses the qt javascript engine. We can think about removing it anyway, but it is not needed for v8 removal.
