### ISSUE TITLE
OS X - Homebrew verify_app failure

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#265]
(Moved from https://github.com/ethereum/homebrew-ethereum/issues/52)

I just need to work out why that `verify_app` has got hooped again.   What's the best way for me to debug that?

-- Analyzing app='/tmp/cpp-ethereum20160208-87580-axosun/alethzero/alethfive/AlethFive.app'
-- bundle='/tmp/cpp-ethereum20160208-87580-axosun/alethzero/alethfive/AlethFive.app'
-- executable='/tmp/cpp-ethereum20160208-87580-axosun/alethzero/alethfive/AlethFive.app/Contents/MacOS/AlethFive'
-- valid='1'
-- executable file 1: /tmp/cpp-ethereum20160208-87580-axosun/alethzero/alethfive/AlethFive.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/Helpers/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess
-- executable file 2: /tmp/cpp-ethereum20160208-87580-axosun/alethzero/alethfive/AlethFive.app/Contents/MacOS/AlethFive
-- verified='0'
-- info='external prerequisites found:
f='/tmp/cpp-ethereum20160208-87580-axosun/alethzero/alethfive/AlethFive.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/Helpers/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess'
external_prereqs='/usr/local/opt/d-bus/lib/libdbus-1.3.dylib'
## '

CMake Error at /usr/local/Cellar/cmake/3.4.3/share/cmake/Modules/BundleUtilities.cmake:973 (message):
  error: verify_app failed
Call Stack (most recent call first):
  alethzero/alethfive/cmake_install.cmake:34 (verify_app)
  alethzero/cmake_install.cmake:33 (include)
  cmake_install.cmake:37 (include)

**Comment by bobsummerwill** [comment]
So the removal of AlethFive seems to have got us past this specific break.
HOWEVER, it looks like the same problem is still showing up for Mix.
More debugging required, after some Homebrew cycling.

**Comment by bobsummerwill** [comment]
And just got a local failure for AlethZero:

```
-- info='external prerequisites found:
f='/tmp/cpp-ethereum20160301-76103-1f5w9h5/alethzero/alethzero/AlethZero.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/Helpers/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess'
external_prereqs='/usr/local/opt/d-bus/lib/libdbus-1.3.dylib'
```

During ...

```
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/Makefile2 preinstall
make[1]: Nothing to be done for `preinstall'.
Install the project...
/usr/local/Cellar/cmake/3.4.3/bin/cmake -P cmake_install.cmake
```

**Comment by balopat** [comment]
moved comment to #574

**Comment by balopat** [comment]
ahhh...I guess I see, the hack in the webthree-helpers/cmake/scripts/macdeployfix.sh is specific to Qt version...let me see if I can override it manually to 5.6.1
