### ISSUE TITLE
OS X: Install Solidity Only via Brew

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#266]
From @VoR0220, moved from https://github.com/ethereum/homebrew-ethereum/issues/42.

I know this has been requested previously, but now it seems doable with the libweb3core libs now available. I continue to receive errors while trying to install cpp-ethereum via brew and I'm not sure how to proceed from here. Will post error separately, but I think that future issues would be mitigated by merely allowing people to simply download only solidity.

**Comment by jorisbontje** [comment]
Any updates on this?

**Comment by bobsummerwill** [comment]
Hey @jorisbontje,

This will happen at the same time we do the repo-reorg (https://github.com/ethereum/webthree-umbrella/issues/251), because then we will have a 1-1 between repos and Brew/PPAs.

Soon :-)

**Comment by bobsummerwill** [comment]
Closed.   Will be done in Solidity repo.
