### ISSUE TITLE
eth segmentation fault as soon as I launch ethminer

### ISSUE THREAD

**Issue by euri10** [ethereum/webthree-umbrella#269]
I do a  `eth -i -j --upnp off` in my terminal then I do  `ethminer -G` and eth segfaults instantly

```
➜  ~ ethminer -V                                                                                                                       
ethminer version 1.1.2                                                                                                                 
Build: Linux/g++/JIT/. 
```

```
➜  ~ eth -V                                                                                                                            
eth version 1.1.2                                                                                                                      
eth network protocol version: 63                                                                                                       
Client database version: 12041                                                                                                         
Build: Linux/g++/JIT/. 
```

built on debian with `cmake .. -DCMAKE_BUILD_TYPE=Debug -DGUI=0` on the develop branch, same issue on the release branch

edit : adding a [backtrace](http://pastebin.com/ZJRF83Bu), I'm a real newb here so please apologize if that doesn't help

**Comment by bobsummerwill** [comment]
Thanks for the report, @euri10!    The backtrace absolutely does help, so thanks for that.

Please could you try updating to the latest release (1.1.4), because you are missing a few weeks worth of changes at the moment, which may or may not affect this.    Best to eliminate that doubt first.   Best wishes!

**Comment by euri10** [comment]
I don't know if I am doing something wrong.
I did a git checkout v1. 1.4 then deleted the build folder then recompiled
and sudo make install.
I still have eth -V that outputs :
...
-- Up-to-date: /usr/local/include/solidity/ASTUtils.h
-- Up-to-date: /usr/local/include/solidity/Types.h
-- Up-to-date: /usr/local/include/solidity/AST.h
-- Installing: /usr/local/bin/solc
-- Removed runtime path from "/usr/local/bin/solc"
➜  build git:(998f43e) ✗ eth -V                                    eth
version 1.1.2
eth network protocol version: 63
Client database version: 12041
Build: Linux/g++/JIT/Debug

benoit barthelet
http://pgp.mit.edu/pks/lookup?op=get&search=0xF150E01A72F6D2EE
Le 26 févr. 2016 19:11, "Bob Summerwill" notifications@github.com a
écrit :

**Comment by bobsummerwill** [comment]
Yeah - that didn't update properly, did it?

Probably the easiest thing to do is to blow away your local directory and do a fresh `git clone https://github.com/ethereum/webthree-umbrella.git` into a different directory.    Then you could `git checkout release` on that, etc - a la https://github.com/ethereum/webthree-umbrella/wiki/Linux--Generic-Building.

**Comment by euri10** [comment]
Ok, deleted the whole folder, and now I compiled fine to v1.1.4 and
segfault disappeared.
Wish I'd understand git better.

benoit barthelet
http://pgp.mit.edu/pks/lookup?op=get&search=0xF150E01A72F6D2EE
Le 26 févr. 2016 22:39, "Bob Summerwill" notifications@github.com a
écrit :

**Comment by bobsummerwill** [comment]
Excellent!    Very glad to hear it.

Yes - it's a bit of a learning curve, I am afraid.   Lots of power when you get to the other side, though.

Have a good weekend.   Happy mining :-)
