### ISSUE TITLE
OS X - Homebrew formula incorrectly using Clang from LLVM?

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#270]
@chfast There is a chunk of homebrew code for EVMJIT which looks wrong to me:
https://github.com/ethereum/webthree-helpers/blob/develop/homebrew/cpp-ethereum.rb.in#L75
Those three lines look like me like they are flipping to the Clang within the LLVM package, and that won't just be for that one module, it will be for EVERYTHING which gets built within the Brew install.    Maybe that is remnants of the Clang use for analysis which you referred to earlier?

Or actually, maybe only that first line is problematic?

**Comment by chfast** [comment]
All this env variables look wrong to me too. `-DEVMJIT=1 -DLLVM_DIR=...` should be enough.
Thanks for looking at that.

**Comment by bobsummerwill** [comment]
Partial fix merged - https://github.com/ethereum/webthree-helpers/pull/100/ - which fixes the path to the LLVM HEAD install.    When that makes its way through into homebrew-ethereum we can then test whether or not the other elements here can safely be removed.
