### ISSUE TITLE
AlethZero crashes when importing JSON wallet

### ISSUE THREAD

**Issue by skabbo** [ethereum/webthree-umbrella#271]
Just installed the windows implementation of Ethereum, and when I attempt to import a JSON wallet to AlethZero I get a crash.   This also happens while mining with AlethOne (though not ethminer.exe), but that's a separate issue.   I'm running Windows 10, R9 290x, 32gb RAM, i7 4770k. 
Using build 1.1.4
Thanks very much

**Comment by bobsummerwill** [comment]
Thanks for the report, @skabbo.    Did you build from source, or use a prebuilt EXE?
Was there any further information or debug text beyond "crash"?   Thanks!

**Comment by skabbo** [comment]
Unfortunately just a generic "A problem has caused this program to stop working correctly,.  Windows will close the program and notify you if a solution is available."    Same with the AlethOne miner crash, although I've noticed with that one that it crashes whenever there's a pause for long enough that it throws the "JSON RPC problem - probably couldn't connect - retrying in 1..".  This happens about once a minute or so, but keeps on going without a problem using ethminer.exe.  AlethOne however crashes when it happens.
I'm running pre-built binaries.

**Comment by bobsummerwill** [comment]
AlethZero is being discontinued, so this will never be addressed.   Sorry!

https://blog.ethereum.org/2016/07/08/c-dev-update-summer-edition/
