### ISSUE TITLE
Linux - Get our PPA automation into a known good state, and document it

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#275]
The plan is to pull any scripts into `webthree-helpers`, so we don't have copies which aren't under version control.    Ensure our Wiki documentation reflects all the parts of our automation process, and that we don't have anything which is "off the books" or which we do not understand.
- [x] move deb packaging files to github.com/ethereum/ethereum-ppa (branches are develop and wily)
- [x] move build scripts from jenkins to webthree-helpers

**Comment by bobsummerwill** [comment]
My main issue with Jenkins-as-documentation is that of visibility and "diff-ability". You have to go poking around in a UI and work out its structure and details versus just looking at repos. If we have something which mirrored Jenkins changes out to Git, that would certainly help.

**Comment by chriseth** [comment]
Most of the configuration files of jenkins are in webthree-helpers. Some are configured as jenkins scripts. If they do not contain sensitive information, we can also move them to webthree-helpers.

**Comment by bobsummerwill** [comment]
Yes, gathering all the scripts there would make a lot of sense.   Plus splitting passwords, etc. out.

**Comment by bobsummerwill** [comment]
See also https://github.com/ethereum/webthree-umbrella/issues/280#issuecomment-191664381 for information on how the Arch packaging works, from @5chdn.

**Comment by chriseth** [comment]
We should also move the emscripten build instructions into a git-controlled file: https://github.com/chriseth/browser-solidity/issues/82 (actual instructions are there)

**Comment by chriseth** [comment]
This task is finished according to its title. Will create a new task for all other build scripts.
