### ISSUE TITLE
ethbuild.sh needs to parse or use the version number - OS X - Need to un-hardcode the versioning for Homebrew

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#279]
We first have to change jenkins to use the ethbinaries.sh script from webthree-helpers (maybe via `curl|sh`)

See https://github.com/ethereum/webthree-helpers/pull/99.

It appears that while the `ethbinaries.sh` script in webthree-helpers is designed to have version passed as a parameter to it, than we aren't actually doing that in our Jenkins flow.

Hence every build being tagged at 1.0rc2 forever.

We should fix that.   Maybe parse a file?

**Comment by chriseth** [comment]
It might be that jenkins does not use the script in webthree-umbrella but in its own config storage (they seem to be identical, though). The job that triggers the binaries build job creates an environment variable called BUILD_RELEASE_VERSION that contains the correct version.

**Comment by bobsummerwill** [comment]
See https://github.com/ethereum/homebrew-ethereum/blob/master/cpp-ethereum.rb#L5.

Finally got this updated.   Yes, it's hardcoded inside a script within Jenkins.
