### ISSUE TITLE
alethone / alethzero cmake

### ISSUE THREAD

**Issue by ghost** [ethereum/webthree-umbrella#28]
Moved here from [cpp-ethereum](https://github.com/ethereum/cpp-ethereum/issues/2961)

The "appdmg" target is named generically which creates a conflict. (issue in eth_package macro)

CMake Error at /Users/home/cpp-ethereum-cmake/EthExecutableHelper.cmake:180 (add_custom_target):
  add_custom_target cannot create target "appdmg" because another target with

**Comment by debris** [comment]
this issue was fixed
