### ISSUE TITLE
error: no matching function for call to dev::WebThreeDirect::composeClientVersion

### ISSUE THREAD

**Issue by 5chdn** [ethereum/webthree-umbrella#280]
Webthree Umbrella does not compile using Archlinux and the latest develop snapshot `1.0rc2.r134.gc308073`:

```
[ 89%] Building CXX object alethzero/libaleth/CMakeFiles/aleth.dir/DappHost.cpp.o
[ 89%] Building CXX object mix/CMakeFiles/mix.dir/mix_automoc.cpp.o
[ 89%] Building CXX object alethzero/libaleth/CMakeFiles/aleth.dir/Context.cpp.o
[ 89%] Building CXX object alethzero/libaleth/CMakeFiles/aleth.dir/Common.cpp.o
[ 89%] Building CXX object alethzero/libaleth/CMakeFiles/aleth.dir/AlethWhisper.cpp.o
[ 89%] Building CXX object alethzero/libaleth/CMakeFiles/aleth.dir/AlethFace.cpp.o
[ 90%] Building CXX object alethzero/libaleth/CMakeFiles/aleth.dir/Aleth.cpp.o
/tmp/pacaurtmp-afri/ethereum-git/src/ethereum/alethzero/libaleth/Aleth.cpp: In member function ‘bool dev::aleth::Aleth::open(dev::aleth::Aleth::OnInit)’:
/tmp/pacaurtmp-afri/ethereum-git/src/ethereum/alethzero/libaleth/Aleth.cpp:129:80: error: no matching function for call to ‘dev::WebThreeDirect::composeClientVersion(std::__cxx11::string&)’
   web3()->setClientVersion(WebThreeDirect::composeClientVersion(m_clientVersion));
                                                                                ^
In file included from /tmp/pacaurtmp-afri/ethereum-git/src/ethereum/alethzero/libaleth/Aleth.h:26:0,
                 from /tmp/pacaurtmp-afri/ethereum-git/src/ethereum/alethzero/libaleth/Aleth.cpp:22:
/tmp/pacaurtmp-afri/ethereum-git/src/ethereum/webthree/libwebthree/WebThree.h:145:21: note: candidate: static std::__cxx11::string dev::WebThreeDirect::composeClientVersion(const string&, const string&)
  static std::string composeClientVersion(std::string const& _client, std::string const& _name);
                     ^
/tmp/pacaurtmp-afri/ethereum-git/src/ethereum/webthree/libwebthree/WebThree.h:145:21: note:   candidate expects 2 arguments, 1 provided
[ 90%] Building CXX object alethzero/libaleth/CMakeFiles/aleth.dir/AccountNamer.cpp.o
[ 90%] Building CXX object alethzero/libaleth/CMakeFiles/aleth.dir/AccountHolder.cpp.o
alethzero/libaleth/CMakeFiles/aleth.dir/build.make:382: recipe for target 'alethzero/libaleth/CMakeFiles/aleth.dir/Aleth.cpp.o' failed
make[2]: *** [alethzero/libaleth/CMakeFiles/aleth.dir/Aleth.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 90%] Linking CXX executable mix
[ 90%] Built target mix
CMakeFiles/Makefile2:3749: recipe for target 'alethzero/libaleth/CMakeFiles/aleth.dir/all' failed
make[1]: *** [alethzero/libaleth/CMakeFiles/aleth.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

Full log available here. https://gist.github.com/5chdn/e847dbb1ce103fe7eb9e

**Comment by bobsummerwill** [comment]
Thanks for the speedy report, @5chdn!

I'm afraid that I have to plead ignorance on the pipeline which is getting that snapshot to you, but it looks like it missing changes on "both sides" from a recent internal API change for construction of version strings.    You will have got a "bad grab" because our multi-repo setup leads to non-atomic checkins.

I would wager this will "sort itself out" next drop.    Do you know who maintains this ArchLinux packaging process?   Thanks!

**Comment by 5chdn** [comment]
That is my feeling too, this might sort out soon. The 1.2.0 release tag builds just fine.

I'm maintaining the ArchLinux packages. Let me know if you need anything else.

**Comment by 5chdn** [comment]
aaaaaaaaaaaand ... it's compiling now in `1.0rc2.r138.ga674bf4`.

**Comment by bobsummerwill** [comment]
Brilliant!

What does the ArchLinux packaging consist of?    Do you have some scripts or something which are running?   Do you have automation set up?    Just curious.

I am clueless to the actual on-the-ground mechanics of Linux package maintenance.

**Comment by 5chdn** [comment]
- Here are [my maintained packages](https://aur.archlinux.org/packages/?SeB=m&K=5chdn).
- If you click a package, e.g., [ethereum-git](https://aur.archlinux.org/packages/ethereum-git/) you will see a package summary.
- Click in the right box [View PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ethereum-git) to see the install script.

Any feedback on the script is welcome. These packages can be installed in Archlinux by either downloading the PKGBUILD manually and run `makepkg` and install it via `sudo pacman -U ethereum-git-1.0rc2.r132.gbc93486-1-x86_64.pkg.tar.xz` or users can use AUR-helpers, like `yaourt` or `pacaur` where they simply run commands like `pacaur -S ethereum-git` to install the packages from the user repository.

**Comment by bobsummerwill** [comment]
Thanks for the info!
