### ISSUE TITLE
Set up remote access for the OS X and windows build machines

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#281]
Looks like we don't have remote access set up for our OS X build machine, which makes it pretty hard to maintain unless you are in the office :-)
- [x] change and document passwords
- [x] setup remote access on macos
- [ ] setup remote access on windows

**Comment by chriseth** [comment]
Is this really done?

**Comment by bobsummerwill** [comment]
Oh ... so I guess for the EXISTING OS X machine, maybe not?

I had closed this on the basis that the NEW OS X machine was set up and accessible.    There is a separate issue for actually generating El Capitan binaries.

**Comment by chriseth** [comment]
@bobsummerwill setup ssh for the macos machine (details in private comms). Which remote desktop software would you like for windows?

**Comment by bobsummerwill** [comment]
Best to use RDC (Remote Desktop Client).   It's built into the OS.

There is a Mac client for accessing Windows machines via this protocol.

**Comment by chriseth** [comment]
RDC port is 3389

**Comment by chriseth** [comment]
Our version of windows 8 does not provide remote desktop. Need to find a better solution.

**Comment by chriseth** [comment]
Closing this, since we will rather set up a new hosted windows machine.
