### ISSUE TITLE
We should have an automation step which auto-merges into webthree-umbrella

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#284]
At the moment we are having to manually update the git sub-modules in the webthree-umbrella project manually, when we remember.    That introduces drift which isn't desirable.

We should just have an automation step which automatically updates the umbrella each time we have a successful build.    If the build gets broken then this would stall.   Which is good.    That way there is a very strong guarantee that syncing to HEAD of develop on the umbrella will give you a working build.

**Comment by chriseth** [comment]
I think we should have a job that runs daily (which does not mean we cannot run it more often by just pressing a button on jenkins), builds and runs the tests. If everything is fine, develop is updated.

**Comment by bobsummerwill** [comment]
Why not just add it as a post-build step on "project-build"?   Will only take a second or two, won't it?

**Comment by chriseth** [comment]
project-build is a catch-all job that runs for anything (especially PRs), we should have another job that just takes the develop branch from all submodules.

**Comment by bobsummerwill** [comment]
We're actually going to need 3 instances of this process after the repo re-org:
- Auto-update for cpp-ethereum sub-module in solidity repo
- Auto-update for cpp-ethereum and solidity sub-modules in mix repo
- Auto-update for cpp-ethereum and solidity sub-modules in alethzero repo

Because we won't have a global umbrella anymore.

**Comment by chriseth** [comment]
Job is here: http://52.28.164.97/job/update-umbrella/
currently testing it.
It builds and pushes if the build is fine.
The job just runs the `sync.sh` script in umbrella.
