### ISSUE TITLE
Remove master password prompt

### ISSUE THREAD

**Issue by chriseth** [ethereum/webthree-umbrella#287]
It should be possible to start eth without interaction, especially the master password prompt should not appear unless needed.

The default should be to start without wallet mode, only if `--wallet` is given, the master password is queried.

The main drawback we currently have is that our bare keys do not store the address. So if you want to know the address of a key, you have to decrypt it.
- [x] store address inside bare keys
- [x] do not open the wallet / query for the password, unless we have an old wallet (use empty password by default)
- [x] if the wallet is open, iterate over all keys and add their addresses if they do not yet have them
- [x] `eth wallet import` should not ask for the master password
- [x] let `eth` try to open the wallet with empty master password first
- [x] bare keys that are just copied into the keystore directory should be visible

**Comment by bobsummerwill** [comment]
I was reading that geth only pops up this dialog on-demand.

We do have the command-line option to set the master password, don't we?   But that leaks the password in plaintext in log files, etc.     So you want some config-file, perhaps?

**Comment by chriseth** [comment]
The default way to start eth is "no interaction". We can add a flag `--wallet` to start it in wallet mode which will prompt for the master password. In the long run, the wallet mode should disappear, we will investigate whether that is possible in the next days.

**Comment by chriseth** [comment]
This was all implemented: eth now tries the empty master password and only queries for a master password if that does not work.
