### ISSUE TITLE
attach to a eth node with geth ?

### ISSUE THREAD

**Issue by euri10** [ethereum/webthree-umbrella#294]
reading the changelog to v1.1.2 i was interested in testing this :

> implemented admin interface (geth attach can now be used with a running eth node)

```
➜  go-ethereum git:(master) eth -V
eth version 1.2.0
eth network protocol version: 63
Client database version: 12041
Build: Linux/g++/JIT/Debug
```

so with a fresh compiled geth (v1.3.4) I tried 

```
➜  go-ethereum git:(master) build/bin/geth attach
Fatal: Unable to initialize console - INVALID_JSON_REQUEST: The JSON sent is not a valid JSON-RPC Request object

➜  go-ethereum git:(master) build/bin/geth attach rpc
Fatal: Unable to attach to geth node - Invalid endpoint

➜  go-ethereum git:(master) build/bin/geth attach rpc:http://localhost:8545
Fatal: Unable to initialize console - Unable to parse module response - <nil>
```

until I read this in the changelog :

> Also note that eth can now be used with geth attach. This will expose some administration interfaces via IPC (i.e. unix sockets / pipes and not http by default) which are not password protected.

so my question is how can I connect to the ipc endpoint since it seems i can't to the RPC one.

I ran eth with `eth -i -j --upnp off -v 2`

**Comment by chriseth** [comment]
Sorry, this was perhaps a bit premature. There was a bug in geth which was fixed in develop / 1.4.0 that sent an invalid request. So to use it, you probably need a newer version of geth or just use [ethconsole](https://github.com/ethereum/ethereum-console)

**Comment by bobsummerwill** [comment]
I had success using the unstable 1.4.0 builds which are autoposted to http://gitter.im/ethereum/go-ethereum every day.

**Comment by euri10** [comment]
success too, in fact I wanted to test this to see if there was a way to get
in geth  eth.pendingTransactions
but it returns :

{
  code: -32601,
  message: "METHOD_NOT_FOUND: The method being requested is not available
on this server"
}

On Thu, Mar 3, 2016 at 12:41 AM, Bob Summerwill notifications@github.com
wrote:

> I had success using the unstable 1.4.0 builds which are autoposted to
> http://gitter.im/ethereum/go-ethereum every day.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ethereum/webthree-umbrella/issues/294#issuecomment-191495047
> .

## 

benoit barthelet
http://pgp.mit.edu/pks/lookup?op=get&search=0xF150E01A72F6D2EE

**Comment by chriseth** [comment]
Thanks, added that to the [list](https://github.com/ethereum/webthree-umbrella/issues/305)

**Comment by ulrichard** [comment]
I just ran into the same problem since the interactive mode seems to have been removed from eth.
Should the fix already be in the ppa versions?
eth 1.2.4
geth 1.3.6
