### ISSUE TITLE
Provide simple key management for eth

### ISSUE THREAD

**Issue by chriseth** [ethereum/webthree-umbrella#297]
`eth wallet` and `eth account` should provide a similar functionality as geth.
- [x] provide the interface with wallet still in place
- [x] make everything work with addresses and not only UUIDs
- [x] store addresses with bare keys
- [x] make everything work with bare keys and without entering the master password

**Comment by winsvega** [comment]
```
eth account update 00a3d084a5d77726e72325d0d52c52d93b0ecff5 
 Please enter your MASTER passphrase: 
Couldn't re-encode 00a3d084a5d77726e72325d0d52c52d93b0ecff5; not found.
```

**Comment by yann300** [comment]
try to use the uuid instead of the address (uuid is basically the name of the key file).
