### ISSUE TITLE
web3.eth.getBlock("pending") causes error "Couldn't find requested block: #00000000…"

### ISSUE THREAD

**Issue by ghost** [ethereum/webthree-umbrella#30]
Moved here from [cpp-ethereum](https://github.com/ethereum/cpp-ethereum/issues/2957)

The following call returns the correct result but still outputs the an error to the eth console:

``` javascript
web3.eth.getBlock("pending", function(error, data) {    
      if (error) {
        console.log("Error getting pending block: " + error);
      } else {
        console.log("Pending block is: " + data.number);
      }
   });
```

Error:

> libmicrohttpd  Couldn't find requested block: #00000000…

**Comment by winsvega** [comment]
tested through geth attach - no errors appeared.
I think we could close the issue
