### ISSUE TITLE
Build fails on openSUSE 42.1

### ISSUE THREAD

**Issue by daschmidty** [ethereum/webthree-umbrella#302]
Trying to build libethereum on openSUSE 42.1 fails consistently with what appears to be an LLVM error. I am currently running LLVM 3.7.0 (does not appear there are official binaries for any later version to this point)

```
avid@David-OpenSUSE:~/Wallets/webthree-umbrella/webthree-helpers> scripts/ethbuild.sh --no-git --cores 6 --project libethereum

ETHBUILD - INFO: Starting build of webthree-helpers/utils for requested project libethereum.

-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- boost headers: /usr/include
-- boost lib   : /usr/lib64/libboost_thread-mt.so;/usr/lib64/libboost_date_time-mt.so;/usr/lib64/libboost_system-mt.so;/usr/lib64/libboost_regex-mt.so;/usr/lib64/libboost_chrono-mt.so;/usr/lib64/libboost_filesystem-mt.so;/usr/lib64/libboost_unit_test_framework-mt.so;/usr/lib64/libboost_program_options-mt.so;/usr/lib64/libboost_random-mt.so
-- Found gmp: /usr/include  
-- Gmp headers: /usr/include
-- Gmp lib   : /usr/lib64/libgmp.so
-- Configuring done
-- Generating done
-- Build files have been written to: /home/david/Wallets/webthree-umbrella/webthree-helpers/webthree-helpers/utils/build
[ 41%] Built target secp256k1
[100%] Built target scrypt

ETHBUILD - INFO: Starting build of libweb3core for requested project libethereum.

-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- boost headers: /usr/include
-- boost lib   : /usr/lib64/libboost_thread-mt.so;/usr/lib64/libboost_date_time-mt.so;/usr/lib64/libboost_system-mt.so;/usr/lib64/libboost_regex-mt.so;/usr/lib64/libboost_chrono-mt.so;/usr/lib64/libboost_filesystem-mt.so;/usr/lib64/libboost_unit_test_framework-mt.so;/usr/lib64/libboost_program_options-mt.so;/usr/lib64/libboost_random-mt.so

------------------------------------------------------------------------
-- Configuring dev
------------------------------------------------------------------------
--                  CMake Version                            3.3.2
-- CMAKE_BUILD_TYPE Build type                               RelWithDebInfo
-- TARGET_PLATFORM  Target platform                          Linux
--------------------------------------------------------------- features
-- PROFILING        Profiling support                        OFF
-- PARANOID         -                                        OFF
-- MINIUPNPC        -                                        ON
------------------------------------------------------------- components
-- TESTS            Build tests                              ON
-- TOOLS            Build tools                              ON
------------------------------------------------------------------------

-- Found jsoncpp: /usr/include  
-- JsonCpp headers: /usr/include
-- JsonCpp lib   : /usr/lib64/libjsoncpp.so
-- Found leveldb: /usr/include  
-- LevelDB headers: /usr/include
-- LevelDB lib   : /usr/lib64/libleveldb.so
-- Found CryptoPP: /usr/include (found suitable version "5.6.2", minimum required is "5.6.2") 
-- CryptoPP headers: /usr/include
-- CryptoPP lib   : /usr/lib64/libcryptopp.so
-- Found miniupnpc: /usr/include  
-- miniupnpc headers: /usr/include
-- miniupnpc lib   : /usr/lib64/libminiupnpc.so
./memorydb.cpp./overlaydb.cpp./test.cpp./libdevcore/./Base36.cpp./libdevcore/./CommonJS.cpp./libdevcore/./FixedHash.cpp./libdevcore/./RangeMask.cpp./libdevcore/./core.cpp./libdevcore/./rlp.cpp./libdevcrypto/./AES.cpp./libdevcrypto/./MemTrie.cpp./libdevcrypto/./SecretStore.cpp./libdevcrypto/./crypto.cpp./libdevcrypto/./hexPrefix.cpp./libdevcrypto/./trie.cpp./libp2p/./capability.cpp./libp2p/./eip-8.cpp./libp2p/./net.cpp./libp2p/./peer.cpp./libp2p/./rlpx.cpp
-- Configuring done
-- Generating done
-- Build files have been written to: /home/david/Wallets/webthree-umbrella/webthree-helpers/libweb3core/build
Scanning dependencies of target dev_BuildInfo.h
[  0%] Built target dev_BuildInfo.h
[ 31%] Built target devcore
[ 41%] Built target devcrypto
[ 43%] Built target rlp
[ 46%] Built target bench
[ 71%] Built target p2p
[100%] Built target testweb3core

ETHBUILD - INFO: Starting build of libethereum for requested project libethereum.

-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- boost headers: /usr/include
-- boost lib   : /usr/lib64/libboost_thread-mt.so;/usr/lib64/libboost_date_time-mt.so;/usr/lib64/libboost_system-mt.so;/usr/lib64/libboost_regex-mt.so;/usr/lib64/libboost_chrono-mt.so;/usr/lib64/libboost_filesystem-mt.so;/usr/lib64/libboost_unit_test_framework-mt.so;/usr/lib64/libboost_program_options-mt.so;/usr/lib64/libboost_random-mt.so

------------------------------------------------------------------------
-- Configuring ethereum
------------------------------------------------------------------------
--                  CMake Version                            3.3.2
-- CMAKE_BUILD_TYPE Build type                               RelWithDebInfo
-- TARGET_PLATFORM  Target platform                          Linux
--------------------------------------------------------------- features
--                  Hardware identification support          
--                  HTTP Request support                     
-- VMTRACE          VM execution tracing                     OFF
-- PROFILING        Profiling support                        OFF
-- FATDB            Full database exploring                  ON
-- ROCKSDB          Prefer rocksdb to leveldb                OFF
-- OLYMPIC          Default to the Olympic network           OFF
-- PARANOID         -                                        OFF
------------------------------------------------------------- components
-- TESTS            Build tests                              ON
-- ETHASHCL         Build OpenCL components                  ON
-- EVMJIT           Build LLVM-based JIT EVM                 ON
------------------------------------------------------------------------

-- Found LLVM 3.7.0
-- Using LLVMConfig.cmake in: /usr/share/llvm/cmake
-- EVM JIT version: 0.9.0
-- Found jsoncpp: /usr/include  
-- JsonCpp headers: /usr/include
-- JsonCpp lib   : /usr/lib64/libjsoncpp.so
-- Found leveldb: /usr/include  
-- LevelDB headers: /usr/include
-- LevelDB lib   : /usr/lib64/libleveldb.so
-- Found CryptoPP: /usr/include (found suitable version "5.6.2", minimum required is "5.6.2") 
-- CryptoPP headers: /usr/include
-- CryptoPP lib   : /usr/lib64/libcryptopp.so
-- Found miniupnpc: /usr/include  
-- miniupnpc headers: /usr/include
-- miniupnpc lib   : /usr/lib64/libminiupnpc.so
-- Looking for CL_VERSION_2_0
-- Looking for CL_VERSION_2_0 - not found
-- Looking for CL_VERSION_1_2
-- Looking for CL_VERSION_1_2 - found
-- Found OpenCL: /usr/lib64/libOpenCL.so (found version "1.2") 
-- OpenCL headers: /usr/include
-- OpenCL lib   : /usr/lib64/libOpenCL.so
-- Cpuid headers: CPUID_INCLUDE_DIR-NOTFOUND
-- Cpuid lib   : CPUID_LIBRARY-NOTFOUND
-- Found json_rpc_cpp: /usr/include (found suitable version "0.6.0", minimum required is "0.4") 
-- json-rpc-cpp headers: /usr/include
-- json-rpc-cpp lib   : /usr/lib64/libjsonrpccpp-common.so;/usr/lib64/libjsonrpccpp-server.so;/usr/lib64/libjsonrpccpp-client.so
-- Found CURL: /usr/include  
-- curl headers: /usr/include
-- curl lib   : /usr/lib64/libcurl.so
-- test: ClientBase |  --eth_testfile=BlockTests/bcJS_API_Test --eth_threads=1; --eth_testfile=BlockTests/bcJS_API_Test --eth_threads=3; --eth_testfile=BlockTests/bcJS_API_Test --eth_threads=10; --eth_testfile=BlockTests/bcValidBlockTest --eth_threads=1; --eth_testfile=BlockTests/bcValidBlockTest --eth_threads=3; --eth_testfile=BlockTests/bcValidBlockTest --eth_threads=10
-- test: JsonRpc |  --eth_testfile=BlockTests/bcJS_API_Test; --eth_testfile=BlockTests/bcValidBlockTest
-- Configuring done
-- Generating done
-- Build files have been written to: /home/david/Wallets/webthree-umbrella/webthree-helpers/libethereum/build
Scanning dependencies of target ethereum_BuildInfo.h
[  2%] Built target natspec
[  5%] Built target ethash
[  6%] Linking CXX shared library libevmjit.so
[  6%] Built target minerfarm.jsonstub
[  6%] Built target minerphonehome.jsonstub
/usr/include/llvm/Support/TargetSelect.h:119: error: undefined reference to 'LLVMInitializeX86TargetInfo'
/usr/include/llvm/Support/TargetSelect.h:121: error: undefined reference to 'LLVMInitializeX86TargetMC'
/home/david/Wallets/webthree-umbrella/webthree-helpers/libethereum/evmjit/libevmjit/JIT.cpp:126: error: undefined reference to 'llvm::EngineBuilder::EngineBuilder(std::unique_ptr<llvm::Module, std::default_delete<llvm::Module> >)'
/usr/include/llvm/ExecutionEngine/ExecutionEngine.h:631: error: undefined reference to 'llvm::EngineBuilder::selectTarget()'
/usr/include/llvm/ExecutionEngine/ExecutionEngine.h:631: error: undefined reference to 'llvm::EngineBuilder::create(llvm::TargetMachine*)'
/home/david/Wallets/webthree-umbrella/webthree-helpers/libethereum/evmjit/libevmjit/JIT.cpp:126: error: undefined reference to 'llvm::EngineBuilder::~EngineBuilder()'
/home/david/Wallets/webthree-umbrella/webthree-helpers/libethereum/evmjit/libevmjit/JIT.cpp:126: error: undefined reference to 'llvm::EngineBuilder::~EngineBuilder()'
/home/david/Wallets/webthree-umbrella/webthree-helpers/libethereum/evmjit/libevmjit/Optimizer.cpp:63: error: undefined reference to 'llvm::ReplaceInstWithInst(llvm::Instruction*, llvm::Instruction*)'
/home/david/Wallets/webthree-umbrella/webthree-helpers/libethereum/evmjit/libevmjit/Optimizer.cpp:157: error: undefined reference to 'llvm::ReplaceInstWithInst(llvm::iplist<llvm::Instruction, llvm::ilist_traits<llvm::Instruction> >&, llvm::ilist_iterator<llvm::Instruction>&, llvm::Instruction*)'
/home/david/Wallets/webthree-umbrella/webthree-helpers/libethereum/evmjit/libevmjit/Optimizer.cpp:79: error: undefined reference to 'llvm::createCFGSimplificationPass(int, std::function<bool (llvm::Function const&)>)'
/home/david/Wallets/webthree-umbrella/webthree-helpers/libethereum/evmjit/libevmjit/Optimizer.cpp:80: error: undefined reference to 'llvm::createInstructionCombiningPass()'
/home/david/Wallets/webthree-umbrella/webthree-helpers/libethereum/evmjit/libevmjit/Optimizer.cpp:81: error: undefined reference to 'llvm::createAggressiveDCEPass()'
/home/david/Wallets/webthree-umbrella/webthree-helpers/libethereum/evmjit/libevmjit/Optimizer.cpp:82: error: undefined reference to 'llvm::createLowerSwitchPass()'
/home/david/Wallets/webthree-umbrella/webthree-helpers/libethereum/evmjit/libevmjit/Optimizer.cpp:174: error: undefined reference to 'llvm::createCFGSimplificationPass(int, std::function<bool (llvm::Function const&)>)'
/home/david/Wallets/webthree-umbrella/webthree-helpers/libethereum/evmjit/libevmjit/Optimizer.cpp:175: error: undefined reference to 'llvm::createDeadCodeEliminationPass()'
collect2: error: ld returned 1 exit status
evmjit/libevmjit/CMakeFiles/evmjit.dir/build.make:568: recipe for target 'evmjit/libevmjit/libevmjit.so.0.9.0.2' failed
make[2]: *** [evmjit/libevmjit/libevmjit.so.0.9.0.2] Error 1
CMakeFiles/Makefile2:140: recipe for target 'evmjit/libevmjit/CMakeFiles/evmjit.dir/all' failed
make[1]: *** [evmjit/libevmjit/CMakeFiles/evmjit.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  6%] Built target ethereum_BuildInfo.h
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
ETHBUILD - ERROR: Building repository "libethereum" failed.
```

**Comment by bobsummerwill** [comment]
Hey there, @daschmidty!   Thanks for the report.

So you are likely hitting something distro-specific, which just requires some little tweak somewhere in our setup.    Those undefined references are all LLVM symbols, which will be in one-or-another of the LLVM libraries we link against (there are LOADS of them).

A quick Google search on the symbols seems to indicate that the problem might be something related to the order in which things are composed on the command-line.

Please could you try to replicate the issue, but building with `--verbose`, and then dumping the FULL build log into a http://gist.github.com and linking to it here?

Hopefully we'll see something in the ordering of the generated command-lines which will make sense.   Maybe we require some minor CMake tweaks, or are missing some configuration settings which affect your result.

Anyway - please do a verbose, and let's see what turns up, eh?   Thanks!

**Comment by daschmidty** [comment]
[https://gist.github.com/daschmidty/b312f1ef15276f64a79d]

Hopefully this helps

**Comment by bobsummerwill** [comment]
Please could you just make a gist of the STDOUT?   Thanks!    Not sure what that make log is, but it is incomplete, I'm afraid.

**Comment by daschmidty** [comment]
https://gist.github.com/daschmidty/601ac999e538410aa8f7

This is for just the libethereum build. I am not sure how to use the build helper script and pass the verbose option to it

**Comment by bobsummerwill** [comment]
Slurping out relevant lines.   Gotta run now.   Will pick this up tomorrow.

Hmm.   What is "c++"?   Is that an alias for g++?   Which version?   Perhaps we have a different compiler/linker being used for this distro than on others, which is more sensitive to ordering of libs?

/usr/bin/c++  -fPIC -std=c++11 -Wall -Wextra -Wconversion -Wno-sign-conversion -Wno-unknown-pragmas -std=c++11 -Wall -Wno-unknown-pragmas -Wextra -Werror -pedantic -DSHAREDLIB -fPIC  -fuse-ld=gold -fno-rtti -fvisibility=hidden -O2 -g -DETH_RELEASE -Wl,--no-undefined -Wl,--exclude-libs,ALL -shared -Wl,-soname,libevmjit.so.0.9 -o libevmjit.so.0.9.0.2 CMakeFiles/evmjit.dir/JIT.cpp.o CMakeFiles/evmjit.dir/JIT-c.cpp.o CMakeFiles/evmjit.dir/Arith256.cpp.o CMakeFiles/evmjit.dir/Array.cpp.o CMakeFiles/evmjit.dir/BasicBlock.cpp.o CMakeFiles/evmjit.dir/Cache.cpp.o CMakeFiles/evmjit.dir/Compiler.cpp.o CMakeFiles/evmjit.dir/CompilerHelper.cpp.o CMakeFiles/evmjit.dir/Endianness.cpp.o CMakeFiles/evmjit.dir/ExecStats.cpp.o CMakeFiles/evmjit.dir/Ext.cpp.o CMakeFiles/evmjit.dir/GasMeter.cpp.o CMakeFiles/evmjit.dir/Instruction.cpp.o CMakeFiles/evmjit.dir/Memory.cpp.o CMakeFiles/evmjit.dir/Optimizer.cpp.o CMakeFiles/evmjit.dir/RuntimeManager.cpp.o CMakeFiles/evmjit.dir/Type.cpp.o CMakeFiles/evmjit.dir/Utils.cpp.o CMakeFiles/evmjit.dir/support/Path.cpp.o /usr/lib64/libLLVMCore.so.3.7.0 /usr/lib64/libLLVMSupport.so.3.7.0 /usr/lib64/libLLVMMCJIT.so.3.7.0 /usr/lib64/libLLVMX86AsmParser.so.3.7.0 /usr/lib64/libLLVMX86CodeGen.so.3.7.0 /usr/lib64/libLLVMipo.so.3.7.0 
/usr/include/llvm/Support/TargetSelect.h:119: error: undefined reference to 'LLVMInitializeX86TargetInfo'
/usr/include/llvm/Support/TargetSelect.h:121: error: undefined reference to 'LLVMInitializeX86TargetMC'
/home/david/Wallets/webthree-umbrella/webthree-helpers/libethereum/evmjit/libevmjit/JIT.cpp:126: error: undefined reference to 'llvm::EngineBuilder::EngineBuilder(std::unique_ptr<llvm::Module, std::default_delete<llvm::Module> >)'
/usr/include/llvm/ExecutionEngine/ExecutionEngine.h:631: error: undefined reference to 'llvm::EngineBuilder::selectTarget()'
/usr/include/llvm/ExecutionEngine/ExecutionEngine.h:631: error: undefined reference to 'llvm::EngineBuilder::create(llvm::TargetMachine_)'
/home/david/Wallets/webthree-umbrella/webthree-helpers/libethereum/evmjit/libevmjit/JIT.cpp:126: error: undefined reference to 'llvm::EngineBuilder::~EngineBuilder()'
/home/david/Wallets/webthree-umbrella/webthree-helpers/libethereum/evmjit/libevmjit/JIT.cpp:126: error: undefined reference to 'llvm::EngineBuilder::~EngineBuilder()'
/home/david/Wallets/webthree-umbrella/webthree-helpers/libethereum/evmjit/libevmjit/Optimizer.cpp:63: error: undefined reference to 'llvm::ReplaceInstWithInst(llvm::Instruction_, llvm::Instruction_)'
/home/david/Wallets/webthree-umbrella/webthree-helpers/libethereum/evmjit/libevmjit/Optimizer.cpp:157: error: undefined reference to 'llvm::ReplaceInstWithInst(llvm::iplist<llvm::Instruction, llvm::ilist_traits<llvm::Instruction> >&, llvm::ilist_iteratorllvm::Instruction&, llvm::Instruction_)'
/home/david/Wallets/webthree-umbrella/webthree-helpers/libethereum/evmjit/libevmjit/Optimizer.cpp:79: error: undefined reference to 'llvm::createCFGSimplificationPass(int, std::function<bool (llvm::Function const&)>)'
/home/david/Wallets/webthree-umbrella/webthree-helpers/libethereum/evmjit/libevmjit/Optimizer.cpp:80: error: undefined reference to 'llvm::createInstructionCombiningPass()'
/home/david/Wallets/webthree-umbrella/webthree-helpers/libethereum/evmjit/libevmjit/Optimizer.cpp:81: error: undefined reference to 'llvm::createAggressiveDCEPass()'
/home/david/Wallets/webthree-umbrella/webthree-helpers/libethereum/evmjit/libevmjit/Optimizer.cpp:82: error: undefined reference to 'llvm::createLowerSwitchPass()'
/home/david/Wallets/webthree-umbrella/webthree-helpers/libethereum/evmjit/libevmjit/Optimizer.cpp:174: error: undefined reference to 'llvm::createCFGSimplificationPass(int, std::function<bool (llvm::Function const&)>)'
/home/david/Wallets/webthree-umbrella/webthree-helpers/libethereum/evmjit/libevmjit/Optimizer.cpp:175: error: undefined reference to 'llvm::createDeadCodeEliminationPass()'
collect2: error: ld returned 1 exit status

**Comment by daschmidty** [comment]
"c++" is a symlink to g++ 4.8.5 . Linker is ld 2.25.0.  You were not kidding about linking against a lot of LLVM libs

**Comment by bobsummerwill** [comment]
/usr/bin/c++  -fPIC -std=c++11 -Wall -Wextra -Wconversion -Wno-sign-conversion
-Wno-unknown-pragmas -std=c++11 -Wall -Wno-unknown-pragmas -Wextra -Werror
-pedantic -DSHAREDLIB -fPIC  -fuse-ld=gold -fno-rtti -fvisibility=hidden -O2 -g
-DETH_RELEASE -Wl,--no-undefined -Wl,--exclude-libs,ALL -shared
-Wl,-soname,libevmjit.so.0.9 -o libevmjit.so.0.9.0.2
CMakeFiles/evmjit.dir/JIT.cpp.o CMakeFiles/evmjit.dir/JIT-c.cpp.o
CMakeFiles/evmjit.dir/Arith256.cpp.o CMakeFiles/evmjit.dir/Array.cpp.o
CMakeFiles/evmjit.dir/BasicBlock.cpp.o CMakeFiles/evmjit.dir/Cache.cpp.o
CMakeFiles/evmjit.dir/Compiler.cpp.o CMakeFiles/evmjit.dir/CompilerHelper.cpp.o
CMakeFiles/evmjit.dir/Endianness.cpp.o CMakeFiles/evmjit.dir/ExecStats.cpp.o
CMakeFiles/evmjit.dir/Ext.cpp.o CMakeFiles/evmjit.dir/GasMeter.cpp.o
CMakeFiles/evmjit.dir/Instruction.cpp.o CMakeFiles/evmjit.dir/Memory.cpp.o
CMakeFiles/evmjit.dir/Optimizer.cpp.o CMakeFiles/evmjit.dir/RuntimeManager.cpp.o
CMakeFiles/evmjit.dir/Type.cpp.o CMakeFiles/evmjit.dir/Utils.cpp.o
CMakeFiles/evmjit.dir/support/Path.cpp.o
/usr/lib64/libLLVMCore.so.3.7.0
/usr/lib64/libLLVMSupport.so.3.7.0
/usr/lib64/libLLVMMCJIT.so.3.7.0
/usr/lib64/libLLVMX86AsmParser.so.3.7.0
/usr/lib64/libLLVMX86CodeGen.so.3.7.0
/usr/lib64/libLLVMipo.so.3.7.0

**Comment by bobsummerwill** [comment]
So when I said "loads" of LLVM libraries, I didn't mean 6, which is what we seem to have here.
It is way worse than that - like 15 or 20 normally :-)

Maybe you can look into what else you have in that /usr/lib64 directory starting with libLLVM?

See https://github.com/ethereum/libethereum/blob/develop/evmjit/CMakeLists.txt, which asks for ...

llvm_map_components_to_libnames(LLVM_LIBS core support mcjit x86asmparser x86codegen ipo)

And then that is some CMake magic (search for that string inside your LLVM install) which adds indirect dependencies for those too, which is a whole bunch of them.

So I imagine that the CMake file there (which ships as part of LLVM, and which we just use) isn't expanding that list properly, maybe because of some tweaky distro-specific thing.

As I said earlier, I so recommend trying 3.7.1, which might give you a different result, and it should also work with LLVM HEAD, if you are feeling very brave?

Have a good weekend!

**Comment by daschmidty** [comment]
Took your advice and dug into /usr/lib64 some more. This was a bit of a brute force approach as I still don't know why the libraries aren't linking correctly, but I made some modifications to CMakelists.txt after wading through the errors, such that it now contains:

```
llvm_map_components_to_libnames(LLVM_LIBS core support mcjit x86asmparser x86codegen ipo executionengine x86info x86desc instrumentation transformutils vectorize aarch64codegen scalaropts instcombine)

```

and now evmjit builds successfully! 

Not out of the woods yet but getting much farther before building ChainParams.cpp.o dies with the following error (warning for unused parameter enforced as an error) [https://gist.github.com/daschmidty/af931ba358046c7a6b3d]

Sorry for the continued pain and thanks again for all your help and patience.

**Comment by bobsummerwill** [comment]
Brilliant, @daschmidty!   Glad to see you getting some momentum.

Hopefully we can come out of this process with some minor tweaks to various things to add openSUSE support, which would be nice.

Do keep reporting back!

The ChainParams error is a warning-as-error problem.    We _do_ have unresolved warnings, and that is a problem which I have slated to attack (https://github.com/ethereum/webthree-umbrella/issues/219), but the odd thing is that my TODO there is to address all our warnings so that we CAN ENABLE warnings as errors, but you are seeing that already!

Maybe defaults are different for GCC on openSUSE?

So your resolution here is either to work out how to disable that -Werror setting for your build, or better yet to work out what the warnings are yapping about, and actually find a fix for the warnings.   Up for that?   Would be very helpful to get the build warning free on at least one platform as a first step towards all platforms, and enabling warnings-as-errors.

**Comment by daschmidty** [comment]
Great news! 
turns out there was only one warning that was hanging (the one mentioned above). I commented out the unused parameter in the ChainParams.h header file and the build chugged right along.

```
ChainParams();
        ///ChainParams(ChainParams const& _org) = default;
    ChainParams(std::string const& _s, h256 const& _stateRoot = h256());
    ChainParams(bytes const& _genesisRLP, AccountMap const& _state) { populateFromGenesis(_genesisRLP, _state); }
    ChainParams(std::string const& _json, bytes const& _genesisRLP, AccountMap const& _state): ChainParams(_json) { populateFromGenesis(_genesisRLP, _state); }
```

After that the only major issue I had was the JS engine build complaining about Handle_Scope.. which after some digging I found to be due to using v8 4.x branch. Downgrading to 3.16 fixed that and I now can build 100% of the code!

Thanks again for all your help

**Comment by bobsummerwill** [comment]
So I've created a pull request for this, @daschmidty, at https://github.com/ethereum/libethereum/pull/199.
When that cycles through the Jenkins build I will submit it.   Thanks!

**Comment by bobsummerwill** [comment]
So hey, if you could add a page for openSUSE linked from here, that would be very much appreciated:

https://github.com/ethereum/webthree-umbrella/wiki/Building-on-Linux

It doesn't have to be anything very fancy at all.    Just linked on the "Building on Linux" page, and essentially just containing a distro-specific "how to install the external packages" section (including any specific-versions you have needed) and then a link to:

https://github.com/ethereum/webthree-umbrella/wiki/Linux--Generic-Building

The Fedora pages might be a good model:

https://github.com/ethereum/webthree-umbrella/wiki/Building-on-Fedora-20

**Comment by bobsummerwill** [comment]
I will be slewing all of the Wiki and old gitbook (https://gavofyork.gitbooks.io/turboethereum/) content over to the Homestead documentation (http://docs.ethereum.org) in the next few days, but please do just make the page on the Wiki, and I'll move it at the same time as the rest of them.   Thanks!
