### ISSUE TITLE
Broken version strings for all AlethOne nodes?

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#304]
Looking at http://ethernodes.org, searching for AlethOne, there are a bunch of nodes like:

```
AlethOne/v1.2.1/ETH_BUILD_TYPE/ETH_BUILD_PLATFORM
```

I think that I had assumed that nodes with "ETH_BUILD_TYPE" as a platform were really old ones with broken ID strings, but this seems to indicate that _all_ AlethOne version strings might be broken, even in our 1.2.1 releases.    We need to fix this ASAP, eh?

**Comment by chriseth** [comment]
It might be more complicated and is not too important, let's postpone it.

**Comment by bobsummerwill** [comment]
Fair enough.    I was surprised to see it was _still_ broken.   It must be something to do with BuildInfo.h generation and #defines.   Probably another side-effect of the not-friendly-for-multiple-repos build system.
