### ISSUE TITLE
Remove eth_compileSolidity and thus link dependency

### ISSUE THREAD

**Issue by chriseth** [ethereum/webthree-umbrella#309]
We might remove `eth_compileSolidity` from webthree and thus the link dependency on solidity.
Compiling via `eth_compileSolidity` is not too useful anyway since that interface only supports a very limited set of compilation options and in e.g. Mist, compilation happens in javascript.

Any thoughts?

**Comment by bobsummerwill** [comment]
Please yes!   And also:
- eth_getCompilers
- eth_compileSerpent
- eth_compileLLL

**Comment by winsvega** [comment]
https://github.com/ethereum/webthree/pull/149
