### ISSUE TITLE
Windows - Our prebuilt binaries are missing DLLs?

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#310]
So @chriseth mentioned to me that our Windows prebuild ZIP might be incomplete too?
Missing OpenCL DLL?
Or perhaps it was the installer?
I've fixed OS X.   See https://github.com/ethereum/webthree-helpers/pull/106/files.

What needs fixing for Windows again, @chriseth?   Thanks!

**Comment by bobsummerwill** [comment]
From gitter welcome channel ...

arasht82 11:04
cant run MIX , MSVCR120.dll error

maran 11:06
You probably need vistual studio runtime

**Comment by bobsummerwill** [comment]
@faenil says ...

M-bobsummerwill: you might be interested in the fact that the Building on Windows instructions seem incomplete, missing Qt5Core.dll from the binaries that getstuff pulls in

**Comment by chriseth** [comment]
Related: https://github.com/ethereum/webthree-umbrella/issues/450

**Comment by chriseth** [comment]
`msvcr120.dll` is part of the `win_eth.zip` created by jenkins. Is windows case sensitive in that regard? It does indeed not contain evmjit.dll, but I think this is because it is a single `.exe` anyway and msvc builds with static linking!
`OpenCL.dll` is not inluded

**Comment by bobsummerwill** [comment]
Right.

The problems are slightly different between the ZIP and the installer.

The NSIS installer needs to have the VC redist installer chained in.     Both the ZIPs and the installer need Qt5 and OpenCL DLLs added.    I **think** that is the TODOs.

**Comment by chriseth** [comment]
the zip does not need qt, because it is only _eth_

**Comment by chfast** [comment]
OpenCL should be loaded dynamically if available by OpenCL ICD. We cannot provided OpenCL.dll as it is a part of GPU driver.

**Comment by bobsummerwill** [comment]
So looking at https://builds.ethereum.org/cpp-binaries-data/develop/win_eth.zip, I think that we are actually DONE on that ZIP.

As of right now, it contains:

![image](https://ipfs.pics/ipfs/QmbQgwoWVD7FwM1HJexM4E9BWmKpHLvDQWtQbw7nXrmgpn)

**Comment by bobsummerwill** [comment]
Do you make any change today, @chriseth, which added that OpenCL.dll?
And are you saying that us including that OpenCL.dll is wrong, @chfast?

So I **think** that I just need to chain the VC++ redist installer into the Ethereum.exe NSIS installer generation, and we're DONE DONE.

**Comment by bobsummerwill** [comment]
So I'll close this.    Please reopen if there is more work.

Because there is another issue for the Installer one -> https://github.com/ethereum/webthree-umbrella/issues/387
