### ISSUE TITLE
Hoist up "base" dependencies to their respective modules

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#311]
At the moment, the "base" functionality in webthree-helpers introduces a global dependency onto all of the following packages for all modules in the entire umbrella, whether or not any particular module actually needs them:
1. Boost
2. jsoncpp
3. LevelDB (or RocksDB, though I don't know that we are even using that)
4. PThreads
5. json_spirit

See http://doublethinkco.github.io/cpp-ethereum-cross/images/dependency_graph.svg

**Comment by chriseth** [comment]
- boost: used just about everywhere, would not bother moving
- jsoncpp: has a lot of users,  might be complicatde
- leveldb: that  makes a lot of sense. it is used in devcore, but that user should be moved somewhere else
- pthreads: might make sense but also has a lot of users, I would guess solidity is just about the only one that does not use it.
- json_spirit: could be worthwhile converting to jsoncpp, but might be a lot of work

**Comment by bobsummerwill** [comment]
Yes, Boost is **massive** too.   500Mb.    So we can scrub that idea right away.

**Comment by bobsummerwill** [comment]
There are more too which I forgot to mention
- scrypt
- sec256k1

**Comment by bobsummerwill** [comment]
See http://doublethinkco.github.io/cpp-ethereum-cross/images/dependency_graph.svg for dependency graph with them all in.

This is also going to be a little complicated by the repo reorg, because where would they be added?

Would we actually KEEP a webthree-umbrella, which would include mix, solidity and cpp-ethereum AND the external dependencies?    Or would we add the "low-down" dependencies into cpp-ethereum as sub-modules, and then have cpp-ethereum as a sub-module in solidity and mix?   Plus maybe some more sub-modules there for extra external dependencies?   I think so, but having the sub-modules nested like that doesn't make me want to smile.

**Comment by bobsummerwill** [comment]
Done - will be merging this soon.
