### ISSUE TITLE
ethminer 100% CPU

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#314]
@polymetric says ... this is occuring on my ethminer. Mining at a local geth node, GPU only on an nvidia gtx970.

Issue moved from https://github.com/ethereum/cpp-ethereum/issues/1949

Please could let us know your operating system (and version), your ethminer version, etc.  Thanks!

**Comment by tswindell** [comment]
I'm solo mining on Ubuntu 14.04LTS using geth and the CUDA adapted ethminer tree with 2x GPUs, getting 200% usage when using both cards, and 100% for either. Could this have something to do with the syncing between CUDA code and CPU?

**Comment by bobsummerwill** [comment]
Hmm - have you seen this before, @Genoil?

**Comment by Genoil** [comment]
Yes it was adressed in https://github.com/Genoil/cpp-ethereum/commit/453726de7fc656a8141530013ee836044430014f by @RoBiK75

**Comment by bobsummerwill** [comment]
Great - thanks for the link, @Genoil.

@tswindell @polymetric I would recommend that you switch to Genoil ethminer, if you aren't already using it.   Thanks!

**Comment by Genoil** [comment]
Well, apparently the CPU usage in OpenCL mode of my fork isn't very good compared to the official miner: http://forum.ethereum.org/discussion/comment/21793/#Comment_21793

I'll have to investigate myself, still. Don't even have any GPU installed in my dev box currently :)

**Comment by bobsummerwill** [comment]
FYI, @Genoil.

@smartbitcoin was looking at inexplicable performance differences in CPU mining between eth and geth as well.
