### ISSUE TITLE
openSUSE - Add build instructions page to Wiki

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#316]
I've asked @daschmidty if he can write up a Wiki page describing what he did to get a successful build on openSUSE.

See https://github.com/ethereum/webthree-umbrella/issues/302.

That content can be migrated by me to the Homestead guide later next week.

**Comment by daschmidty** [comment]
I've created a high-level summary of the requirements to build on SUSE here [https://github.com/ethereum/webthree-umbrella/wiki/Building-on-OpenSUSE] and linked to it from the building on linux wiki entry.

**Comment by bobsummerwill** [comment]
Brilliant!   Much appreciated.   Thank you!
Just revectored the "generic Linux build" link, which was pointing to the wrong place.
Great to have this content.   Thanks again.
