### ISSUE TITLE
AlethOne v1.2.1 Pool Mining setting doesn't fully persist

### ISSUE THREAD

**Issue by destenson** [ethereum/webthree-umbrella#318]
When you exit the AlethOne with Pool Mining selected, the next time it is started, Pool Mining is selected, but the Reward Address input and copy button are there as if Solo Mining were selected instead.

**Comment by chriseth** [comment]
Thanks for reporting! This was already fixed in https://github.com/ethereum/alethzero/pull/147 and will be part of the next release.
