### ISSUE TITLE
net.addPeer wont work if clients on different platforms

### ISSUE THREAD

**Issue by winsvega** [ethereum/webthree-umbrella#319]
it appears that clients on a different platforms might not add each other by net.addPeer

should check this one on private network

**Comment by smartbitcoin** [comment]
would this be a firewall issue?   win->linux works , b/c ubuntu default not blocking 30303, but linux->win,  30303 will be blocked if not manually turn it off.

**Comment by winsvega** [comment]
tested in local network

ubuntu <-> ubuntu  add peers on localnetwork

**Comment by bobsummerwill** [comment]
Do you have Windows and Ubuntu boxes you were seeing this happening to, @winsvega?

**Comment by winsvega** [comment]
No. I am trying to reproduce this issue. It was mentioned on gitter channel.

**Comment by winsvega** [comment]
current windows develop build not working

**Comment by bobsummerwill** [comment]
Please could you clarify "not working", @winsvega?

**Comment by bobsummerwill** [comment]
This thing in Jenkins?

CMake Error at webthree-helpers/extdep/install/windows/x64/share/llvm/cmake/LLVMExports.cmake:386 (message):
  The imported target "llvm-tblgen" references the file

```
 "C:/Jenkins/sharedspace/ethrelease/label/windows-slave/webthree-umbrella/webthree-helpers/extdep/install/windows/x64/bin/llvm-tblgen.exe"
```

Or are you getting a local build error, @winsvega?

**Comment by winsvega** [comment]
No. I mean building itself is fine. The actual eth.exe wont sync and crash. 

 eth 1.2.2 with assert on windows in
webthree-umbrella\libweb3core\libdevcore\TrieDB.h line 909

```
N X 11:19:13.301|p2p Receiving UDP message failed. 10061 :
N X 11:19:16.496|p2p|a31c961eвЂ¦|eth/v1.2.1/Windows/msvc/JIT/Release/1b72dc78/ all 1024 unknown blocks requested; peer on different chain?
The thread 0x141c has exited with code 0 (0x0).
N X 11:19:51.436|p2p|bcef1be6вЂ¦|Geth/v1.4.0-unstable/linux/go1.5.1 Error reading - Abrupt peer disconnect: End of file
```
