### ISSUE TITLE
PPA can't build package since 1.2.1: Missing Flu

### ISSUE THREAD

**Issue by Belphemur** [ethereum/webthree-umbrella#320]
Hello, 

It's been a couple of days that your PPA fail to build cpp-ethereum for all ubuntu version:
https://launchpad.net/~ethereum/+archive/ubuntu/ethereum-dev/+packages

You removed flu from the release but you forgot to remove it from your building script:

```
make[1]: Leaving directory '/«PKGBUILDDIR»'
   dh_install
cp: cannot stat ‘debian/tmp/usr/local/bin/flu’: No such file or directory
dh_install: cp -a debian/tmp/usr/local/bin/flu debian/flu/usr/bin/ returned exit code 1
make: *** [binary] Error 2
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
debian/rules:21: recipe for target 'binary' failed
```

**Comment by chriseth** [comment]
Waiting for the ppa to pick up the build job

**Comment by bobsummerwill** [comment]
Thanks for picking this up, @chriseth.

And thanks for the report @Belphemur.   See also https://github.com/ethereum/webthree-umbrella/issues/275.

**Comment by bobsummerwill** [comment]
Is this working now, guys?

**Comment by Belphemur** [comment]
Thanks @chriseth I've been able to install the package for 1.2.1.

**Comment by bobsummerwill** [comment]
WOOT WOOT!   Thanks, guys.
