### ISSUE TITLE
AlethOne - "No OpenCL Platforms founds"

### ISSUE THREAD

**Issue by martinbrion** [ethereum/webthree-umbrella#324]
I start the AlethOne and it tells me the following on the "console".

i 12:35:26.141 : p2p upnp device not found

Then i click on start mining and then it tells me the following:

i 12:36:15.508 : gpuminer0 workloop 0 #000000....
i 12:36:15.512 :gpuminer0 initializing miner...
No OpenCL platforms found 
clEnqueuewritebuffer(-36)

Can someone help me to start mining ether and colaborate with this wonderfull proyect?
image:

![alethone](https://cloud.githubusercontent.com/assets/17726806/13606815/418e8228-e52c-11e5-8604-359dfa41cc35.png)

Thanks

**Comment by bobsummerwill** [comment]
What GPU hardware do you have, @martinbrion?
It looks like Windows 8.1?   Please could you confirm?

**Comment by martinbrion** [comment]
Thank you in advance for your help, please let me know if this images solve your question.

![1](https://cloud.githubusercontent.com/assets/17726806/13613129/8e565ee2-e549-11e5-8b2a-bb1c9dc3d3d7.png)
![2](https://cloud.githubusercontent.com/assets/17726806/13613131/8e59c79e-e549-11e5-915d-15116795f427.png)

**Comment by bobsummerwill** [comment]
We'll need to know the specific Intel HD card.

GPU mining is pretty specific in what it needs.    Not all graphics cards can be used.   In specific, lots of memory is required.   Many GPUs aren't suitable for that reason.

**Comment by smartbitcoin** [comment]
please find compatible graphic card and make sure opencl driver installed.  embedded graphic device won't work.
