### ISSUE TITLE
Page on how to geth attach to eth

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#327]
Because that requires a bit of magic right now.

**Comment by winsvega** [comment]
Run eth with some working directory

```
eth -d "/media/www/STUFF/Ethereum/testnet/ethnode1/datadir"
```

Run geth attach with ipc socket in that directory to attach to the given eth instance (you might run multiple eth instance with different working directories set up) 

```
geth attach ipc:/media/www/STUFF/Ethereum/testnet/ethnode1/datadir/geth.ipc
```

**Comment by bobsummerwill** [comment]
And also that we need to be using develop of geth.   1.3.5 doesn't work

**Comment by chriseth** [comment]
or use ethconsole (we need to add a way to attach to a non-standard ipc socket, though)

**Comment by smartbitcoin** [comment]
just wondering if  web3 javascript api able to communicate with IPC or not. :)   if it's on same local nodes.

**Comment by chriseth** [comment]
@yann300 could you please take a look here, i.e. add appropriate docs in the homestead guide also mentioning ethconsole?

**Comment by yann300** [comment]
PR https://github.com/ethereum/homestead-guide/pull/183
