### ISSUE TITLE
Windows - Trying to eliminate boost chrono and datetime dependencies

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#328]
In progress at https://github.com/ethereum/webthree-helpers/pull/90

**Comment by chriseth** [comment]
De-prioritizing. Can still be done "at leisure", but not essential.

**Comment by bobsummerwill** [comment]
Yes ... this is not at all important, but I will be very happy when I get to the bottom of the issue.

It is a very insipid bit of auto-link magic which is the reason why I still haven't manage to resolve this.

It is nagging at me!

**Comment by bobsummerwill** [comment]
I've tried to resolve this several times now, without success.

There is some implicit linking happening which is very hard to track down.

I am going to give up for now.    It might be easier to address after the dependencies are in better shape (specifically https://github.com/ethereum/webthree-umbrella/issues/311)
