### ISSUE TITLE
doesnt work on 32 bit windows 7 system

### ISSUE THREAD

**Issue by coderwithattitude** [ethereum/webthree-umbrella#329]
Cant get it to work on my 32 bit system is there a workaround?

**Comment by bobsummerwill** [comment]
Hey @CoderWithAttitude,

If you are comfortable building from source and doing some work it MIGHT be possible to get this going, but you are in unsupported configuration land here.

@gcolvin was having a look at 32-bit builds, though I think that was for Linux, right, Greg?

And I think the conclusion was that if you disable EVMJIT (so you don't need LLVM) that it was just about possible.    Is that correct, Greg?    What was the issue number for that?

**Comment by coderwithattitude** [comment]
thanks @bobsummerwill  i am taking a shot at installing ubuntu and running it there.

**Comment by bobsummerwill** [comment]
From gitter welcome channel ...

@CoderWithAttitude said:

i tried installing geth and on my pc but it says my PC is not 64 bit. so i am thinking if i install ubuntu on oracle virtual box i will be able to install all the required packages on it

@bobsummerwill said:

Right - well, yeah, that might be possible, if you can run a 64-bit OS in a VM on a 32-bit machine. Even if that is possible, the performance will likely be horrifically bad.

Might be time for you to get a new computer, eh?  :-)
