### ISSUE TITLE
eth connecting to clients from another network

### ISSUE THREAD

**Issue by winsvega** [ethereum/webthree-umbrella#331]
running eth with  --network-id 25 and it is constantly connecting to random peers and prints errors of RLPX negotiation or incorrect timestamp from that nodes. 

I think eth should not talk to such nodes with different network id in the first place. 

```
✘  16:51:54.176|p2p  Internal error in handshake: RLPXFrameCoder disappeared.
```

**Comment by bobsummerwill** [comment]
This issue was moved to ethereum/cpp-ethereum#3127
