### ISSUE TITLE
Warn if seal engine different in ethminer and eth

### ISSUE THREAD

**Issue by winsvega** [ethereum/webthree-umbrella#332]
running eth with custom genesis and on a private network
ethminer output: 

```
miner  17:05:01.264|ethminer  Getting work package...
  ✘  17:05:01.265|ethminer  Failed to submit hashrate.
  ✘  17:05:01.265|ethminer  Dynamic exception type: jsonrpc::JsonRpcException
std::exception::what: Exception -32602 : INVALID_PARAMS: Invalid method parameters (invalid name and/or type) recognised: INVALID_PARAMS: Invalid method parameters (invalid name and/or type) recognised
```

**Comment by winsvega** [comment]
ok. found the issue. it was due to the difference in sealEngine on a node and ethminer
better be a warning in such case

**Comment by bobsummerwill** [comment]
What was the miner in this case?    Genoil?

**Comment by winsvega** [comment]
ethminer (Ethash) + eth (BasicAuthority)

**Comment by bobsummerwill** [comment]
Can this be fixed, @winsvega?   Or is such a difference in sealEngine allowable and valid?   And we just need to improve our handling of this situation?

**Comment by sunildhillon** [comment]
```
JSON-RPC problem. Probably couldn't connect. Retrying in 1...
miner  21:33:27.936|main  Getting work package...
  X  21:33:29.163|main  Failed to submit hashrate.
  X  21:33:29.173|main  Dynamic exception type: class jsonrpc::JsonRpcException
std::exception::what: Exception -32003 : Client connector error: libcurl error: 7 -> Could not connect to http://127.0.0.1:8545
```

I'm getting this error in windows 10.

**Comment by winsvega** [comment]
@bobsummerwill this is not a bug. and it's already handled. we may just add some more info like
"Failed o submit hashrate, please check your sealengine."

**Comment by bobsummerwill** [comment]
So would you like to make a PR with any extra debug text you think is appropriate, @winsvega?
And then we will close this issue.    Thanks!
