### ISSUE TITLE
ethminer mining stops on disconnect

### ISSUE THREAD

**Issue by winsvega** [ethereum/webthree-umbrella#334]
ethminer works fine with eth. but then if connection is interrupted (network delay or something) it would print an error message,  

then. if connection restored again, it resumes mining but do 0 hash rate until miner restarted

father more. ethminer shows that mining was successfull. 

```
  ℹ  19:26:01.446|ethminer  B-) Submitted and accepted.
```

but web3.eth.syncing still output 0 blocks mined and latest block is still 0 from geth attach console to eth

**Comment by bobsummerwill** [comment]
This issue was moved to ethereum/cpp-ethereum#3128
