### ISSUE TITLE
Windows - Add automated tests to Jenkins

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#335]
We are missing automated test runs in Jenkins for Windows.
This is a pretty major omission considering how important a platform Windows is for us.
It isn't an entirely trivial thing to set up, but it shouldn't be too hard.

**Comment by winsvega** [comment]
can't get admin rights to Jenkins

**Comment by bobsummerwill** [comment]
Hey @winsvega!

Why did you close this?    We still don't have Windows automation, do we?

Were you just waiting for somebody to give you Jenkins admin rights?    You should have nagged me!    I've just added you as an admin.   I think :-)

**Comment by bobsummerwill** [comment]
Happening in Appveyor and Travis now.
