### ISSUE TITLE
Can't set default account in eth

### ISSUE THREAD

**Issue by YamashitaRen** [ethereum/webthree-umbrella#336]
I'm trying to change the default account in eth.
--sign-key and --session-sign-key seem to have the same effect : it changes the signing account only for the current session.
If I type
`web3.eth.defaultAccount` = '0x8888f1f195afa192cfee860698584c030f4c9db1'
in the console, the value will be reset to "undefined" if I restart eth.

I'm using eth 1.2.1 on Archlinux.

**Comment by smartbitcoin** [comment]
in web3,  variable without a settter function can't be changed by direct assign "="

**Comment by chriseth** [comment]
@frozeman is `admin_eth_setSigningKey` used by `web3.eth.defaultAccount`? If yes, we should implement this in eth.

**Comment by frozeman** [comment]
the web3.js default account has nothing to do with the `eth` options.
This is purely handled client side in js. and will be reset on each page reload.

It is there to make the use of an account on many functions easier.

**Comment by chriseth** [comment]
Does that answer your question, @YamashitaRen ? Please reopen if not.

**Comment by YamashitaRen** [comment]
Ah, sorry, this wasn't really what I was asking.

Basically, I want to "migrate" from geth to eth in order to fully test eth.
I added my geth key with ethkey and it's now visible in `web3.eth.accounts`.
But I have no clue on how to change the defaults "Transaction Signer" and "Mining Beneficiary" shown when I start eth.
I thought that `--sign-key` would change the default but it is not the case (so I wonder if it's a bug or if another thing differentiate if from `--session-sign-key`).
Since your answers, I tried to use `web3.admin.eth.setMiningBenefactor` but, like `--sign-key`, it doesn't change the defaults.
So I'm still wondering if I'm doing this wrong, if it's a bug, or if I'm asking for a nonexistent feature...

**Comment by chriseth** [comment]
@YamashitaRen ah, thanks for the clarification. We are actually in the process of cleaning up eth and removing features (especially those that are not working) from the commandline options. So if I understand you correctly, you are just irritated by the fact that the settings do not change, and thus would not mind if we just remove them, right?

**Comment by YamashitaRen** [comment]
@chriseth
Yes, you could say that I am trying eth to see if I like using it. Nothing too serious.
I totally support your idea of cleaning it.
So there are two things : 
1) `--sign-key` seems to only change the signing key for the current session, which led me to believe that you should remove either `--sign-key` or `--session-sign-key`.
2) Since I bumped into this, I wonder if there are any plans to allow the user to permanently change the default addresses in eth.
