### ISSUE TITLE
Windows - Add support for Chocolatey packages

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#345]
See http://ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/installing-binaries/windows-chocolatey.html.

@tgerring has been doing some Chocolatey work.    I'm sure we can get that going between us.

Effectively "apt-get for Windows"

**Comment by smartbitcoin** [comment]
sounds interesting.  I just like apt-get or yum if it works on windows.

**Comment by bobsummerwill** [comment]
Yes, it's a really useful tool from what I understand, @smartbitcoin.

It is built on top of NuGet packages.   It has been around for a few years now, and is pretty popular.

**Comment by bobsummerwill** [comment]
This issue was moved to ethereum/cpp-ethereum#3132
