### ISSUE TITLE
Doesn't work with Windows XP 32bit

### ISSUE THREAD

**Issue by gr225607** [ethereum/webthree-umbrella#347]
Not sure if you planning to support  Windows XP 32bit, but it doesn't seem to work with it. The following error appears:
"Mix.exe is not a valid Win32 application."
"AlethOne.exe is not a valid Win32 application."
"AlethZero.exe is not a valid Win32 application."

**Comment by bobsummerwill** [comment]
Thanks for the report, @gr225607!

No.   We're not supporting either XP or 32-bit binaries.
http://docs.ethereum.org/en/latest/ethereum-clients/cpp-ethereum/installing-binaries/windows-installer.html

I would really recommend that you update to at least Win7, if you can.    Running XP is a horrible security risk!   Best wishes.
