### ISSUE TITLE
Add link to tests Wiki in new ethdocs.org guide

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#354]
New site is ... http://www.ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/index.html

As @winsvega raised, we need to link to https://github.com/ethereum/tests/wiki.

https://github.com/ethereum/tests/wiki

Anything else where the existing Wiki has content which we must have right now?   Please comment here.

**Comment by chriseth** [comment]
Is that done?

**Comment by bobsummerwill** [comment]
Nope!

**Comment by winsvega** [comment]
https://github.com/ethereum/homestead-guide/pull/239
