### ISSUE TITLE
OpenCL 1.0 is not supported

### ISSUE THREAD

**Issue by ghost** [ethereum/webthree-umbrella#355]
Hello, I try to use AlethOne and it's not so simple as everybody wrote. After I wated two days for Syncing it wrote me that my OpenCL 1.0 is not supported and clEnqueueWriteBuffer<-36>. I have Nvidia Geforce GTS 250M. I tried to google it and I installed CUDA drivers without any success. It's peevishly that it let me download 15GB of some blocks and after all that suffering it did me that. Is there any solution except angrily throwing it through the window?

**Comment by bobsummerwill** [comment]
Have you tried seeking help at https://www.reddit.com/r/ethermining?

The other people doing mining themselves often have the best knowledge on particular GPUs, and whether there are solutions, or if you are just out of luck.

I hope you find an answer, but it is possible that your GPU just won't work.

Something we could address is the fact that you aren't getting a useful error message PRIOR to needing a full block-chain download.

Thanks for the report and I sympathize with your pain.

**Comment by bobsummerwill** [comment]
Hey @Jendovnik,

AlethOne and AlethZero are slated for death (https://blog.ethereum.org/2016/02/12/ethereum-dev-update-c-roadmap/), and it increasingly looks like we need to put a bullet in their backs right now and remove that prominent link to "One Click Miner" on http://ethereum.org.     Sorry that you were a victim of their imminent demise.

I would recommend that you consider switching to ethminer+geth, which is what nearly all miners appear to be doing, and also to check out the https://github.com/Genoil/cpp-ethereum/ ethminer fork, which appears to be the leading solution.

Also check out the side-bar on http://reddit.com/r/etherminer for the guides there.

Good luck.  Please do let us know if you find a working setup and let us know what you did.   Thanks!

**Comment by ghost** [comment]
Thanks for your info. I am trying geth miner, but I am downloading blockchains thrre days in a row and I am still downloading. I am affraid, my 500 GB disc won't be large enough. I had to delete a lot of programs for geth. I hope it will finish download soon.

**Comment by bobsummerwill** [comment]
Hey @Jendovnik,
I hear you.   I have long-running block-chain syncs going on both OS X and Windows machines.   The initial setup is a painfully long process at the moment.   There are lots of improvements planned in the coming months.

**Comment by bobsummerwill** [comment]
Closing issue, because AlethOne will be removed very soon.
