### ISSUE TITLE
Need to rework all the C++ content on "ethereum-org" site

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#356]
All the C++ content on the "ethereum-org" site is based on old Frontier instructions and is less than ideal.

Should completely revamp it, and have it point to docs.ethereum.org for more details.

Need to remove all webthree-umbrella Wiki references from there.

**Comment by winsvega** [comment]
so this page is outdated too 
https://ethereum.org/cli

Button download Mix points to 
https://github.com/ethereum/webthree-umbrella/releases/tag/v1.2.2

what about this?
https://ethereum.org/ether

there are outdated links in line 
"Learn more on the Main, Go and C++ Wikis"

Should we check solidity examples as well?  like this one
https://ethereum.org/dao

**Comment by bobsummerwill** [comment]
Yes - the whole thing needs to a good beating with a stick!
