### ISSUE TITLE
when rust send invalid transaction, eth++ hang up. ( should just reject )

### ISSUE THREAD

**Issue by smartbitcoin** [ethereum/webthree-umbrella#360]
Eth++ hang up when syncing.  An invalid transaction from rust trigged it.

![fullsizerender](https://cloud.githubusercontent.com/assets/5984485/13756578/ed1a73ee-e9f6-11e5-9996-ade87a56a61d.jpg)

**Comment by chriseth** [comment]
What exactly happened, do you mean eth crashed by "Eth++ hang up", or did it just stop syncing?

**Comment by chriseth** [comment]
Happened to me, too, but did not cause a crash, so I don't think this is an issue. Please reopen if it did crash for you.
