### ISSUE TITLE
Eth stops syncing

### ISSUE THREAD

**Issue by naughtyfox** [ethereum/webthree-umbrella#363]
Hi collegues! I faced problem which is constantly reproduces. I have master branch of eth checked out. After it's been synchronized it stops syncing further after some time. Here's some logs:

``` javascript
> web3.admin.setVerbosity(6)
true
> web3.eth.syncing
{
  currentBlock: 1150086,
  highestBlock: 1153874,
  startingBlock: 1149944
}
> web3.eth.syncing
{
  currentBlock: 1150086,
  highestBlock: 1153874,
  startingBlock: 1149944
}
> web3.eth.syncing
{
  currentBlock: 1150086,
  highestBlock: 1153914,
  startingBlock: 1149944
}
> web3.eth.syncing
{
  currentBlock: 1150086,
  highestBlock: 1154015,
  startingBlock: 1149944
}
> web3.eth.syncing
{
  currentBlock: 1150086,
  highestBlock: 1154015,
  startingBlock: 1149944
}
> web3.eth.syncing
{
  currentBlock: 1150086,
  highestBlock: 1154015,
  startingBlock: 1149944
}
> web3.eth.syncing
{
  currentBlock: 1150086,
  highestBlock: 1154015,
  startingBlock: 1149944
}
> web3.eth.syncing
{
  currentBlock: 1150086,
  highestBlock: 1154015,
  startingBlock: 1149944
}
> web3.eth.syncing
{
  currentBlock: 1150086,
  highestBlock: 1154015,
  startingBlock: 1149944
}
> web3.eth.syncing
{
  currentBlock: 1150086,
  highestBlock: 1154015,
  startingBlock: 1149944
}
> web3.eth.syncing
{
  currentBlock: 1150086,
  highestBlock: 1154015,
  startingBlock: 1149944
}
> web3.eth.syncing
{
  currentBlock: 1150086,
  highestBlock: 1154015,
  startingBlock: 1149944
}
> web3.eth.syncing
{
  currentBlock: 1150086,
  highestBlock: 1154015,
  startingBlock: 1149944
}
> web3.eth.syncing
{
  currentBlock: 1150086,
  highestBlock: 1154015,
  startingBlock: 1149944
}
> web3.eth.syncing
{
  currentBlock: 1150086,
  highestBlock: 1154015,
  startingBlock: 1149944
}
> web3.eth.syncing
{
  currentBlock: 1150086,
  highestBlock: 1154532,
  startingBlock: 1149944
}
> web3.eth.syncing
{
  currentBlock: 1150086,
  highestBlock: 1154532,
  startingBlock: 1149944
}
> web3.eth.syncing
{
  currentBlock: 1150086,
  highestBlock: 1154532,
  startingBlock: 1149944
}
> web3.eth.syncing
{
  currentBlock: 1150086,
  highestBlock: 1154590,
  startingBlock: 1149944
}
> web3.eth.blockNumber
1150086
```

As you can see highestBlock is being changed, but currentBlock isn't. So i can conclude it's not syncing. It reproduces constantly after some time waiting. I run this code on Ubuntu 15.10 under virtual box. 

Thank you and I hope the issue will be fixed soon.

**Comment by smartbitcoin** [comment]
two ways to confirm that:
1. check if your network just timeout in that moment.
2. restart your eth++ to check if it works again.

possible reason:
1. network lost.
2. you are on side-chain.
3. the peers you connected just no response at that moment.
4. maybe bug in eth++

**Comment by naughtyfox** [comment]
ways:
1. it couldn't be just network timeout because eth updates network height
2. restarting eth helps. But let be frank it's not production level

reasons:
1. absolutly not
2. doubt it, how to confirm?
3. all of them at the same time? where eth can get network height in this case?
4. maybe?

**Comment by chriseth** [comment]
You say "master branch" - you probably meant either develop or release. Which version is it exactly, i.e. what does `eth --version` print?

**Comment by naughtyfox** [comment]
Hi chriseth!

> You say "master branch" - you probably meant either develop or release. Which version is it exactly, i.e. what does eth --version print?

 here is the command output

```
$ ./webthree/eth/eth --version
eth version 1.2.1
eth network protocol version: 63
Client database version: 12041
Build: Linux/g++/JIT/Release
```

**Comment by chriseth** [comment]
Could you update to 1.2.2, that should be latest

**Comment by winsvega** [comment]
works for me on Ubuntu 14.04  eth 1.2.2

**Comment by 3thereum** [comment]
I have the same bug as OP, using the latest 1.2.2
Syncing just completely stops after a while (maybe 20minutes-ish?)
I think this is a critical bug if trying to run an eth node doesn't work at all :S

**Comment by 3thereum** [comment]
Just adding that I was running 1.2.0 before and it was syncing, albeit often with many 'SLOW IMPORT's, which is also not very good unfortunately...Additionally, I couldn't upgrade to 1.2.1 because the packaged release builds were failing.
I'm also on Ubuntu 14.04.

**Comment by chriseth** [comment]
Probably fixed by https://github.com/ethereum/libethereum/pull/208
Testing now...

**Comment by chriseth** [comment]
Should be fixed. Please try latest develop and reopen if it is not fixed for you.
