### ISSUE TITLE
Switch all build.ethdev.com references to build.ethereum.org

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#365]
- [X] In shell scripts and batch files (see https://github.com/ethereum/webthree-helpers/pull/107)
- [X] In documentation (see https://github.com/ethereum/homestead-guide/pull/182)
- [x] In links to installers from the releases page, etc.
- [x] In READMEs
- [x] In Jenkins

**Comment by chriseth** [comment]
Changing jenkins references to `builds.ethereum.org` (with `s`) as this seems to be the native name of the server.

**Comment by chriseth** [comment]
Done.

**Comment by bobsummerwill** [comment]
Excellent, thanks, @chriseth!
I started looking for references within Jenkins, but couldn't work out how it was plugged together.
What did you need to do to fix this?

**Comment by chriseth** [comment]
It was in manage jenkins -> configure system -> publish over ssh, i.e. it was an option of one of the plugins.
