### ISSUE TITLE
AlethOne slow net

### ISSUE THREAD

**Issue by Yjakara** [ethereum/webthree-umbrella#366]
help me. I installed this program .. and then I uninstalled it because I began slowly ist internet, hardly. and now I do not know how to fix it. It goes horribly wrong like the Internet. What stim?
need help me Yjakara@gmail.com
thx

**Comment by bobsummerwill** [comment]
Is this on a Windows PC, @Yjakara?

Are you just wanting to remove AlethOne from your machine entirely?    Or wanting to get it working?

**Comment by Yjakara** [comment]
Problem solved. When you turn the program I detonate router ...

**Comment by bobsummerwill** [comment]
OK - glad you got past it.
