### ISSUE TITLE
eth slow synchronization

### ISSUE THREAD

**Issue by winsvega** [ethereum/webthree-umbrella#367]
I have eth syncing at a very slow speed. from 4-5 b/s  to 0.09 b/s. 
Thus I am starting a review of block import code. 
Lets post any issues we found here.

**Comment by chriseth** [comment]
In debug mode, you usually get reports about which stages of the import take how long. Do you have such a report?

**Comment by winsvega** [comment]
SLOW IMPORT: #ee43714c…  # 1156374
  ℹ  19:04:14.845|eth    Import took: 0.681543
  ℹ  19:04:14.845|eth    preliminaryChecks: 0.005195
  ℹ  19:04:14.845|eth    enactment: 0.673079
  ℹ  19:04:14.845|eth    collation: 1.7e-05
  ℹ  19:04:14.845|eth    writing: 0.000249
  ℹ  19:04:14.845|eth    checkBest: 0.002938
  ℹ  19:04:14.845|eth    7  transactions
  ℹ  19:04:14.845|eth    2146612  gas used
 ⚡   19:04:14.845|eth  Block import 1156374 681 ms
 ℹ  19:06:31.303|eth  3 blocks imported in 1466 ms ( 2.04579 blocks/s) in # 1156722

**Comment by chriseth** [comment]
most of the time is spent on enactment which includes running the VM. Which vm type did you use?

**Comment by smartbitcoin** [comment]
I just wondering what' s the slowest rate all the time.    above case is 2 blocks/ sec,   in case it possible approach 1 block / 10 sec, that's very dangerous signal .

in above block, the 3th transaction have a pretty long run smart contract.

https://www.etherchain.org/tx/0x362b89a644e68da40c712076e439edb7534d8c882fc7e43fa79bf31325348dc3

almost hit half gas limit.  I just wondering if a smart contract hit the gas limitation , what gona happen?

**Comment by winsvega** [comment]
@chriseth 
    --vm <vm-kind>  Select VM; options are: interpreter, jit or smart (default: interpreter).

so I guess it is interpreter

**Comment by bobsummerwill** [comment]
Is that a command-line option on `eth`?   Which I assume is only even offered if you build with EVMJIT=on?

**Comment by bobsummerwill** [comment]
This issue was moved to ethereum/cpp-ethereum#3133
