### ISSUE TITLE
Ethminer GPU failure handling

### ISSUE THREAD

**Issue by ghost** [ethereum/webthree-umbrella#37]
Moved here from [cpp-ethereum](https://github.com/ethereum/cpp-ethereum/issues/2940)

In multi AMD GPU rig if one GPU fails, ethminer does not produce hashes, but still polling for new work (sometimes it does not poll) and the rest of GPU still running under load and consume energy for nothing.

Rarely if one GPU fails, ethminer continue to run on the rest of GPUs, but failed GPU will never backup. I am wondering if it's possible to fix?

**Comment by bobsummerwill** [comment]
Won't fix - old.
