### ISSUE TITLE
Ethminer - Exception thrown in Worker Thread

### ISSUE THREAD

**Issue by billprescott** [ethereum/webthree-umbrella#370]
Hi

Latest version of Ethminer on Windows

Will not run hashtest and will not mine properly.

Reason - Exception thrown in Worker Thread.

GPU - AMD Readeon Fury X

Windows 8.1

Did a full windows install. Made no difference.

Does not mine in a pool either.

Any suggestions?

thanks

Bill
![ethminer](https://cloud.githubusercontent.com/assets/13895845/13872500/346a8a36-ed3f-11e5-88c5-2e59708af2e3.PNG)

**Comment by billprescott** [comment]
When pool mining it appears to mine but does not submit results. Just moves onto the next work package.

**Comment by bobsummerwill** [comment]
Thanks for the report, Bill.

No immediate suggest to make, I'm afraid, but it's on our work heap now.   Best wishes!

Please do also try looking for help at http://ethereum.stackexchange.com/.   There is a mining section there.

**Comment by billprescott** [comment]
Thanks Bob

How long does it usually take to get someone to look at these issues?  

Regards

Bill.

**Comment by bobsummerwill** [comment]
Hey @billprescott.

There is no "normal", I am afraid.   The team is rebooting (see http://www.ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/index.html#project-reboot).

There are 158 logged issues in webthree-umbrella and more in various other repositories, and there is only a small team, many of whom are in Europe where it is currently nearly 10pm.

Lots of miners are using a fork of ethminer - see
https://github.com/ethereum/webthree-umbrella/issues/315.    You might like to try that out.

Also check out https://www.reddit.com/r/ethermining.    Others may be hitting the same issues as you.

**Comment by billprescott** [comment]
Ok many thanks.  

More than happy to provide access to the machine when you do eventually review this issue.  

Regards

Bill.

**Comment by bobsummerwill** [comment]
Thanks, Bill.

My North American based colleague @gcolvin and myself will be having a pow-wow about ethminer issues this afternoon, because a few things have popped up at Homestead.   Those probably just reflect an increased number of users and eyeballs, or maybe a broader range of machine configurations which people are trying to run the code on (especially WRT OpenCL support).

Whatever the case, we need to do a quick triage, and see whether we need to jump on these right now ahead of other priorities.     We are both relatively new to the team, though, but both grey-of-hair :-)

Will keep you in the loop!   Best wishes.

**Comment by billprescott** [comment]
Thanks Bob

I downloaded this version of the miner. 

http://cryptomining-blog.com/tag/ethminer-0-9-41-download/

I can now pool mine.  Will try solo mining and let you know.  This tells me some bug has recently been added.  

Thanks

Bill.

**Comment by bobsummerwill** [comment]
Well, not necessarily.    See https://github.com/ethereum/webthree-umbrella/issues/315

If you have a working setup, I'm going to close this issue.

I really think our resolution here is to upstream all the Genoil changes, and work with them to get the boxes the right shape.

Sorry you were the victim!    Others have been successful.    We don't know what the common factors to success or failure are yet.   TBD.   Thanks!
