### ISSUE TITLE
can not compile on fedora 22

### ISSUE THREAD

**Issue by tflux99** [ethereum/webthree-umbrella#371]
iam trying to get the webthree-umbrella compiled on linux fedora 22 but get this error on make

[root@ns3511722 build3]# make
[  0%] Built target cpp-ethereum_BuildInfo.h
[  2%] Built target scrypt
[  2%] Built target secp256k1
[  2%] Built target dev_BuildInfo.h
[  6%] Built target devcore
[  8%] Built target devcrypto
[ 11%] Built target p2p
[ 11%] Linking CXX executable rlp
../libdevcrypto/libdevcrypto.so: error: undefined reference to 'CryptoPP::StringSinkTemplate<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::StringSinkTemplate(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)'
../libdevcrypto/libdevcrypto.so: error: undefined reference to 'dev::fromHex(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, dev::WhenError)'
../libdevcrypto/libdevcrypto.so: error: undefined reference to 'CryptoPP::RandomNumberGenerator::GenerateIntoBufferedTransformation(CryptoPP::BufferedTransformation&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long long)'
../libdevcrypto/libdevcrypto.so: error: undefined reference to 'CryptoPP::RandomPool::GenerateIntoBufferedTransformation(CryptoPP::BufferedTransformation&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long long)'
../libdevcrypto/libdevcrypto.so: error: undefined reference to 'dev::writeFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, dev::vector_ref<unsigned char const>, bool)'
../libdevcrypto/libdevcrypto.so: error: undefined reference to 'dev::toUUID[abi:cxx11](dev::FixedHash<16u> const&)'
../libdevcrypto/libdevcrypto.so: error: undefined reference to 'dev::contentsString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../libdevcrypto/libdevcrypto.so: error: undefined reference to 'dev::fromUUID(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../libdevcrypto/libdevcrypto.so: error: undefined reference to 'dev::isHex(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../libdevcrypto/libdevcrypto.so: error: undefined reference to 'dev::g_logPost[abi:cxx11]'
collect2: error: ld returned 1 exit status
libweb3core/rlp/CMakeFiles/rlp.dir/build.make:114: recipe for target 'libweb3core/rlp/rlp' failed
make[2]: **\* [libweb3core/rlp/rlp] Error 1
CMakeFiles/Makefile2:501: recipe for target 'libweb3core/rlp/CMakeFiles/rlp.dir/all' failed
make[1]: **\* [libweb3core/rlp/CMakeFiles/rlp.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: **\* [all] Error 2

i read in another forum fix it with json-rpc https://gitter.im/ethereum/cpp-ethereum/archives/2015/11/05 

but i have installed everything listed here https://github.com/ethereum/webthree-umbrella/wiki/Building-on-Fedora

**Comment by bobsummerwill** [comment]
Hey @tflux99.

Instructions are now at http://www.ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/building-from-source/linux.html.    As you'll see there, there are Fedora 20 and 21 instructions, but it looks like you are the first to try Fedora 22, and nobody has tried Fedora 23.

No doubt it will be some nasty little difference with one of the packages.    CryptoPP is repeatedly problematic, as are jsoncpp and jsonrpccpp.

All I can suggest is that you try to get the latest versions of them all, and build from source, and see how that goes for you.    Needing specific versions is entirely possible too.

We don't have a Fedora environment.    Our primary focus is Ubuntu, and we're relying on the community to fill in where people prefer other distros.

Do you think you could dig around a bit more and try to see if you can get it working?   If so, it would be great to get those instructions updated to reflect your learning in the process!   Best wishes.

**Comment by tflux99** [comment]
thx for replying @bobsummerwill i try i will give my best to get it running hehe i already digged deep into it spent already a few hours of getting it to work first of all those cmake .. errors now on make hmm i will update it if i find the solution :)

**Comment by bobsummerwill** [comment]
Thanks for trying!

Desktop Linux distro fragmentation, combined with the complexity of C++ builds in general makes trying to support everything a real time-sink.     I hope that you can work through it, or at least identify some fellow-Fedorans :-)     You could try asking for help on StackExchange's Ethereum area too.

Somebody obviously put the effort into getting Fedora 20 and 21 working, so maybe that individual can help?   Good luck!

**Comment by tflux99** [comment]
hmm after another few hours i installed CryptoPP, jsoncpp and jsonrpccpp from source latest versions from github and removed them from my packet manager the old ones that came with the distro or third party repos...! it configures with the new libs (cmake ..) but the error is the same with (make) even with the latest packets i tryed also the expected versions of all these packs but always the same error iam tired now i will see tomorrow sorry 4 bad english...

**Comment by tflux99** [comment]
where can i find some cmake cofigure commands to disable gui and stuff like that ..?? can someone pont me there i couldnt find anything usefull 4 me big thx :)

**Comment by bobsummerwill** [comment]
Thanks for chasing, @tflux99!

Most of the CMake setup is in https://github.com/ethereum/webthree-helpers/tree/develop/cmake, though for some packages it does `find_package()` on them, and then includes CMake fragments from within the package itself.    LLVM does that, for example, and other may.    Boost dependencies appear to have built-in CMake support.    But yeah, that is your starting directory.

Best wishes!

**Comment by bobsummerwill** [comment]
Oh - this might help too ...
https://github.com/ethereum/webthree-umbrella/wiki/Linux--Generic-Building

Wiki Linux build instructions which were moved to http://ethdocs.org, but simplified in the process, because the extra info isn't useful to most people, and we're still working out exactly what these shell scripts do, and whether they are useful or do.   They may help you, though.

So maybe something like this to build only eth?

```
scripts/ethbuild.sh --no-git --cores $(nproc) --project eth
```

**Comment by tflux99** [comment]
ok i think i got around the error i installed gcc version 4.9 with my distri came version 5.3 that fixes the CryptoPP errors 4 me simply install gcc4.9 from src than in build dir of webthree-umbrella type
`export CXX=/home/app/gcc49/bin/g++`
`export CC=/home/app/gcc49/bin/gcc`

where /home/app/gcc49/bin is my install template of gcc49 dont remove your standart gcc 5.3 from original fedora repos... do not install gcc4.9 systemwide hehe

so but now i come to 18 % than compile crushes with gcc49 but it gives me a lot of livm and libllvm errors i think i have to install libllvm3.7 on my system is llvm 3.8 from the rawhide repo so not the stablest one i try now to install llvm3.7 the required one from src somehow

**Comment by bobsummerwill** [comment]
Glad to see your progress.

If you disable EVMJIT (the Just In Time compiler) then you won't need the LLVM dependency.   That might save you quite a bit of hassle.

I believe that is just -DEVMJIT=off, but the syntax might vary a little from that.

**Comment by tflux99** [comment]
hehe i finaly made it issue can be closed
[root@ns3511722 build20]# make
[  0%] Built target cpp-ethereum_BuildInfo.h
[  2%] Built target scrypt
[  2%] Built target secp256k1
[  2%] Built target dev_BuildInfo.h
[  6%] Built target devcore
[  8%] Built target devcrypto
[ 11%] Built target p2p
[ 12%] Built target rlp
[ 13%] Built target bench
[ 18%] Built target testweb3core
[ 18%] Built target ethereum_BuildInfo.h
[ 24%] Built target evmjit
[ 26%] Built target ethcore
[ 26%] Built target evmcore
[ 29%] Built target evmasm
[ 30%] Built target lll
[ 32%] Built target evm
[ 40%] Built target ethereum
[ 41%] Built target ethash
[ 42%] Built target ethash-cl
[ 44%] Built target ethashseal
[ 45%] Built target natspec
[ 46%] Built target testutils
[ 46%] Built target ethkey
[ 46%] Built target minerphonehome.jsonstub
[ 46%] Built target minerfarm.jsonstub
[ 46%] Built target ethminer
[ 46%] Built target ethvm
[ 46%] Built target lllc
[ 53%] Built target testeth
[ 53%] Built target webthree_BuildInfo.h
[ 55%] Built target whisper
[ 56%] Built target webthree
[ 56%] Built target solidity_BuildInfo.h
[ 64%] Built target solidity
[ 64%] Built target admin_eth.jsonstub
[ 64%] Built target bzz.jsonstub
[ 64%] Built target admin_utils.jsonstub
[ 64%] Built target personal.jsonstub
[ 64%] Built target admin_net.jsonstub
[ 64%] Built target db.jsonstub
[ 64%] Built target eth.jsonstub
[ 64%] Built target whisper.jsonstub
[ 64%] Built target net.jsonstub
[ 64%] Built target web3.jsonstub
[ 68%] Built target web3jsonrpc
[ 70%] Built target jsengine
[ 71%] Built target jsconsole
[ 71%] Built target eth
[ 72%] Built target testweb3
[ 73%] Built target ethrpctest
[ 74%] Built target solc
[ 74%] Built target soljson
[ 78%] Built target soltest
[ 78%] Built target alethzero_BuildInfo.h
[ 80%] Automatic moc and uic for target aleth
[ 80%] Built target aleth_automoc
[ 83%] Built target aleth
[ 83%] Automatic moc, uic and rcc for target alethone
[ 83%] Built target alethone_automoc
[ 84%] Built target alethone
[ 84%] Automatic moc and uic for target alethzero
[ 84%] Built target alethzero_automoc
[ 92%] Built target alethzero
[ 92%] Automatic moc and uic for target mix
[ 92%] Built target mix_automoc
[ 92%] Built target mix_BuildInfo.h
[100%] Built target mix
[root@ns3511722 build20]#

ok the deal is to install qtwebengine 5.7.0 from github and you have to install CryptoPP, libjson-rpc-cpp and llvm3.7 newest from src you have to compile everything with gcc4.9 your fedora distri comes with cc5.3 wich doesnt compile the webthree-umbrella! and you have to symlinking the jsonrpcstub simply enter jsonrpcstub and see if its responding if there comes can not find file you have to symlinking it i had to.... hope i didnt forget something all i can say its a pain in the ass to compile it with fredora 22 i took me all about 3 days to figure out what all has to be done and a lot of research but finaly it compiles very well newest version on fedora 22 with everything nothing leftout or disabled iam happy now :)

**Comment by bobsummerwill** [comment]
Fantastic, @tflux99!

Before we lose that gold-dust information from the horse's mouth, I would really love for us to capture than in our documentation.

If you fork-and-clone https://github.com/ethereum/homestead-guide onto your machine, you can add that detail to https://github.com/ethereum/homestead-guide/blob/master/source/ethereum-clients/cpp-ethereum/building-from-source/linux.rst, and then create a PR, and I will review and merge.    The markup is really easy to understand.

Please could you do that?    And I'll add you to the contributor list for the docs too.

Good persistence!

**Comment by tflux99** [comment]
ok i have written a few lines of code to the linux install from src file i hope i didnt forget anything important first time that i made such things pull request something new for me hehe :)

**Comment by 3esmit** [comment]
I managed to build from source easily in fedora 23 32bit using webthree-helpers.

I used this guides 
https://github.com/ethereum/webthree-umbrella/wiki/Linux--Generic-Building
https://github.com/ethereum/webthree-umbrella/wiki/Building-on-Fedora

**Comment by 3esmit** [comment]
For what I remember this are the steps for fedora 23:

Install dependencies:

```
sudo dnf install llvm llvm-devel cmake boost boost-devel jsoncpp jsoncpp-devel leveldb leveldb-devel cryptopp cryptopp-devel miniupnpc miniupnpc-devel curl curl-devel argtable argtable-devel doxygen libmicrohttpd libmicrohttpd-devel gmp gmp-devel mesa-libOpenCL-devel
wget https://raw.githubusercontent.com/philsquared/Catch/master/single_include/catch.hpp
sudo cp catch.hpp /usr/include/
```

Compile e install dependency (not avaliable on DNF repository)

```
 git clone git://github.com/cinemast/libjson-rpc-cpp.git
 cd libjson-rpc-cpp/
 mkdir build
 cd build/
 cmake .. && make
 sudo make install
 sudo ldconfig
```

Compile webthree

```
git clone --recursive https://github.com/ethereum/webthree-umbrella
cd webthree-umbrella
git checkout release
git submodule update
webthree-helpers/scripts/ethupdate.sh --no-push --simple-pull --project all
webthree-helpers/scripts/ethbuild.sh --no-git --cores $(nproc) --project all
```

*for 32bits use  `webthree-helpers/scripts/ethbuild.sh --no-git --cores $(nproc) --project all -DEVMJIT=OFF` instead of the ethbuild above.

**Comment by tflux99** [comment]
for me this didnt work i found it also b4 but there was some missing stuff for me... so i figured it out installed it setted up some new symlinks and now it compiles :)

**Comment by 3esmit** [comment]
@bobsummerwill I did on F23 32-bit. I will do today in F23 64-bit, but I believe it would be pretty simple, just as was in F23 32-bit. I will follow the wiki guide (not mine guide). 
I will try this about 11 PM (GMT-3). Let me know if there is need of specific details build process, I will fully describe it here to contribute fixing build instructions for Fedora.
I will do your suggestion to pull request the guide.

**Comment by bobsummerwill** [comment]
Thanks, @3esmit!

Please do work through that process on Fedora, and contribute a PR to the homestead-guide, as we've just done for Fedora 22.

Those Wiki links you posted were used to create the http://ethdocs.org guides, and I will be deleting their content soon.    I deliberately did not include the ethbuilds.sh details because I don't want to encourage people NOT to use the webthree-umbrella (and because we are about to reorg the repos so that we won't need to "compose them" that way anymore).

@gcolvin reports, though, that for 32-bit Linux builds he was ONLY able to get some stuff working with those scripts.    There is some value still there, but I can't quite quantify what or why.    We need to dig some more.

If you are able, @3esmit, to build using just cmake/make directly and still get it to work, that would be cool.

**Comment by 3esmit** [comment]
@bobsummerwill I was not able to build using cmake on 32bit, the missing library was the qtwebengine that I see its now described how to install in Fedora. Maybe I can retry it someday. 

So if you're are only including build instructions using cmake I will try to make that...

**Comment by bobsummerwill** [comment]
Sure - same applies for 64-bit too.     If you can try to build NOT using those scripts, that would be the most helpful information and approach.   Thanks :-)

**Comment by 3esmit** [comment]
Ok, I will try first without this scripts. Sadly I am not able to do it today, but tomorrow I will, as I need to do it anyway ;)

**Comment by bobsummerwill** [comment]
Thanks!   There is no rush.

**Comment by bobsummerwill** [comment]
Just going to close this issue, because we have Fedora 22 working + docs now.

Feel free to keep comment here, @3esmit, or to create a new Fedora 23 issue if you like?

**Comment by bobsummerwill** [comment]
Hey @3esmit and @tflux99!

I have been working on an infrastructure-as-code alternative to these tedious per-distro sets of instructions, which will "go live" when we switch back to cpp-ethereum.

You can see my work-in-progress on that here:
- https://github.com/bobsummerwill/cpp-ethereum/blob/merge_repos/.travis.yml
- https://github.com/bobsummerwill/cpp-ethereum/blob/merge_repos/install_deps.sh

Now for the TravisCI bit, we're stuck with just Ubuntu Trusty automation for the time being, but we might well be able to expand that via Docker in the future.

Whatever the case, I would like to expand this install_deps.sh pattern pattern to cover more distros, so that our ethdocs.org instructions for the distros which we have bothered to do that can be simplified to, with the steps being executed directly and committed in with the code itself.
- git clone --recursive
- ./install_deps.sh
- cmake
- make

So maybe for Fedora we can take that approach instead, rather than bothering with written instructions?

Please could help me out and copy https://github.com/bobsummerwill/cpp-ethereum/blob/merge_repos/install_deps.sh locally and run it, does it go into the right conditional?

I suspect that it won't work, and that we will need to do something different for Fedora detection.  Thanks!

**Comment by bobsummerwill** [comment]
Moved to https://github.com/ethereum/webthree-umbrella/issues/631 and re-closed this one.
