### ISSUE TITLE
Update boost on Windows to 1.61

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#374]
We are currently using an old version of boost on Windows (which isn't problematic in itself).

What is problematic, though, is that our binaries were built without boost_atomic enabled.   That was somehow OK with CMake 3.4, but is problematic for CMake 3.5, which automatically adds indirect dependencies.   atomic is an indirect dependency of thread, and we don't have a LIB for it.

See https://github.com/ethereum/cpp-dependencies/pull/2 and https://github.com/ethereum/webthree-umbrella/issues/249.

**Comment by chfast** [comment]
In 1.60 Boost.Test has changed command line interface:
http://www.boost.org/doc/libs/1_60_0/libs/test/doc/html/boost_test/change_log.html

**Comment by bobsummerwill** [comment]
Oh yuck.

So we're already on boost-1.60.0 on OS X, and I imagine that some Linux distros will already have updated.

Where do you see a failure because of this?    Do we need to update batch files / shell scripts / docs?

**Comment by chfast** [comment]
The change is about command line interface for `testeth`. Our options must be provided after `--` mark.
Before: `testeth --vm jit -t VMTests`.
After: `testeth -t VMTests -- --vm jit`.
So we will need to update some Jenkins configs.

**Comment by bobsummerwill** [comment]
Right - do you have access?   Can you login OK?

**Comment by chfast** [comment]
I will get boost 1.61 straight away.

**Comment by chfast** [comment]
Done for Visual Studio 2015.
