### ISSUE TITLE
CM - Add TravisCI support for the project

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#378]
TravisCI is free for open-source projects.

https://travis-ci.org/
It would be good for us to have a second means of automating our builds, which is not dependent on our own physical machines.

This is low priority, but would be a useful step if we want to start working towards https://wiki.debian.org/ReproducibleBuilds/About for eth.

**Comment by chriseth** [comment]
I think we considered it once but they either did not have support for c++ at all or our compilation times were too long.

**Comment by bobsummerwill** [comment]
OK ... well I might have a poke around on some rainy day.

I don't think it would have the turnaround we would need for continuous builds, but it would be good to have a backup, or to use it for slow and thorough testing, etc.

**Comment by chfast** [comment]
We should consider [CircleCI](https://circleci.com) as an alternative. The main advantage to TravisCI is that CircleCI provides Ubuntu 14.04 containers.

**Comment by bobsummerwill** [comment]
Right ... thanks for that alternative option, @chfast :-)

**Comment by bobsummerwill** [comment]
DONE!
