### ISSUE TITLE
Fix utcTime() function

### ISSUE THREAD

**Issue by ghost** [ethereum/webthree-umbrella#38]
Moved here from [cpp-ethereum](https://github.com/ethereum/cpp-ethereum/issues/2936)

This PR is for implementing a `utcTime()` function that does not just use time(0) to return the current UTC timestamp. The reasoning behind this is that according to the [documentation](http://www.cplusplus.com/reference/ctime/time/) 

> The value returned generally represents the number of seconds since 00:00 hours, Jan 1, 1970 UTC (i.e., the current unix timestamp). Although libraries may use a different representation of time: Portable programs should not use the value returned by this function directly, but always rely on calls to other elements of the standard library to translate them to portable types (such as localtime, gmtime or difftime).

the `time(0)` function is not guaranteed to return a UTC timestamp, even though in most implementations, as we have seen, it will. Only way to do that seems to be to combine it with gmtime() as we do in this PR.

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ethereum/cpp-ethereum/2936)

**Comment by debris** [comment]
@LefterisJP can we close this?

**Comment by LefterisJP** [comment]
yes
