### ISSUE TITLE
block Corrupted or i dont know what is happend

### ISSUE THREAD

**Issue by xfarhan** [ethereum/webthree-umbrella#382]
sorry cant able to copy from Aleth one so i have uploaded the screenshot

this is happened because electricity failure the similier problem was caused me this before 2 days now this happened again i need to download whole lot of blocks again ?

http://i65.tinypic.com/j157au.png

**Comment by bobsummerwill** [comment]
Which windows version are you using please, @xfarhan?
And this is from the 1.22 installer?   Or built from source?

**Comment by xfarhan** [comment]
its 1.22 installer and win 7

**Comment by chriseth** [comment]
It might have been caused by an invalid state in the db during power failure. Sorry, but I think you have to re-sync your blockchain. If you have problems with power more often, please consider making backups of the blockchain data while the node is not running.
Closing for now.
