### ISSUE TITLE
segfault while syncing eth

### ISSUE THREAD

**Issue by winsvega** [ethereum/webthree-umbrella#383]
One of the pointers in sessions array is null. that might be the problem
https://github.com/ethereum/libethereum/blob/develop/libethereum/EthereumHost.cpp#L193

sessions[0].first = null
sessions[0].second = null

[![Screenshot from 2016-03-18 20:06:21.png](https://files.gitter.im/ethereum/cpp-internal/VKFy/thumb/Screenshot-from-2016-03-18-20_06_21.png)](https://files.gitter.im/ethereum/cpp-internal/VKFy/Screenshot-from-2016-03-18-20_06_21.png)

**Comment by bobsummerwill** [comment]
Old.   I assume we'll never do anything with this.
