### ISSUE TITLE
How to skip over integrated graphics?

### ISSUE THREAD

**Issue by bumski** [ethereum/webthree-umbrella#385]
My AlethOne will not detect my GPU.  I have the same problem with other miners, but am able to use the --opencl-platform 1 command to work around it.  Is there a similar way to do this with AlethOne?

To be clear I upgraded to an R9 390 with 8MB video ram.

Is there a .config file or something I could edit to include that command?  When I try to boot it up in cmd prompt with that command it says meaningless prefix.

**Comment by bobsummerwill** [comment]
I don't believe there is, no, @bumski.

AlethZero and AlethOne are being killed soon anyway, so if you have this issue you are probably best focusing on command-line mining, probably with Genoil, because we won't be fixing it.   Good luck!
