### ISSUE TITLE
Building for El Capitan

### ISSUE THREAD

**Issue by flaviocordova** [ethereum/webthree-umbrella#388]
Since there are no binaries for OS X El Capitan yet, is there any cookbook-like documentation of how to build a stable release locally and start mining ?

If not, is there any expected date to have the binaries available ?

**Comment by bobsummerwill** [comment]
Hey @flaviocordova,

All the instructions are here - http://www.ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/index.html#installing-and-building

Your quickest route is to use Homebrew - http://www.ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/installing-binaries/osx-homebrew.html

"Soon" :-) - https://github.com/ethereum/webthree-umbrella/issues/307
