### ISSUE TITLE
OS X - Homebrew install results in (pre Homestead) eth-1.2.0 install.  Eeek!

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#389]
Something in our Homebrew / Jenkins setup is hooped, such that:

```
brew update
brew upgrade
brew install cpp-ethereum
```

Is resulting in an `eth-1.2.0` (released 20 days ago).     I need to dig in and understand why.

We also still have an incorrect version showing (1.0rc2 for months), which is not good, but probably not part of this particular issue.   That is tracked by https://github.com/ethereum/webthree-umbrella/issues/279

See https://github.com/ethereum/homebrew-ethereum/issues/61, logged by @b1uebox.

**Comment by debris** [comment]
> Is resulting in an `eth-1.2.0` (released 20 days ago). I need to dig in and understand why.

`LICENSE` and `README.md` (afaik, they are required by hombrew) files were removed from homebrew directory, but they are still used by [prepare_receipt.sh](https://github.com/ethereum/webthree-helpers/blob/45f01ff5c72eec558d77a85bb7e01f24e837bac1/homebrew/prepare_receipt.sh#L27)

**Comment by bobsummerwill** [comment]
Thanks, @debris.
See https://github.com/ethereum/webthree-helpers/pull/110 for a quick fix.

Looks like the root cause here is just our failure to update some version strings, though, but thanks for the Homebrew heads-up!

**Comment by bobsummerwill** [comment]
This is a partial fix, @chriseth ... https://github.com/ethereum/webthree-umbrella/pull/391.

Looks like the version-strings was a slight red-herring, and the root cause was more related to branches and sub-modules.    It also appear that Homebrew has "flushed" since the original report anyway.

**Comment by bobsummerwill** [comment]
@blackknightsatelitte reports ...

Yes i used your source code en installed it. After i opened it it srill shows 1.1.4. Openend my macbook terminal en updraded through : brew install brew upgrade brew install ccp-ethereum. Things started updating after that. I opened up Aleth Zero again and still shows 1.1.4. I'm currently downloading the 1.3.5 Geth node again. But i'll predict it's not gonna work for me. I'm new to using the mac terminal hopefully i won't be making a big of a mess. Thanks again and sorry about the newbee questions ...

**Comment by bobsummerwill** [comment]
Hey @blackknightsatelitte!  Please you try the ...

```
brew update
brew upgrade
brew reinstall cpp-ethereum
```

Dance again?   I believe that we have cleared the blockage, but I would love to see that the resolution has reached all the way to you.   Best wishes!

**Comment by bobsummerwill** [comment]
I think we're done.   We can reopen if that proves to be a premature assessment.
