### ISSUE TITLE
CUDA mining support

### ISSUE THREAD

**Issue by ghost** [ethereum/webthree-umbrella#39]
Moved here from [cpp-ethereum](https://github.com/ethereum/cpp-ethereum/issues/2925)

I know you guys are busy reorganizing the whole repo, but after you've completed that work, it shouldn't be too difficult to merge this in.

Some work is still needed on copying the right DLLs into the release folder etc. Also untested on Linux.

**Comment by bobsummerwill** [comment]
Dupe.
