### ISSUE TITLE
windows 10 - Release build of alethzero from source does not execute

### ISSUE THREAD

**Issue by bruciebruce** [ethereum/webthree-umbrella#394]
Hi!

I cloned the repo from last week.  I would have thought this would have compiled and run.  Here is the error I get when I invoke:

Qt: Untested Windows version 10.0 detected!
  i  06:18:10.850|main  Web developers: Debugger on 127.0.0.1: 21993
eth Network protocol version: 63
Client database version: 12041
QtWebEngineProcess not found at location C:/devel/ethereum/webthree-umbrella/build/alethzero/alethzero/Release/bin\QtWebEngineProcess.exe. Trying fallback path...
QObject::connect: No such signal dev::aleth::Aleth::knownAddressesChanged(AccountNamer_)
QObject::connect:  (receiver name: 'Main')
QObject::connect: No such signal dev::aleth::Aleth::addressNamesChanged(AccountNamer_)
QObject::connect:  (receiver name: 'Main')
Failed to set up Chromium debug tools. Get Qt-5.5.

Okay,  So I did download and install qt-5.5 (I would have thought the dependencies would have been hardwired in the build process), but same error.

Hints anyone?  I would like to use visual studio (community edition 2013) (I am not really a windows developer) to step through the source and examine this code.  Thanks!

**Comment by bruciebruce** [comment]
I get this same error when I download, install and invoke the compiled version that I found here:
https://build.ethdev.com/cpp-binaries-data/release-1.2.2/Ethereum.exe

I have the same qt*.dll files that I see in this built version that I see in my release build directory.
(?)

**Comment by bobsummerwill** [comment]
Hey @bruciebruce!

So @yann300 is working on a Qt 5.5 update for Windows right now.

Windows 10 support in Qt 5.4 was pretty primitive.     They've also just released (a couple of weeks ago) a Qt 5.6 LTS version which finally has official Windows 10 support.    We're starting work on supporting Qt 5.6 as well.    OS X got forced to Qt 5.6 already, because it uses the Homebrew rolling release manager which moved the Qt version underneath us and broke the build there :-)

Coming soon!

**Comment by bobsummerwill** [comment]
FYI ... Window 7, Windows 8 and Windows 8.1 don't suffer this issue.    It's unique to Windows 10, afaik.

**Comment by bruciebruce** [comment]
Thanks for the _prompt_ update!  Should I attempt to put in the 5.6 dll's?

**Comment by bobsummerwill** [comment]
You can if you like!

See also https://github.com/ethereum/mix/issues/244, where @taoteh1221 is working through (presumably) the same issue but for Mix.    You guys can have a race :-)

**Comment by bruciebruce** [comment]
Have to get back to my 'regular' job.  Maybe later.  Thanks again.

**Comment by taoteh1221** [comment]
@bobsummerwill I'm still held up by my regular job as well, but still have that in my scheduler along with reviewing the homestead docs. :smile:

**Comment by bobsummerwill** [comment]
@taoteh1221 @bruciebruce No worries.   Will keep you guys in the loop on our Qt 5.5 work.

**Comment by bruciebruce** [comment]
Hi again,

Okay, so Installed ubuntu 14.04 in vBox, updated build dependencies found on the website, cloned the git as before, did a cmake and launched the executable:

----------- start of screen shot ----------------

root@bruce-VirtualBox:/devel/ethereum/webthree-umbrella/build/alethzero/alethzero# ./alethzero 
  ℹ  11:47:09.223|alethzero  Web developers: Debugger on 127.0.0.1: 15867
pci id for fd 16: 80ee:beef, driver (null)
libGL error: core dri or dri2 extension not found
libGL error: failed to load driver: vboxvideo
⧎ ℹ  11:48:09 AM.572|alethzero  Id: ##1d8d432d…
...  11:48:09 AM.711|alethzero  Opened blockchain DB. Latest: #d4e56740… (rebuild not needed)
...  11:48:09 AM.729|alethzero  Opened state DB.
 ⚡   11:48:17 AM.179|alethzero  void dev::eth::Client::init(dev::p2p::Host_, const string&, dev::WithExisting, dev::u256) 7467 ms
  ◇  11:48:17 AM.180|alethzero  Setting author @00e95f56…
eth Network protocol version: 63
Client database version: 12041
  ◇  11:48:25 AM.856|alethzero  newBlock watch ID: 0
  ◇  11:48:25 AM.856|alethzero  Initialising plugin: Mining
  ◇  11:48:25 AM.856|alethzero  Initialising plugin: NewAccount
  ◇  11:48:25 AM.856|alethzero  Initialising plugin: AllAccounts
  ◇  11:48:25 AM.856|alethzero  Initialising plugin: ImportKey
  ◇  11:48:25 AM.856|alethzero  Initialising plugin: BrainWallet
  ◇  11:48:25 AM.856|alethzero  Initialising plugin: Browser
  ◇  11:48:27 AM.480|alethzero  Initialising plugin: Cors
  ◇  11:48:27 AM.480|alethzero  Initialising plugin: JsConsole
  ◇  11:48:27 AM.559|alethzero  Initialising plugin: OurAccounts
  ◇  11:48:27 AM.560|alethzero  Initialising plugin: OtherAccounts
  ◇  11:48:27 AM.560|alethzero  Initialising plugin: EVMJIT
  ◇  11:48:27 AM.560|alethzero  Initialising plugin: WhisperPeers
Failed to set up Chromium debug tools. Get Qt-5.5.
  ◇  11:48:27 AM.563|alethzero  Initialising plugin: ExportState
  ◇  11:48:27 AM.564|alethzero  Initialising plugin: GasPricing
  ◇  11:48:27 AM.564|alethzero  Initialising plugin: InjectTransactions
  ◇  11:48:27 AM.564|alethzero  Initialising plugin: Transact
  ◇  11:48:27 AM.568|alethzero  Initialising plugin: SpecialBlockChain
  ◇  11:48:27 AM.568|alethzero  Initialising plugin: BlockList
  ◇  11:48:27 AM.591|alethzero  Initialising plugin: NameRegNamer
  ◇  11:48:27 AM.591|alethzero  Initialising plugin: PrivateChain
  ◇  11:48:27 AM.592|alethzero  Initialising plugin: Whisper
  ◇  11:48:27 AM.600|alethzero  Initialising plugin: LogPanel
QObject::connect: No such signal dev::aleth::Aleth::knownAddressesChanged(AccountNamer_)
QObject::connect:  (receiver name: 'Main')
QObject::connect: No such signal dev::aleth::Aleth::addressNamesChanged(AccountNamer*)
QObject::connect:  (receiver name: 'Main')
QXcbWindow: Unhandled client message: "_COMPIZ_TOOLKIT_ACTION"
  ◇  11:57:18 AM.849|alethzero  !!! Main: uninstalling watch 1
  ◇  11:57:18 AM.849|alethzero  !!! Main: uninstalling watch 2
 ⚡   11:57:19 AM.513|alethzero  Stop worker 648 ms

----------- end of screen shot ---------------------

Same error as before, different OS.  Hints on how to proceed here?

As usual....MUCHAS GRACIAS!!

-Bruce

**Comment by bruciebruce** [comment]
Sorry, meant to say ubuntu 14.04

**Comment by bobsummerwill** [comment]
Hey @bruciebruce!   What Qt version for your Ubuntu build, please?   Were you seeing this against Qt 5.5 on Ubuntu?

**Comment by bruciebruce** [comment]
Hi Bob,

I have not installed any Qt's on this Ubuntu instance that I know of.  Let me investigate this and get back.

Thanks again,
Bruce

**Comment by bobsummerwill** [comment]
Did you work from these instructions?

http://www.ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/building-from-source/linux.html#installing-dependencies-for-ubuntu

**Comment by bruciebruce** [comment]
Bob,

Yes, I did.  This was done on a virgin ubuntu 14.04 iso.

-Bruce

**Comment by bobsummerwill** [comment]
AlethZero is being discontinued, so this will never be addressed.   Sorry!

https://blog.ethereum.org/2016/07/08/c-dev-update-summer-edition/
