### ISSUE TITLE
Windows 7 64bit - installer just quits unexpectedly on extract: qt5gui.dll

### ISSUE THREAD

**Issue by logicalup** [ethereum/webthree-umbrella#395]
Windows 7 64bit - installer just quits unexpectedly on extract: qt5gui.dll
version 1.2.2
Tried running normally and as admin. Tried unchecking CLI in the install options. Didn't help. No error messages.

**Comment by bobsummerwill** [comment]
Hmm.   Thanks for highlight this.

Please could you try the previous release too?   Do you see the exact same issue with that too?   Thanks!

https://build.ethereum.org/cpp-binaries-data/release-1.2.1/Ethereum.exe

**Comment by logicalup** [comment]
Tried it, first time it got a bit further to qt5network.dll and quit on that. All times after that quit on qt5gui.dll just like the 1.2.2 version. So I think the same behavior as 1.2.2. Here's a screenshot on what it pauses for few seconds on then just quits without any messages/errors.
![capture](https://cloud.githubusercontent.com/assets/8228441/14057096/c0d6a294-f2bb-11e5-9c00-fc84a1998e96.PNG)

**Comment by bobsummerwill** [comment]
Thanks for the details, @DevJackSmith.
This is all pretty horrible, isn't it?

We have **just** the `eth` command-line tool available in a Windows zip at https://builds.ethereum.org/cpp-binaries-data/release-1.2.2/win_eth.zip if that is of any use to you?     Both AlethZero and AlethOne are on the road to death.    Mix will be hanging around.

Have you tried rebooting?   I wonder whether there are some nasty file-locks or similar happening?

**Comment by bobsummerwill** [comment]
Note to self:   Read https://wiki.qt.io/Building_Qt_Installers

**Comment by logicalup** [comment]
Thank you. I tried rebooting, didn't help. I wanted to use gui to mine Ether. I'll take a look at the eth. Thanks again.

**Comment by bobsummerwill** [comment]
Right ... but yeah, the "One Click Miner", AlethOne, is being removed, so yeah, command-line `ethminer` is probably best anyway.    We'll need to get to the bottom of this issue for Mix, though.

Here is the Windows mining guide which is linked from http://reddit.com/r/ethermining ... https://medium.com/@timothyjcoulter/mining-ethereum-on-windows-55f3f4f2217c#.n9z1ne3yx.

As well as that sub-reddit, you can find answers in ethereum.stackexchange.com/?tags=mining.

Good luck.   And we'll see what we can do about this installer issue!

**Comment by bobsummerwill** [comment]
AlethOne and other GUI apps have been retired now.
