### ISSUE TITLE
alethone crash ubuntu 14.04

### ISSUE THREAD

**Issue by SentinalBais** [ethereum/webthree-umbrella#400]
I downloaded the blockchain using ethereum cpp from windows 10. I exported the blockchain and imported it in ubuntu 14.04. 

I attempted to start Alethone from the terminal however it crashes with a segmentation fault. I tried re-installing and the same issue occurs 

It complains about a missing key and there is a segmentation fault.

**Comment by bobsummerwill** [comment]
Hey, @SentinalBais,

I am unsure whether the blockchain export is supported across OSes.

How exactly did you do it?  Thanks!

**Comment by SentinalBais** [comment]
Hi its not crashing now...

I think it's because i manually copied the directory from windows 10

When i did the import i forgot to clean up the ethereum folder, because i thought uninstalling ethereum would do this. The second time i did the import i cleaned the directory first, then the import took much longer (initially i copied the folder across ) 

However when I was opening alethone on ubuntu it asked for a new passphrase, I was expecting it would request the phase phrase used in my windows 10 account. _So i am a bit confused now, does import, recover the wallets and the blockchain?_

Also I noticed that when I opened it it was syncing to the network, from block zero so it seems the import failed... Maybe you are right import is not supported across OS's.

https://github.com/ethereum/go-ethereum/wiki/Backup-&-restore

> Accounts are stored in the keystore subdirectory. The contents of this directories should be transportable between nodes, platforms, implementations (C++, Go, Python).
> ( it's probably just referring to the key store directory )

**Comment by SentinalBais** [comment]
I think we can close this issue 

user error, with a fresh install it doesn't crash

**Comment by bobsummerwill** [comment]
Thanks for the update.

You will notice that the Wiki page you linked to is from the go-ethereum (geth) client.

I don't know if their blockchain backup is OS-agnostic, but I can tell you that the actual blockchain data is stored in different ways between eth, geth, etc, and that is not transferable.    The network protocol is obviously identical between clients, but the implementations are completely independent, including the databases they use, etc.

This note ...

```
Accounts are stored in the keystore subdirectory. The contents of this directories should be
transportable between nodes, platforms, implementations (C++, Go, Python).
```

...  is only talking specifically about the keystore subdirectory used for accounts.   That is the most golden directory of all, which definitely needs consistent backup.    The data directories between the two clients are in different locations, though, so to transport your accounts from one client to anyone, you probably need to manually copy those files.

Sorry for the confusion.   Glad you are functional :-)
