### ISSUE TITLE
Move lll, llc and evmasm from libethereum to solidity repo

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#402]
[ X ] Move modules
[ ] Install and packaging scripts might look at different paths if they want to find lllc.

Work is in progress on this ...

https://github.com/ethereum/libethereum/pull/214
https://github.com/ethereum/webthree-helpers/pull/113
https://github.com/ethereum/solidity/pull/448
https://github.com/ethereum/solidity/pull/441
https://github.com/ethereum/alethzero/pull/153

**Comment by chriseth** [comment]
ppa files do not need changes, it seems dpkg-buildpackage just performs `make install` and then uses `/usr/local/bin/lllc`.

**Comment by bobsummerwill** [comment]
Just looking through webthree-helpers, I _think_ that OS X and Windows are OK too.
We can look at what comes out of the overnight builds, if they succeed!

**Comment by bobsummerwill** [comment]
Still need to double-check on solc, etc. in our final 1.2.3 binaries tomorrow, @chriseth

**Comment by chriseth** [comment]
confirmed working on windows

**Comment by ghost** [comment]
this resolves some issues with using the Intel compiler platform. @bobsummerwill 
Please minimize libethereum and libweb3core for easier porting.
Thanks!

**Comment by bobsummerwill** [comment]
Sorry, @mancoast.   Did you add this comment in the wrong place?

**Comment by winsvega** [comment]
so, this issue is done ?

**Comment by bobsummerwill** [comment]
I think we're just waiting on confirmation that the `solc` is still coming through in our binaries after the changes.   That is not confirmed yet for Ubuntu because of https://github.com/ethereum/webthree-umbrella/issues/432.

Looks like Homebrew includes a `solc` on OS X, and I am just checking that now.    The Windows installer only appears to include the GUI apps, so I guess we have no delivery mechanism for `solc` binaries on Windows?

Alos, @chriseth, we need to update http://solidity.readthedocs.org/en/latest/installing-solidity.html, maybe just to point to http://www.ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/installing-binaries/index.html and http://www.ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/building-from-source/index.html, and ensuring those instructions are adequate for `solc`.

**Comment by chriseth** [comment]
@bobsummerwill I don't see why we need to update the install instructions with this task. There still is no solidity package. Please check osx for lllc so we can close this.

**Comment by bobsummerwill** [comment]
Just confirmed working on OS X.    Was stuck being Qt5.6 update and other WIP.
