### ISSUE TITLE
Installation blocked by antivirus

### ISSUE THREAD

**Issue by oneala** [ethereum/webthree-umbrella#405]
Hello,

I am not able to install it, my bitdefender is showing that trojans was found in the software.

any advice?

thanks!

**Comment by 3esmit** [comment]
Where you downloaded the file? What is the version?

**Comment by chriseth** [comment]
"Antivirus" software often take bitcoin mining or perhaps even cryptographic signing routines as trojans because they also occur there. If you got the binary from `https://builds.ethereum.org/cpp-binaries-data/` then you should be safe. Can you disable the "antivirus" software?

**Comment by oneala** [comment]
I just uninstalled it :) thanks!
