### ISSUE TITLE
Cut-and-paste evmcore constants into Solidity

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#410]
- [ ] copy all files from evmcore to the solidity repo
- [ ] modify webthree-helpers UseSolidity.cmake to not pull in evmcore

See http://doublethinkco.github.io/cpp-ethereum-cross/images/dependency_graph.svg for our current dependencies in develop right now.

The lll, lllc and libevmasm moves have improved things a lot, but we still have a solidity -> libethereum dependency which we need to sever.

As we have already discussed and decided, the resolution will be to cut-and-paste gas cost constants and other "stuff" which Solidity needs across into the Solidity repo, to sever this dependency.

We need to do that right now, prior to the 1.3.0 release.

That will still leave us with a dependency from soltest to ethereum, but that is workable, and we can look to eliminate that at a later stage.

**Comment by chriseth** [comment]
Note that we _still_ have header-dependencies across the repositories.

**Comment by bobsummerwill** [comment]
What are those?   Do you have an enumerated list?   devcore ones?
We will have CMake cleanup to do for sure, but C++ dependencies are a concern.

**Comment by chriseth** [comment]
Oh that's actually much better than I thought. We mostly need libdevcore, and need to remove some references to libethcore:

```
⚡ git grep '#include' | cut -d : -f 2- |egrep -v 'libsolidity|libdevcore|boost|libevmcore|libevmasm' | sort -u
#include <algorithm>
#include <array>
#include "Assembly.h"
#include "AssemblyItem.h"
#include "CodeFragment.h"
#include "CommandLineInterface.h"
#include "Compiler.h"
#include "CompilerState.h"
#include <cstddef>
#include <ctype.h>
#include_directories(BEFORE ${JSONCPP_INCLUDE_DIRS})
#include_directories(${Boost_INCLUDE_DIRS})
#include <ethereum/BuildInfo.h>
#include "ethereum/BuildInfo.h"
#include "Exceptions.h"
#include <fstream>
#include <functional>
#include "GasEstimator.h"
#include "GasMeter.h"
#include <iostream>
#include <json/json.h>
#include "KnownState.h"
#include <libethcore/ABI.h>
#include <libethcore/ChainOperationParams.h>
#include <libethcore/SealEngine.h>
#include <libethereum/ChainParams.h>
#include <libethereum/Executive.h>
#include <libethereum/State.h>
#include <liblll/Compiler.h>
#include <limits>
#include <list>
#include <map>
#include <memory>
#include <numeric>
#include <ostream>
#include "Parser.h"
#include "PathGasMeter.h"
#include <set>
#include <solidity/BuildInfo.h>
#include "solidity/BuildInfo.h"
#include <sstream>
#include <stack>
#include <string>
#include "../TestHelper.h"
#include "TestHelper.h"
#include <test/TestHelper.h>
#include <tuple>
#include <utility>
#include <vector>
```

And from devcore we need:

```
⚡ git grep '#include' | cut -d : -f 2- |egrep 'libdevcore' | sort -u#include <libdevcore/Assertions.h>
#include <libdevcore/CommonData.h>
#include <libdevcore/Common.h>
#include <libdevcore/CommonIO.h>
#include <libdevcore/Exceptions.h>
#include <libdevcore/FixedHash.h>
#include <libdevcore/Hash.h>
#include <libdevcore/Log.h>
#include <libdevcore/SHA3.h>
#include <libdevcore/UndefMacros.h>
```

**Comment by winsvega** [comment]
libevmasm in solidity depends on Eth::ethcore

lllc requires 3 functions 
../liblll/liblll.so: error: undefined reference to 'dev::eth::c_instructions'
../liblll/liblll.so: error: undefined reference to 'dev::eth::instructionInfo(dev::eth::Instruction)'
/home/wins/Ethereum/umbrella/solidity/lllc/main.cpp:105: error: undefined reference to 'dev::eth::disassemble(std::vector<unsigned char, std::allocator<unsigned char> > const&)'

I guess it is not a couple of constants from libevmcore
