### ISSUE TITLE
Linux - Retire Ubuntu 14.10 (Utopic) and Vivid (15.04)

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#411]
These are end-of-line non-LTS versions, and it doesn't make sense for us to expend any effort on them any more.

[ ] Stop PPA automation for these versions
[ ] Remove "building from source" instructions for these versions, and add INFO saying that we don't support these versions anymore.

**Comment by 5chdn** [comment]
for later reference: https://wiki.ubuntu.com/Releases

**Comment by bobsummerwill** [comment]
Won't fix.
