### ISSUE TITLE
Ethereum MIX client on Windows 7 64bits crashes

### ISSUE THREAD

**Issue by Jacck** [ethereum/webthree-umbrella#417]
I just trying to use the latest (Ethereum Homestead) Ethereum MIX client on Windows 7 64bits (Windows installation). AlethOne works fine, but MIX and AlethZero crashes when open. I have already successfully tested some other tools: Meteor client with javascript web3 API and basic one: Ethereum Wallet. Any idea?

**Comment by 3esmit** [comment]
Use Mist and Geth. The software you mentioned is outdate.

**Comment by bobsummerwill** [comment]
Do you have any more information you could share on the nature of the crash, @Jacck?

Did you just use the Installer?   For 1.22.0?

**Comment by Jacck** [comment]
Hi, I have downloaded Homestead ready 1.2.2 version (but I have already used Ethereum Frontier geth on my laptop). Mix is crashing and when I call Visual Studio debugger the message is:
Unhandled win32 exception at 0x000000006F07F5BF (aticfx64.dll) in Mix.exe: 0xC0000005: Access violation reading location 0x0000000000000144.If there is a handler for this exception, the program may be safely continued.

**Comment by bobsummerwill** [comment]
Yikes.

I would guess that aticfx64.dll is an ATI/AMD specific driver.     Maybe have a look for newer (or older) drivers?    I've sen various threads on mining forums talking about needing specific driver versions for reliable results.

**Comment by bobsummerwill** [comment]
This won't be fixed, because Mix is not being supported anymore.
See https://blog.ethereum.org/2016/07/08/c-dev-update-summer-edition/ for information on the mix -> remix plans.
