### ISSUE TITLE
mix2 research

### ISSUE THREAD

**Issue by chriseth** [ethereum/webthree-umbrella#419]
This is a research task to answer some questions that should allow us to get a more solid start with the web-debugger.
Questions to be answered (add answers here):
- What will be the name of the repository? 
- How do we distribute the program?
  - npm package, github repository (+ Travis to create github pages).
  - in Mist (step 1: just navigate to the github page, step 2: make it a "real" dapp)
  - as a standalone electron app (low priority, more important once we get more of the mix functionality)
- Is meteor+react suitable for our needs?
  using only react is ok, we can use npm to retrieve external libraries we need.
- Can we integrate the debugger in the "electron dev tools"?
    "Electron dev tools" 's a basic integration of the chromium dev panel. So it has directly nothing to do with Contract debugging. But we can imagine developing such an extension that could display the web3 context. We could use a special "debugging" interface of mist so that when you open the dev tools, you can see a list of all transactions initiated by this dapp and clicking on one transaction lets you step through it.

**Comment by yann300** [comment]
- how non meteor project could reference the debugger?
  if we don't use meteor, this is ok

**Comment by yann300** [comment]
some links:
https://react-in-meteor.readthedocs.org/en/latest/
https://www.meteor.com/tutorials/react/creating-an-app
https://themeteorchef.com/recipes/writing-a-package/
