### ISSUE TITLE
Blockchain tests refactoring

### ISSUE THREAD

**Issue by ghost** [ethereum/webthree-umbrella#42]
Moved here from [cpp-ethereum](https://github.com/ethereum/cpp-ethereum/issues/2868)

based on blockchain test PR https://github.com/ethereum/cpp-ethereum/pull/2850
this one introduce new approach on blockchain tests
and separetes testing and mining logic

**Comment by winsvega** [comment]
PR here 
https://github.com/ethereum/libethereum/pull/8
