### ISSUE TITLE
Fix seal engines

### ISSUE THREAD

**Issue by chriseth** [ethereum/webthree-umbrella#420]
We use static variable initializers in the macro `ETH_REGISTER_SEAL_ENGINE` to create and register different seal engines with the seal engine registrar. This approach is fundamentally flawed when used across multiple libraries (as we apparently do because the noproof and ethash seal engines reside in different libraries) because the linker may remove unused symbols at will.

Possible solution:
We can live with a fixed set of seal engines, so the registrar can look for the engines itself, as opposed to the seal engines reporting to the registrar.

If this is fixed, we should be able to re-enable the  tests in Blockchain.cpp and BlockChainInsert.cpp in windows

If this is implemented, then the following bug can be closed: https://github.com/ethereum/webthree-umbrella/issues/256

**Comment by bobsummerwill** [comment]
Where is this existing registration code, @chriseth?

**Comment by winsvega** [comment]
https://github.com/ethereum/libethereum/blob/develop/libethcore/SealEngine.h

**Comment by bobsummerwill** [comment]
Oh dear.   This kind of C++ really makes sad.

So we are using a macro to declare a static factory variable, and the initialization of that static variable by calling a static function which itself uses a singleton and does a dynamic memory allocation.

And this working at all is dependent on linker behavior which may vary by platform.    Certain platforms will strip unused global or static variables, even if they do have side-effects.

And why do any of this.   Is a one-line to register each seal really such a hardship.
