### ISSUE TITLE
Mining but not solving shares

### ISSUE THREAD

**Issue by TheDeafMute** [ethereum/webthree-umbrella#422]
I've tried on 2 pools and neither picks up my 4.5MH/s r7 360 rig - It never finds a share. Ever. Hours, while all 5 of my 20+MH rigs do. Whats wrong here...

**Comment by bobsummerwill** [comment]
Have you tried the Genoil ethminer?   If not, you probably should.   It's had a lot more love that the official ethminer.   We hope to upstream their changes back, but for right now they have a better miner.

http://github.com/Genoil/cpp-ethereum

**Comment by TheDeafMute** [comment]
I havent, mostly because building fails for me on linux and I don't even know where to begin building on win :( I only know python which is Realtime scripting lang not compiled.. so bad at compiling lol

Ended up returning gpu now have 2 other gpus on it and it works with 33mh..

**Comment by TheDeafMute** [comment]
I only know python not cpp xD

**Comment by bobsummerwill** [comment]
OK - so you're up-and-running?   I'll close the issue then.   Thanks!
Please reopen or open a new issue if you hit any other problems.   Happy mining.

**Comment by TheDeafMute** [comment]
Hi - Just started occurring again - with the 2GPUs. They were showing only 23MH already within a week. Does hashrate go down over time or does difficulty go up and hashrate stays the same, or both?

It's the same PC running win7- will try genoil version..
