### ISSUE TITLE
BlockQueue hang forever at stop function

### ISSUE THREAD

**Issue by winsvega** [ethereum/webthree-umbrella#43]
There is a strange bug with BlockQueue which is hard to reproduce. 
I got this one when importing over hundred of blocks into blockchain. 
It happens ~ 1/10000 blocks imported into chain.

The debugger wont follow into the thread. Trace lead to function BlockQueue::stop
https://github.com/ethereum/libethereum/blob/develop/libethereum/BlockQueue.cpp#L72
verifier threads never join and thus application hang for unlimited time.

Verifier thread code apparently located at https://github.com/ethereum/libethereum/blob/develop/libethereum/BlockQueue.cpp#L97

**Comment by winsvega** [comment]
More info: 
-it happens in destructor of empty BlockQueue

**Comment by winsvega** [comment]
debugtrace http://pastie.org/10481338
http://pastie.org/10481513

**Comment by winsvega** [comment]
code to reproduce

```
BOOST_AUTO_TEST_CASE(BlockQueueDestructor)
{
    size_t i = 5000;
    while(i > 0)
    {
        i--;
        TestBlock genesisBlock = TestBlockChain::defaultGenesisBlock();
        TestBlockChain blockchain(genesisBlock);
        BlockQueue blockQueue;
        BlockChain& bc = blockchain.interfaceUnsafe();
        blockQueue.setChain(bc);
        bc.sync(blockQueue, genesisBlock.state().db(), (unsigned)4);
        cout << "test blockQueue destructor: " << 5000 - i << std::endl;
    }
}
```

**Comment by winsvega** [comment]
http://en.cppreference.com/w/cpp/thread/condition_variable

**Comment by chriseth** [comment]
Probably fixed.

**Comment by winsvega** [comment]
it is not
