### ISSUE TITLE
MSCR120.dll missing

### ISSUE THREAD

**Issue by nerdralph** [ethereum/webthree-umbrella#430]
installed cpp-ethereum-v1.2.3.exe
Running ethminer gives MSCR120.dll missing error.
ddl should be included in installer.
Work-around is to download and install vc-redist from MS.
https://www.microsoft.com/en-us/download/details.aspx?id=40784

**Comment by bobsummerwill** [comment]
Hey @nerdralph,   Thanks for the note!
This is a known issue, already tracked by https://github.com/ethereum/webthree-umbrella/issues/387.
Sorry it "bit" you!
