### ISSUE TITLE
ubuntu ppa still 1.2.2

### ISSUE THREAD

**Issue by nerdralph** [ethereum/webthree-umbrella#432]
ran apt-get upgrade cpp-ethereum about 5 minutes ago.  Some dependencies got upgraded, but ethminer -V still reports 1.2.2.  Looks like the 1.2.3 build still didn't get pushed to the ppa?

**Comment by bobsummerwill** [comment]
Thanks for the report, @nerdralph!

I believe that @chriseth was looking at the PPAs yesterday.   Maybe he didn't finish that work before the weekend?

We are still learning about the PPA setup, which was implemented by people who are no longer working for the Ethereum Foundation - https://github.com/ethereum/webthree-umbrella/issues/275 - so we're not entirely on top of things, there, I'm afraid.    OS X is in a better state.   We're working on improving our Windows setup too.

Sorry for the disruption.   We'll have new binaries up soon, I'm sure.

**Comment by chriseth** [comment]
We are having some issues. We had a build failure on the PPA and now launchpad somehow does not pick up our uploads anymore (yes, I incremented the sub version number).

**Comment by chriseth** [comment]
Should be fixed now (xenial still pending but tracked in different issue).
