### ISSUE TITLE
in China - GETH connection problems

### ISSUE THREAD

**Issue by rawsushi** [ethereum/webthree-umbrella#434]
WinOs 10 most recent version of GETH 1.3.6

I've posted a bunch of VERBOSITY 6 --fast --nat=none posts to GIST ... here's one https://gist.github.com/rawsushi/7588a40eb5efe5d96ff1891b710fbecc

I'm letting it run ... but it continues to fail . . . 

VPN is fine - I've tested and can access every site

**Comment by bobsummerwill** [comment]
Hello again @rawsushi!

Geth issues need to be logged in http://github.com/ethereum/go-ethereum/issues, I'm afraid.   Please could you just log a new issue there?  Thanks!

webthree-umbrella is for eth.   Completely different codebase.
