### ISSUE TITLE
Anyone the error "double free or corruption (fasttop)" has been occured??

### ISSUE THREAD

**Issue by freeyssu** [ethereum/webthree-umbrella#438]
Hello.

I have succeed building from source in RHEL 6 environment.

But, If i execute "ethminer", the ""Ddouble free or corruption (fasttop)"" message occur.

Please refer below information.

**\* glibc detected **\* ./ethminer: double free or corruption (fasttop): 0x0000000000942250 ***
======= Backtrace: =========
/lib64/libc.so.6[0x3a9a676166]
/lib64/libc.so.6(__cxa_finalize+0x9d)[0x3a9a6361bd]
/tmp/webthree-umbrella/build/libweb3core/libp2p/libp2p.so(+0x2e6de6)[0x7f8e1a81cde6]

anyone, does have any idea to this issue??

**Comment by bobsummerwill** [comment]
Thanks for the report, @vero-ssoo.

Is that as much of a stack as you can get by running the app under gdb?

**Comment by bobsummerwill** [comment]
This issue was moved to ethereum/cpp-ethereum#3146
