### ISSUE TITLE
CI: Move "managed scripts" to webthree-helpers

### ISSUE THREAD

**Issue by chriseth** [ethereum/webthree-umbrella#439]
NOTE - [ethdocs.org content on our current setup](http://www.ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/automation.html), including links to some of these.

All "managed scripts" should be moved from jenkins into webthree-helpers. We already did that for the ppa-build and it seems to work. Some scripts already exist as a copy in webthree-helpers, but they are not always identical.
The managed scripts can be found here: http://52.28.164.97/configfiles/
- [x] move build scripts to webthree-helpers
- [x] move emscript build script (currently as non-managed script as part of the emscripten job) to webthree-helpers
- [x] change jenkins jobs to just run them using `curl | /bin/sh` (does that work on all platforms?)
- [ ] there is still some jenkins script in all -pr jobs that manages the crossrepo-prs.
- [x] ethbinaries-build still has a managed script for homebrew
- [x] project-build still has managed script
- [x] code-coverage-run still has managed script

**Comment by chriseth** [comment]
_Moved to description_.

**Comment by chfast** [comment]
I removed "update" and "build" scripts (have a backup). The versions in webthree-helpers look newer.

**Comment by chfast** [comment]
@chriseth Do you need [solidity-emscripten Dockerfile](http://52.28.164.97/configfiles/editConfig?id=org.jenkinsci.plugins.managedscripts.ScriptConfig1442008433392)?

**Comment by chfast** [comment]
`project-build` is clean.

**Comment by chriseth** [comment]
emscripten dockerfile is unused and outdated, delete it

**Comment by chfast** [comment]
`ethbinaries-build` has some weird packaging for Windows, one step depends on Powershell and packs some system libraries.

Can that be simplified to remove this step and relay on "Archive the artifacts" later on?

There are also some warning and errors in the configuration.

I would like someone with bigger Jenkins/Windows experience to check that out.

**Comment by chriseth** [comment]
@chfast I think the "archive" step is run on master, so we cannot use powershell.

**Comment by chriseth** [comment]
I think we moved as much as we could. Closing as done.
