### ISSUE TITLE
Memory usage (Windows) way too high

### ISSUE THREAD

**Issue by ghost** [ethereum/webthree-umbrella#44]
Moved here from [cpp-ethereum](https://github.com/ethereum/cpp-ethereum/issues/2860)

eth.exe/altethzero.exe memory usage is about 1.4GB private bytes (+160M working set) after sync.
Even Bitcoin Core is not that memory hungry.
ethminer.exe is eating 90MB+ private and 1.1GB+ in working set

**Comment by bobsummerwill** [comment]
Won't fix - old.
