### ISSUE TITLE
Analyze and maybe eliminate devcore dependencies in solidity

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#440]
These are the remaining devcore dependencies in solidity:

```
#include <libdevcore/Assertions.h>
#include <libdevcore/Common.h>
#include <libdevcore/CommonData.h>
#include <libdevcore/CommonIO.h>
#include <libdevcore/CommonJS.h>
#include <libdevcore/Exceptions.h>
#include <libdevcore/Hash.h>
#include <libdevcore/FixedHash.h>
#include <libdevcore/Log.h>
#include <libdevcore/SHA3.h>
#include <libdevcore/UndefMacros.h>
```

Not sure what kind of surface area each of these has, or what subset of that is used within Solidity, but I don't imagine it would a huge effort to replicate this subset within the solidity namespace.

Connects to https://github.com/ethereum/webthree-umbrella/issues/453

**Comment by chriseth** [comment]
Are you sure MemoryDB is part of the dependencies?

**Comment by bobsummerwill** [comment]
Looks like that one was in-error.   Removed.

**Comment by bobsummerwill** [comment]
So I've done as much as can on this as part of https://github.com/bobsummerwill/solidity/tree/solidity_standalone/libdevcore.

Other tasks cover the rest of the TODOs, but my "chopping" has brought the surface area down to just that needed.

**Comment by chfast** [comment]
Have you checked which one is a header only dependency?

**Comment by bobsummerwill** [comment]
Yes, @chfast, where there are still CPPs in https://github.com/bobsummerwill/solidity/tree/solidity_standalone/libdevcore, it is because they have linkage.
