### ISSUE TITLE
Windows - Support Visual Studio 2015

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#443]
We should support CMake generating Visual Studio 2015 solutions.     That is what we should be encouraging people to use.

The Visual Studio 2015 Community Edition is free of cost, and supports multiple target platforms.

**Comment by chfast** [comment]
CMake 3.5 generates correct Visual Studio 2015 solution. Is it all this issue is about?

**Comment by bobsummerwill** [comment]
No - it's all the other stuff around that which would be required to make it work.

ie. hardcoded references to VS 2013 in build files.   Prebuilt libraries, etc.

End-to-end testing, essentially.    And preferably switching our automation too.

**Comment by bobsummerwill** [comment]
Oh wow - I didn't know you could have multiple assignees.    That is cool!

**Comment by chfast** [comment]
New feature. However waffle does not support it yet.

**Comment by chfast** [comment]
VS 2015 Update 3 just released.

**Comment by bobsummerwill** [comment]
Still only an RC, I think, right?
https://www.visualstudio.com/news/releasenotes/vs2015-update3-vs

See also https://twitter.com/BobSummerwill/status/740783388353826816.    I aim to commit those VS2013 "move binaries to Github" changes tomorrow, and then to do the VS2015 switch.

**Comment by bobsummerwill** [comment]
Another future target ... [Windows Server 2016 Nano](https://technet.microsoft.com/en-us/library/dn765472.aspx?f=255&MSPPError=-2147217396).

**Comment by bobsummerwill** [comment]
OK ... So I just had an attempt at switching over to VS2015 within our existing Jenkins setup, but I think it needs to wait until we do the repo reorg and switch to TravisCI and Appveyor.

See https://github.com/ethereum/webthree-helpers/pull/198.

The issue is that element in the Jenkins which adds and removes a symlink for extdep, to work around the fact that the Jenkins setup is constantly switching between different workspaces.    We haven't got that crutch for "deps", so it looks this the VS2015 LIB binaries have got deleted at some stage.    I don't think it is worth the effort to add such a hack back in for VS2015.

So let's just switch to VS2015 and drop VS2013 at the same time as the repo reorg,

**Comment by bobsummerwill** [comment]
So we have got support.    It's just a matter of switching the automation.    There is no more specific work here, and the automation for Travis and Appveyor will be captured elsewhere.
