### ISSUE TITLE
Refactor the seal engine registration NOT to rely on macros and side-effects

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#447]
See https://github.com/ethereum/webthree-umbrella/issues/420#issuecomment-206981560

And also see cpp-ethereum gitter channel on 7th April 2016

**Comment by chriseth** [comment]
@bobsummerwill aren't we already doing this?

**Comment by bobsummerwill** [comment]
Yes, it's a dupe now.   It wasn't at the time.
