### ISSUE TITLE
Windows - evmjit.dll is missing from the cpp-ethereum-1.2.3 ZIP

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#450]
As reported by @alwaysninja, the Windows ZIP for the cpp-ethereum-1.2.3 release is missing the `evmjit.dll` binary.    Only that single file is missing.

Compare and contrast the contents of the following:
- https://builds.ethereum.org/cpp-binaries-data/release-1.2.2/win_eth.zip
- https://builds.ethereum.org/cpp-binaries-data/release-1.2.3/win_eth.zip

CC @frozeman, @chriseth.

**Comment by bobsummerwill** [comment]
Was it this run, @chriseth?
http://52.28.164.97/job/ethbinaries-release/44/
And we've lost the logs now (presumably they are culled off after a while to save disk space?)

**Comment by chriseth** [comment]
High priority because it is needed for our next release that should happen in the next days.

**Comment by bobsummerwill** [comment]
Yes - and it's a very odd one, isn't it?

I wonder if it's related to the ConfigInfo.h oddness I am fighting through on cpp-ethereum dry-run?
