### ISSUE TITLE
Getting Below error on running sudo apt-get install mix

### ISSUE THREAD

**Issue by haldhar** [ethereum/webthree-umbrella#452]
The following packages have unmet dependencies:
 mix : Depends: libethereum-gui (= 1.2.3-SNAPSHOT-251-20160408-f9ae28a~trusty-0ubuntu1) but 1.2.3-SNAPSHOT-255-20160411-f5dc3f1~trusty-0ubuntu1 is to be installed
       Depends: eth (= 1.2.3-SNAPSHOT-251-20160408-f9ae28a~trusty-0ubuntu1) but 1.2.3-SNAPSHOT-255-20160411-f5dc3f1~trusty-0ubuntu1 is to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by bobsummerwill** [comment]
It's "mix-ide" now, @haldhar.

Do we have docs which need updating, @chriseth?    Nobody every did any work on docs for Mix in http://ethdocs.org.
