### ISSUE TITLE
Dry run for repository reorganization

### ISSUE THREAD

**Issue by chriseth** [ethereum/webthree-umbrella#453]
See work-in-progress branches at:
- https://github.com/bobsummerwill/cpp-ethereum/tree/merge_repos
- https://github.com/bobsummerwill/solidity/tree/standalone_prior_to_splat

Sub-tasks:
- [x] Create work branch at https://github.com/bobsummerwill/cpp-ethereum/tree/merge_repos
- [x] Manual copy of latest content from the various repos back on top of cpp-ethereum
- [x] Iterate through edits required to CMake files to get things building, ignoring ConfigInfo.h files
- [x] Work through BuildInfo.h and ConfigInfo.h generation process, and get that working
- [x] Commit various edits "upstream" based on this learning
- [x] Learn what all the pre-processor symbols are and comment them in webthree-helpers
- [x] Eliminate ETH_TRUE pre-processor symbol
- [x] Lots of iteration on "root" CMake files.   These will need to be manually maintained.
- [x] Start working on running tests (lots is still broken)
- [x] Create shell script to rsync content from webthree-umbrella
  - That is https://github.com/ethereum/webthree-umbrella/blob/develop/recreate-cpp-ethereum.sh
- [x] Add ifdefs in original locations for edits needed in dry-run, so they can be committed in original locations.
- [x] Create ~~Jenkins~~ TravisCI/Appveyor projects for building these dry-runs.
- [ ] Get all the tests working to the same degree
- [ ] Create shell script to mirror commits from webthree-umbrella
- [ ] Code reviews of CONTENT CHANGES
  - [ ] cpp-ethereum PR is https://github.com/ethereum/cpp-ethereum/pull/3008
  - [ ] Solidity PR is https://github.com/ethereum/solidity/pull/525

The end-goal of all of this is to:
- [x] Have all necessary edits committed in the original repos (inside conditionals)
- [x] Have scripts which create the correct content without respecting history (for testing)
- [x] Have branches for the dry-run which have that content
- [x] Have ~~Jenkins~~ TravisCI/Appveyor targets which build-and-test those branches
- [ ] Have script which does the same as the "messy script", but with version history, which is what we will actually use.

**Comment by bobsummerwill** [comment]
Good progress on this today, re-enabling the BuildInfo.h and ConfigInfo.h generation.    `eth` runs now and seems to be working OK, and `testeth` is running with lots of tests failing.

See https://github.com/bobsummerwill/cpp-ethereum/tree/merge_repos

**Comment by chriseth** [comment]
Did you make further progress? If you, please document it and close this issue for this sprint.

**Comment by bobsummerwill** [comment]
No - got sidelined with other tasks, but might get a little more done today.
Yes, this can be closed, and another issue created for next sprint to continue the dry-run.

**Comment by chriseth** [comment]
If you think the estimation is still valid, let's just keep the task and take it into the next sprint again.

**Comment by bobsummerwill** [comment]
OK - will do!

**Comment by bobsummerwill** [comment]
Work remaining is captured as https://github.com/ethereum/webthree-umbrella/issues/477.

**Comment by bobsummerwill** [comment]
How to preserve history?
- http://stackoverflow.com/questions/17371150/moving-git-repository-content-to-another-repository-preserving-history
- http://blog.neutrino.es/2012/git-copy-a-file-or-directory-from-another-repository-preserving-history/

**Comment by bobsummerwill** [comment]
done
