### ISSUE TITLE
Add automation for El Capitan, including generation of binaries

### ISSUE THREAD

**Issue by chriseth** [ethereum/webthree-umbrella#454]
- [x] Upgrade Operating System (ended up using @bobsummerwill's Apple account)
- [x] Install the latest xcode
- [x] Update/upgrade Homebrew (including length Qt5 build-from-source)
- [x] Install rbenv and then Ruby 1.x (had to troubleshoot and learn about this issue)
- [x] Manual PATH setup in Jenkins (had to troubleshoot and learn about this issue)
- [x] Add new build node for El Capitan into Jenkins, and add into `project-build` and `project-test`
- [x] Add appropriate parameterization to Homebrew generation and call from Jenkins
  - [x] But we have a bug in the ZIP copying, so it's got "dangling pointers" to the bottles
  - [x] And Yosemite missing bottles too?   See https://github.com/ethereum/homebrew-ethereum/issues/69
- [x] Add appropriate parameterization to DMG generation and call from Jenkins
- [x] Test the new binaries
- [x] Hmm.   Looks like we have lost `eth_standalone_osx.zip` somewhere along the line.
- [x] Still working on incorrect Qt DLLs inside the Windows ZIP.

**Comment by bobsummerwill** [comment]
The El Capitan build machine is now up-and-running within the Jenkins `project-build` and `project-test` projects.

All that now remains is the packaging element, ie. `ethbinaries-build`, which will need parameterization in various places in Jenkins, scripts, Homebrew, etc.

**Comment by chriseth** [comment]
Task is not done. Reopening.

**Comment by bobsummerwill** [comment]
Smaller scope of work remaining is captured in new task - https://github.com/ethereum/webthree-umbrella/issues/478.

**Comment by bobsummerwill** [comment]
See https://github.com/ethereum/webthree-helpers/pull/173.

**Comment by bobsummerwill** [comment]
El Capitan bottle ZIPs aren't being copied correctly.   Brew formulas are being posted, but they reference ZIPs which aren't being copied to the network drive properly.

The Jenkins battle continues.

**Comment by bobsummerwill** [comment]
Hello, @Arachnid!    Welcome to hell.

**Comment by bobsummerwill** [comment]
ALL DONE - finally :-)
