### ISSUE TITLE
OS X - URGENT - Fix broken Homebrew build pipeline

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#458]
It looks like something is missing on the new OS X build machine.
Just the wrong version of Ruby, even?
The Homebrew for `eth` hasn't updated for a week.

**Comment by bobsummerwill** [comment]
OK ... so I am a little bit stumped on the Homebrew breaks, @chriseth.

The issue is that Yosemite comes with Ruby 2.0, and we need to be using Ruby 1.8.7 or Ruby 1.93.    I tried to do that on that machine, but I think I've managed to do that only for "administrator", so "JenkinsWorker" is still using the wrong version, and so breaking.    I tried to log into that machine via VNC using the details you gave me, but cannot log in.    Maybe because that worker user doesn't have elevated rights?      I was following http://blog.zerosharp.com/installing-ruby-with-homebrew-and-rbenv-on-mac-os-x-mountain-lion/ and got the administrator account showing 1.9.3 for `ruby -v`.    I copied the .profile file to the JenkinsWorker account too, but maybe it's still got "administrator" as an owner?    And maybe still needs "rnenv global" running it on, to flip over to the right Ruby, and then the Jenkins restarting.

I think this is going to be way easier to resolve on the machine itself in person.    Please could you take a look tomorrow?   Thanks!

**Comment by chriseth** [comment]
Will take a look.

**Comment by bobsummerwill** [comment]
Thanks!

**Comment by chriseth** [comment]
Actually read the description again. If this is about the remote macos machine and not the one in our office, then we both have exactly the same level and means of access.

**Comment by bobsummerwill** [comment]
Oh right ... so the new Yosemite machine is **not** in your office?    But the old one is?

OK - I will pick this one up again, then.    Any idea why trying to VNC in using the JenkinsWorker account might not be working?

**Comment by chriseth** [comment]
if the second account creates problems, only use a single account for everything

**Comment by bobsummerwill** [comment]
Finally fixed!
- Installing Ruby 1.9.3 on machine, with rbenv.
- Manually updating the PATH for that machine in Jenkins, to add the rbenv shims
- Updating the shebang in the locdep.rb script
- Adding an explicit call to the ruby interpreter in the ethbinaries.sh script
- And then finally doing a `gem install ftools`

**Comment by bobsummerwill** [comment]
Still broken!

**Comment by bobsummerwill** [comment]
Fixed by @chriseth by copying the certificates across.

Aside - where is the actual line which does the **git push** to the homebrew repo?   I still haven't found that.
