### ISSUE TITLE
We should have a setup.sh script

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#460]
We should have a **setup.sh** script which implements the per-platform "pre-requisites" from http://www.ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/building-from-source/index.html#building-from-source, ie. installs all the appropriate packages, etc.

To get any given machine to the point where it can be used to git clone and build.

Maybe that is actually a Chef recipe?   Or maybe it is a shell script.    But we should have **THAT THING**.

Having individuals typing in command-lines from a website is just stupid.

**Comment by chfast** [comment]
I don't think it is good idea. Those scripts are very hard to maintain. We have troubles having wiki up do date.

**Comment by bobsummerwill** [comment]
Well ... the key is to make the instructions executable, and then they become the documentation.

And we use them ourselves on our own machines, and we use them within the automation too.

I'm having to maintain all of this stuff at http://www.ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/building-from-source/index.html#building-from-source anyway.   I'm just spotting that it is a bit silly that maintenance is of text files describing command-line operations to type in, where they could literally be scripts for everybody to run.

So "How to install pre-requisites" becomes "run setup.sh".

**Comment by bobsummerwill** [comment]
Done
