### ISSUE TITLE
ethvm segfault

### ISSUE THREAD

**Issue by gcolvin** [ethereum/webthree-umbrella#463]
Every example I tried failed, but this is the one I debugged

> ethvm --gas-limit 100000000 --gas 10000000 output loop.bin

The loop.bin, loop.evm, and loop.sol firles are here:

> https://github.com/gcolvin/libethereum/tree/develop/times

The stack trace for the segfault is

> (gdb) bt
> # 0  0x00007ffff681d4b9 in std::string::assign(std::string const&) ()
> 
>    from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
> # 1  0x00007ffff74600d1 in dev::eth::ChainOperationParams::operator= (this=0x60)
> 
> ```
> at /home/gcolvin/webthree-umbrella/libethereum/libethcore/ChainOperationParams.h:51
> ```
> # 2  0x00007ffff750b519 in dev::eth::SealEngineFace::setChainParams (this=0x0,
> 
> ```
> _params=...)
> at /home/gcolvin/webthree-umbrella/libethereum/libethcore/SealEngine.h:76
> ```
> # 3  0x00007ffff750a281 in dev::eth::ChainParams::createSealEngine (
> 
> ```
> this=0x7fffffffdb50)
> at /home/gcolvin/webthree-umbrella/libethereum/libethereum/ChainParams.cpp:119
> ```
> # 4  0x0000000000444027 in main (argc=7, argv=0x7fffffffe598)
> 
> ```
> at /home/gcolvin/webthree-umbrella/libethereum/ethvm/main.cpp:197
> ```

Main.cpp:197 is

> unique_ptr<SealEngineFace> se(ChainParams(genesisInfo(networkName)).createSealEngine());

The real problem comes just a little earlier, because the attempt to create a _SealEngineFace_ returns a _nullptr_ because _m_sealEngines_ is empty.

> Breakpoint 2, dev::eth::ChainParams::createSealEngine (this=0x7fffffffdb50)
>     at /home/gcolvin/webthree-umbrella/libethereum/libethereum/ChainParams.cpp:118
> 118       SealEngineFace\* ret = SealEngineRegistrar::create(sealEngineName);
> (gdb) s
> dev::eth::SealEngineRegistrar::create (_name="Ethash")
>     at /home/gcolvin/webthree-umbrella/libethereum/libethcore/SealEngine.h:119
> 119       static SealEngineFace\* create(std::string const& _name) { if (!get()->m_sealEngines.count(_name)) return **nullptr**; return get()->**m_sealEngines[_name]()**; }
> (gdb) n
> dev::eth::ChainParams::createSealEngine (this=0x7fffffffdb50)
>     at /home/gcolvin/webthree-umbrella/libethereum/libethereum/ChainParams.cpp:119
> 119       ret->setChainParams(*this);
> (gdb) p ret
> $2 = (dev::eth::SealEngineFace *) 0x0

Things go south fast when the null pointer gets used.  It seems that _m_sealEngines_ is empty because _m_sealEngines[string]_ is assigned to only by _registerSealEngine()_, which is invoked only by _ETH_REGISTER_SEAL_ENGINE_, which appears in only three places.  Breakpoints in those three places are never hit.  In particular, _Ethash::init()_ at Ethash.cpp:36 is never hit, so the "Ethhash" seal is not registered.

> ~/webthree-umbrella/libethereum/libethashseal/Ethash.cpp:36:      ETH_REGISTER_SEAL_ENGINE(Ethash);
> ~/webthree-umbrella/libethereum/libethcore/SealEngine.cpp:32:     ETH_REGISTER_SEAL_ENGINE(NoProof);
> ~/webthree-umbrella/libethereum/libethcore/BasicAuthority.cpp:35:     ETH_REGISTER_SEAL_ENGINE(BasicAuthority);

By now I am deep into code I don't understand.  The only files I find that reference _Ehash::init()_ are MixClient.cpp, WebThree.cpp, eth/main.cpp, TestHelper.cpp, and MinerAux.h.  None of them appear to be part of the build for ethvm.

**Comment by bobsummerwill** [comment]
OK, so this will be a knock-on from those sealengine registration changes which were made to avoid those horrible macros and side-effects.

Explicit initializations for the relevant sealengines were added into appropriate places for our various applications, but seemingly NOT for ethvm.

You can just add them straight into the main(), or into some other place early on.

See https://github.com/ethereum/webthree/commit/89dcfc8d4d2bb969b0d7dbb9383df6e3e9ac32bd, for example.

What also must, must, must be fixed here is the code which is crashing, to be more defensive, to include some debug text, and not to CRASH!

**Comment by bobsummerwill** [comment]
See also https://github.com/ethereum/webthree-umbrella/issues/457.

**Comment by gcolvin** [comment]
Ditto.  Just fixed it.  Need to make a new fork to commit the change to before I can make the PR, but that would involve staying awake for longer than it will take to finish this sentence...

**Comment by gcolvin** [comment]
Fixing the 'crash on nullptr' is a bigger issue.  The code that returns the null is a hash table that can well be empty, so throwing would be wrong.  The problem is the caller, who could once expect that at least the default was registered, so doesn't check for the null and throw. (Which is not a good C++ idiom anyway.)  With the (broken) mechanism for automagic registration gone that expectation is less certain, so something should be thrown.  And every other call to this routine should be found and also checked.  But I want to close this one first so ethvm stops crashing.

**Comment by gcolvin** [comment]
Pulled.  Thanks @bobsummerwill
