### ISSUE TITLE
Why does our CMake run "not find" solidity?

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#465]
There appears to be a minor (harmless?) bug in our CMake process, which means that it searches for solidity headers and libs, but doesn't "find them".

As far as I can determine there are no negative consequences, but something isn't right and should be investigated at some point during the repo reorgs.

Minor issue.

**Comment by chriseth** [comment]
I have also seen that at some point. We should remove this "searching for solidity". Can you give a quote of the actual error in case it somehow disappears over time, so we can tell for sure this is fixed?

**Comment by bobsummerwill** [comment]
They just look like this:

```
-- LevelDB headers: /usr/local/include
-- LevelDB lib   : /usr/local/lib/libleveldb.dylib
-- solidity headers: 
-- solidity lib   : 
-- Found CryptoPP: /usr/local/include (found suitable version "5.6.3", minimum required is "5.6.2") 
-- CryptoPP headers: /usr/local/include
-- CryptoPP lib   : /usr/local/lib/libcryptopp.a
```
