### ISSUE TITLE
Experiment with prune-by-copy

### ISSUE THREAD

**Issue by chriseth** [ethereum/webthree-umbrella#467]
We could get a very crude pruned state database by traversing the state tree at `current  block - 1000` and inserting every node into a fresh database, then do the same with the rest of the blocks (obviously stopping the traversal at nodes that are already present).

**Comment by chriseth** [comment]
There are (unverified) reports that go-ethereum can do a state db copy in 60 seconds.

**Comment by bobsummerwill** [comment]
This issue was moved to ethereum/cpp-ethereum#3152
