### ISSUE TITLE
AlethOne withdraw not working

### ISSUE THREAD

**Issue by whatever-whatever** [ethereum/webthree-umbrella#471]
I am new to this and have recently got AlethOne up and mining. At the bottom left it went from 0 wei to 5 Ether. So, it seems that I have some Ether to play with now.

I have been trying to use the withdraw button to send the Ether to my wallet that I have from the official site (Ethereum-Wallet.app). I am on a Mac. Nothing happens when I try to send it. I am on the Geth Go node and the main network for my wallet.

I have been searching this site and the internet quite a bit. I would appreciate some help. I'm sure I missed something simple.

**Comment by chriseth** [comment]
First, please check whether you are actually mining on the correct chain. In order to do so, check the balance of the address you use in alethone using a blockchain explorer.

**Comment by bobsummerwill** [comment]
AlethOne is no longer supported or released, so closing this issue.
