### ISSUE TITLE
AlreadyHaveBlock sync exception on win64

### ISSUE THREAD

**Issue by winsvega** [ethereum/webthree-umbrella#472]
had an exception during syncing on win64 in release. 
no much of information now. need to reproduce. 
but this happened occasionally at around 1358000 block

https://files.gitter.im/ethereum/cpp-ethereum-development/Uq5Q/import-error.jpg

**Comment by bobsummerwill** [comment]
This issue was moved to ethereum/cpp-ethereum#3154
