### ISSUE TITLE
OS X - Do our Homebrew builds have EVMJIT off by default?

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#473]
See [cpp-ethereum.rb#L33](https://github.com/ethereum/homebrew-ethereum/blob/master/cpp-ethereum.rb#L33).

I suspect (but have not proven) that we might be building with EVMJIT Off by default.

Some of those other settings look out of date too.

**Comment by chfast** [comment]
CC

**Comment by chfast** [comment]
CC

**Comment by bobsummerwill** [comment]
I did a pass, and don't think this is the case.
