### ISSUE TITLE
Windows - Move our prebuilt binaries to Github

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#474]
So it is easier to maintain them.

Prototyped by Bob.    You just drop the ZIPs into releases, and then point there instead of our current network location:

See https://github.com/doublethinkco/webthree-helpers/commit/ce1614a9e6f6c3c60e3c7e2f74f6513beaf1caf5

That specific location isn't working anymore, but the principle is the same.

They should actually be added to `cpp-ethereum-dependencies` repo as releases.

We also need to find an alternative to BITSAdmin which works for GitHub (which maybe uses HTTPS instead of HTTP?).    The current batch file doesn't work as-is.     Doing a curl or wget shows the URLs are fine, but some different setting is maybe needed?

Or just use PowerShell.

**Comment by chfast** [comment]
Binaries: https://github.com/ethereum/cpp-dependencies/releases/tag/vc140
Script: https://github.com/ethereum/cpp-dependencies/blob/master/install_deps.cmake

**Comment by bobsummerwill** [comment]
How exactly are you invoking that CMake script, @chfast?
We could use a replacement for `getstuff.bat` which does the correct invocation.

**Comment by chfast** [comment]
Using cmake process script mode `-P`. https://cmake.org/cmake/help/latest/manual/cmake.1.html

```
cmake -P webthree-helpers/deps/install_deps.cmake
```

**Comment by chfast** [comment]
CMake scripts are better than .bat and others because cmake has built-in file downloading and tar.

**Comment by bobsummerwill** [comment]
Yes, indeed.   Anything is better than bash and batch!
