### ISSUE TITLE
Fix inconsistent module/executable name for webthree tests

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#476]
See https://github.com/ethereum/webthree/pull/146.

The tests for webthree are actually named TWICE, as ethrpctest and testweb3, which must have been merged together at some stage.

So there is both some ordering issue there, and just some inconsistency.

Minor issue which I spotted and have started working on.   Should finish it off sometime.

**Comment by chriseth** [comment]
So the executable that is actually called for testing is testweb3 (the script that calls it is `webthree-helpers/ethtest.sh`). "ethrpctest" seems to be a separate binary which is not a unit test but rather a commandline program that can be used to do some manual testing. We might remove that executable.

**Comment by bobsummerwill** [comment]
Right ... yeah - it is a little confusing.

Let me stick my head back in here again when I get a chance.

**Comment by bobsummerwill** [comment]
I'll just close this.    It's minor and not worth any more time.
