### ISSUE TITLE
alethzero crashes when you try importing json key made by geth

### ISSUE THREAD

**Issue by ghost** [ethereum/webthree-umbrella#48]
Moved here from [cpp-ethereum](https://github.com/ethereum/cpp-ethereum/issues/2782)

If trying to import on alethzero an UTC-xxxx json file made by geth, alethzero crashes.

Solved editing the UTC-xxx json file. Just lower case the C of the word: "Crypro", from "Crypto" to "crypto"

Can you fix?

**Comment by bobsummerwill** [comment]
Hey @corsaro1.   Closing as a dupe of #10.
