### ISSUE TITLE
Windows - Remove Windows Installer generation from our automation

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#484]
When we complete the repro switchover, we won't want a single installer anymore, and I would argue that we don't actually want a Windows installer at all.

Instead, we would have separate ZIPs for each of cpp-ethereum, AlethZero, Solidity and Mix.

**Comment by chriseth** [comment]
I think adding e.g. mix to the windows menu is a good feature we should keep.

**Comment by SystemOfSilence** [comment]
I like the idea of installers either unified or separate if the MS recommended directories are used (%appdata%,%programdata%,%programfiles%) for state storage.  If distribution is switched to archive files all default paths should keep the applications self-contained. Either is fine but mixing the strategies is confusing. I have symlinks all over trying to contain applications that were written to be OS agnostic (pointing at python) but decided to drop files in the current user's profile even though the application is a daemon by nature. Are you developing a first class windows application(Installer, roaming profile support, terminal server support, ...) or a first class application that happens to run on windows(Self-Contained)? I would prefer the self-contained archive distribution, let the end user do what they want  and throw in a simple script that modifies the path and creates the shortcuts for the start menu.

Note: I run eth as a service to contribute to the network, with all paths symlinked %programdata% currently and interact with it via "geth attach". This is probably a typical windows setup for those that don't want the node dependent on the interactive session.

**Comment by bobsummerwill** [comment]
Thanks for the feedback, @SilentSystem.

Yes, the current setup is indeed really rather inconsistent and non-idiomatic.

See also https://github.com/ethereum/webthree-umbrella/issues/489.

**Comment by bobsummerwill** [comment]
It's gone for now.

If we want to start doing Windows installers again, we'll need to create new issues to track that work.
