### ISSUE TITLE
Fix naming inconsistencies before our next round of releases

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#485]
If you look in https://builds.ethereum.org/cpp-binaries-data/release-1.2.4/ you will see that our output files are very messily named:
- Ethereum.dmg
- Ethereum.exe
- eth_standalone_osx.zip
- win_eth.zip

In https://github.com/ethereum/webthree-umbrella/issues/483 and https://github.com/ethereum/webthree-umbrella/issues/484, I have noted that I think we should get rid of the DMG and EXE and only have ZIPs.

So I think those should just be named simply, and including version numbers, something like so:
- AlethZero-windows-x64-v.1.2.4.zip
- Mix-osx-yosemite-v.1.0.3.zip
- cpp-ethereum-linux-x64-v.1.2.4.zip
- solidity-emscripten-v.0.3.2.zip

Or for the snapshots (on the assumption that we always only want to keep the latest)
- solidity-develop-windows-x64.zip

**Comment by chriseth** [comment]
I would say this can only be done after we have our independent release cycles.

**Comment by bobsummerwill** [comment]
Yes - that is correct, @chriseth, which I think is for our first releases AFTER we are decoupled, which I think we would do right after the repo-reorg.

**Comment by bobsummerwill** [comment]
All fixed now.
