### ISSUE TITLE
For our coding standards to be meaningful, they need to be automatable

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#486]
That probably means either `astyle` or `clang-format`, and we need the ability to run it locally and to have it run as part of our automation.

So probably `make style` to report on violations, lint-style, and `make fix-style` to automatically fix the violations in-place if that is possible.

I **do not** think it would be a good idea for the automation to do this automatically, because that runs the risk of the automation introducing issues into the code which then have not ever been tested.    Instead, this would be in the form of an additional gate in the PR process.

**Comment by chfast** [comment]
Please do not make it more complicated than it is. Add .clang-format to repo. Run clang-format. Have your automation. Please do not try to learn CMake formatting code.

**Comment by bobsummerwill** [comment]
Those were just example command-lines, @chfast.    I have never used `clang-format` myself.

Does it reformat-in-place, or just report issues?    Because I think we need both modes, right?

**Comment by gcolvin** [comment]
Well, not automatable, but enforceable.  And when it comes to style,  enforcement that can't be automated can too easily lead to wasted time and hurt feelings.

**Comment by gcolvin** [comment]
From what I can tell neither tool has a diff-only mode, but as we discussed one can be created by diffing its output with its input.  I don't know which tool is better, but astyle is better documented, and there is a start at https://github.com/ethereum/webthree-umbrella/blob/develop/astylerc that I notice Paweł has contributed to.  However, Paweł is right that .clang-format can simply be dropped into the top-level directory of a repo, whereas .astylerc must be referenced by an environment variable or on the command-line.

**Comment by chriseth** [comment]
Please don't spend time on things like that. We have much more important tasks at hand. Coding style is for humans, not for machines.

Lefteris tried to use clang-format for our coding style once, but found out that it is not possible to map our multi-line rule into a clang-style specification. I would assume this is similar for astyle.

**Comment by chfast** [comment]
For the record, astyle is too simple. Last time we tried to use it it was disaster.

**Comment by bobsummerwill** [comment]
Have you got experience with clang-format, @chfast?
I have generally found Clang/LLVM tools to be pretty solid.    Do you think we have more hope there?

The scope here would be purely whitespace/lexical.

**Comment by chfast** [comment]
`clang-format` is very nice. You can integrate it to every editor you want. And it can only selected part of the code.

I tried to reproduce our style with clang-format, but there were some issues. E.g. there is no config option to for placing `:` without leading space in case of inheritance list and ranged for. I even create a patch for clang-format to support that. But in the end I gave up. I would suggest changing style here.

Also clang-format works best is it has line length limit. 80 column war is in the air...

I will try to configure it once again as I'm very curious what it can do.

**Comment by bobsummerwill** [comment]
@chfast Great!

Whatever you have we should get into some shared place where we can collaborate on it, even if that is on our own time.
