### ISSUE TITLE
OS X - Mix version within DMG is old

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#496]
The Mix version which is showing within https://builds.ethereum.org/cpp-binaries-data/release-1.2.4/Ethereum.dmg self-identifies as 1.0.1, where it should be 1.0.3.    Solidity version shows as 0.2.2 as well, also old.

Are we getting stale binaries here?   Also, why do we still have AlethOne showing?

Reported by @akomba in https://gitter.im/ethereum/mix?at=5726e5fcce9e8bce0fd371a7.

**Comment by chriseth** [comment]
@bobsummerwill this  sounds quite serious, could you please take care of it? Try to check with those here: https://build.ethdev.com/cpp-binaries-data/develop/ and then fiddle with the jenkins develop binaries until we have the correct package for develop, then let's hope that this also works for the next release package. In any case, we should probably manually create the correct packages for the older releases.

**Comment by bobsummerwill** [comment]
Sure - I will pull it into my pile for this sprint.

The other urgent thing is the Mix crash bugs.    I'm sure I can fiddle about and get the correct build into the DMG, but if it just crashes at boot then there's not much point :-)

**Comment by bobsummerwill** [comment]
And @subtly reports that the AlethZero appears to be broken in exactly the same way.

Looks like they stopping moving forward at 1.1.4, prior to Homestead.

@bobsummerwill will investigate when he gets a chance this weekend.

**Comment by bobsummerwill** [comment]
Fixed by https://github.com/ethereum/webthree-helpers/pull/178.

It looks like this got broken when we switched the machines in February.     The DMG was coming from an old "workspace" - macos_slave, which wasn't moving.   D'oh!
