### ISSUE TITLE
GCC - Can we get rid of -Wno-unknown-pragmas?

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#502]
Why do we need this global warning suppression?   What happens is we remove it?

https://github.com/ethereum/webthree-helpers/blob/develop/cmake/EthCompilerSettings.cmake#L34

**Comment by chfast** [comment]
We should keep that. Pragmas are not portable by definition.

**Comment by bobsummerwill** [comment]
They aren't, no, but they should be inside platform-conditional #ifdefs.

If we need to do this, it probably indicates that we have pragmas "in the wild", which need wrapping.    That's what the warning is telling you, but we're suppressing them rather than fixing them.

**Comment by bobsummerwill** [comment]
This issue was moved to ethereum/cpp-ethereum#3159
