### ISSUE TITLE
Clang - Can we get rid of -Wno-unused-function and -Wno-dangling-else?

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#503]
See https://github.com/ethereum/webthree-helpers/blob/develop/cmake/EthCompilerSettings.cmake#L107.

Can we remove these?   What happens?   What code needs these?   Can we just fix the code?

**Comment by chfast** [comment]
Remove -> build -> fix code -> commit.

**Comment by bobsummerwill** [comment]
I know.   This is a reminder to try that at some stage.

**Comment by bobsummerwill** [comment]
This issue was moved to ethereum/cpp-ethereum#3160
