### ISSUE TITLE
Can we mask out unused configurations?

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#505]
Can we remove/block MINSIZEREL and RELEASE configurations, which we aren't using?

We would only support Debug and RelWithDebInfo, and generate a build error if the user tries to use anything else.

There is a support for this in CMake, I believe.    We're just using the defaults because we're using the defaults.

See https://github.com/ethereum/webthree-helpers/blob/develop/cmake/EthCompilerSettings.cmake#L65.

**Comment by chfast** [comment]
I use Release. Having MinSizeRel would be nice too.

**Comment by bobsummerwill** [comment]
So you want to keep all 4, @chfast?    ie. to NOT do this? :-)

**Comment by chfast** [comment]
I don't see problems having all 4. I'm not sure it is easy to _mask_ them _out_. You can set `-DCMAKE_BUILD_TYPE=WTF` and that will work.

**Comment by bobsummerwill** [comment]
You might be right.    I did see a code snippet somewhere, but given that it is just primitive string composition, that does seem a bit unnecessary.    I'll forget this.

**Comment by bobsummerwill** [comment]
Also, with SAAS automation, we can likely just build them all anyway.   We're not constrained to a single machine.
