### ISSUE TITLE
Support installing without JIT, thus on 32-bit

### ISSUE THREAD

**Issue by ghost** [ethereum/webthree-umbrella#51]
Moved here from [cpp-ethereum](https://github.com/ethereum/cpp-ethereum/issues/2743)

According to the Ubuntu build page,

> The best supported platform as of December 2014 is Ubuntu 14.04, 64 bit, with at least 2 GB RAM

Doesn't appear, in any use of English I'm familiar with, to say that 32-bit is not supported, and I can imagine no reason why ethereum would require any 64-bit functionality, so I optimistically spent a couple of days attempting to build.
I failed.

If anyone has managed in _any_ way to install on 32-bit, please let me know how!

My process was: 

`git clone https://github.com/ethereum/cpp-ethereum
 git checkout develop`

followed by cmake.

It failed on the llvm 3.8 dependency, but got a little closer after additionally
`sudo apt-get install cpp-ethereum`

cmake still failed, essentially for the lack of llvm 3.7 / 3.8

I saw a workaround for broken llvm 3.7 /3.8 in [evmjit/CMakeLists](https://github.com/ethereum/evmjit/blob/master/CMakeLists.txt) so I tried git cloning llvm to ~/llvm/build , then

`cd ~/cpp-ethereum/ && rm -rf build && mkdir build && cd build
 cmake .. -DETHASHCL=1 -DOpenCL_INCLUDE_DIR=/usr/include/hwloc -DLLVM_DIR=~/llvm/build/share/llvm/cmake/ 
 make -j2`

cmake suceeded, but make failed, giving:
`In file included from /home/mimi/llvm/include/llvm/IR/IntrinsicInst.h:30:0,
                from /home/mimi/cpp-ethereum/evmjit/libevmjit/Arith256.cpp:8:
/home/mimi/llvm/include/llvm/IR/Intrinsics.h:40:34: fatal error: llvm/IR/Intrinsics.gen: No such file or directory
 #include "llvm/IR/Intrinsics.gen"
                                  ^
compilation terminated.
make[2]: *** [evmjit/libevmjit/CMakeFiles/evmjit.dir/Arith256.cpp.o] Error 1
make[1]: *** [evmjit/libevmjit/CMakeFiles/evmjit.dir/all] Error 2`

(apologies for the erratic formatting - this is a digest from paper notes)

Intrinstics.gen appears to be a restating of available number types, but that's way beyond me (anyone with a little experience might say that I'd reached and passed the 'way beyond me' stage earlier than that in any case ;)

So, where are we here?
It seems to me that the build fails on what appears to me to be a not-particularly-necessary dependency on llvm at 3.7 / 3.8, which are not available in any repositories I've found (apart from 64bit ubuntu).
On the other hand, though if I'm right, the root cause is trivial, fixing that problem is way beyond me (I guess it inolves sanitising the C code to make it backwards-compatible?) and it seems strange that there is apparently a whole ethereum ecosystem starting up and that _all_ of those involved have spare 64-bit machines to turn over to testing it, so I'm guessing someone somewhere knows an easy way to install on a 32-bit  machine.

My 32-bit machine is going to be dedicated (for now) to ethereum, so I am happy to choose (or complie) the OS to suit,

**Comment by bobsummerwill** [comment]
Hey @Morkski!
Are you still interested in getting this working?  Looking at your notes on the original issue, and @phonikg's notes, it seems like you were very close.

**Comment by bobsummerwill** [comment]
Over to you, Greg, if you like?

**Comment by gcolvin** [comment]
Seems worth a little work before I give up and switch the machine to either Ubuntu 64 bit or Windows 7 64 bit.

**Comment by gcolvin** [comment]
Success, so far.  Run cmake... Use ubuntu software center, synaptic or apt-get to install what it complains is missing... lather, rinse, repeat...  Now I guess I start peeling off the -D options...

greg@Latitude:~/webthree-umbrella/build$ cmake .. -DFATDB=OFF -DMINIUPNPC=OFF -DGUI=OFF -DTESTS=OFF -DTOOLS=OFF -DETHASHCL=OFF -DEVMJIT=OFF -DSOLIDITY=OFF
-- boost headers: /usr/include
-- boost lib   : /usr/lib/i386-linux-gnu/libboost_thread.so;/usr/lib/i386-linux-gnu/libboost_date_time.so;/usr/lib/i386-linux-gnu/libboost_system.so;/usr/lib/i386-linux-gnu/libboost_regex.so;/usr/lib/i386-linux-gnu/libboost_chrono.so;/usr/lib/i386-linux-gnu/libboost_filesystem.so;/usr/lib/i386-linux-gnu/libboost_unit_test_framework.so;/usr/lib/i386-linux-gnu/libboost_program_options.so;/usr/lib/i386-linux-gnu/libboost_random.so;/usr/lib/i386-linux-gnu/libpthread.so

------------------------------------------------------------------------
-- Configuring cpp-ethereum
------------------------------------------------------------------------
--                  CMake Version                            3.2.2
-- CMAKE_BUILD_TYPE Build type                               
-- TARGET_PLATFORM  Target platform                          Linux
--------------------------------------------------------------- features
-- PROFILING        Profiling support                        OFF
------------------------------------------------------------- components
-- GUI              Build GUI components                     OFF
-- SOLIDITY         Build Solidity                           OFF
------------------------------------------------------------------------

-- Gmp headers: /usr/include/i386-linux-gnu
-- Gmp lib   : /usr/lib/i386-linux-gnu/libgmp.so

------------------------------------------------------------------------
-- Configuring dev
------------------------------------------------------------------------
--                  CMake Version                            3.2.2
-- CMAKE_BUILD_TYPE Build type                               
-- TARGET_PLATFORM  Target platform                          Linux
--------------------------------------------------------------- features
-- PROFILING        Profiling support                        OFF
-- PARANOID         -                                        OFF
-- MINIUPNPC        -                                        OFF
------------------------------------------------------------- components
-- GUI              Build GUI components                     OFF
-- TESTS            Build tests                              OFF
-- TOOLS            Build tools                              OFF
-- SOLIDITY         Build Solidity                           OFF
------------------------------------------------------------------------

-- JsonCpp headers: /usr/include/jsoncpp
-- JsonCpp lib   : /usr/lib/i386-linux-gnu/libjsoncpp.so
-- LevelDB headers: /usr/include
-- LevelDB lib   : /usr/lib/i386-linux-gnu/libleveldb.so
-- CryptoPP headers: /usr/include
-- CryptoPP lib   : /usr/lib/libcryptopp.so
-- miniupnpc headers: /usr/include
-- miniupnpc lib   : /usr/lib/libminiupnpc.so

------------------------------------------------------------------------
-- Configuring ethereum
------------------------------------------------------------------------
--                  CMake Version                            3.2.2
-- CMAKE_BUILD_TYPE Build type                               
-- TARGET_PLATFORM  Target platform                          Linux
--------------------------------------------------------------- features
--                  Hardware identification support          
--                  HTTP Request support                     
-- VMTRACE          VM execution tracing                     OFF
-- PROFILING        Profiling support                        OFF
-- FATDB            Full database exploring                  OFF
-- ROCKSDB          Prefer rocksdb to leveldb                OFF
-- OLYMPIC          Default to the Olympic network           OFF
-- PARANOID         -                                        OFF
------------------------------------------------------------- components
-- GUI              Build GUI components                     OFF
-- TESTS            Build tests                              OFF
-- ETHASHCL         Build OpenCL components                  OFF
-- EVMJIT           Build LLVM-based JIT EVM                 OFF
-- SOLIDITY         Build Solidity                           OFF
------------------------------------------------------------------------

-- json-rpc-cpp headers: /usr/include
-- json-rpc-cpp lib   : /usr/lib/libjsonrpccpp-common.so;/usr/lib/libjsonrpccpp-server.so;/usr/lib/libjsonrpccpp-client.so
-- curl headers: /usr/include
-- curl lib   : /usr/lib/i386-linux-gnu/libcurl.so
-- microhttpd headers: /usr/include
-- microhttpd lib   : /usr/lib/i386-linux-gnu/libmicrohttpd.so
-- jsonrpcstub location    : /usr/bin/jsonrpcstub
-- Cpuid headers: CPUID_INCLUDE_DIR-NOTFOUND
-- Cpuid lib   : CPUID_LIBRARY-NOTFOUND

------------------------------------------------------------------------
-- Configuring webthree
------------------------------------------------------------------------
--                  CMake Version                            3.2.2
-- CMAKE_BUILD_TYPE Build type                               
-- TARGET_PLATFORM  Target platform                          Linux
--------------------------------------------------------------- features
-- PROFILING        Profiling support                        OFF
------------------------------------------------------------- components
-- GUI              Build GUI components                     OFF
-- TESTS            Build tests                              OFF
-- SOLIDITY         Build Solidity                           OFF
------------------------------------------------------------------------

-- solidity headers: /home/greg/webthree-umbrella/solidity
-- solidity lib   : solidity
-- V8 headers: /usr/include
-- V8 lib   : /usr/lib/libv8.so
-- readline headers: /usr/include
-- readline lib   : /usr/lib/i386-linux-gnu/libreadline.so
-- Configuring done
-- Generating done
-- Build files have been written to: /home/greg/webthree-umbrella/build

**Comment by gcolvin** [comment]
Success, so far.  Run cmake... Use ubuntu software center, synaptic or apt-get to install what it complains is missing... lather, rinse, repeat...  Now I guess I start peeling off the -D options...

greg@Latitude:~/webthree-umbrella/build$ cmake .. -DFATDB=OFF -DMINIUPNPC=OFF -DGUI=OFF -DTESTS=OFF -DTOOLS=OFF -DETHASHCL=OFF -DEVMJIT=OFF -DSOLIDITY=OFF
-- boost headers: /usr/include
-- boost lib   : /usr/lib/i386-linux-gnu/libboost_thread.so;/usr/lib/i386-linux-gnu/libboost_date_time.so;/usr/lib/i386-linux-gnu/libboost_system.so;/usr/lib/i386-linux-gnu/libboost_regex.so;/usr/lib/i386-linux-gnu/libboost_chrono.so;/usr/lib/i386-linux-gnu/libboost_filesystem.so;/usr/lib/i386-linux-gnu/libboost_unit_test_framework.so;/usr/lib/i386-linux-gnu/libboost_program_options.so;/usr/lib/i386-linux-gnu/libboost_random.so;/usr/lib/i386-linux-gnu/libpthread.so

------------------------------------------------------------------------
-- Configuring cpp-ethereum
------------------------------------------------------------------------
--                  CMake Version                            3.2.2
-- CMAKE_BUILD_TYPE Build type                               
-- TARGET_PLATFORM  Target platform                          Linux
--------------------------------------------------------------- features
-- PROFILING        Profiling support                        OFF
------------------------------------------------------------- components
-- GUI              Build GUI components                     OFF
-- SOLIDITY         Build Solidity                           OFF
------------------------------------------------------------------------

-- Gmp headers: /usr/include/i386-linux-gnu
-- Gmp lib   : /usr/lib/i386-linux-gnu/libgmp.so

------------------------------------------------------------------------
-- Configuring dev
------------------------------------------------------------------------
--                  CMake Version                            3.2.2
-- CMAKE_BUILD_TYPE Build type                               
-- TARGET_PLATFORM  Target platform                          Linux
--------------------------------------------------------------- features
-- PROFILING        Profiling support                        OFF
-- PARANOID         -                                        OFF
-- MINIUPNPC        -                                        OFF
------------------------------------------------------------- components
-- GUI              Build GUI components                     OFF
-- TESTS            Build tests                              OFF
-- TOOLS            Build tools                              OFF
-- SOLIDITY         Build Solidity                           OFF
------------------------------------------------------------------------

-- JsonCpp headers: /usr/include/jsoncpp
-- JsonCpp lib   : /usr/lib/i386-linux-gnu/libjsoncpp.so
-- LevelDB headers: /usr/include
-- LevelDB lib   : /usr/lib/i386-linux-gnu/libleveldb.so
-- CryptoPP headers: /usr/include
-- CryptoPP lib   : /usr/lib/libcryptopp.so
-- miniupnpc headers: /usr/include
-- miniupnpc lib   : /usr/lib/libminiupnpc.so

------------------------------------------------------------------------
-- Configuring ethereum
------------------------------------------------------------------------
--                  CMake Version                            3.2.2
-- CMAKE_BUILD_TYPE Build type                               
-- TARGET_PLATFORM  Target platform                          Linux
--------------------------------------------------------------- features
--                  Hardware identification support          
--                  HTTP Request support                     
-- VMTRACE          VM execution tracing                     OFF
-- PROFILING        Profiling support                        OFF
-- FATDB            Full database exploring                  OFF
-- ROCKSDB          Prefer rocksdb to leveldb                OFF
-- OLYMPIC          Default to the Olympic network           OFF
-- PARANOID         -                                        OFF
------------------------------------------------------------- components
-- GUI              Build GUI components                     OFF
-- TESTS            Build tests                              OFF
-- ETHASHCL         Build OpenCL components                  OFF
-- EVMJIT           Build LLVM-based JIT EVM                 OFF
-- SOLIDITY         Build Solidity                           OFF
------------------------------------------------------------------------

-- json-rpc-cpp headers: /usr/include
-- json-rpc-cpp lib   : /usr/lib/libjsonrpccpp-common.so;/usr/lib/libjsonrpccpp-server.so;/usr/lib/libjsonrpccpp-client.so
-- curl headers: /usr/include
-- curl lib   : /usr/lib/i386-linux-gnu/libcurl.so
-- microhttpd headers: /usr/include
-- microhttpd lib   : /usr/lib/i386-linux-gnu/libmicrohttpd.so
-- jsonrpcstub location    : /usr/bin/jsonrpcstub
-- Cpuid headers: CPUID_INCLUDE_DIR-NOTFOUND
-- Cpuid lib   : CPUID_LIBRARY-NOTFOUND

------------------------------------------------------------------------
-- Configuring webthree
------------------------------------------------------------------------
--                  CMake Version                            3.2.2
-- CMAKE_BUILD_TYPE Build type                               
-- TARGET_PLATFORM  Target platform                          Linux
--------------------------------------------------------------- features
-- PROFILING        Profiling support                        OFF
------------------------------------------------------------- components
-- GUI              Build GUI components                     OFF
-- TESTS            Build tests                              OFF
-- SOLIDITY         Build Solidity                           OFF
------------------------------------------------------------------------

-- solidity headers: /home/greg/webthree-umbrella/solidity
-- solidity lib   : solidity
-- V8 headers: /usr/include
-- V8 lib   : /usr/lib/libv8.so
-- readline headers: /usr/include
-- readline lib   : /usr/lib/i386-linux-gnu/libreadline.so
-- Configuring done
-- Generating done
-- Build files have been written to: /home/greg/webthree-umbrella/build

**Comment by bobsummerwill** [comment]
RE:  "Success, so far. Run cmake... Use ubuntu software center, synaptic or apt-get to install what it complains is missing... lather, rinse, repeat... Now I guess I start peeling off the -D options..."

If you have to peel them all.    Maybe you just try a default first, and see what (if anything) is broken?

**Comment by phonikg** [comment]
When you end up needing llvm this may help you(you will have to edit the svnxxxxx to match the latest):

https://gist.github.com/phonikg/0150910dc1083035e478

**Comment by phonikg** [comment]
...also, have you successfully run `make` to confirm it compiles?

**Comment by gcolvin** [comment]
Thanks  @phonikg, @bobsummerwi.  llvm is already installed, version is  3.4-0ubuntu1.  Is that right?  And indeed the make failed, complaining about a file that is indeed missing.

greg@Latitude:~/webthree-umbrella/build$ make
[  0%] Built target cpp-ethereum_BuildInfo.h
[  5%] Built target scrypt
[  5%] Built target secp256k1
[  5%] Built target dev_BuildInfo.h
[ 16%] Built target devcore
[ 19%] Built target devcrypto
[ 28%] Built target p2p
[ 28%] Built target ethereum_BuildInfo.h
[ 34%] Built target ethcore
[ 35%] Built target evmcore
[ 42%] Built target evmasm
[ 44%] Built target lll
[ 46%] Built target evm
[ 61%] Built target ethereum
[ 63%] Built target ethash
[ 67%] Built target ethashseal
[ 68%] Built target natspec
[ 70%] Built target testutils
[ 70%] Built target webthree_BuildInfo.h
[ 74%] Built target whisper
[ 77%] Built target webthree
CMake Error at /home/greg/webthree-umbrella/webthree-helpers/cmake/scripts/jsonrpcstub.cmake:56 (file):
  file failed to open for reading (No such file or directory):

```
/home/greg/webthree-umbrella/webthree/libweb3jsonrpc/Web3Face.h.tmp
```

make[2]: **\* [web3.jsonstub] Error 1
make[1]: **\* [webthree/libweb3jsonrpc/CMakeFiles/web3.jsonstub.dir/all] Error 2
make: **\* [all] Error 2

greg@Latitude:~/webthree-umbrella/build$ ls  /home/greg/webthree-umbrella/webthree/libweb3jsonrpc
AbstractWebThreeStubServer.h  AdminUtilsFace.h  Eth.h              Net.cpp             UnixSocketServer.cpp
AccountHolder.cpp             AdminUtils.h      eth.json           NetFace.h           UnixSocketServer.h
AccountHolder.h               admin_utils.json  IpcServerBase.cpp  Net.h               Web3.cpp
AdminEth.cpp                  Bzz.cpp           IpcServerBase.h    net.json            Web3Face.h
AdminEthFace.h                BzzFace.h         IpcServer.h        Personal.cpp        Web3.h
AdminEth.h                    Bzz.h             JsonHelper.cpp     PersonalFace.h      web3.json
admin_eth.json                bzz.json          JsonHelper.h       Personal.h          Whisper.cpp
AdminNet.cpp                  CMakeLists.txt    LevelDB.cpp        personal.json       WhisperFace.h
AdminNetFace.h                DBFace.h          LevelDB.h          SafeHttpServer.cpp  Whisper.h
AdminNet.h                    db.json           MemoryDB.cpp       SafeHttpServer.h    whisper.json
admin_net.json                Eth.cpp           MemoryDB.h         SessionManager.cpp  WinPipeServer.cpp
AdminUtils.cpp                EthFace.h         ModularServer.h    SessionManager.h    WinPipeServer.h

**Comment by phonikg** [comment]
Minimum version of LLVM required is 3.7 as per https://github.com/ethereum/webthree-umbrella/wiki/Building-on-Ubuntu <--all other dependencies are listed here as well in case one was missed(could be why `make` failed)

**Comment by gcolvin** [comment]
Aha, I had run the command on the Ubuntu page, but forgot that it failed on llvm. And 3.7 is hard to find, thus the script.  Thanks @phonikg.   The script has been building stuff for a long time now.

**Comment by gcolvin** [comment]
Oh.  The Ubuntu dependency getter fell down as follows.

The following packages have unmet dependencies:
 llvm-3.7-dev : Depends: libjsoncpp0v5 but it is not installable
                Depends: libllvm3.7 but it is not going to be installed
                Depends: libstdc++6 (>= 5.2) but 4.8.4-2ubuntu1~14.04.1 is to be installed
                Depends: llvm-3.7 (= 1:3.7.1~svn254351-1~exp1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by gcolvin** [comment]
Ah, but does "Depends: libjsoncpp0v5 but it is not installable" mean what it says?

**Comment by gcolvin** [comment]
I had patched the svn* path incorrectly.  Now it's very busy compiling things.

**Comment by bobsummerwill** [comment]
How is it going, @gcolvin?
I'm weirdly seeing different comments here than in the e-mail notifications (which seem to be MORE up-to-date), with the most recent being "I had patched the svn\* path incorrectly. Now it's very busy compiling things."

**Comment by gcolvin** [comment]
I edited two and deleted two that were then irrelevant.  Waiting on the @phonikg script to finish.  Wondering why make needs llvm when cmake was told no jit or even compiler?
-DFATDB=OFF \
-DMINIUPNPC=OFF \
-DGUI=OFF \
-DTESTS=OFF \
-DTOOLS=OFF \
-DETHASHCL=OFF \
-DEVMJIT=OFF \
-DSOLIDITY=OFF \

**Comment by bobsummerwill** [comment]
Yeah ... should definitely NOT need llvm if JIT is disabled.

**Comment by gcolvin** [comment]
So that's a problem right there, but at this point I'll let it finish.

**Comment by gcolvin** [comment]
And now I hit a wall.

make[8]: Entering directory `/home/greg/llvm-toolchain-snapshot-3.8~svn257294/build-llvm/tools/clang/tools/extra/clang-tidy/tool'
llvm[8]: Linking Release executable clang-tidy (without symbols)
g++-4.8 -std=c++0x -g -O2 -Wl,--gc-sections -Wl,-R -Wl,'$ORIGIN/../lib' -L/home/greg/llvm-toolchain-snapshot-3.8~svn257294/build-llvm/Release/lib -L/home/greg/llvm-toolchain-snapshot-3.8~svn257294/build-llvm/Release/lib -Wl,--version-script=/home/greg/llvm-toolchain-snapshot-3.8~svn257294/autoconf/ExportMap.map -fuse-ld=gold   -o /home/greg/llvm-toolchain-snapshot-3.8~svn257294/build-llvm/Release/bin/clang-tidy  /home/greg/llvm-toolchain-snapshot-3.8~svn257294/build-llvm/tools/clang/tools/extra/clang-tidy/tool/Release/ClangTidyMain.o -lclangTidy -lclangTidyLLVMModule -lclangTidyGoogleModule -lclangTidyMiscModule -lclangTidyModernizeModule -lclangTidyPerformanceModule -lclangTidyReadability -lclangTidyUtils -lclangTidyCERTModule -lclangStaticAnalyzerFrontend -lclangTidyCppCoreGuidelinesModule -lclangStaticAnalyzerCheckers -lclangStaticAnalyzerCore -lclangFormat -lclangASTMatchers -lclangTooling -lclangToolingCore -lclangFrontend -lclangSerialization -lclangDriver -lclangParse -lclangSema -lclangAnalysis -lclangRewriteFrontend -lclangRewrite -lclangEdit -lclangAST -lclangLex -lclangBasic \
    -lLLVM-3.8   -lz -lpthread -lffi -ledit -ltinfo -ldl -lm 
/usr/bin/ld.gold: fatal error: /home/greg/llvm-toolchain-snapshot-3.8~svn257294/build-llvm/Release/bin/clang-tidy: mmap: failed to allocate 801567436 bytes for output file: Cannot allocate memory
collect2: error: ld returned 1 exit status

**Comment by gcolvin** [comment]
This says it is mmap failing for lack of 800MB of virtual memory.  Could ld have flat run out of address space? @phonikg  @bobsummerwill

**Comment by bobsummerwill** [comment]
Entirely possible.

This build error you are seeing appears to be when BUILDING LLVM, which you shouldn't need to be doing.  You should work out how to get rid of the Clang/LLVM bits which cannot have been eliminated (as you suggested earlier) based on that command-line.

**Comment by gcolvin** [comment]
That will be tomorrow's job.  I just saw no point in shutting down a build long in progress, and found its death informative.  This version of llvm is just too big to build in a 4GB address space.  So we know up front that 32-bit systems are not going to build with a JIT.

**Comment by bobsummerwill** [comment]
Yes-and-no.   LLVM is available pre-built on many distros.   I'm not sure why you are having to build it yourself.

**Comment by phonikg** [comment]
Hello gents, my apologies if my script suggestion has blown you a little
off course.  My suggestion was based on Bob's comment of a "more default"
install rather than with everything turned off. In which case you would Def
need llvm.

In addition,If I remember correctly with regards to my 32bit ARM builds,
even with evmjit turned off, the build complained if >llvm-3.7 was not
installed.  The issue with available distro binaries is that as they are
all <llvm-3.7.  If you look outside of package maintainers all that is
available are 64 bit binaries.

I hope I did not waste anyone's time, I know first hand that time spent in
this arena can not be taken back:)

**Comment by gcolvin** [comment]
You're script has been very helpful @phonikg, and the time a learning experience.  The distros do not have an up-to-date llvm, @bobsummerwill.  Perhaps because it can't be reliably built in a 32-bit environment.  The question now is why cmake is dragging in llvm at all.  It must not have done so in your many cross-compiles, so what is different this time?

**Comment by bobsummerwill** [comment]
No problem.   That is good to know.

So here are the exact command-line invocations for the cross-builds:

https://github.com/doublethinkco/webthree-umbrella-cross/blob/master/cross-build/ethereum/libethereum.sh#L32

https://github.com/doublethinkco/webthree-umbrella-cross/blob/master/cross-build/ethereum/libweb3core.sh#L37

https://github.com/doublethinkco/webthree-umbrella-cross/blob/master/cross-build/ethereum/webthree.sh#L44

You could also look at the eth*.sh shell scripts in https://github.com/ethereum/webthree-helpers/tree/develop/scripts.   I have not used them at all myself.

**Comment by bobsummerwill** [comment]
Could you share a gist for the CMake invocation which is unexpectedly dragging in LLVM?

**Comment by gcolvin** [comment]
The command line is simply:

cmake \
-DFATDB=OFF \
-DMINIUPNPC=OFF \
-DGUI=OFF \
-DTESTS=OFF \
-DTOOLS=OFF \
-DETHASHCL=OFF \
-DEVMJIT=OFF \
-DSOLIDITY=OFF \
..

Spent a lot of time examining its output, finding the JIT set off everywhere, but generated nonetheless.  Unfortunately your comments of ten hours ago remained invisible here until I just manually refreshed the page.  I think we should discuss running your scripts as is, or slightly modified for the situation of cross-compiling to yourself.  If they work we are on track.  I am hoping that only the JIT need be excised to get a clean build.

**Comment by gcolvin** [comment]
@bobsummerwill @chriseth @phonikg   My plan is to first work through the instructions on the wiki - on a cleanly installed, stock Ubuntu 14.04 - fixing any problems in the documentation and/or cmake as I go.  When that is clean (as it should be for Homestead) I can look at the 32-bit build.

**Comment by gcolvin** [comment]
The instructions at
https://github.com/ethereum/webthree-umbrella/wiki/Building-on-Ubuntu
went fine up to:
_You'll need to install several develop packages if you want to build the full suite, including the GUI components. Here is a list of minimal requirements for (some of) the packages you'll need:
   Qt 5.5 or higher
   llvm 3.7_
At that point llvm 3.7 had already been installed above, but not Qt 5.5.  For that I had to go to qt.io and download the installer.  Then a little later we have
_If you have Qt already installed elsewhere, make sure you have version 5.5, and set your path accordingly..._
But still, no hint as to how to tell what version you have installed, where it is, or what to do if you don't have it.  Once past that it's on to the generic Linux instructions.

**Comment by bobsummerwill** [comment]
Well - edit away as you see fit, @gcolvin!

**Comment by gcolvin** [comment]
Started with the **Building using umbrella project** commands, which went fine.  Except I didn't bother with the **-j 8** on this two-core machine.  Not sure why the -j is there.

Next is **Building modules separately**  which gets in trouble fast:

gcolvin@Dell:~$_ git clone https://github.com/ethereum/webthree-helpers
__gcolvin@Dell:~$ git clone https://github.com/ethereum/webthree-helpers
Cloning into 'webthree-helpers'...
remote: Counting objects: 1539, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 1539 (delta 1), reused 0 (delta 0), pack-reused 1534
Receiving objects: 100% (1539/1539), 374.46 KiB | 0 bytes/s, done.
Resolving deltas: 100% (948/948), done.
Checking connectivity... done.
gcolvin@Dell:~$ cd webthree-helpers
gcolvin@Dell:~/webthree-helpers$ git checkout release
error: pathspec 'release' did not match any file(s) known to git.

Proceeded anyway and all the individual scripts went fine, other than some similar complaints about 'release'.

**Comment by gcolvin** [comment]
And yes, @bobsummerwill, I'll be editing.  Will run these notes by you later.

**Comment by bobsummerwill** [comment]
Yeah - you don't want to use "release" branches in general, so if the instructions say you do then they are probably wrong.    We are working off "develop" for everything.    There is a "release" branch for the webthree-umbrella as a whole, but not, as far as I can see, for the individual repos.

**Comment by gcolvin** [comment]
We are working off of develop, but should non-developing users?

**Comment by bobsummerwill** [comment]
Generally it is fine for them to do so, yes.

Non-developing users would normally not be building-from-source at all.   If you are building from source, you may as well be on the bleeding edge.   Breaks are pretty rare.   Also, that puts them in a better position to contribute pull-requests.

**Comment by gcolvin** [comment]
Paranoid (i.e. cautious) users build from source too. Any reason for them not to do this?  Any advantage?
_git clone --recursive https://github.com/ethereum/webthree-umbrella
cd webthree-umbrella
git checkout **release**
mkdir build
cd build
cmake ..
make_

**Comment by bobsummerwill** [comment]
They can do that, yes.

The advantage of that over using pre-built binaries is that they have matching source code for the latest release, and can debug, etc.

The disadvantage they have is that they then won't be at the same point in the timeline as we are.   Having said that, we also have a "timeline issue" in general with the whole webthree-umbrella pattern, which is that we need to manually update the umbrella, so that even "umbrella develop" is not exactly what we have on our desktops.

Merging some of the repos will certainly make this a simpler problem.    Having auto-integrations to update the sub-modules in webthree-umbrella when automation succeeds would be helpful too.

**Comment by gcolvin** [comment]
One advantage of compiling from source is that your compiler can optimize for your hardware.  Another is that you can audit the source you are compiling; seems like best practice to me.

**Comment by gcolvin** [comment]
For 64-bit Ubuntu with prerequisites satisfied the umbrella script builds, as do the individual repository scripts.  The manual instructions don't get so far.
_/home/gcolvin/solidity/libsolidity/Compiler.cpp:28:31: fatal error: libevmcore/Params.h: No such file or directory
 #include <libevmcore/Params.h>_
That causes every target but web3,js to fail for lack of Solidty.

**Comment by gcolvin** [comment]
What is mysterious is that the "libvmcore"  path is called out literally in libsolidy/Compiler.cpp, so this should be failing on all the other builds.  Anyone have an idea?  @chriseth @bobsummerwill

**Comment by bobsummerwill** [comment]
Sounds like missing include paths.    Could you do a verbose build and share the full command-line for and of the failing command-line steps?

Looks to me like disabling EVMJIT has sniped out evmcore too (which is likely a build script bug).

**Comment by bobsummerwill** [comment]
With regard to building the umbrella release branch from source ... sure, it has some benefits.

**Comment by gcolvin** [comment]
This build has not disabled EVMJIT, and the other projects do not build libvmcore, they builds libweb3core.  I don't know if a macro or some sort of magic maps libvmcore to libweb3core during the other builds, or whether Compiler.cpp is not part of those builds.  Anyway, I have to leave now to see a doctor in Denver.  120 miles across South Park.  Online late tonight or early tomorrow.

**Comment by bobsummerwill** [comment]
libevmcore is one of the modules in libethereum.
See dependency graph in https://github.com/doublethinkco/webthree-umbrella-cross/.
Catch you later, when you have some logs and we can dig in!

**Comment by gcolvin** [comment]
A careful rebuild from a clean slate and the build is fine Ubuntu 14.04 for AMD64, by all three documented methods.  Next step is to make it build without the JIT, which appears to be the obstacle in the way of building on 32 bit systems.

**Comment by gcolvin** [comment]
-DEVMJIT=OFF seems to work correctly on 64-bit Ubuntu, preventing the jit from being built.

**Comment by bobsummerwill** [comment]
Good to know, but I suspect that the CMake files still require LLVM to be installed, don't they?    Even though it isn't used.    That has been my experience for the cross-builds, anyway.    We had to write hacks for the build files which stripped out the actual module-dependencies to avoid dragging in V8 and LLVM.

**Comment by bobsummerwill** [comment]
I have made a bug to track this -> https://github.com/ethereum/webthree-umbrella/issues/306
Please do update that with a comment to confirm/deny that you are seeing the issue as I describe it, @gcolvin.   Thanks!

**Comment by gcolvin** [comment]
So long as one avoids attempting to pull in llvm 3.7 and uses EVMJIT=OFF things build fine on 32 bit.  So it is not necessary to fix https://github.com/ethereum/webthree-umbrella/issues/306 in order to build on 32 bit.  I am updating the build instructions and will close this issue when I finish testing them.

**Comment by gcolvin** [comment]
@bobsummerwill  Building on 32 bit systems is limited: neither the umbrella nor the manual builds work.  But the per-module helper scripts work.  I don't think 32-bit builds are important enough to spend more time on this now, as there is a way to build.  Getting all scripts to work will require closing https://github.com/ethereum/webthree-umbrella/issues/306

**Comment by bobsummerwill** [comment]
Great - thanks, @gcolvin!

**Comment by tflux99** [comment]
@gcolvin this error CMake Error at /home/greg/webthree-umbrella/webthree-helpers/cmake/scripts/jsonrpcstub.cmake:56 (file):
file failed to open for reading (No such file or directory): ... belongs to missing jsonrpcstub libs what happens if you enter "jsonrpcstub" in console if it tells you missing argument everythging is ok but if its telling you you have missing libs (jsonrpcstaub-common.so) then you have to move this libs to usr/lib64 or usr/lib depends on your system or just make symbolic links to those libs hope it helps :)
