### ISSUE TITLE
windows cmake failed: Cpuid?

### ISSUE THREAD

**Issue by debugrelease** [ethereum/webthree-umbrella#510]
My system is win10_x64,following the steps of http://www.ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/building-from-source/windows.html#pre-requisites, run cmake -G "Visual Studio 12 2013 Win64" ..,then failed:
-- EVM JIT 0.9.0
-- Using LLVM 3.7.0 (E:/work/GitHub/webthree-umbrella/webthree-helpers/extdep/install/windows/x64/share/llvm/cmake)
-- OpenCL headers: E:/work/GitHub/webthree-umbrella/webthree-helpers/extdep/install/windows/x64/include
-- OpenCL lib   : optimized;E:/work/GitHub/webthree-umbrella/webthree-helpers/extdep/install/windows/x64/lib/OpenCL.lib;debug;E:/work/GitHub/webthree-umbrella/webthree-helpers/extdep/install/windows/x64/lib/OpenCL_d.lib
-- OpenCL dll   : optimized;E:/work/GitHub/webthree-umbrella/webthree-helpers/extdep/install/windows/x64/bin/OpenCL.dll;debug;E:/work/GitHub/webthree-umbrella/webthree-helpers/extdep/install/windows/x64/bin/OpenCL_d.dll
-- Cpuid headers: CPUID_INCLUDE_DIR-NOTFOUND
-- Cpuid lib   : CPUID_LIBRARY-NOTFOUND
CMake Error at libethereum/ethminer/CMakeLists.txt:7 (eth_simple_add_executable):
  Unknown CMake command "eth_simple_add_executable".

-- Configuring incomplete, errors occurred!
See also "E:/work/GitHub/webthree-umbrella/build/CMakeFiles/CMakeOutput.log".
See also "E:/work/GitHub/webthree-umbrella/build/CMakeFiles/CMakeError.log".

[CMakeError.log.txt](https://github.com/ethereum/webthree-umbrella/files/258921/CMakeError.log.txt)
[CMakeOutput.log.txt](https://github.com/ethereum/webthree-umbrella/files/258922/CMakeOutput.log.txt)
[cmd_failed.txt](https://github.com/ethereum/webthree-umbrella/files/258923/cmd_failed.txt)

**Comment by bobsummerwill** [comment]
The failure is because you must have an incompatible set of repos.

If you `git clone --recursive` on the webthree-umbrella, you shouldn't have hit this issue.    Did you clone the repos independently?

Or maybe you just hit a very unlucky bit of timing?    If you refresh your umbrella to HEAD you won't hit this.

You have some code which uses a new CMake function which we added to webthree-helpers, but it looks like you have older revision of that repo and newer revision of libethereum.

Please can you retry and verify?   Thanks!

**Comment by hkjayakumar** [comment]
@debugrelease This is basically related to #511 . The docs were updated yesterday so try [this](http://www.ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/building-from-source/windows.html) again.

**Comment by bobsummerwill** [comment]
OK - I'm assuming this was just a docs issue.   Please reopen or make a new issue if you're still having issues, @debugrelease.   Thanks!
