### ISSUE TITLE
Ubuntu Trusty - LLVM 3.7 not "sticking"

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#514]
Hitting an issue in TravisCI where the install instructions for Ubuntu Trusty are NOT ended up with llvm 3.7 being used.   Hmm.   Is it installed to the wrong place?   Is the issue because we don't have `apt-get upgrade` calls (because they were causing other problems)?

https://travis-ci.org/bobsummerwill/cpp-ethereum/builds/130224930

```
CMake Error at /usr/local/clang-3.5.0/share/llvm/cmake/LLVMConfig.cmake:50 (include):
```

  include could not find load file:
    /home/ben/development/llvm/3.5/final/Phase3/Release/llvmCore-3.5.0-final.install/share/llvm/cmake/LLVMExports.cmake
    Call Stack (most recent call first):
  evmjit/CMakeLists.txt:29 (find_package)
    CMake Error at /usr/local/clang-3.5.0/share/llvm/cmake/LLVMConfig.cmake:53 (include):
  include could not find load file:
    /home/ben/development/llvm/3.5/final/Phase3/Release/llvmCore-3.5.0-final.install/share/llvm/cmake/LLVM-Config.cmake
    Call Stack (most recent call first):
  evmjit/CMakeLists.txt:29 (find_package)
    CMake Error at evmjit/CMakeLists.txt:31 (message):
      Incompatible LLVM version 3.5.0

**Comment by chfast** [comment]
It is probably because of search order. I will fix that later in CMake. The workaround is to uninstall `llvm-3.5-dev`.

**Comment by bobsummerwill** [comment]
Aha - yes, that would make sense :-)

I'll try to fix it in my cpp-ethereum branch which I'm working on, and will make a PR.

**Comment by bobsummerwill** [comment]
Hmm.  Couldn't get either clang-3.5 or llvm-3.5-dev removes to work, strangely:
- https://travis-ci.org/bobsummerwill/cpp-ethereum/builds/130318387
- https://travis-ci.org/bobsummerwill/cpp-ethereum/builds/130318927

So I ended up just doing a specific version find_package() to 3.7 as a workaround, which seems to have worked, but is obviously not something we could commit, unless we did some loop there through a list of versions.   Strange!
- https://travis-ci.org/bobsummerwill/cpp-ethereum/builds/130319410

**Comment by bobsummerwill** [comment]
This workaround has got my TravisCI automation to the same failure point as the CircleCI automation:
- https://travis-ci.org/bobsummerwill/cpp-ethereum/builds/130319410
- https://circleci.com/gh/bobsummerwill/cpp-ethereum/38

Both are now failing on the `jsonrpcstub` failure - https://github.com/ethereum/webthree-umbrella/issues/513.

**Comment by bobsummerwill** [comment]
The building from source for LLVM changes in @chfast's latest evmjit repo might make this one irrelevant.   I assume it is a search-path issue anyway.

Also to consider ... how does the evmjit change affect the release flow for Linux?    Do the `.so` files end up getting copied as expected?   Do our locally built LLVM `.so` files need installing on top of whatever PPAs may have installed previously?

**Comment by chfast** [comment]
It does not change output at all. evmjit is still single binary -- evmjit.so. The binary does not depend on any LLVM binary, only some system libraries.

```
ldd build/libevmjit/libevmjit.so
    linux-vdso.so.1 =>  (0x00007ffd519ee000)
    libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007efc97b62000)
    libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007efc97949000)
    libtinfo.so.5 => /lib/x86_64-linux-gnu/libtinfo.so.5 (0x00007efc97720000)
    libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007efc9751c000)
    libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007efc97218000)
    libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007efc96f12000)
    libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007efc96cfc000)
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007efc96937000)
    /lib64/ld-linux-x86-64.so.2 (0x00007efc98ee5000)
```

**Comment by bobsummerwill** [comment]
RIght - so the LLVM libs end up getting statically linked?   Very good to know.

And that would be the same for OS X?   If so, then the Homebrew changes would just be to strip the one-liner for `llvm37`, rather than updating it, which would be great.

https://github.com/ethereum/homebrew-ethereum/blob/master/cpp-ethereum.rb#L62

**Comment by chfast** [comment]
The results should be the same. However, you can save some time if you will download pre-built binaries of LLVM with homebrew instread of builing it

**Comment by bobsummerwill** [comment]
Right - so I guess that gives us 3 "levels" on OS X:
- `brew install` - just gives us bottles with binaries
- Build from source using `llvm38` prebuilt LLVM binaries
- Build from source including LLVM build-from-source

**Comment by bobsummerwill** [comment]
There is no work left here.
