### ISSUE TITLE
Windows - Jenkins build machine has file locks in ethbinaries release flow

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#516]
ethbinaries has been broken for several days due to Windows file-lock issues.

There is literally nothing I can do to resolve these, given the lack of remote access we have to that Windows 8.1 Home edition machine.

See http://52.28.164.97/job/ethbinaries-build/label=windows-slave/.

**Comment by chriseth** [comment]
Working now.
