### ISSUE TITLE
OS X - Are we even running tests for Mac?

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#517]
Some doubts persist.   Perhaps only a subset of the PR projects are correctly configured.

See https://github.com/ethereum/solidity/issues/573.   CC @VoR0220.

We should now be running tests on all PRs for all repos, for both Yosemite and El Capitan.   But I don't think we are.

Aside - it is KNOWN that we are not running any automated tests on Windows.  That is being tracked elsewhere and is on @winsvega's plate.

**Comment by VoR0220** [comment]
Jenkins supposedly runs tests for both OSs...but those OS systems are clearly not picking up the errors the rest of the mac users are...so something must be wrong with the testing system.

**Comment by chfast** [comment]
Can we have integration tests? E.g.:
- start eth with RPC, sync fist 5000 blocks, stop.
- start ethminer and mine something.

**Comment by chriseth** [comment]
Tests are run now, and the el capitan run even picks up the reported bugs.

@chfast yes we should, but only as soon as we have a bit more resources for working on eth at all.
