### ISSUE TITLE
brew install cpp-ethereum new issue

### ISSUE THREAD

**Issue by Makaronodentro** [ethereum/webthree-umbrella#518]
I am trying to install eth on a OSX ElCapitan v10.11.4 but I receive the following error:

==> Cloning https://github.com/ethereum/webthree-umbrella.git
Updating /Library/Caches/Homebrew/cpp-ethereum--git
==> Checking out branch develop
Synchronizing submodule url for 'evmjit'
Synchronizing submodule url for 'deps'
error: no such remote ref ebb5b11dc516a5df3cb0d8579bb81f194dbce0d5
Fetched in submodule path 'webthree-helpers/deps', but it did not contain ebb5b11dc516a5df3cb0d8579bb81f194dbce0d5. Direct fetching of that commit failed.
Failed to recurse into submodule path 'webthree-helpers'
Error: Failed to download resource "cpp-ethereum"
Failure while executing: git submodule -q update --init --recursive

**Comment by chfast** [comment]
That's my fault. I've just fixed that.

**Comment by Makaronodentro** [comment]
All good now thanks!
