### ISSUE TITLE
eth binary fails to start on Windows

### ISSUE THREAD

**Issue by chfast** [ethereum/webthree-umbrella#519]
I've noticed that recent builds of eth fails to start on Windows (10). The popup says:

```
The application was unable to start correctly (0xc000007b). Click ok
to close the application.
```

Current latest "release" build is ok: http://52.28.164.97/job/ethbinaries-release/46/artifact/label=windows-slave/
Current latest "develop" build is not: http://52.28.164.97/job/ethbinaries-develop/343/artifact/label=windows-slave/ (win_eth.zip, eth.zip is some old artifact).

**Comment by chriseth** [comment]
Please try again with https://build.ethdev.com/cpp-binaries-data/develop/win_eth.zip

**Comment by chfast** [comment]
I tested the binary pointed by @chriseth on Windows 7 (can't do the previous one as it was deleted by Jenkins).

The failure is different: libcurl.dll is missing.

Actually that may explain my previous failures. Maybe on the other machine I had libcurl.dll somewhere in the PATH but the 32-bit version. The error 0xc000007b is about running 32-bit binary in 64-bit mode.

**Comment by chriseth** [comment]
@bobsummerwill is this fixed?

**Comment by bobsummerwill** [comment]
Yes, I think it was just on @chfast's machine.
