### ISSUE TITLE
using .dmg to upgrade mix

### ISSUE THREAD

**Issue by inigo-montoya** [ethereum/webthree-umbrella#520]
i've got a version in about that is 1.0.1....downloaded the v1.2.4.dmg release and replaced the .app in applications.  

On relaunch the about shows 1.0.1 and I do not have a 1.0.3 functionality (arrow keys in debugger or debugger button at the transaction view)

**Comment by bobsummerwill** [comment]
This was resolved in v1.2.9.   Thanks!
