### ISSUE TITLE
Mix-ide Create Poject wipes existing directory without warning.

### ISSUE THREAD

**Issue by o0ragman0o** [ethereum/webthree-umbrella#521]
I've just lost an entire months DAPP work and associated research because MIX first became corrupted, then wiped my project directory without warning when I tried to rebuild the project a new in the same directory.

To repoduce behaviour (on Windows 10 at least):

Start mix-ide
create new project -> creates project directory and files
create another new project in the same directory -> deletes previous project directory and fails create new project.

**Comment by bobsummerwill** [comment]
Yikes, @o0ragman0o!

Sorry to hear that.   Thanks for the bug report.

Backup routines are so important, eh?  Not that it helps you now.

I hope you've managed to get going again quickly enough?

**Comment by o0ragman0o** [comment]
@bobsummerwill, 
Fileio::mkdir() looks to perform an unconditional recursive remove if it detects an existing directory.

https://github.com/ethereum/mix/blob/6cb09e75a2cdf8c66d169a80d4c7d3d7e5396a60/src/FileIo.cpp#L106

**Comment by bobsummerwill** [comment]
Yeah - that is pretty terrible, isn't it :-(

Thanks again for the report.

**Comment by bobsummerwill** [comment]
I believe this was fixed, right, @yann300, @chriseth?
