### ISSUE TITLE
make fails with "file failed to open for reading (...) PersonalFace.h.tmp"

### ISSUE THREAD

**Issue by giacecco** [ethereum/webthree-umbrella#525]
Hi All, I'm building from source for Fedora 23, using the general instructions at http://www.ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/building-from-source/linux.html . I got successfully through the `cmake` stage, I've workarounded [a `make` issue related to LLVM](https://github.com/ethereum/webthree-umbrella/issues/524), but now I'm stuck with this other error. Thank you in advance for any suggestion.

```
[giacecco@giaceccos-linux build]$ sudo make
[  0%] Built target cpp-ethereum_BuildInfo.h
(...)
Scanning dependencies of target personal.jsonstub
CMake Error at /usr/local/src/webthree-umbrella/webthree-helpers/cmake/scripts/jsonrpcstub.cmake:56 (file):
  file failed to open for reading (No such file or directory):

    /usr/local/src/webthree-umbrella/webthree/libweb3jsonrpc/PersonalFace.h.tmp


webthree/libweb3jsonrpc/CMakeFiles/personal.jsonstub.dir/build.make:57: recipe for target 'personal.jsonstub' failed
make[2]: *** [personal.jsonstub] Error 1
CMakeFiles/Makefile2:2347: recipe for target 'webthree/libweb3jsonrpc/CMakeFiles/personal.jsonstub.dir/all' failed
make[1]: *** [webthree/libweb3jsonrpc/CMakeFiles/personal.jsonstub.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
[giacecco@giaceccos-linux build]$
```

In case it was relevant, `libjson-rpc-cpp` is installed, built from source.

**Comment by giacecco** [comment]
This may be a duplicate of https://github.com/ethereum/webthree-umbrella/issues/513 , although the other issue is a problem at `cmake` stage, not `make`.

**Comment by bobsummerwill** [comment]
Thanks for the report, but yes, it is the same issue.

It does happen during the make run (which triggers a cmake target to TRY to run that stub generator).

For some reason which we still don't understand, in some circumstances, `jsonrpcstub` just doesn't work, and then the very next make step falls over because of the missing files).

I'll add you onto the other bug.
