### ISSUE TITLE
Mix 1.2.4 crashes on start on latest Yosemite

### ISSUE THREAD

**Issue by davidhq** [ethereum/webthree-umbrella#527]
Any ideas?

http://pastebin.com/8a4whabi

Process:               Mix [68101]
Path:                  /Applications/Mix.app/Contents/MacOS/Mix
Identifier:            .
Version:               ??? (mix )
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Mix [68101]
User ID:               501

Date/Time:             2016-05-24 17:29:10.495 +0200
OS Version:            Mac OS X 10.11.4 (15E65)
Report Version:        11
Anonymous UUID:        3D47D0AC-B7B4-D89D-712A-1777A0BEC837

Sleep/Wake UUID:       6AA66ADA-A5B6-4E5C-8DAD-70589294E245

Time Awake Since Boot: 220000 seconds
Time Since Wake:       480 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
/Applications/Mix.app/Contents/MacOS/../Frameworks/libdevcrypto.dylib

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libdevcrypto.dylib              0x000000010f65ce9a 0x10f5f2000 + 437914
1   dyld                            0x00007fff6fa4ffeb ImageLoaderMachO::doModInitFunctions(ImageLoader::LinkContext const&) + 265
2   dyld                            0x00007fff6fa50164 ImageLoaderMachO::doInitialization(ImageLoader::LinkContext const&) + 40
3   dyld                            0x00007fff6fa4c79d ImageLoader::recursiveInitialization(ImageLoader::LinkContext const&, unsigned int, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) + 305

**Comment by bobsummerwill** [comment]
Hey, @davidhq,

Thanks for the report.    Yes, we've had a few reports of "crash at start" issues.    Do you have a non-US-English locale set, by any chance?

Over to you, @yann300!

**Comment by bobsummerwill** [comment]
This won't be fixed, because Mix is not being supported anymore.
See https://blog.ethereum.org/2016/07/08/c-dev-update-summer-edition/ for information on the mix -> remix plans.
