### ISSUE TITLE
Failed to generate solution file on Windows: 'CL_VERSION_2_0' : undeclared identifier

### ISSUE THREAD

**Issue by remyroy** [ethereum/webthree-umbrella#529]
Using:
- Windows 7 x64
- Windows SDK v7.1A
- Microsoft Visual Studio 2010 Express
- cmake 3.4.3
- webthree-umbrella 6a471ad169b93da88b79f63961834e76e0ffd73b

When trying to generate a Visual Studio solution [as described in the documentation](http://www.ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/building-from-source/windows.html#build-from-within-visual-studio) using the `Visual Studio 10 2010 Win64` generator, I get the following output in `CMakeError.log`:

```
Determining if the CL_VERSION_2_0 exist failed with the following output:
Change Dir: C:/Users/Remy/Projects/webthree-umbrella/build/CMakeFiles/CMakeTmp

Run Build Command:"C:/Windows/Microsoft.NET/Framework/v4.0.30319/MSBuild.exe" "cmTC_8cdde.vcxproj" "/p:Configuration=Debug" "/p:VisualStudioVersion=10.0"
Microsoft (R) Build Engine version 4.6.1055.0

[Microsoft .NET Framework, version 4.0.30319.42000]

Copyright (C) Microsoft Corporation. All rights reserved.



Build started 5/25/2016 9:50:45 AM.

Project "C:\Users\Remy\Projects\webthree-umbrella\build\CMakeFiles\CMakeTmp\cmTC_8cdde.vcxproj" on node 1 (default targets).

PrepareForBuild:

  Creating directory "cmTC_8cdde.dir\Debug\".

  Creating directory "C:\Users\Remy\Projects\webthree-umbrella\build\CMakeFiles\CMakeTmp\Debug\".

InitializeBuildStatus:

  Creating "cmTC_8cdde.dir\Debug\cmTC_8cdde.unsuccessfulbuild" because "AlwaysCreate" was specified.

ClCompile:

  C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\x86_amd64\CL.exe /c /I"C:\Users\Remy\Projects\webthree-umbrella\webthree-helpers\extdep\install\windows\x64\include" /Zi /W3 /WX- /Od /Ob0 /D WIN32 /D _WINDOWS /D _DEBUG /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Fo"cmTC_8cdde.dir\Debug\\" /Fd"cmTC_8cdde.dir\Debug\vcWindows7.1SDK.pdb" /Gd /TC /errorReport:queue CheckSymbolExists.c

  Microsoft (R) C/C++ Optimizing Compiler Version 16.00.40219.01 for x64

  Copyright (C) Microsoft Corporation.  All rights reserved.



  cl /c /I"C:\Users\Remy\Projects\webthree-umbrella\webthree-helpers\extdep\install\windows\x64\include" /Zi /W3 /WX- /Od /Ob0 /D WIN32 /D _WINDOWS /D _DEBUG /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Fo"cmTC_8cdde.dir\Debug\\" /Fd"cmTC_8cdde.dir\Debug\vcWindows7.1SDK.pdb" /Gd /TC /errorReport:queue CheckSymbolExists.c



  CheckSymbolExists.c

CheckSymbolExists.c(8): error C2065: 'CL_VERSION_2_0' : undeclared identifier [C:\Users\Remy\Projects\webthree-umbrella\build\CMakeFiles\CMakeTmp\cmTC_8cdde.vcxproj]

Done Building Project "C:\Users\Remy\Projects\webthree-umbrella\build\CMakeFiles\CMakeTmp\cmTC_8cdde.vcxproj" (default targets) -- FAILED.



Build FAILED.



"C:\Users\Remy\Projects\webthree-umbrella\build\CMakeFiles\CMakeTmp\cmTC_8cdde.vcxproj" (default target) (1) ->

(ClCompile target) -> 

  CheckSymbolExists.c(8): error C2065: 'CL_VERSION_2_0' : undeclared identifier [C:\Users\Remy\Projects\webthree-umbrella\build\CMakeFiles\CMakeTmp\cmTC_8cdde.vcxproj]



    0 Warning(s)

    1 Error(s)



Time Elapsed 00:00:00.16


File C:/Users/Remy/Projects/webthree-umbrella/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <C:/Users/Remy/Projects/webthree-umbrella/webthree-helpers/extdep/install/windows/x64/include/CL/cl.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef CL_VERSION_2_0
  return ((int*)(&CL_VERSION_2_0))[argc];
#else
  (void)argc;
  return 0;
#endif
}
```

Any tip on how to solve this would be appreciated. Thanks.

**Comment by remyroy** [comment]
The pre-built OpenCL ICD binaries available on https://builds.ethereum.org/builds/windows-precompiled/ do not include an identifier for `CL_VERSION_2_0` in `cl.h` which seems to be needed. Maybe that's a recent addition.

**Comment by bobsummerwill** [comment]
Hmm.   Thanks for the report, @remyroy.

I wonder whether we are seeing some difference between OpenCL support in different Windows versions?     You should be able to side-step this issue with `-DETHASHLCL=0` added as a parameter to your `cmake` invocation, but that will disable OpenCL.

Do you want to use OpenCL, or is this just a hinderance to just getting a build at all :-)

Any thoughts on this, @chfast?

**Comment by remyroy** [comment]
All I want is to build the latest version of Solidity. I think I should be good with disabling OpenCL. I will try it later today or tomorrow.

**Comment by remyroy** [comment]
After trying with `-DETHASHLCL=0` and doing some more review, it seem my problem is unrelated OpenCL ICD or the CL_VERSION_2_0 identifier. It seems related to the boost libraries not being found.

I'm closing this and I'll open another issue.

**Comment by bobsummerwill** [comment]
OK - Did you run the `getstuff.bat`?

**Comment by remyroy** [comment]
Yes. The libraries were downloaded and expanded in `webthree-helpers\extdep\install`.

I'm still investigating.

**Comment by remyroy** [comment]
cmake is trying to find boost libraries compiled with Visual Studio 10 but the pre-built Boost binaries are compiled with Visual Studio 12 2013. I'm guessing that was changed somewhat recently because I used to be able to build with Visual Studio 10 and the documentation specify using VS 10.

Should I create an issue for this? It might just be a documentation issue specifying that you need VS 12  2013 to build it.

**Comment by bobsummerwill** [comment]
Covered in https://github.com/ethereum/webthree-umbrella/issues/531.

IT WILL ALL BE BETTER VERY SOON :-)
