### ISSUE TITLE
Illegal instruction: 4

### ISSUE THREAD

**Issue by ghost** [ethereum/webthree-umbrella#53]
Moved here from [cpp-ethereum](https://github.com/ethereum/cpp-ethereum/issues/2691)

I've compiled eth on my MacBook - but unfortunately it gives the error: "Illegal instruction: 4". Does anyone know how to avoid the problem?

**Comment by markusfi** [comment]
Sample problem here with MacBook:

MacBook-Pro:~ markus$ eth
Illegal instruction: 4

  Model Name:   MacBook Pro
  Model Identifier: MacBookPro5,2
  Processor Name:   Intel Core 2 Duo
  Processor Speed:  3,06 GHz
  Number of Processors: 1
  Total Number of Cores:    2
  L2 Cache: 6 MB
  Memory:   8 GB
  Bus Speed:    1,07 GHz
  Boot ROM Version: MBP52.008E.B05
