### ISSUE TITLE
Get to clarity on licensing and copyright

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#530]
Greetings, cpp-ethereum contributors!

As you are probably aware, [efforts were made in 2015](https://github.com/ethereum/webthree-umbrella/commit/1de4b2cd8f31de6ea417c49aeadc83a0ef935baa) to clarify the licensing of various components within Ethereum, namely [liberalizing the core](https://github.com/ethereum/wiki/wiki/Licensing) to encourage the broadest possible adoption for Ethereum.    We never completed that effort.

The licensing for cpp-ethereum itself has [flip-flopped a few times](https://github.com/ethereum/webthree-umbrella/commits/develop/LICENSE) and we aren't in a particular clear state right at the moment.   To my knowledge we have never had a Contributor License Agreement (https://en.wikipedia.org/wiki/Contributor_License_Agreement) as is standard on many open source projects.

_The purpose of a CLA is to ensure that the guardian of a project's outputs has the necessary ownership or grants of rights over all contributions to allow them to distribute under the chosen licence._

With more and more projects looking to build on top of Ethereum, it is important that we have appropriate licensing and most important CLARITY of licensing :-)

In particular, we have an opportunity for Ethereum to become a foundational piece of Hyperledger, following Vitalik's [very successful presentation to the Hyperledger Tech Steering Committee in April](http://www.coindesk.com/vitalik-buterin-addresses-hyperledger-possible-ethereum-integration/), but that cannot happen while we have ambiguity of licensing and copyright.

How fantastic would it be if Ethereum could become the basis of a "Linux-like-techbase for blockchain" which could be used as a de-facto standard for both public and private/consortium chains?

Anyway - first things first!

Before anything, though, I want to open the communication lines with all the contributors, so that you can be part of this process to get us to "known status".     I will include you all on this issue.

If you have contributed to cpp-ethereum, please could I ask that you add yourself to the Pirate Pad below with your Github login, name and your preferred e-mail address which you can be contacted at?    If you want to use a pseudonym, that is fine.    I just need to be able to talk to you all for now :-)

http://piratepad.net/g9A0NTQjcI

Thanks, everyone!
# SCRUB THAT!

Using the Wiki instead now - https://github.com/ethereum/webthree-umbrella/wiki/Contributors

**Comment by bobsummerwill** [comment]
@gavofyork, @chfast, @debris, @chriseth, @CJentzsch, @LefterisJP, @arkpar, @subtly, @yann300, @winsvega, @azawlocki, @LianaHus, @gluk256, @programmerTim, @caktux, @bobsummerwill, @guanqun, @giact, @cubedro, @danielhams, @obscuren, @xcthulhu, @Genoil, @onepremise, @josephyzhou, @CodeShark, @vbuterin, @msimovic, @alexvandesande, @autolycus, @jesuscript, @Mashatan, @wanderer, @SharpCoiner, @imifos, @Gustav-Simonsson, @fjl, @AronVanAmmers, @frewsxcv, @ivan1986, @nicksavers, @psalami, @jorisbontje, @bargst, @nejucomo, @austonst, @dreid93, @tymat, @etherninja

**Comment by bobsummerwill** [comment]
@artur-kink, @kaustavha, @dennismckinnon, @ryepdx, @pompomJuice, @larspensjo, @chulsupark, @kejace, @cdetrio, @jgabios, @eco, @heavyplayer2, @Erkan-Yilmaz, @sebilasse, @vipjeffreylee, @MelissaCole, @mquandalle, @holiman, @zelig, @programonauta, @csibbitt, @xeroc

**Comment by bobsummerwill** [comment]
Actually - let's use this Pirate Pad instance, to avoid a million notifications:

http://piratepad.net/g9A0NTQjcI

**Comment by frewsxcv** [comment]
I don't have enough time to read too much about this, but I agree to license my contributions under whatever license you want (I prefer [CC0](https://creativecommons.org/publicdomain/zero/1.0/)).

**Comment by bobsummerwill** [comment]
And more people from after the webthree-umbrella split:
@smartbitcoin, @mancoast, @kejace, @fossilet, @zant95, @larspensjo, @gcolvin, @SharpCoiner, @rainbeam, @moneroexamples, @area, @Legogris, @redsquirrel, @VoR0220, @Denton-L, @pipermerriam, @uberlaufer, @ethers, @ssonicblue, @raineorshine, @rainbeam, @michaltrzesimiech, @4tXJ7f, @BrainArchitect, @AlwaysBCoding, @MrChico, @OlegIakovlev, @mario02423, @u2.

**Comment by bobsummerwill** [comment]
Hey @frewsxcv,
Please can you add your Github login, name and e-mail address into http://piratepad.net/g9A0NTQjcI?   That's all I need for now.  Thanks!

**Comment by VoR0220** [comment]
I'm of the opinion (for whatever my opinion is worth) that Ethereum should stay in the MIT/GPL realm. Just my personal belief. That's all.

**Comment by bobsummerwill** [comment]
There is no real consideration of moving to anything other than mainstream [OSI-approved licenses](https://opensource.org/licenses), @VoR0220.

That would either mean sticking with GPLv3 or moving to a permissive license.    Originally only [MIT](https://opensource.org/licenses/MIT) was considered, but multiple knowledgable people have said to me .... _"For the love of god, go with [Apache 2.0](http://www.apache.org/licenses/LICENSE-2.0) not MIT"_ because of the patent-protection clause.

**Comment by LefterisJP** [comment]
Those of us who worked for the foundation, signed a document regarding this at some point ... what happened to that document?

**Comment by bobsummerwill** [comment]
Ahem ... yeah, @LefterisJP.
@chriseth has been looking around the Berlin office for that paperwork, with no success so far.
Which is a bit embarrassing, isn't it?   :-) 
So we'll probably have to do it all again.    I'm also unsure whether said paperwork ever made it out to the non-Foundation contributors.   @gavofyork would know best, I suppose.

**Comment by giact** [comment]
I am a non-Foundation contributor, and I can confirm that in August 2015 I received and signed a permission to switch from GPL to MIT

**Comment by bobsummerwill** [comment]
Good to know, @giact.   Thanks!

**Comment by cubedro** [comment]
me too. I signed it and sent it to Kelly Becker.

**Comment by guanqun** [comment]
Added to the privatepad, as someone mentioned, I also agree to license my contributions under whatever license you want.

**Comment by bobsummerwill** [comment]
POKE POKE, everybody, especially you ex and current Foundation folk!    Thanks.

**Comment by moneroexamples** [comment]
I just added myself. But used pseudonym instead of real name. Hope its ok.

**Comment by bobsummerwill** [comment]
Greetings, everybody!

See http://piratepad.net/g9A0NTQjcI, where I have now added entries for everybody.    Just need you to add your names and **preferred email**.

**Foundation and ex-Foundation people** - please can you guys reply!   The non-Foundation people are kicking our arses for this.    The main bit I am missing for the internal people is your preferred PERSONAL e-mail addresses.   Thanks!

**Comment by bobsummerwill** [comment]
Greetings, everybody!

I have had a boring few hours gathering some of this information myself, to save you the effort, and I now think that I have nearly all the contributor contact information which we need.

I have also looked in more detail at the specific repos, and am able to REMOVE various of the people I had originally tagged here, because their contributions have been to Solidity or other repos which WILL NOT end up in the reconstituted cpp-ethereum repo.

We now have 80 people on the list, 36 with over 100 LOCs and 44 with under 100 LOCs:

See https://github.com/ethereum/webthree-umbrella/wiki/Contributors.

So what am I still missing?    I am missing information on the following contributors.    If they are you, or if you have any information on these individuals (especially e-mail addresses), please do let me know, thanks!

**NOTE - No need for real names at this stage.   Not sure if those will become problematic later?  We'll deal with that when if/when is a problem.**
- @autolycus
- @azawlocki
- @CodeShark
- @Genoil
- @jesuscript
- @msimovic
- @programmerTim
- @wanderer
- @chulsupark
- @heavyplayer2
- @ijcoe6ru
- @jgabios
- @kejace
- @MelissaCole
- @pompomJuice
- @SharpCoiner

Also, please do check your own entry.   I might have old or incorrect information for you, if you didn't supply it on the earlier Pirate Pad yourself.

Best wishes!

**Comment by programonauta** [comment]
@bobsummerwill I filled the PiratePad, but my name isn't there. 
Name: Ricardo de Azevedo Brandao
e-mail: rbrandao.br@gmail.com

**Comment by bobsummerwill** [comment]
Hey @programonauta!

Added you back.   Sorry about that.     While rebuilding the more minimal and correct list here, both yourself and @sebilasse fell victim to being the ONLY people who had made contributions only to files in the root directory of webthree-umbrella, but not to any of the sub-modules, or to cpp-ethereum pre-split.

My optimization had a bug :-)    Thanks for the bug report!

**Comment by jonathanbmorley** [comment]
Hello,

Pretty sure all I did was fix a typo or some incidental grammar error… I
don't see my name on the list, which is fine. :) I trust you all are well,
and thanks for your efforts!

/jm (@mario02423)

**Comment by msimovic** [comment]
Hey, I am msimovic. Codeshark is Eric Lombrozo. I know a few others on that
list but names escape me right now.
On Jun 6, 2016 9:14 PM, "Bob Summerwill" notifications@github.com wrote:

Greetings, everybody!

I have had a boring few hours gathering some of this information myself, to
save you the effort, and I now think that I have nearly all the contributor
contact information which we need.

I have also looked in more detail at the specific repos, and am able to
REMOVE various of the people I had originally tagged here, because their
contributions have been to Solidity or other repos which WILL NOT end up in
the reconstituted cpp-ethereum repo.

We now have 80 people on the list, 36 with over 100 LOCs and 44 with under
100 LOCs:

See https://github.com/ethereum/webthree-umbrella/wiki/Contributors.

So what am I still missing? I am missing information on the following
contributors. If they are you, or if you have any information on these
individuals (especially e-mail addresses), please do let me know, thanks!

*\* NOTE - No need for real names at this stage. Not sure if those will
become problematic later? We'll deal with that when if/when is a problem.**
- @autolycus https://github.com/autolycus
- @azawlocki https://github.com/azawlocki
- @CodeShark https://github.com/CodeShark
- @Genoil https://github.com/Genoil
- @jesuscript https://github.com/jesuscript
- @msimovic https://github.com/msimovic
- @programmerTim https://github.com/programmerTim
- @wanderer https://github.com/wanderer
- @chulsupark https://github.com/chulsupark
- @heavyplayer2 https://github.com/heavyplayer2
- @ijcoe6ru https://github.com/ijcoe6ru
- @jgabios https://github.com/jgabios
- @kejace https://github.com/kejace
- @MelissaCole https://github.com/MelissaCole
- @pompomJuice https://github.com/pompomJuice
- @SharpCoiner https://github.com/SharpCoiner

Also, please do check your own entry. I might have old or incorrect
information for you, if you didn't supply it on the earlier Pirate Pad
yourself.

Best wishes!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
https://github.com/ethereum/webthree-umbrella/issues/530#issuecomment-224135026,
or mute the thread
https://github.com/notifications/unsubscribe/ABctMrwBqVajK0ZHD5DwFERBYIEk8vAMks5qJMXygaJpZM4Im2BU
.

**Comment by area** [comment]
My name and email address are incorrect - I'm happy to edit the wiki, but am concerned about simply deleting the details that are already there, which presumably belong to someone and came from somewhere. I didn't fill out the PiratePad (apologies!).

**Comment by bobsummerwill** [comment]
Hey @mario02423,
It looks like your contribution was to Solidity (https://github.com/ethereum/solidity/commits?author=mario02423), so would not be in-scope for the re-constituted cpp-ethereum which we are considering for re-licensing.    Good luck - no more badgering for you :-)

**Comment by bobsummerwill** [comment]
@area I gathered the data (wrongly!), so please either just edit the Wiki yourself or let me know the name/e-mail to use, and I will update accordingly.

@msimovic What e-mail address should I use for you?

**Comment by Souptacular** [comment]
Is @wanderer someone who has not given their real name? I know who they are and can ask them if they want to give their real name or not (most of us know them).

**Comment by bobsummerwill** [comment]
@Souptacular already added.

**Comment by azawlocki** [comment]
Hi Bob,

azawlocki is me, the name and the e-mail are correct.
I contributed to the evmjit repository only.

**Comment by bobsummerwill** [comment]
Thanks, @azawlocki.

164 times :-)    Thank you!   https://github.com/ethereum/cpp-ethereum/commits?author=azawlocki

The changes occurred before the EVMJIT repo was split off.

Looking at https://github.com/ethereum/evmjit/graphs/contributors, it's all the same people.

**Comment by chfast** [comment]
This is because the git subtree push/pull crap. I'm thinking about cleaning this up (by history rewrite).

**Comment by bobsummerwill** [comment]
Commented to @chfast's post at https://gitter.im/ethereum/cpp-ethereum?at=57574500c2a6e42f7e994d36, to avoid a discussion chain here which spams everybody with notifications.

**Comment by bobsummerwill** [comment]
FYI .... this is a useful site:
- https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)

Versus:
- https://tldrlegal.com/license/mit-license
- https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)

**Comment by bobsummerwill** [comment]
Hey @msimovic - please could you add an e-mail address for yourself to https://github.com/ethereum/webthree-umbrella/wiki/Contributors?  Thanks!

**Comment by bobsummerwill** [comment]
GREETINGS EVERYBODY!

So, as of Saturday 11th June we nearly all the information.

See https://github.com/ethereum/webthree-umbrella/wiki/Contributors.

I am only missing e-mail addresses for the following:
- @autolycus
- @CodeShark (Eric Lombrozo)
- @Genoil
- @jesuscript (Konstantin Kudryavtsev)
- @chulsupark (Chul Su Park?)
- @heavyplayer2 ("Heavy Player")
- @MelissaCole
- @pompomJuice ("Vern")
- @SharpCoiner

**Comment by bobsummerwill** [comment]
@/all **OK - MY C++ RE-LICENSING PROPOSAL ARTICLES ARE FINALLY READY**
- [Ethereum Everywhere](https://bobsummerwill.com/2016/07/12/ethereum-everywhere/)
- [C++ relicensing plan](https://bobsummerwill.com/2016/07/12/c-re-licensing-plan/)
- [Ethereum Apache 2.0 relicensing template (2016-07-11).doc](https://drive.google.com/open?id=1C5LEvZ5CrmxuZdBew2ChRUk5NK72Lp1q1wiZaG9ujko)

See also https://reddit.com/r/ethereum, but let's have any discussion [on Gitter](https://gitter.im/ethereum/cpp-ethereum).    Thanks, everyone!

Next step will be to give you all a few days to look through the articles and provisional "paperwork", and raise any objections or issues or thoughts you may have.     And then within a few days I hope to be in a position to start contacting you individually and to get either e-mail or DocuSign or paper signatures (TBD, still talking to IP lawyer).

NOTE:  I tagged more people on this issue than will end up being contributors to the codebase being relicensed, so if you only contributed to solidity, or mix, or web3.js or alethzero, you might not be in this list of people who I believe are the contributors for the code we are looking to relicense:

https://github.com/ethereum/webthree-umbrella/wiki/Contributors

Best wishes!

**Comment by bobsummerwill** [comment]
This issue was moved to ethereum/cpp-ethereum#3218
