### ISSUE TITLE
Cannot build with Visual Studio 2010

### ISSUE THREAD

**Issue by remyroy** [ethereum/webthree-umbrella#531]
According to [the documentation](http://www.ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/building-from-source/windows.html#pre-requisites), you need Visual Studio 2010 to build on Windows.

It used to work but that does not work anymore. There are a few related issues with this:
- The pre-built Boost library binaries on https://builds.ethereum.org/builds/windows-precompiled/ are compiled with Visual Studio 2013 (vc12). When you want to generate the solution with cmake and the `-G "Visual Studio 10 2010 Win64"` generator, it cannot find the Boost libraries for Visual Studio 10. It's looking for file names with a `vc100` in their name instead of the provided `vc120` like `libboost_thread-vc100-mt-1_55` instead of `libboost_thread-vc120-mt-1_55`.
- libweb3core now depends [on the `<chrono>` standard library](https://github.com/ethereum/libweb3core/blob/03944c60a4795ecc7bdbb2d4fb21f5f663e059db/libdevcore/CommonIO.h#L38) which was not part of Visual Studio 2010. Even if you have the proper Boost library binaries, the build fails to complete because of that. I believe it previously used the Boost version of that time library which is why it used to work.

The documentation might need to be updated to reflect that.

**Comment by remyroy** [comment]
I was mistaken. The documentation mention using VS Community 2013 Desktop.

**Comment by bobsummerwill** [comment]
Yeah - I haven't managed to work out WHY we supposedly need VC10 runtime libs.

@chfast has been working on a VS2015 upgrade for us, and we will be going live with that soon, at which point we will actually strip all the older stuff out of those instructions.

Anybody can get VS2015 Community edition on any of the OS versions, so we would just drop all the other stuff from the instructions.    Given that we need to host our own binaries for these external packages, it's not worth us even trying to support multiple VS versions.

So we'll end up only doing VS2015 against Windows 7 SDK (as min-OS-version), which should work on Windows 7, 8, 8.1, 10 and Windows Server 2012.

So did you get a working build now?   It was just that you were using VS2010 for the build, and then that didn't find boost version matching?

Sorry for your pain.   Should be a lot clearer soon.

**Comment by remyroy** [comment]
I'm still trying to build it. I have a lot of different errors and I'm still trying to figure them out.

**Comment by bobsummerwill** [comment]
OK - comment away as you go, and we'll get you to the other side!

**Comment by remyroy** [comment]
I just completed a successful build. I had to call `C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\x86_amd64\vcvarsx86_amd64.bat` first to setup the environment.

Sorry for this back and forth.

It would be nice to have official Windows binaries for Solidity published somewhere.

**Comment by bobsummerwill** [comment]
Yes, we're the process of completely revamping our CI and release flow, and reorganizing the repositories, to make exactly that simple/possible.

Sorry for the mess right now.

Glad you have some binaries.   Many people are using the browser solidity.
