### ISSUE TITLE
solidity tests via RPC

### ISSUE THREAD

**Issue by winsvega** [ethereum/webthree-umbrella#542]
- implement setChainParams in ethereum-console for eth --test 
- make solidity code checks through rpc calls to local test node

**Comment by chriseth** [comment]
This is not finished yet.

**Comment by chriseth** [comment]
Almost there! Needs some PRs in libethereum to be merged.

**Comment by bobsummerwill** [comment]
This issue can be closed now, can it, @chriseth?
