### ISSUE TITLE
Update Solidity build instructions

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#543]
At https://solidity.readthedocs.io/en/latest/installing-solidity.html#building-from-source.

They are out-of-date and out-of-sync with the main instructions, especially WRT to Homebrew.

**Comment by giact** [comment]
I tried cleaning up the Ubuntu part a bit: https://github.com/ethereum/solidity/pull/629

There's still some work to do (i.e. re-add the instructions for 14.04).

**Comment by bobsummerwill** [comment]
This issue was moved to ethereum/solidity#956
