### ISSUE TITLE
OS X - Can we switch the Mix binaries to be Debug?

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#546]
As a workaround for the Heisenbug, can we switch the OS X Mix binaries to be Debug?

See https://gitter.im/ethereum/cpp-ethereum-development?at=574f4d816bbc2d1d4df0560a

**Comment by bobsummerwill** [comment]
Adding @ktorn, @SorenPeterson and @sussegaduss, all of whom are currently hindered by the broken El Capitan Mix binaries, and can then verify this workaround.

**Comment by bobsummerwill** [comment]
See also https://github.com/ethereum/webthree-umbrella/issues/565 (Fix the Heisenbug!)

**Comment by SorenPeterson** [comment]
Sorry, but I don't quite understand what the workaround is. Will you explain it to me?

**Comment by bobsummerwill** [comment]
The workaround is something which **I** still need to do, and which this issue is tracking.

My workaround will be to switch our automation to use Debug configuration for our `Mix.app` file in the DMG, because that doesn't hit the Heisenbug.

I will be working on that today and will let you guys know when there is a DMG for you to try :-)

Sorry for the lack of clarity, @SorenPeterson!

**Comment by bobsummerwill** [comment]
See also  "Fix the Heisenbug!" - https://github.com/ethereum/webthree-umbrella/issues/565

**Comment by bobsummerwill** [comment]
Could you guys try this DMG, please?   Thanks!

http://52.28.164.97/job/ethbinaries-build/472/label=osx_elcapitan/artifact/webthree-umbrella/build/cpp-ethereum-osx-elcapitan.dmg

Or, for Yosemite ...

http://52.28.164.97/job/ethbinaries-build/472/label=osx_yosemite/artifact/webthree-umbrella/build/cpp-ethereum-osx-yosemite.dmg

**Comment by bobsummerwill** [comment]
Or better yet:
- https://builds.ethereum.org/cpp-binaries-data/develop/cpp-ethereum-osx-elcapitan.dmg
- https://builds.ethereum.org/cpp-binaries-data/develop/cpp-ethereum-osx-yosemite.dmg

**Comment by sussegaduss** [comment]
Hi all..

im not being able to download.. it downloads 2mb and then the connection get lost!
None of the links above works. All gets the same error.
Can you verify this?

**Comment by bobsummerwill** [comment]
Nope - all 4 are working for me right now.   Are you in a remote area?   Is your network usually reliable?

**Comment by sussegaduss** [comment]
Downloaded and still getting the same error... before it opens i get "quit unexpectedly" again...

**Comment by ktorn** [comment]
I successfully downloaded both El Capitan DMGs, but on both occasions Mix still crashes on startup with the same error.
Currently building from source with `cmake -DCMAKE_BUILD_TYPE=Debug` as you suggested in #562, but I guess it will run into the same issue (assuming that's what you did with the above DMGs).

**Comment by bobsummerwill** [comment]
Bah!   I see the issue now.   Sorry, guys.

There are multiple branches with very similar looking code, and the fix was in the wrong place.

Around the loop again.    Stay tuned, and I will give you a heads up when the DMGs are refreshed.

**Comment by bobsummerwill** [comment]
OK - these interim ones are ready again now ...

http://52.28.164.97/job/ethbinaries-build/472/label=osx_elcapitan/artifact/webthree-umbrella/build/cpp-ethereum-osx-elcapitan.dmg

http://52.28.164.97/job/ethbinaries-build/472/label=osx_yosemite/artifact/webthree-umbrella/build/cpp-ethereum-osx-yosemite.dmg

**Comment by ktorn** [comment]
Sorry to report that it still crashes.

The crash log shows that the thread number changed from 7 to 9 but it is still the same thread name `QThread` and still on the same call of the thread stack: `dev::eth::PathGasMeter::handleQueueItem()`

**Comment by bobsummerwill** [comment]
Ugh.   Bloody Heisenbug.    Thanks for testing, @ktorn.

CC @VoR0220, @chriseth.

I have switched the OS X binaries to Debug, but we're still not happy.    So I will close this issue, and add the people from this thread onto the Heisenbug issue.

**Comment by SorenPeterson** [comment]
It doesn't help everyone else... But that link (https://builds.ethereum.org/cpp-binaries-data/develop/cpp-ethereum-osx-elcapitan.dmg) worked for me. Thanks so much.

**Comment by bobsummerwill** [comment]
Thanks for that follow-up, @SorenPeterson.

Please could you try again, @ktorn, with that "final location" DMG?    It _should_ work :-)

**Comment by ktorn** [comment]
Unfortunately it doesn't work for me. Still crashes.

```
Thread 7 Crashed:: QThread
0   libevmasm.dylib                 0x0000000108779259 dev::eth::PathGasMeter::handleQueueItem() + 2793
```

**Comment by bobsummerwill** [comment]
@ktorn Please can you do a `brew update` and `brew upgrade`, please?    You might be out-of-sync on those other packages compared to us.

**Comment by ktorn** [comment]
`brew update` and `brew upgrade` all done. `brew doctor` reports no warnings. Latest DMG still crashes, on 2 machines with El Capitan.
In the mean time I'm resorting to running it under Ubuntu in a VBox VM.

**Comment by bobsummerwill** [comment]
Alrighty ... sorry our voodoo magic didn't work for you, @ktorn.

We've just got to find this Heisenbug and kill it!
