### ISSUE TITLE
Linux - geth attach broken on Ubuntu Trusty?

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#547]
I have verified on various occasions that `geth attach` onto an `eth` node works correctly on OS X El Capitan (my primary working platform).    That only started working with `geth-1.4.x`, but does continue to work.

Got the following bug report today ...

oh yes, and what happens is that geth.ipc file is written into .ethereum directory; in case of geth it contains some valid text, but with eth it is an empty file. So the issue must exist and probably indeed specific to ubuntu.

**Comment by chriseth** [comment]
`geth.ipc` is a unix socket, not a regular file. It should not contain any text.

**Comment by bobsummerwill** [comment]
This was resolved, I believe.
