### ISSUE TITLE
ecRecoverInfinityTestFiller

### ISSUE THREAD

**Issue by ghost** [ethereum/webthree-umbrella#55]
Moved here from [cpp-ethereum](https://github.com/ethereum/cpp-ethereum/issues/2591)

correct test filler ecRecoverInfinity
blockChain emptyMining Test

**Comment by chriseth** [comment]
@winsvega can you comment on whether this can be closed?

**Comment by bobsummerwill** [comment]
This issue was moved to ethereum/cpp-ethereum#3082

**Comment by winsvega** [comment]
I guess. 
what was this issue about? 
I done see such a test filler. `ecRecoverInfinity`
is it about internal code coverage?  
then yes. we changed that a long time ago
