### ISSUE TITLE
Linux - OpenCL detection is unreliable

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#557]
Multiple people have hit issues with OpenCL detection in their Linux builds.

I don't know if it is distro-specific?   Are all the issues occurring on non-Ubuntu distros?

Need to investigate.

See, for example, https://github.com/ethereum/webthree-umbrella/issues/552#issuecomment-224146290

And I should search from the previous reports of this and see if I can spot a pattern.

**Comment by bobsummerwill** [comment]
So, as per https://github.com/ethereum/webthree-umbrella/issues/552#issuecomment-224146290, @wainersec, the issue looks like it might be related to the syntax of the command-line, do you think?

Because `-lname` usually doesn't include a fully qualified path, does it?    Instead, library paths are usually added, and the `-lname` are usually without paths.

Maybe different versions of GGC or Clang can or cannot cope with this.

Could you look at the fully qualified command-line which is within the generated makefiles?     Are other external libraries being composed differently?

**Comment by bobsummerwill** [comment]
Hmm - yeah - check this out:

https://github.com/ethereum/webthree-helpers/blob/develop/cmake/UseOpenCL.cmake#L9

That "smells" like the problem.    Perhaps that workaround is OK for Ubuntu but broken for other distros?

The command-line composition likely works in a different way when not "hacked in" like this.

Could you try removing that conditional?

So replace:

```
    if ("${CMAKE_SYSTEM_NAME}" MATCHES "Linux" AND ETHASHCL)
        # workaround for https://github.com/ethereum/alethzero/issues/69
        # force linking to libOpenCL as early as possible
        target_link_libraries(${TARGET} "-Wl,--no-as-needed -l${OpenCL_LIBRARIES} -Wl,--as-needed")
    else()
        target_link_libraries(${TARGET} ${OpenCL_LIBRARIES})
    endif()
```

With

```
target_link_libraries(${TARGET} ${OpenCL_LIBRARIES})
```

**Comment by bobsummerwill** [comment]
CC @chfast.    Hello, Pawel!

This is in relation to https://github.com/ethereum/alethzero/issues/69.

CC @chriseth.    So funnily enough it looks like we have found the root cause here of the "sometimes OpenCL detection doesn't seem to work on Linux" issue which I was pondering changing the default on yesterday.

**Comment by w-sec** [comment]
Just replaced those lines but it is still not working. Trying workarround.

**Comment by bobsummerwill** [comment]
You would need to replace those lines, re-run cmake, then re-run make.

If you got the same issue, I would suspect that you were using the same makefile.

**Comment by w-sec** [comment]
No, used new one.

**Comment by bobsummerwill** [comment]
See https://github.com/ethereum/webthree-umbrella/issues/557 too.

**Comment by w-sec** [comment]
I think the error is dragged from before, at FindOpenCL.make. OpenCL_LIBRARIES and OpenCL_INCLUDE_DIRS are not getting defined I think.

**Comment by bobsummerwill** [comment]
And you got the exact some error message?    About the -l/usr/... ?
That doesn't sound right.    Could you try just blowing away the whole build directory please, and then share the gist?

**Comment by w-sec** [comment]
Yes, same error. I tried deleting the directory and cloning again. https://gist.github.com/wainersec/296d651d58f663ed150f27cb05a14d49

**Comment by bobsummerwill** [comment]
OK - so the info we are still missing is the full command-line which make is trying to execute.

Please can you grep your makefiles, and try to find the exact fully-expanded command-line?     Or I think there is a make "flag" for showing the command-lines it would execute, rather than running them, right?

That would be even better.

**Comment by w-sec** [comment]
This is the gist for the --recon flag of make (the function you just mentioned) https://gist.github.com/wainersec/f865721f2866a50b3ff22b7f30bd17f3

**Comment by w-sec** [comment]
Just found the full command: 
`/usr/bin/c++  -fPIC -std=c++11 -fpermissive -O2 -g -DETH_RELEASE  -shared -Wl,-soname,libethash-cl.so -o libethash-cl.so CMakeFiles/ethash-cl.dir/ethash_cl_miner.cpp.o -lcryptopp ../libethash/libethash.so -Wl,--no-as-needed -l/usr/lib64/libOpenCL.so -Wl,--as-needed -Wl,--no-as-needed -l/usr/lib64/libOpenCL.so -Wl,--as-needed -lcryptopp -Wl,-rpath,/home/limechain/Dev/webthree-umbrella/build/libethereum/libethash:`

It is found in libethereum/libethash-cl/CMakeFiles/ethash-cl.dir/link.txt

**Comment by bobsummerwill** [comment]
Oh, delightful ... it looks like that workaround got cut-and-pasted in two places.

See https://github.com/ethereum/webthree-helpers/pull/196/files.    I have updated the PR to fix both sites.    Please could you try applying both changes, and re-generating from scratch?   Thanks!

And you will need the `cmake -DGUI=0`

**Comment by w-sec** [comment]
Yay! ld error is gone. New PR works perfect. But just got another error, it has to be with devcrypto and solidity. Should I create a new issue? https://gist.github.com/wainersec/6ba3b7a9ca8fb86e8af8581c58486c7f Thanks.

**Comment by bobsummerwill** [comment]
Let's head back to your original issue.
