### ISSUE TITLE
Ethminer Problem Since 1.2.6

### ISSUE THREAD

**Issue by ghost** [ethereum/webthree-umbrella#558]
Since the update 1.2.6 i can't mine anymore ? My friends have the same issu on his rig too ? Someone have a solution ? Thanks

Ubuntu 14.04

I use ethermine.org pool with the stratum proxy. I try to mining using the standard ethminer it's not working. I try to reboot it's not working. I try with the last 2 other update since 1.2.6 not working

I have 5 MSI R9 390x

Some other have the same issu i post on ethreum community forum :
https://forum.ethereum.org/discussion/7380/mining-problem-since-last-update

![o181n68q6jrs](https://cloud.githubusercontent.com/assets/19805549/15872144/e9f7268c-2cc5-11e6-8948-d0edefa8c3d2.png)

**Comment by bobsummerwill** [comment]
Hey @jtremblaytdst,

I would recommend that you switch to @Genoil's http://github.com/Genoil/cpp-ethereum, which is better supported than our official ethminer.

I am planning to attempt to backport the Genoil changes to our codebase (https://github.com/ethereum/webthree-umbrella/issues/315), but in the meantime, if you have having problems then I would strongly recommend that you "jump ship".

**Comment by ghost** [comment]
Thank you

**Comment by bobsummerwill** [comment]
See also https://gitter.im/ethereum/mix?at=575723d1666c4ff55aebfea9.

**Comment by ross-p** [comment]
I have the same issue, as of 1.2.7.  I know 1.2.5 was stable, but I didn't try 1.2.6.

<img width="662" alt="minerbroken" src="https://cloud.githubusercontent.com/assets/4956475/15915225/6244967a-2d9c-11e6-8280-9b46203baba9.png">

Will give @genoil's a try.

EDIT: Genoil's is working great.

**Comment by bobsummerwill** [comment]
Thanks for the confirmation, @ross-p.     That is very regrettable :-(

**Comment by wariner84** [comment]
Same here.

1.2.5 not problem
1.2.7 and 1.2.6 can't mine

Genoil's Working

I have 3 rigs ubuntu 14.04 with 10 r9 380x

**Comment by bobsummerwill** [comment]
Fix brewing at https://github.com/ethereum/libethereum/pull/281.

**Comment by bobsummerwill** [comment]
Just prepping v1.2.8 binaries.

**Comment by bobsummerwill** [comment]
Thanks, guys!

See https://twitter.com/BobSummerwill/status/741450414290149376.

**Comment by ross-p** [comment]
LOL!  Nice one @bobsummerwill :)

**Comment by wariner84** [comment]
1.2.8 to me it does not solve..somebody else?

update, I noticed that:

after PPA update 1.2.8 ethminer remains to version 1.2.7:

$ ethminer --version
ethminer version 1.2.7
Build: Linux/g++/Interpreter/RelWithDebInfo

**Comment by siemien** [comment]
@wariner84 I have the same problem after update, today i try upgrade ethimner by I still have 1.2.7 version... Does any one have old deb binaries of the last stable version? I also try genoil ethminer, but it not work for me

**Comment by debris** [comment]
I built ethminer from source. Everything seems to work on `1.2.8`.

**Comment by siemien** [comment]
@debris Can you show me how to do it? Step by step?

**Comment by debris** [comment]
```
git clone --recursive git@github.com:ethereum/webthree-umbrella.git
cd webthree-umbrella
mkdir build && cd $_
cmake ..
make -j 8 ethminer
```

then run:

```
./libethereum/ethminer/ethminer
```

**Comment by siemien** [comment]
Thank you! I just find this guide http://ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/building-from-source/linux.html sorry for my derp question :D

**Comment by bobsummerwill** [comment]
Sorry, all ... see https://github.com/ethereum/webthree-umbrella/issues/583.

Building from source on develop will work just fine, but the release branch wasn't refreshed correctly, so the published binaries got old content.

I am about to crank the handle on that again with a new release.    My bad.   And very annoying.

**Comment by wariner84** [comment]
PPA updated, now ethminer version 1.2.9, everything works perfectly.

Thank you

**Comment by bobsummerwill** [comment]
Hurrah!   I am delighted to hear that, @wariner84 ;-)
