### ISSUE TITLE
using openCL even if --cpu specified 

### ISSUE THREAD

**Issue by ghost** [ethereum/webthree-umbrella#56]
Moved here from [cpp-ethereum](https://github.com/ethereum/cpp-ethereum/issues/2583)

in case cpu mining 
still looking for openCL

running: 

```
./eth --cpu --upnp off --peers 50 -r 111.0.0.1 --listen 10101 -t 2 --mining on
```

halts with:

```
[OPENCL]:No OpenCL platforms found
[OPENCL]:clEnqueueWriteBuffer(-36)
```

**Comment by bobsummerwill** [comment]
This issue was moved to ethereum/cpp-ethereum#3083
