### ISSUE TITLE
OS X - Homebrew now has Qt 5.6.1.   Has that broken anything?

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#574]
So the Qt version in Homebrew has been updated from 5.6 to 5.6.1 which might well have broken some of our horrible hard-coded scripts to ensure that the `.app` files are self-contained.

See https://github.com/ethereum/webthree-helpers/blob/develop/cmake/scripts/macdeployfix.sh.

We wouldn't see that in Jenkins because there is nothing which does a `brew update` and `brew upgrade`.    I do have those in my TravisCI setup, but am not building the Qt apps there.

The only way to test this right now is on my local machine, and it may be the case that the Mix and AlethZero binaries have become broken for SOME people as a result of this Homebrew update.

**Comment by devops398** [comment]
not sure if it related to Qt, but I have 5.6.1 and my build is broken, I followed all your instructions in previous posts, but no luck.. If I try to run provided Mix binary - it just crashes on start.. here is more info about what I tried to do:
https://github.com/ethereum/mix/issues/320#issuecomment-226398410

**Comment by bobsummerwill** [comment]
Aha, thanks for the heads-up, @igorlimansky.

That verify_app error which you see will be a direct consequence of horrific technical debt which I added out of expedience in https://github.com/ethereum/webthree-helpers/commit/a83c575aad4f6fd4b2dda0b293048b1e782a2173.

So the bad news is that this horrific hack has stopped being correct between 5.6 and 5.6.1 and needs rehacking (or better yet the root cause needs resolving).     The good news is that the fact that the verify_app fails doesn't mean that the `.app` is unusable.    It just means that it is not self-contained and transportable to somebody else's machine, because some of the Qt references are pointing to Homebrew install locations, rather than to the copies of those dylibs, etc within the `.app` itself.

So thanks for highlighting this.

But it won't be why Mix crashes.   That will be "The Heisenbug" (https://github.com/ethereum/webthree-umbrella/issues/565).

If you build the Debug configuration, you may get away with it :-)

**Comment by balopat** [comment]
I can reproduce unfortunately the verify_app error, it's happening for me on 10.11.5 (15F34) El Capitan.

The verify_app error comes up with homebrew installation at the end.
I switched to "develop" branch from the temporary git repo from webthree-umbrella which was created by hombrew, ran the `make` commands which succeeded (with `make -j2` at the end) and `make install` failed with the following error:

```

-- info='external prerequisites found:
f='/Users/balopat/Library/Caches/Homebrew/cpp-ethereum--git/build/alethzero/alethzero/AlethZero.app/Contents/MacOS/AlethZero'
external_prereqs='/usr/local/Cellar/qt5/5.6.1-1/lib/QtCore.framework/Versions/5/QtCore;/usr/local/Cellar/qt5/5.6.1-1/lib/QtGui.framework/Versions/5/QtGui;/usr/local/Cellar/qt5/5.6.1-1/lib/QtWidgets.framework/Versions/5/QtWidgets;/usr/local/lib/libsnappy.1.dylib;/usr/local/opt/dbus/lib/libdbus-1.3.dylib'
'
-- 
CMake Error at /usr/local/Cellar/cmake/3.5.2/share/cmake/Modules/BundleUtilities.cmake:975 (message):
  error: verify_app failed
Call Stack (most recent call first):
  alethzero/alethzero/cmake_install.cmake:34 (verify_app)
  alethzero/cmake_install.cmake:33 (include)
  cmake_install.cmake:37 (include)

make: *** [install] Error 1
```

What can I do to get around it? I see ethereum/webthree-helpers#105 has a hack-of-hack fix but somehow it might have not been included in the latest versions or we regressed? I cloned the whole umbrella repo fresh (as per the instructions) too - that didn't help either, it's not a sudo issue either.

Also - running it from the built app directly (`open /Users/balopat/Library/Caches/Homebrew/webthree-umbrella/build/mix/./Mix-ide.app/`) results in a waiting Mix-ide - no GUI appears, not sure why is that? It doesn't crash though, so it's not the heisenbug, it just brings up the menu, does nothing else.

![image](https://cloud.githubusercontent.com/assets/635073/16506889/a580c7f2-3ef3-11e6-8a58-e0c1fd1448af.png)

**Comment by bobsummerwill** [comment]
So yes, you WILL get this issue in a build-from-source.     The hack-of-hack fix is for Qt 5.6.0 and it looks like some paths will need updating in the hack-of-hack to get past the verify_app.

That only stops the install step, though, not running from the built copy, as you show above.

So ... what we have here is, I believe just symptoms of issues tracked elsewhere.

And as for your Mix issue, I am afraid I don't have an answer there, but would suggest that you ask on the Mix gitter channel.

Best wishes and thanks for all the useful details!

I'll close this issue when we address the verify_app breaks.

Other option - use DMG from https://github.com/ethereum/webthree-umbrella/releases/tag/v1.2.9.

**Comment by bobsummerwill** [comment]
So, @balopat, seeing your comments from the other issue, if you do have a go at hacking the hack-on-a-hack so that it works for 5.6.1, I would be delighted to merge that PR.

There is another issue tracking that we MUST fix that stuff properly, but a quick-fix would be handy too.

**Comment by balopat** [comment]
Thanks @bobsummerwill for the explanation!
I don't have the quick fix yet, if I can come up with something, I'm more than happy to share as a PR (it's not "quick" for me as I am new to pretty much the whole stack :)).

The DMG does crash actually as soon as I want to create a new project (https://gist.github.com/balopat/f8a10783ff1b42410118c56c7abd3f75) but that might be something I should actually mention in https://github.com/ethereum/mix/issues/320  instead. 

I have one more clue for the empty start behavior which might suggest that it is related to the build: These are the app logs if I directly open the built binary, at the end the last line seems odd but maybe I'm doing something wrong: 
https://gist.github.com/balopat/59d7664513d0ed106dbe4a840db6d11f

```
QQmlApplicationEngine failed to load component
qrc:/qml/Application.qml:-1 File not found
```

**Comment by bobsummerwill** [comment]
Yes, I would take your Mix runtime issues to the other ticket.

I haven't done any work on Mix myself, so I am afraid I have nothing useful to add to that :-)

**Comment by bobsummerwill** [comment]
Mix and AlethZero are now retired, so all this fixup code has gone.
