### ISSUE TITLE
WIndows - 1.2.8 installer EXE is failing integrity check

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#577]
https://www.reddit.com/r/ethereum/comments/4njkrc/released_cppethereumv128_on_the_trail_of_the/d44hb19?context=3

As per @rfikki.

**Comment by chriseth** [comment]
I am pretty sure that this is not a new issue. "Antivirus" software has always flagged our binaries, probably because of mining code or the bitcoin secp256k1 library.

**Comment by rfikki** [comment]
![windows128error](https://cloud.githubusercontent.com/assets/1055929/15985063/2a86b760-2fa7-11e6-9a10-b37d551ae8e5.PNG)

**Comment by rfikki** [comment]
I don't believe the above error has anything to do with my anti-virus. I downloaded the file several times and it looks to me like it is corrupted. I have not had anti-virus problems previously with prior downloads. I have been able to install most previous versions without this error.

**Comment by bobsummerwill** [comment]
Yeah - I just tried it, and the file is just plain truncated.    Happily it is only the version on Github which got truncated.   The Jenkins output is just fine, so I am reuploading that to Github now.

**Comment by bobsummerwill** [comment]
OK -> https://github.com/ethereum/webthree-umbrella/releases/download/v1.2.8/cpp-ethereum-windows-v1.2.8.exe.

**Comment by bobsummerwill** [comment]
And I've installed it, and it's working.   Thanks, @rfikki!
