### ISSUE TITLE
Ubuntu - 1.2.8 PPAs now showing up yet.

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#578]
https://twitter.com/awrelllRo/status/741513465848811520

I hadn't run the PPA release target, only PPA develop.

Now running ... http://52.28.164.97/job/ppa-build-release/39/

**Comment by bobsummerwill** [comment]
So, looking at the log for Xenial for that manual release PPA I started yesterday, @chriseth:

http://52.28.164.97/job/ppa-build-release/39/debplatform=xenial/console

You had mentioned before about needing to register a "public key".    Are you talking about a PGP public key for the new e-mail address which we would register?   Looks like something maybe isn't even quite right with the setup for `build@ethdev.com` anyway.    Also, I don't see where that is set up either, as an admin.

I think that you need to get the ownership of the team re-assigned to you by @msimovic.   Hey Marko!

And then we can start working it from there.

Is it your understanding, @chriseth, that the PPA uploads are failing for some reason, but that the only log/record of that is an email to that e-mail account which we don't have access to?    How have you unstuck these in the past?

**Comment by chriseth** [comment]
Uploading now. Actually the job has been broken longer now and I already uploaded the packages "manually" for 1.2.7.

Note that we explicitly do NOT require group ownership, although it would be nice to get that.

I guess we should just create a ppa-creation job on something like travis-ci and forget about the jenkins job.

And yes, we just need to create a now launchpad user, associate a PGP key with that account, upload it to launchpad, store it encrypted in e.g. travis and move the job over.

**Comment by siemien** [comment]
Guys after update I still have 1.2.7 version of ethminer, why? Did I do something wrong? :(
How long it will take, after some one upload new binaries into repo? I hope that will be soon :)

**Comment by chriseth** [comment]
So it seems that that ethminer binary in the 1.2.8 package still reports "1.2.7" as its version.

**Comment by siemien** [comment]
Yes, I just report this, the 1.2.8 binarry is availble soon :)


W dniu poniedziałek, 13 czerwca 2016 chriseth <notifications@github.com>
napisał(a):
> So it seems that that ethminer binary in the 1.2.8 package still reports
"1.2.7" as its version.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci3.googleusercontent.com/proxy/BIUAMF1whYI-j4TV62kZTzmCnKMySK0RpcyhHfHPZhL0wRVARAZrFxhWgh-a1bgFEQHjb1VH0Ohsd3FOJluKUyPstGyTHygGhuz4gtp3-jVUJzE0l9XnrLBSTDXe18T3-dNeybz7oD4pDsupDL55d9AYoI2BeA=s0-d-e1-ft#https://github.com/notifications/beacon/AS_LoVAidSVZsx_Tj2Rvbg01pNEMlBctks5qLWm2gaJpZM4Izfcp.gif
>

**Comment by siemien** [comment]
Please Update repo

**Comment by bobsummerwill** [comment]
Superceded by https://github.com/ethereum/webthree-umbrella/issues/583.
