### ISSUE TITLE
DVE-2015-0099 AES CTR man-in-the-middle through keystream reusage

### ISSUE THREAD

**Issue by ghost** [ethereum/webthree-umbrella#58]
Moved here from [cpp-ethereum](https://github.com/ethereum/cpp-ethereum/issues/2573)

See: https://github.com/ethereum/devp2p/issues/32

Separate keys need to be used for each stream.

**Comment by bobsummerwill** [comment]
This issue was moved to ethereum/cpp-ethereum#3084
