### ISSUE TITLE
macOS El Capitan - Synchronizing AlethZero fills up hard drive and crashes

### ISSUE THREAD

**Issue by alper** [ethereum/webthree-umbrella#580]
The past three versions for me on El Capitan when trying to synchronize the network fill up my hard drive and then crash out. I'm pretty sure this is not supposed to happen.

**Comment by bobsummerwill** [comment]
Indeed it is not, but if you are having any issues with AlethZero, I would just recommend that you stop using it.

It is deprecated and will be removed very soon.

Try some of the alternatives listed at http://solidity.readthedocs.io/en/latest/.

Best wishes!

**Comment by alper** [comment]
I am trying to move some funds out of AlethZero to Wallet but for the transaction to go through I need to be up to date?

I just hoped this software tool might be in a stable state before it's abandoned so people can responsibly get off of it.

**Comment by bobsummerwill** [comment]
Did you try @chriseth's suggestion about copying the keys, and with just that single manual case-change needed?    I cannot find that now.

Was it on Reddit, perhaps?    I don't see it on Gitter.

**Comment by alper** [comment]
I think that was on Reddit but I couldn't really figure out what that meant.

With lots of restarting I'm now approaching a full sync with my AlethZero which is in fact filling up my hard drive. Various ethereum related files take up some 20G of space. Is that correct?

**Comment by bobsummerwill** [comment]
Yes.   It will be about that size, yes.

What block is the sync up-to?   There are 1,710,000 blocks or so.   See https://ethstats.net/.

**Comment by bobsummerwill** [comment]
Where did you get to on this, @alper?

**Comment by alper** [comment]
I think I got it to sync but didn't manage to complete the transfer. Never mind.

**Comment by bobsummerwill** [comment]
Sorry :-(
