### ISSUE TITLE
Linux - Investigate 'snap' package format

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#590]
So Ubuntu 'snap' packages are usable on Ubuntu*, Debian, Arch, Fedora already and are being validate on CentOS, Elementary, Gentoo, Mint, OpenSUSE, OpenWrt and RHEL.

That is hugely interesting to me.

https://insights.ubuntu.com/2016/06/14/universal-snap-packages-launch-on-multiple-linux-distros/

Perhaps we have a path to a near-universal binary delivery format for Linux distros here?

What needs to be installed for snap packages to be installable?   Will support be available for older and LTS versions of the distros?

**Comment by LefterisJP** [comment]
This is obviously of huge interest to us at slock.it too! Commenting to follow the issue :)

**Comment by nerdralph** [comment]
They look a lot like docker containers, which is good and bad.  Good is the portability (since the package contains its dependencies), but the bad part is bloat.

I think it would be better to get static linking working with all the non-system libs.  All Linux distros in the last 5 years should have libc6, so it should be possible to keep libc dynamically linked, if linking it statically increases the size too much.

**Comment by bobsummerwill** [comment]
Yes, you could be right.

The good news is that static linking is well underway (https://github.com/ethereum/webthree-umbrella/issues/495) and is a priority for my own cross-builds too (http://github.com/doublethinkco/cpp-ethereum-cross) because just GLIBC differences are a killer there.

See https://github.com/doublethinkco/cpp-ethereum-cross/issues/20#issuecomment-168243356.

I have heard that glibc doesn't really support static linkage, so was considering musl as the most likely solution there, following its successful use for a static binary on Alpine.     Beyond that, versioning of GLIBC is an issue.   Tizen 2.3, for example, for the Gear S2 smartwatch, only has a GCC 4.6.1 era glibc.

But yeah - an all-in-one executable makes deployment trivial.   That's what `geth` does, as go-lang does everything statically, I believe.

I am relatively new to Linux development, having been Windows-hosted for many years, and the dynamic linkage pattern endemic to Linux does really bother me.     It really feels like it trying to solve problems of a different era.    Windows apps (especially .NET) have been self-contained for years, and side-by-side installation is an expectation even when using assembly caches.

Having executables pointing to a hardcoded `/usr/` path, with symlinks pointing to .SO files, and those being globally updated just feels horribly dangerous.

**Comment by nerdralph** [comment]
It's getting a bit off-topic, but you are right about it solving a long-ago problem.  With shared libs and demand-paged loading, 20 years ago Linux could perform well with 8MB of RAM, while Windows was barely usable with 8MB.
However some things need to be shared for functionality; i.e. auth stuff like libpam.

**Comment by bobsummerwill** [comment]
This issue was moved to ethereum/cpp-ethereum#3179
