### ISSUE TITLE
OS X - We *must* fix the Jenkins test failures

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#593]
They are likely issues within the automation more than issues with the code itself (or maybe a mixture).

But we need to get them running cleanly.    Without that, our automated test infrastructure is of little value at spotting NEW test breaks.

There is also the issue of getting reliable automation for tests on Windows, which @winsvega is working towards, with the approach there being to use Appveyor.    Is there a specific issue we can link for that, @winsvega?   Thanks!

**Comment by bobsummerwill** [comment]
See https://github.com/ethereum/libethereum/pull/290, which is a NULL PR which I just created, so we can see exactly what the status is of the automated tests at HEAD.

**Comment by bobsummerwill** [comment]
The OS X [El Capitan tests](http://52.28.164.97/job/project-test/label=osx_elcapitan/2785/console) are hitting an issue with the Jenkins xUnit plugin failing to parse the XML results file:

```
ETHTESTS - INFO: Will run test file solidity/build/test/soltest for project "libethereum".
Build step 'Conditional step (single)' marked build as failure
[Execution node] check if [osx_elcapitan] is in [[master, osx_elcapitan, osx_yosemite]]
Regular expression run condition: Expression=[webthree|libethereum|solidity], Label=[libethereum]
Run condition [And] enabling perform for step [[Publish xUnit test result report]]
[xUnit] [INFO] - Starting to record.
[xUnit] [INFO] - Processing BoostTest-1.x (default)
[xUnit] [INFO] - [BoostTest-1.x (default)] - 5 test report file(s) were found with the pattern '*_results.xml' relative to '/Users/jenkins/home/sharedspace/libethereum/label/osx_elcapitan' for the testing framework 'BoostTest-1.x (default)'.
[xUnit] [ERROR] - The result file '/Users/jenkins/home/sharedspace/libethereum/label/osx_elcapitan/libethereum_results.xml' for the metric 'BoostTest' is not valid. The result file has been skipped.
```

... which looks like it is a [known issue](https://issues.jenkins-ci.org/browse/JENKINS-22268) with that Jenkins plugin.

**Comment by bobsummerwill** [comment]
Hmm.   Interesting.    See [latest test run](http://52.28.164.97/job/project-test/2815/), which is now clean on Ubuntu and on Yosemite, but not on El Capitan.

Might we have different Boost versions on El Capitan and Yosemite machines, purely accidentally, because of timing of Homebrew updates?

**Comment by chriseth** [comment]
Closing after death of jenkins.
