### ISSUE TITLE
ctrl-c closes Mix-Ide on Linux instead of copy text

### ISSUE THREAD

**Issue by o0ragman0o** [ethereum/webthree-umbrella#595]
ctrl-c appears to be the only function to copy text, however on Linux it closes Mix-Ide.

**Comment by bobsummerwill** [comment]
This won't be fixed, because Mix is not being supported anymore.
See https://blog.ethereum.org/2016/07/08/c-dev-update-summer-edition/ for information on the mix -> remix plans.
