### ISSUE TITLE
geth attach doesn't work with eth (OSX El Capitan)

### ISSUE THREAD

**Issue by programonauta** [ethereum/webthree-umbrella#596]
I’ve run `eth —morden` and in other terminal tryed `geth attach`, as a response I got:

```
Fatal: Unable to attach to remote geth: dial unix /Users/rbrandao/Library/Ethereum/geth.ipc: connect: no such file or directory
```

**Comment by dearlordylord** [comment]
I have the same issue on newly installed with `bash <(curl -L https://install-geth.ethereum.org)` geth.

**Comment by programonauta** [comment]
The same installation on Yosemite works fine

**Comment by blake41** [comment]
I got this to work by doing geth attach ipc:location/of/ipc/file.ipc

**Comment by bobsummerwill** [comment]
This issue was moved to ethereum/cpp-ethereum#3181
