### ISSUE TITLE
no .a for libdevcrylto

### ISSUE THREAD

**Issue by nerdralph** [ethereum/webthree-umbrella#598]

**Comment by nerdralph** [comment]
Cant see a way to edit, so I'll add the details in the comment.
Libraries should have both .so and .a, but libcryptopp ppa only has a .so.

**Comment by bobsummerwill** [comment]
Sorry - looks like I missed this while I was on vacation and nobody picked it up.

I assume this is on Ubuntu?

Yeah - generally we are dynamic-libraries for everything right now.   Which sucks, IMHO.

Hence the work in https://github.com/ethereum/webthree-umbrella/issues/495.

I think ultimately, our best delivery mechanic will be complete static executables, built on Alpine with musl, which "just work" on any distro.

You know that libcryptopp is something we use, not build ourselves, right?

Source code is at ... https://www.cryptopp.com/

So what you report is expected and correct.    Thanks!
