### ISSUE TITLE
OS X - Homebrew upgrade is broken

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#599]
## Posted by @CodingAnarchy as ... https://github.com/ethereum/homebrew-ethereum/issues/76

Updating cpp-ethereum to version 1.2.9 results in the following failure:

```
==> Upgrading ethereum/ethereum/cpp-ethereum
==> Installing dependencies for ethereum/ethereum/cpp-ethereum: libmicrohttpd
==> Installing ethereum/ethereum/cpp-ethereum dependency: libmicrohttpd
==> Downloading https://homebrew.bintray.com/bottles/libmicrohttpd-0.9.50.el_capitan.bottle.tar.gz
######################################################################## 100.0%
==> Pouring libmicrohttpd-0.9.50.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/libmicrohttpd/0.9.50: 46 files, 956.4K
==> Installing ethereum/ethereum/cpp-ethereum
==> Cloning https://github.com/ethereum/webthree-umbrella.git
Updating /Users/vision/Library/Caches/Homebrew/cpp-ethereum--git
==> Checking out branch develop
Synchronizing submodule url for 'evmjit'
Synchronizing submodule url for 'deps'
==> cmake -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/cpp-ethereum/1.2.9 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -
==> make
==> make install
Last 15 lines from /Users/vision/Library/Logs/Homebrew/cpp-ethereum/03.make:
-- info='external prerequisites found:
f='/tmp/cpp-ethereum-20160621-98728-1dj3aun/alethzero/alethzero/AlethZero.app/Contents/MacOS/AlethZero'
external_prereqs='/usr/local/Cellar/qt5/5.6.1/lib/QtCore.framework/Versions/5/QtCore;/usr/local/Cellar/qt5/5.6.1/lib/QtGui.framework/Versions/5/QtGui;/usr/local/Cellar/qt5/5.6.1/lib/QtWidgets.framework/Versions/5/QtWidgets;/usr/local/lib/libsnappy.1.dylib;/usr/local/opt/dbus/lib/libdbus-1.3.dylib'
'
-- 
CMake Error at /usr/local/Cellar/cmake/3.5.2/share/cmake/Modules/BundleUtilities.cmake:975 (message):
  error: verify_app failed
Call Stack (most recent call first):
  alethzero/alethzero/cmake_install.cmake:34 (verify_app)
  alethzero/cmake_install.cmake:33 (include)
  cmake_install.cmake:37 (include)



make: *** [install] Error 1
```

I installed version 1.2.8 just fine when that was released and changed nothing in the configuration of the system since then.  `brew doctor` also reports no issues.

**Comment by bobsummerwill** [comment]
Yes, I'm afraid that Homebrew's [rolling release pattern](https://github.com/ethereum/webthree-umbrella/issues/118) has screwed us again here.

CC @chriseth.

This doesn't have the same root cause as https://github.com/ethereum/webthree-umbrella/issues/574.   It is worse.

The other issue was saying that our development bottles were broken (and was temporary), but this one affects the v1.2.9 release permanently.   It worked at the time, but has been broken by the subsequent update of Qt underneath us from 5.6 to 5.6.1.  See https://github.com/ethereum/webthree-umbrella/issues/574.   It is all the hacks for macdeployqt which screw us here.

**Comment by bobsummerwill** [comment]
Hey @CodingAnarchy,

So I think there may be a workaround for you here.   You hit this when UPDATING, but I think you may see a different result if you `brew uninstall` and then `brew install`.    I think and hope that you will just get the rebuilt bottle, which will contain the Qt 5.6.0 dylibs already.

The inconsistency is being tracked as another TODO - https://github.com/ethereum/webthree-umbrella/issues/573

**Comment by CodingAnarchy** [comment]
I'm willing to give it a shot. I'll try tonight and report the result.

**Comment by CodingAnarchy** [comment]
So I started to install it from scratch and the output was this:

```
==> Installing cpp-ethereum from ethereum/ethereum
==> Downloading https://build.ethereum.org/cpp-binaries-data/brew_receipts/cpp-ethereum-1.2.9.el_capitan.bottle.491.tar.gz
==> Downloading from https://builds.ethereum.org/cpp-binaries-data/brew_receipts/cpp-ethereum-1.2.9.el_capitan.bottle.491.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "cpp-ethereum"
Download failed: https://builds.ethereum.org/cpp-binaries-data/brew_receipts/cpp-ethereum-1.2.9.el_capitan.bottle.491.tar.gz
Warning: Bottle installation failed: building from source.
```

`brew install cpp-ethereum --with-gui` was "worse", immediately reinstalling Qt 5.6.1 from scratch despite it already being installed on the system.  I eventually stopped it because I know that will take hours.

**Comment by bobsummerwill** [comment]
Right - so you've hit https://github.com/ethereum/webthree-umbrella/issues/597.   Argh!

Sorry!

And to compound the issues here, our creaking Jenkins setup appeared to die yesterday, which is going to force us into an emergency TravisCI + Appveyor migration.   It was planned anyway, but not in this way.

Apologies ... we'll on the case (though I am on vacation myself).

**Comment by c3works** [comment]
Having the same experience, so glad to see it's been reported.

**Comment by bobsummerwill** [comment]
@CodingAnarchy @c3works ... I don't know why it didn't cross my mind yesterday, but there is an obvious workaround here, which is to use DMG or ZIP file from https://github.com/ethereum/webthree-umbrella/releases/tag/v1.2.9.

The ZIP contains just `eth` and its dependencies.    The DMG contains the GUI applications (AlethZero and Mix).

So I imagine you're now going to tell me that it is `solc` you want, right?  ::-)   @chriseth.

If so, a workaround there would be to use the npm version.   Or you can build from source.

See http://solidity.readthedocs.io/en/latest/installing-solidity.html.

**Comment by zedtux** [comment]
Thank you @bobsummerwill for posting the workarounds. I'll try them.

**Comment by bobsummerwill** [comment]
Adding @zenoid2, who was affected by the Homebrew breaks.

**Comment by elsesiy** [comment]
Same here, even brew uninstall / install again doesn't do the trick...

**Comment by bobsummerwill** [comment]
No, @elsesiy, it won't.    Working on it!

See workarounds above.

**Comment by bobsummerwill** [comment]
This is no longer occurring as written.

We're missing bottles, but that is a separate issue.
