### ISSUE TITLE
I don't know how to use ethereum-console

### ISSUE THREAD

**Issue by AjkThu** [ethereum/webthree-umbrella#604]
I setup cpp- ethereum in ubuntu 14.04 and when I start a private network I don't know how to join the console?
**user@instant-contiki:~/webthree-umbrella/build/webthree/eth$ ./eth --genesis customgenesis.json --private 11000 --port "30301" --datadir "/tmp/ethNetData1"**

Please, help me!

**Comment by chriseth** [comment]
We removed the built-in console. You have to use an external application like https://github.com/ethereum/ethereum-console or `geth attach`.
