### ISSUE TITLE
Debian - Update instructions?

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#608]
See [alternative steps](https://gist.github.com/drandreaskrueger/912e704cfc86fd757277a5fd9bd372d4) from @drandreaskrueger.

CC @programonauta.

But what might be even better than improving the documentation is to actually make those steps executable, and maybe one of you guys would like to have a go at that?

If you look at https://github.com/bobsummerwill/cpp-ethereum/tree/merge_repos, you will see the work-in-progress on the C++ repo reorganization, which includes a switch over to TravisCI and Appveyor, with the "installing dependencies" being infrastructure-as-code, in the form of:
- https://github.com/bobsummerwill/cpp-ethereum/blob/merge_repos/.travis.yml
- https://github.com/bobsummerwill/cpp-ethereum/blob/merge_repos/install_dependencies.sh

At the moment, the Linux branch of `setup.sh` is only working for Ubuntu Trusty, and has no "guards" whatsoever to ensure it doesn't just fail horribly on other distros, but I want to richen that up over time to cover all the distros which we have existing build instructions for.

So our build instructions for all distros which we have "done" should become something as simple as:

```
git clone --recursive https://github.com/ethereum/cpp-ethereum
cd cpp-ethereum
./install_dependencies.sh
mkdir build && cd build
cmake ..
make
```

Would either of you like to have a go at working out what the bash conditionals might look like to add Debian support to [install_dependencies.sh](https://github.com/bobsummerwill/cpp-ethereum/blob/merge_repos/install_dependencies.sh)?     Are there idiomatic ways to distinguish distros, and versions of distros?

**Comment by bobsummerwill** [comment]
BTW - this reformed cpp-ethereum repo removes the GUI apps, which simplifies things, because Qt is not needed.    Solidity is also removed.

When I refresh this branch the next time, we will end up losing the package-system dependency for LLVM, which has been replaced by a build-from-source in CMake in evmjit.

**Comment by programonauta** [comment]
> Would either of you like to have a go at working out what the bash conditionals might look like to add Debian support to install_dependencies.sh? Are there idiomatic ways to distinguish distros, and versions of distros?

I'm not used to write bash for "multi-distros" scripts, but I can try to find out and write one that fit to Debian.

I've just create a new Debian in my Virtual Box and tomorrow and I'll start to make some tests.

I'll register here step by step issues and progress.

**Comment by programonauta** [comment]
> When I refresh this branch the next time, we will end up losing the package-system dependency for LLVM, which has been replaced by a build-from-source in CMake in evmjit.

Please, let me see if I understood: I will not need to worry about LLVM or qt?

**Comment by bobsummerwill** [comment]
Awesome - thanks, @programonauta.

I'm thinking it is likely to be very crude and verbose, ie.

```
if (mac)
    ...
else if (freebsd)
    ....
else if (linux)
    if (debian)
        ...
    else if (ubuntu)
        if (trusty)
            ...
        elseif (xenial)
            ...
        endif
    endif
endif
```

Correct - we would ignore LLVM and Qt, which should make it much simpler.

**Comment by bobsummerwill** [comment]
The main thing I am missing in my understanding is what the best way to do the conditionals is.

ie. what is the canonical way of detecting specific Linux distros and versions?

**Comment by programonauta** [comment]
>  The main thing I am missing in my understanding is what the best way to do the conditionals is.
> ie. what is the canonical way of detecting specific Linux distros and versions?

@panaggio, could you help us on how to detect Linux distros on .sh?

**Comment by ijcoe6ru** [comment]
The platform can be detected like this:

```sh
case $(uname -s) in
	Darwin)
		#Darwin
		case $(sw_vers -productVersion | awk -F . '{printf $1"."$2}') in
			10.11)
				#10.11 El Capitan
				echo "OS X 10.11 El Capitan"
				;;
			10.12)
				#10.12 Sierra
				echo "OS X 10.12 Sierra"
				;;
			*)
				#other Darwin
				echo "other Darwin"
				;;
		esac
		;;
	FreeBSD)
		#FreeBSD
		echo FreeBSD
		;;
	Linux)
		#Linux
		case $(lsb_release -is) in
			Debian)
				#Debian
				echo Debian
				;;
			Ubuntu)
				#Ubuntu
				case $(lsb_release -cs) in
					trusty)
						#trusty
						echo "Ubuntu Trusty"
						;;
					utopic)
						#utopic
						echo "Ubuntu Utopic"
						;;
					vivid)
						#vivid
						echo "Ubuntu Vivid"
						;;
					wily)
						#wili
						echo "Ubuntu Wily"
						;;
					xenial)
						#xenial
						echo "Ubuntu Xenial"
						;;
					yakkety)
						#yakkety
						echo "Ubuntu Yattety"
						;;
					*)
						#other Ubuntu
						echo "other Ubuntu"
						;;
				esac
				;;
			*)
				#other Linux
				echo "other Linux"
				;;
		esac
		;;
	*)
		#other
		echo other
		;;
esac
```

I tested the script on Ubuntu Vivid and other Linux. Somebody test it on other platforms.

**Comment by ijcoe6ru** [comment]
The platform can be detected in this way:

``` sh
case $(uname -s) in
    Darwin)
        #Darwin
        case $(sw_vers -productVersion | awk -F . '{print $1"."$2}') in
            10.11)
                #10.11 El Capitan
                echo "OS X 10.11 El Capitan"
                ;;
            10.12)
                #10.12 Sierra
                echo "OS X 10.12 Sierra"
                ;;
            *)
                #other Darwin
                echo "other Darwin"
                ;;
        esac
        ;;
    FreeBSD)
        #FreeBSD
        echo FreeBSD
        ;;
    Linux)
        #Linux
        case $(lsb_release -is) in
            Debian)
                #Debian
                echo Debian
                ;;
            Ubuntu)
                #Ubuntu
                case $(lsb_release -cs) in
                    trusty)
                        #trusty
                        echo "Ubuntu Trusty"
                        ;;
                    utopic)
                        #utopic
                        echo "Ubuntu Utopic"
                        ;;
                    vivid)
                        #vivid
                        echo "Ubuntu Vivid"
                        ;;
                    wily)
                        #wili
                        echo "Ubuntu Wily"
                        ;;
                    xenial)
                        #xenial
                        echo "Ubuntu Xenial"
                        ;;
                    yakkety)
                        #yakkety
                        echo "Ubuntu Yattety"
                        ;;
                    *)
                        #other Ubuntu
                        echo "other Ubuntu"
                        ;;
                esac
                ;;
            *)
                #other Linux
                echo "other Linux"
                ;;
        esac
        ;;
    *)
        #other
        echo other
        ;;
esac
```

I tested the script on Ubuntu Vivid. Somebody test it on other platforms, please.

**Comment by programonauta** [comment]
Tested on Debian Jessie:

```
$ lsb_release -is
Debian
$ lsb_release -cs
jessie
```

**Comment by bobsummerwill** [comment]
Great!   Thanks, @ijcoe6ru, @programonauta.

See [install_dependencies.sh](https://github.com/bobsummerwill/cpp-ethereum/blob/c86bd722e4c63c4972211ca4c7a01d7eb0fe5bf7/install_dependencies.sh) and [TravisCI](https://travis-ci.org/bobsummerwill/cpp-ethereum/builds) and [Appveyor](https://ci.appveyor.com/project/bobsummerwill/cpp-ethereum/history) automation.

That is currently doing El Capitan, Yosemite and Ubuntu Trusty.   I'm just working to get the tests automation green in TravisCI for this repo-reorg branch.

**Comment by programonauta** [comment]
@bobsummerwill, I tried to fork your repo to work on [install_dependencies.sh](https://github.com/bobsummerwill/cpp-ethereum/blob/merge_repos/install_dependencies.sh), but I only get a repo with `.gitignore`, `.gitmodules` and `README.md`.

How to fork to work on it?

**Comment by bobsummerwill** [comment]
You'll need to switch to the merge_repos branch.

**Comment by programonauta** [comment]
> You'll need to switch to the merge_repos branch.

Thanks @bobsummerwill

**Comment by bobsummerwill** [comment]
So I've created a number of issues, tracking the work on this for various distros.

For Debian, this is now being tracked at https://github.com/ethereum/webthree-umbrella/issues/634, so I will close this issue.
