### ISSUE TITLE
performing null rpc request causes crash (exception thrown)

### ISSUE THREAD

**Issue by subtly** [ethereum/webthree-umbrella#611]
Behavior: Calling eth_getStorageAt with "0x" as address causes crash.
Expected: Invalid input should result in an error log not crash the client.

**Comment by bobsummerwill** [comment]
Thanks for the report, @subtly.

**Comment by winsvega** [comment]
Can't reproduce. 
My request: 
`"{"jsonrpc":"2.0","method":"eth_getStorageAt","params":["0x", "0x", "0"],"id":7}"`
Reply:
`"{"error":{"code":-32602,"message":"INVALID_PARAMS: Invalid method parameters (invalid name and/or ty"... (140)`

what eth node configuration, chain status did you use?

**Comment by bobsummerwill** [comment]
This issue was moved to ethereum/cpp-ethereum#3184
