### ISSUE TITLE
Ubuntu - TravisCI - No output from tests for 10mins

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#619]
See https://travis-ci.org/bobsummerwill/cpp-ethereum/jobs/142383215.

We're seeing this on macOS as well sometimes.

```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
```

**Comment by bobsummerwill** [comment]
Is this actually a hang/crash?   I suspect it might be.
@winsvega mentioned he'd added debug info locally and had seen such a situation when running the mining test.

**Comment by winsvega** [comment]
yes. the last log message was. mining starts...
however next run was green.

**Comment by bobsummerwill** [comment]
Workaround when we see this is to prepend `travis_wait`.   We're doing that now.
