### ISSUE TITLE
Arch Linux - add support in install_deps.sh

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#629]
Hey @LefterisJP and @markusmazurczak,

I have been working on an infrastructure-as-code alternative to these tedious per-distro sets of instructions, which will "go live" when we switch back to cpp-ethereum.

You can see my work-in-progress on that here:
- https://github.com/bobsummerwill/cpp-ethereum/blob/merge_repos/install_deps.sh

I would like to expand this install_deps.sh pattern pattern to cover more distros, so that our ethdocs.org instructions for the distros which we have bothered to do that can be simplified to, with the steps being executed directly and committed in with the code itself.
- git clone --recursive
- ./install_deps.sh
- cmake
- make

So maybe for Arch we can take that approach instead, rather than bothering with written instructions?

Please could help me out and copy https://github.com/bobsummerwill/cpp-ethereum/blob/merge_repos/install_deps.sh locally and run it, does it go into the right conditional?

I suspect it won't, and that we will need to do something fancier, as per http://unix.stackexchange.com/questions/92199/how-can-i-reliably-get-the-operating-systems-name

Thanks!

**Comment by bobsummerwill** [comment]
Closed this.

infrastructure-as-code TODO in https://github.com/ethereum/webthree-umbrella/issues/630.

**Comment by LefterisJP** [comment]
For ArchLinux the "right" way is to have an AUR package, which already exists and is maintained by @5chdn.

The package can be seen [here](https://aur.archlinux.org/packages/ethereum-git/). It's `PKGBUILD` can be adjusted to follow whatever build process you guys decide to have.

**Comment by bobsummerwill** [comment]
That is more idiomatic for Arch than building from source, is it, @LefterisJP?

Aha - I see.   It is the other way around.

So the [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD) on Arch is a set of build-from-source instructions, but combined with the metadata for the dependencies.     So you don't have an `apt-get install` equivalent which you would use within your own "build from source" process, as we have for Ubuntu.

And the "special cases" which we have needed for libsonrpccpp and libcryptopp on Ubuntu are also not required on Arch, because it is a rolling release manager, so those packages are new enough.

Thanks!

**Comment by bobsummerwill** [comment]
Please could do me a favor, @LefterisJP?
Does `lsb_release -is` work for you on your Arch box, and if so, what does it return?

**Comment by LefterisJP** [comment]
Ofc it does. It returns `Arch`.

**Comment by bobsummerwill** [comment]
Actually, looking through our [building from source](http://www.ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/building-from-source/linux-arch.html) steps for Arch, I think that pattern will work just fine on Arch too.

@5chdn - perhaps you can give the updated https://github.com/bobsummerwill/cpp-ethereum/blob/merge_repos/install_deps.sh#L122 a try?   And review?   The Qy packages are intentionally removed.    That will be part of the reformed cpp-ethereum repo, so Arch setup becomes trivial (as above), and the same as on Debian, Ubuntu, macOS, etc.

[Installing binaries](http://www.ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/installing-binaries/linux-arch-aur.html) is a different flow, where I think our existing instructions should probably be simplified to just ... `yaourt -Sb ethereum-git`, @5chdn?  With the middle chunk of the page just removed.

Is `Maintainer: Ordoe ordoe <aur@cach.co>` from https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ethereum you, @5chdn?

**Comment by ijcoe6ru** [comment]
> Please could do me a favor, @LefterisJP?
> Does lsb_release -is work for you on your Arch box, and if so, what does it return?

In Arch Linux, `/usr/bin/lsb_release` is owned by the package lsb-release, which is not included in  base. But `/usr/bin/uname` is owned by the package coreutils, which is included in base. So some Arch Linux installations may not have lsb-relase installed.

**Comment by ijcoe6ru** [comment]
> So you don't have an `apt-get install` equivalent which you would use within your own "build from source" process, as we have for Ubuntu.

You do.

``` sh
pacman -S --needed <packages needed>
```

installs the packages needed, although I would recommend the way it's done in aur.

**Comment by bobsummerwill** [comment]
Yeah, @ijcoe6ru,
I updated it a bit after the initial post.   See https://github.com/bobsummerwill/cpp-ethereum/blob/merge_repos/install_deps.sh#L122.

Thanks for the lsb_release information, so I guess we'll need to do something slightly different for the platform detection to get the working.    What does `uname` show on your distro?   Maybe I can key it off that?

I'm hoping I can keep things pretty simple and not have to start building a real rats-nest of difference checks to cover all the distros.

**Comment by 5chdn** [comment]
@bobsummerwill Hi. [L145](https://github.com/bobsummerwill/cpp-ethereum/blob/merge_repos/install_deps.sh#L145) will cause an issue:

```
 yaourt -Sy libjson-rpc-cpp
```

`yaourt` is not installed by default and not available from repositories. A more generic way would be to check out the AUR git repository and issue an `makepkg`, something like this:

```
git clone https://aur.archlinux.org/libjson-rpc-cpp.git 
cd ./libjson-rpc-cpp/
makepkg
sudo pacman -U libjson-rpc-cpp-0.6.0-1x86_64.pkg.tar.xz
```

But you need to do checks on the version string and/or the file name.

What's the general idea behind that? To provide a oneliner to install all deps?

**Comment by ijcoe6ru** [comment]
The output of `uname` will differ on Arch Linux. For example, the kernel affects it. Someone using Arch Linux may be using his own modified kernel. I think we can use `lsb_release`. People who use Arch Linux should be smart enough to install it if they see the command is not found. Sorry for saying that `lsb_release` may not be available on some Arch Linux installations if it caused confusion.

**Comment by LefterisJP** [comment]
@bobsummerwill Yes please don't rely on yaourt. @5chdn 's suggestion of using makepkg directly is a nice one.

I am still not sure what you are trying to do. ArchLinux is one of these system where users would either:
1. Build it themselves from source
2. Use the package either from official sources or AUR sources. 

And since for (2) we have a package already I don't see what's the use case here.

**Comment by bobsummerwill** [comment]
The use-case here is purely (optional) streamlined process for build-from-source, ie. that this:

```
git clone --recursive https://github.com/ethereum/cpp-ethereum
cd cpp-ethereum
./install_deps.sh
mkdir build && cd build
cmake .. && make
```

... "Just works" on pretty much any Linux or UNIX platform (at least the subset which we have people already build successfully for).

That is a better form of documentation too than our current hand-written and error-prone manual instructions.

It doesn't replace package delivery.   It just makes building from source easier and more uniform.

Thanks for the updates, everybody!

**Comment by bobsummerwill** [comment]
I would like "just works" for all of these ...
http://www.ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/portability.html

**Comment by 5chdn** [comment]
Should be fixed with https://github.com/ethereum/cpp-ethereum/pull/3040

**Comment by bobsummerwill** [comment]
Indeed - thanks, @5chdn!
