### ISSUE TITLE
Wiki: Building on ArchLinux: libcpuid dependency outdated

### ISSUE THREAD

**Issue by tuxayo** [ethereum/webthree-umbrella#63]
https://github.com/ethereum/webthree-umbrella/wiki/Building-on-ArchLinux

libcpuid from official packages doesn't exist anymore, but there is libcpuid-git from AUR.

(I can't confirm it works I have other build issues)

**Comment by LefterisJP** [comment]
Hmm thanks for noticing this. Can you try without it? I just checked in my system and I don't seem to have libcpuid installed and all works fine.

**Comment by tuxayo** [comment]
It works also without libcpuid.
Should it be removed from dependencies of should the dependency be renamed?

**Comment by LefterisJP** [comment]
Hmm I think it's also an optional dependency so it would be best to try with the AUR version and see if there is any problem in building. Then we can just rename the dependency.

**Comment by bobsummerwill** [comment]
@tuxayo Have you tried anything to resolve this since October?

**Comment by tuxayo** [comment]
I just built `ethereum` and `ethereum-git` from the AUR without any issues. And none of them uses `libcpuid`

**Comment by bobsummerwill** [comment]
So do any instructions need updating?
Is there work still to be done here, or are we in a happy place? :-)

**Comment by tuxayo** [comment]
`libcpuid` still doesn't exist from the official packages.

And I could build from source without it. Cmake didn't warned about missing libcpuid so it doesn't even seem to be an optional dependency.

**Comment by bobsummerwill** [comment]
"Cmake didn't warned about missing libcpuid" - Could you share a build log?

Let me show you what this looks like on OS X:

https://gist.github.com/bobsummerwill/7defb2fea901b7991620

```
-- OpenCL headers: /System/Library/Frameworks/OpenCL.framework
-- OpenCL lib   : /System/Library/Frameworks/OpenCL.framework
-- Cpuid headers: CPUID_INCLUDE_DIR-NOTFOUND
-- Cpuid lib   : CPUID_LIBRARY-NOTFOUND
-- test: ClientBase |  --eth_testfile=BlockTests/bcJS_API_Test --eth_threads=1; --eth_testfile=BlockTests/bcJS_API_Test --eth_threads=3; --eth_testfile=BlockTests/bcJS_API_Test --eth_threads=10; --eth_testfile=BlockTests/bcValidBlockTest --eth_threads=1; --eth_testfile=BlockTests/bcValidBlockTest --eth_threads=3; --eth_testfile=BlockTests/bcValidBlockTest      --eth_threads=10
-- test: JsonRpc |  --eth_testfile=BlockTests/bcJS_API_Test; --eth_testfile=BlockTests/bcValidBlockTest
```

So it is only showing up when configuring libethereum, because that's where it is used, not in webthree or libweb3core.

See dependency diagram - https://camo.githubusercontent.com/b8decc1517241cfe67e05d4dce4ca7fd1b27c03d/687474703a2f2f646f75626c657468696e6b636f2e6769746875622e696f2f77656274687265652d756d6272656c6c612d63726f73732f696d616765732f646570656e64656e63795f67726170682e737667.

Are you seeing something different to this on Arch, @tuxayo?   Or maybe you just missed that in the CMake log?

**Comment by bobsummerwill** [comment]
From what I understand, the optional dependencies will just look for those dependencies during the CMake configure stage, and add include paths and linker line entries and add the hash-define if they are found.

REQUIRED dependencies will give you build errors.
OPTIONAL dependencies will use the packages if they are found - which gives the side-effect of slightly masking configuration issues for these package.   Which seems to be what is happening for you now.

"but there is libcpuid-git from AUR." - Should the instructions be updated for this, guys?

**Comment by tuxayo** [comment]
> "Cmake didn't warned about missing libcpuid" - Could you share a build log?

Log for `cmake ..`
http://sebsauvage.net/paste/?64fb3718e38702f0#k2N3Ihup5d4gXJRq7nmRjZsbvbIfOXUl0qhDd5OwD0o=

I understand now, I installed `libcpuid` when it still existed, thats why it found it.

> "but there is libcpuid-git from AUR." - Should the instructions be updated for this, guys?

I could build successfully using `libcpuid-git`

**Comment by bobsummerwill** [comment]
Thanks for the extra detail, @tuxayo.

I've updated https://github.com/ethereum/webthree-umbrella/wiki/Building-on-ArchLinux.

Do you have a working Arch build now, or are you still blocked on other issues which aren't already logged?   Seems there are a few!

**Comment by tuxayo** [comment]
Thanks.

I could build and run the command line. However as I don't know how to use it and I'm waiting for #125 to be able to use the test suite, I'm not sure it really works.
