### ISSUE TITLE
Ubuntu - TravisCI - libethereum test failures

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#635]
This was the first time I saw this issue, but maybe it is more frequent.   Can experiment with that tomorrow:

```
Test Case "sync": 
/home/travis/build/bobsummerwill/cpp-ethereum/libethereum/Block.cpp(556): fatal error in "dev::u256 dev::eth::Block::enact(const dev::eth::VerifiedBlockRef&, const dev::eth::BlockChain&)": std::exception: UncleInChain
```
- https://travis-ci.org/bobsummerwill/cpp-ethereum/jobs/143257687
- https://github.com/bobsummerwill/cpp-ethereum/commit/81fb3ef2d237b2a3bc6abb58b854f0404ecc54aa

**Comment by winsvega** [comment]
this started to happen after chriseth fixed UncleInChain exception in testClient.

**Comment by chriseth** [comment]
The one I fixed was the strange case where the same uncle was mentioned multiple times. We could add an additional check there, whether the uncle is mentioned multiple times in the same block or whether a great uncle is mentioned here.

**Comment by bobsummerwill** [comment]
Another new break, which I've not seen until today (this one was actually El Capitan, not Ubuntu):

```
Test Case "AccountDiff": 
unknown location:0: fatal error: in "libethereum/AccountDiff": signal: SIGSEGV, si_code: 0 (memory access violation at address: 0x00000000)
/Users/travis/build/bobsummerwill/cpp-ethereum/test/libethereum/test/libethereum/AccountDiff.cpp:103: last checkpoint
*** 1 failure is detected in the test module "Master Test Suite"
```

https://travis-ci.org/bobsummerwill/cpp-ethereum/jobs/145497486

**Comment by chriseth** [comment]
If it helps, I have seen it before :-)

**Comment by bobsummerwill** [comment]
We seem to have got to a happy place on these.
I will create new individual issues for anything which pops up from here onwards.
