### ISSUE TITLE
Build: Arch Linux: Error in UPnP.cpp

### ISSUE THREAD

**Issue by tuxayo** [ethereum/webthree-umbrella#64]
I have installed the dependencies listed on the wiki.

[cmake output](http://sebsauvage.net/paste/?b52c3263d578e8fd#k0JXzHdXQaX+mN4r2xTp876BSSbQd8RZYKPIKXPqnNY=)

[build output](http://sebsauvage.net/paste/?6c6d25ba73c285ee#U5efpO7CM0gAwUfilb2qV3U2rsbmHCkunfh7p5E9z4o=)

Is there more data that I can provide?

**Comment by LefterisJP** [comment]
It seems that you have an incompatibe version of  miniupnpc. It's an optional dependency and as such you can actually build without it.

I am also an ArchLinux user and I don't have this library installed so I have no problem building. Can you give me the output of

`pacman -Qi miniupnpc` to see which version you have installed?

**Comment by tuxayo** [comment]
miniupnpc 1.9.20150730-1
I removed it and it built successfully, thanks!

Should miniupnpc be removed from the dependencies in the [wiki page](https://github.com/ethereum/webthree-umbrella/wiki/Building-on-ArchLinux) ?

**Comment by tuxayo** [comment]
Well it builds but running `eth` gives
`error while loading shared libraries: libweb3jsonrpc.so: cannot open shared object file: No such file or directory`
It seem `make install` forget to copy `./build/webthree/libweb3jsonrpc/libweb3jsonrpc.so`

Is this related to this issue or should I open another?

**Comment by LefterisJP** [comment]
This is a totally unrelated issue. But I have not tried make install myself in a long while. I just do make and run the binaries from the build directory. Thanks for reporting that make install discrepancy.

**Comment by LefterisJP** [comment]
As for miniupnpc, we would have to remove it for now, and figure out at which version the breaking change happened. Then make sure that cmake checks for that version and does not accept anything greater than that.

**Comment by chriseth** [comment]
I assume this is fixed. Please reopen if not the case.
