### ISSUE TITLE
deploy_key.enc shouldn't be published?

### ISSUE THREAD

**Issue by EtherTyper** [ethereum/webthree-umbrella#641]
I'm not an RSA master, but I don't think you should have the Travis CI deploy key on the public repo. Time to do some git filter-branching...

**Comment by bobsummerwill** [comment]
Where do you see that, @ethertype?

We have a few of us working on the automation, but both Appveyor and TravisCI have pretty clear instructions on how to encrypt tokens and passwords and keys.   I've just worked through exactly that to my https://github.com/bobsummerwill/cpp-ethereum/blob/merge_repos/appveyor.yml#L60.

Please do point that out, and we'll fix it, if it needs fixing.

**Comment by bobsummerwill** [comment]
You're looking in https://github.com/ethereum/webthree-umbrella/tree/develop/ci/travis-emscripten?

.enc would seem to imply encrypted.   Over to you, @chriseth!

**Comment by EtherTyper** [comment]
@bobsummerwill @chriseth Yep. The emscripten solidity deploy is what I was talking about.

**Comment by chriseth** [comment]
Yes, the key is encrypted. AFAIK this is the only way to perform a push from within travis. Also, travis only provides the decryption keys for non-pull requests so as long as we are careful with merges, there should be no way to retrieve the decryption keys or the encrypted git keys. Please reopen if we missed something.

**Comment by bobsummerwill** [comment]
Did you create your encrypted key using the `travis` command-line Gem, @chriseth?
