### ISSUE TITLE
Windows - Appveyor - Command exited with code -1073740791

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#643]
First time I've seen this one.   Just failing somewhere in the libethereum tests:

https://ci.appveyor.com/project/bobsummerwill/cpp-ethereum/build/1.0.187

```
Test Case "bCopyOperator": 
Command exited with code -1073740791
```

**Comment by winsvega** [comment]
might be same as the bug we have on Travis where it hangs.

**Comment by bobsummerwill** [comment]
At least one of these appears to be some kind of network connectivity issue.

**Comment by bobsummerwill** [comment]
This issue was moved to ethereum/cpp-ethereum#3201
