### ISSUE TITLE
Minimise dependencies for sub-projects

### ISSUE THREAD

**Issue by chriseth** [ethereum/webthree-umbrella#65]
Moved from here: https://github.com/ethereum/solidity/issues/111

I would like to be able to install `solc` with minimal dependencies. When I try this:

``` bash
$ git clone 'https://github.com/ethereum/solidity`
$ mkdir -p solidity/build
$ cd solidity/build
$ cmake ..
```

-then this fails because I need `webthree-helpers`, and that, in turn, depends on many things like `leveldb`, `opencl`, etc...

I don't see why `solc` would require leveldb, since I expect it just compiles source files to asts or bytecode. It would be nice if building only `solc` did not require excessive dependencies.

(BTW, is this the right approach to building `solc`? I had some trouble finding clear documentation, so I filed #110 separately.)

**Comment by debris** [comment]
> I don't see why solc would require leveldb, since I expect it just compiles source files to asts or bytecode. It would be nice if building only solc did not require excessive dependencies.

easiest solution for that, would be moving `libevmcore` and `libevmasm` out of libethereum. Alternatively we could add additional cmake options, but imo, it would add additional complexity.

**Comment by bobsummerwill** [comment]
Ah - here it is!
This is the "webthree-helper introduces lots of global dependencies" issue, right, @chriseth?
Yes it does, and we _should_ fix it.

**Comment by bobsummerwill** [comment]
We're doing this now.    It's covered in other specific issues.   Closing this old one.
