### ISSUE TITLE
Hard-fork caused ethminer crash & crashes upon restart (Windows 10)

### ISSUE THREAD

**Issue by destenson** [ethereum/webthree-umbrella#668]
I woke up this morning to find that my ethminer instance had crashed after the hard fork. Now every time I restart it, it just crashes. I am using a release version so there are no debugging symbols, but here is the stack trace reported by Visual Studio 2015:

![image](https://cloud.githubusercontent.com/assets/282538/16992096/e751962a-4e52-11e6-85f9-1a173cea7b78.png)

**Comment by destenson** [comment]
Recreating the DAG solved the issue.

**Comment by bobsummerwill** [comment]
Glad you're up again!

**Comment by destenson** [comment]
Me too, thanks! :smile:
