### ISSUE TITLE
eth crash in KeyManager::write

### ISSUE THREAD

**Issue by winsvega** [ethereum/webthree-umbrella#676]
https://github.com/ethereum/libethereum/pull/325

**Comment by bobsummerwill** [comment]
Details?  :-)

**Comment by winsvega** [comment]
ome where in a first loop of

void KeyManager::write(SecureFixedHash<16> const& _key, string const& _keysFile) const
{

winsvega
@winsvega
Jul 25 15:28
at line
auto const& ki = m_keyInfo.at(address);
winsvega
@winsvega
Jul 25 15:33

accounts created both from

Addresses KeyManager::accounts() const
{
    set<Address> addresses;
    for (auto const& i: m_keyInfo)
        addresses.insert(i.first);
    for (auto const& key: m_store.keys())
        addresses.insert(m_store.address(key));
    // Remove the zero address if present
    return Addresses{addresses.upper_bound(Address()), addresses.end()};
}

m_store and m_keyInfo
it seems that some m_store addresses does not exist in m_keinfo
here is how this function looked like

Addresses KeyManager::accounts() const
{
    Addresses ret;
    ret.reserve(m_keyInfo.size());
    for (auto const& i: m_keyInfo)
        ret.push_back(i.first);
    return ret;
}

**Comment by winsvega** [comment]
https://github.com/ethereum/libethereum/pull/325
