### ISSUE TITLE
Eth stalled on resync at block 1766190

### ISSUE THREAD

**Issue by agnewpickens** [ethereum/webthree-umbrella#687]
Had been attempting a resync with Eth in 0.8.1 and had issues (AlreadyHaveBlock) where it would stall resync which fixed themselves on relaunch of Eth.  Now my Eth has stalled completely at block 1766190 saying it couldn't find requested block #75e0189d and Bad RLP error.

**Comment by bobsummerwill** [comment]
This issue was moved to ethereum/cpp-ethereum#3212
