### ISSUE TITLE
trace functionality for calls

### ISSUE THREAD

**Issue by chriseth** [ethereum/webthree-umbrella#688]
In order to debug calls without executing them (for example to simulate a transaction and see the effects), an rpc endpoint should be added that allows to trace a transaction (potentially unsigned) that is not broadcast. The interface should look like a combination of `eth_call` and `debug_traceTransaction` and should be in the `debug` namespace.

**Comment by bobsummerwill** [comment]
This issue was moved to ethereum/cpp-ethereum#3213
