### ISSUE TITLE
Readme.md 

### ISSUE THREAD

**Issue by graber65** [ethereum/webthree-umbrella#69]
The "Yet To Do" section on the readme.md still points to https://github.com/ethereum/cpp-ethereum/wiki/TODO, I was unable to find the TODO section on https://github.com/ethereum/webthree-umbrella/wiki.

It looks like the "Yet To Do" list did not get moved in the migration.

**Comment by LianaHus** [comment]
the "yet to do" page has been removed because it was outdated.
