### ISSUE TITLE
Eth - UPNP Device not found

### ISSUE THREAD

**Issue by rodriglporto** [ethereum/webthree-umbrella#70]
Hi

I've been using Eth for around 1.5 months and it was working beautifully... Two days ago I turned off my computer and when I turned it on again, I couldn't connect anymore nor sync the blockchain. I've got a wallet with some ether on and I can't send my ethers to another wallet, since I can't connect to the network anymore...

This is the error I receive when I start eth:

i 00:45:43|p2p UPnP device not found.
Node ID: enode://f156d05db713b7203af1864543ef53cc4e2c28fab0387a40f1d6f9a13ffa5b62fb493d7cd80ea23ca5d27d7e9eeef0c47f923080987132b8c287dd9e1f120c74@0.0.0.0:0

Some more log errors:

N C 00:00:48|p2p Connection refused to node ##5374c1bf… @ tcp://92.51.165.126:30300 ( No connection could be made because the target machine actively refused it )
N C 00:00:49|p2p Connection refused to node ##979b7fa2… @ tcp://5.1.83.226:30303 ( A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond )
N C 00:00:49|p2p Connection refused to node ##7f25d3ea… @ tcp://54.207.93.166:30303 ( A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond )

I'm using Windows 10. Right now I just made a new test. I've setup Geth, created a new account and all and it works fine. So it's something specifically on Eth.

Can you help me?

Cheers!

Rodrigo.

**Comment by rodriglporto** [comment]
Hello Guys! Just to let you know that this issue can be closed. I've downloaded the new version 0.9.92 and I was able to connect to network. Before I was still using the 0.9.41.

After some testing on the new version, Just some comments to support you guys:

AlethOne doesn't seem to be compatible with multiple GPU.
ethminer didn't work with the pool coinotron. I had to continue using the ethminer from version 0.9.41

Aside from this, the new version looks great and awesome job. Keep rocking!

Cheers!

Rodrigo.

**Comment by rodriglporto** [comment]
Guys I would like to reopen this issue. After I installed version 0.9.92 everything was working fine... But once I restarted AlelthZero, the problem came back and I can no download the blockchain...

Any ideas?

Tks!

Rodrigo.

**Comment by rodriglporto** [comment]
Guys I would like to reopen this issue. After I installed version 0.9.92 everything was working fine... But once I restarted AlelthZero, the problem came back and I can no download the blockchain...

Any ideas?

Tks!

Rodrigo.

**Comment by chriseth** [comment]
We fixed some parts in the discovery protocol. Please reopen if it does not work.
