### ISSUE TITLE
VMTests broken by --vmtrace

### ISSUE THREAD

**Issue by gcolvin** [ethereum/webthree-umbrella#704]
$ cd build
$ cmake .. -DVMTRACE=true
$ make
$ cd libethereum/test/
$ ./testeth -t VMTests --vmtrace
Running 15 test cases...
. . .
**\* 25 failures detected in test suite "Master Test Suite"

**Comment by winsvega** [comment]
dublocate of https://github.com/ethereum/webthree-umbrella/issues/703

**Comment by bobsummerwill** [comment]
This issue was moved to ethereum/cpp-ethereum#3216
