### ISSUE TITLE
Just downloaded the village idiot on mac, getting a lot of crashes

### ISSUE THREAD

**Issue by joshterrill** [ethereum/webthree-umbrella#706]
I am trying to learn solidity and downloaded a release at this link as provided by the Ethereum website: https://github.com/ethereum/webthree-umbrella/releases/tag/v1.2.9

I am getting tons of random crashes. It's happened 3 times in the first 10 minutes that I've been using it. Seems to happen every time I press "Rebuild Scenerio". Is there a more stable version, or is there something that I can do to avoid these crashes?

**Comment by bobsummerwill** [comment]
I am afraid that you are out of luck.   Both Mix and AlethZero have been retired, and "The Village Idiot" was the final release for both of them:
- https://github.com/ethereum/alethzero
- https://github.com/ethereum/mix

The reason they were discontinued were the stability issues which you are experiencing.   They both provided to have very high maintenance costs, and were not delivering sufficient value to enough end-users to justify.

Please check out http://solidity.readthedocs.org for alternative Solidity development options.

We have refocused our Mix efforts onto http://github.com/ethereum/remix, but it will be a while before that reaches full functionality.

See https://blog.ethereum.org/2016/05/04/c-dev-update-announcing-remix/.

Best wishes and sorry for your wasted effort :-(

**Comment by joshterrill** [comment]
Ah okay. I didn't even bother to check the README of this repo. I was just clicking links that the main Ethereum site brought me to. Should have checked first. Ethereum.org should also be updated it seems! Thanks for the info.

**Comment by bobsummerwill** [comment]
Thanks for the heads-up.

TODO logged as https://github.com/ethereum/ethereum-org/issues/285.
