### ISSUE TITLE
Windows install link leads to missing page

### ISSUE THREAD

**Issue by zeroactive** [ethereum/webthree-umbrella#709]
Following link is missing:  http://ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/installing-binaries/windows-installer.html

**Comment by bobsummerwill** [comment]
We don't have a Windows installer anymore.

Where is the broken link **to** that URL, please?

**Comment by bobsummerwill** [comment]
Closing this issue here, because all issue tracking has migrated to `cpp-ethereum`, `solidity` and `remix` repos.

Moved to https://github.com/ethereum/cpp-ethereum/issues/3278.
