### ISSUE TITLE
Error 404 for Windows

### ISSUE THREAD

**Issue by ay00b** [ethereum/webthree-umbrella#712]
When I click on windows installer it doesn't work.

**Comment by ghost** [comment]
Got the same

**Comment by chriseth** [comment]
We currently do not have a released version of cpp-ethereum that can sync to the mainnet. If you want to use it, I recommend to either build from source or wait for the metropolis release.

**Comment by axic** [comment]
Please reopen on https://github.com/ethereum/cpp-ethereum if issue presists.
