### ISSUE TITLE
Failur to run MSBuild command

### ISSUE THREAD

**Issue by boyle-suwono** [ethereum/webthree-umbrella#713]
Hi, when I try to make a build in Windows platform, during the generation of Visual Studio project files phase, I got the following error:

**E:\cpp-ethereum\cpp-ethereum\build>cmake -G "Visual Studio 15 2017 Win64" ..
CMake Error at CMakeLists.txt:44 (project):
  Failed to run MSBuild command:

    MSBuild.exe

  to get the value of VCTargetsPath:

-- Configuring incomplete, errors occurred!
See also "E:/cpp-ethereum/cpp-ethereum/build/CMakeFiles/CMakeOutput.log".**

Does anyone know what's going on here? In line 44, it says the version is 1.3.0.

Thanks.

**Comment by xiaoerlaigeid** [comment]
I also have this problem,

**Comment by rajmohan747** [comment]
I am also having same trouble

**Comment by vamosdalian** [comment]
me too

**Comment by reigota** [comment]
o/

**Comment by adityaruplaha** [comment]
same here

**Comment by lolcocks123** [comment]
Did you guys find a solution for this issue?

**Comment by adityaruplaha** [comment]
I found a solution. You first configure everything & then generate. I used the CMake GUI for that.

**Comment by lolcocks123** [comment]
@adityaruplaha Thank you.
I actually reinstalled Visual Studio 2017 and got it working. It seemed to be an issue with paths.

**Comment by adityaruplaha** [comment]
Solution : You have to have cmake & MSBuild in your default path.

CAn we close this issue now ?

**Comment by carolin22** [comment]
i couldn't understand what you are saying @adityaruplaha can you please explain in detail.

**Comment by ghost** [comment]
Solved this by adding the msbuild.exe folder to PATH

**Comment by carolin22** [comment]
Thank you for your reply.. I will try and let you know

**Comment by ryanxiaogit** [comment]
please install the C++ component on visual studio at first.

**Comment by axic** [comment]
Please reopen on https://github.com/ethereum/cpp-ethereum if issue presists.
