### ISSUE TITLE
Clients staying connected despite wrong network id

### ISSUE THREAD

**Issue by hdiedrich** [ethereum/webthree-umbrella#75]
We observe nodes coming and stay connected with our nodes in a private network despite a different network id and genesis blocks:

{
   Caps: "eth/60, eth/61",
   ID: "5374c1bff8df923d3706357eeb4983cd29a63be40a269aaa2296ee5f3b2119a8978c0ed68b8f6fc84aad0df18790417daadf91a4bfbb786a16c9b0a199fa254a",
   LocalAddress: "158.85.109.244:52014",
   Name: "++eth-v1.0.0-1e6e0b75/Gav's Node//.-Linux/g++/JIT",
   RemoteAddress: "92.51.165.126:30300"
}

{
   Caps: "eth/60, eth/61",
   ID: "e58d5e26b3b630496ec640f2530f3e7fa8a8c7dfe79d9e9c4aac80e3730132b869c852d3125204ab35bb1b1951f6f2d40996c1034fd8c5a69b383ee337f02ddc",
   LocalAddress: "158.85.109.244:38146",
   Name: "++eth-v1.0.0-1e6e0b75/Gav's Morden Node//.-Linux/g++/JIT",
   RemoteAddress: "92.51.165.126:30303"
}

Those 2 nodes never go away, but others do come and go.

**Comment by hdiedrich** [comment]
The nodes do not fail the genesis block test. This is the one we use:

{
   "nonce": "0x0000000000000042",
   "difficulty": "0x000000100",
   "alloc": {  },
   "mixhash": "0x0000000000000000000000000000000000000000000000000000000000000000",
   "coinbase": "0x0000000000000000000000000000000000000000",
   "timestamp": "0x00",
   "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
   "gasLimit": "0x5dc6c0"
}

We add one account to it before we start geth and we set the coin base dynamically.

**Comment by chriseth** [comment]
These are the boot nodes, I think you will always stay connected to them. If you provide `--no-bootstrap`, this functionality should be disabled. Please re-open if it does not work.
