### ISSUE TITLE
Build fails with clang: error: unknown argument: '-fstack-protector-strong'

### ISSUE THREAD

**Issue by timnugent** [ethereum/webthree-umbrella#8]
Preqequisites installed as described here: https://github.com/ethereum/cpp-ethereum/wiki/Building-on-MacOS

OS X 10.9.5. 

aquaporin:build tnugent$ make -j 8
[  0%] Building CXX object libethereum/libnatspec/CMakeFiles/natspec.dir/NatspecExpressionEvaluator.cpp.o
[  2%] Building CXX object libethereum/libethash/CMakeFiles/ethash.dir/sha3_cryptopp.cpp.o
[  3%] Built target secp256k1
[  3%] Built target scrypt
clangclang: : errorerror: : unknown argument: '-fstack-protector-strong'unknown argument: '-fstack-protector-strong'

make[2]: **\* [libethereum/libethash/CMakeFiles/ethash.dir/sha3_cryptopp.cpp.o] Error 1
make[2]: **\* [libethereum/libnatspec/CMakeFiles/natspec.dir/NatspecExpressionEvaluator.cpp.o] Error 1
make[1]: **\* [libethereum/libethash/CMakeFiles/ethash.dir/all] Error 2
make[1]: **\* Waiting for unfinished jobs....
make[1]: **\* [libethereum/libnatspec/CMakeFiles/natspec.dir/all] Error 2
[  3%] Built target Sentinel.jsonstub
[  3%] Built target cpp-ethereum_BuildInfo.h
[  3%] Built target dev_BuildInfo.h
[  3%] Built target ethereum_BuildInfo.h
[  3%] Built target minerphonehome.jsonstub
[  3%] Built target minerfarm.jsonstub
make: **\* [all] Error 2

**Comment by debris** [comment]
There are two ways to fix it quickly:
- install new xcode. It contains new version of clang

**or**
- modify this [line](/develop/cmake/EthCompilerSettings.cmake#L23) and remove `-fstack-protector-strong -Wstack-protector`. Although I don't exactly know what will impact will it have on the build.

**Comment by timnugent** [comment]
Updated to Xcode Version 6.2 (6C131e) but that didn't help. My clang version is:

clang --version
Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin13.4.0
Thread model: posix
aquaporin:build tnu

Can you fix the link to the file/line I need to try removing those flags please?

**Comment by debris** [comment]
I think that you need at least xcode 6.3 (llvm 3.6). Here is the list of [xcode/llvm versions](https://en.wikipedia.org/wiki/Xcode). 

> Can you fix the link to the file/line I need to try removing those flags please?

I will check if I can get llvm version there and I make this params optional;

**Comment by timnugent** [comment]
I managed to fix this up updating OSX to 10.10 then updating Xcode to the latest version.
