### ISSUE TITLE
Cannot Retrieveing Dependencies 

### ISSUE THREAD

**Issue by trickybluefox** [ethereum/webthree-umbrella#80]
I put this issue in another section but closed it since it seemed more appropriate to post it here. 

I followed the instructions from the webpage here:
https://github.com/ethereum/webthree-umbrella/wiki/Building-on-Windows

Everything seems okay until I get to this part of the instructions:

1.)    Getting dependencies

cd C:\PATHTO\webthree-helpers\extdep
getstuff.bat
rem #you must run/click this script from .\extdep directory!
rem #Note that the getstuff.bat will not work if you have a path with spaces!

I believe I was successful in downloading the source files and received this in the CMD prompt:

C:\Windows\system32>git clone --recursive https://github.com/ethereum/webthree-u
mbrella.git
Cloning into 'webthree-umbrella'...
remote: Counting objects: 70750, done.
remote: Compressing objects: 100% (64/64), done.
remote: Total 70750 (delta 31), reused 0 (delta 0), pack-reused 70686
Receiving objects: 100% (70750/70750), 28.69 MiB | 3.82 MiB/s, done.
Resolving deltas: 100% (53374/53374), done.
Checking connectivity... done.
Submodule 'alethzero' (https://github.com/ethereum/alethzero) registered for pat
h 'alethzero'
Submodule 'libethereum' (https://github.com/ethereum/libethereum) registered for
path 'libethereum'
Submodule 'libweb3core' (https://github.com/ethereum/libweb3core) registered for
path 'libweb3core'
Submodule 'mix' (https://github.com/ethereum/mix) registered for path 'mix'
Submodule 'solidity' (https://github.com/ethereum/solidity) registered for path
'solidity'
Submodule 'web3.js' (https://github.com/ethereum/web3.js) registered for path 'w
eb3.js'
Submodule 'webthree' (https://github.com/ethereum/webthree) registered for path
'webthree'
Submodule 'webthree-helpers' (https://github.com/ethereum/webthree-helpers) regi
stered for path 'webthree-helpers'
Cloning into 'alethzero'...
remote: Counting objects: 1892, done.
emote: Total 1892 (delta 0), reused 0 (delta 0), pack-reused 1892R
Receiving objects: 98% (1855/1892)
Receiving objects: 100% (1892/1892), 1.12 MiB | 0 bytes/s, done.
Resolving deltas: 100% (1401/1401), done.
Checking connectivity... done.
Submodule path 'alethzero': checked out '22f4dd099bf011aea11e7d17fe4b4c9fe44607d
1'
Cloning into 'libethereum'...
remote: Counting objects: 34553, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 34553 (delta 0), reused 0 (delta 0), pack-reused 34548
Receiving objects: 100% (34553/34553), 10.96 MiB | 3.36 MiB/s, done.
Resolving deltas: 100% (24634/24634), done.
Checking connectivity... done.
Submodule path 'libethereum': checked out 'bd7d51102a2bc785dd037cf745a2a8fb67814
ee7'
Cloning into 'libweb3core'...
remote: Counting objects: 20129, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 20129 (delta 0), reused 0 (delta 0), pack-reused 20122
Receiving objects: 100% (20129/20129), 6.26 MiB | 2.98 MiB/s, done.
Resolving deltas: 100% (11961/11961), done.
Checking connectivity... done.
Submodule path 'libweb3core': checked out 'a95f5622efc9715334065fb12ebef2eaa2c02
aef'
Cloning into 'mix'...
remote: Counting objects: 8252, done.
remote: Compressing objects: 100% (75/75), done.
remote: Total 8252 (delta 35), reused 0 (delta 0), pack-reused 8177
Receiving objects: 100% (8252/8252), 7.37 MiB | 3.40 MiB/s, done.
Resolving deltas: 100% (6225/6225), done.
Checking connectivity... done.
Submodule path 'mix': checked out 'ae389f5bd1482d2321a9051b4f7b390cf6a190e7'
Cloning into 'solidity'...
remote: Counting objects: 14745, done.
remote: Total 14745 (delta 0), reused 0 (delta 0), pack-reused 14745
Receiving objects: 100% (14745/14745), 6.55 MiB | 3.08 MiB/s, done.
Resolving deltas: 100% (9988/9988), done.
Checking connectivity... done.
Submodule path 'solidity': checked out '7a9f8d9f35ee3791ba4e41bcee224fbffa9d2b28
'
Cloning into 'web3.js'...
remote: Counting objects: 9086, done.
remote: Compressing objects: 100% (84/84), done.
remote: Total 9086 (delta 43), reused 0 (delta 0), pack-reused 9001
Receiving objects: 100% (9086/9086), 15.92 MiB | 3.54 MiB/s, done.
Resolving deltas: 100% (6682/6682), done.
Checking connectivity... done.
Submodule path 'web3.js': checked out '6df0cd6e2e815c7dc06c077ff7acdea020f1e13f'

Cloning into 'webthree'...
remote: Counting objects: 1889, done.
emote: Total 1889 (delta 0), reused 0 (delta 0), pack-reused 1889R
Rs: 95% (1795/1889)
Receiving objects: 100% (1889/1889), 419.10 KiB | 0 bytes/s, done.
Resolving deltas: 100% (1251/1251), done.
Checking connectivity... done.
Submodule path 'webthree': checked out 'de2bfa371e5867e52c47d879cdd7965f3469d9a6
'
Cloning into 'webthree-helpers'...
remote: Counting objects: 1296, done.
remote: Compressing objects: 100% (9/9), done.
Receiving objects: emote: Total 1296 (delta 2), reused 0 (delta 0), pack-reused
Receiving objects: 96% (1245
Receiving objects: 100% (1296/1296), 413.06 KiB | 0 bytes/s, done.
Resolving deltas: 100% (749/749), done.
Checking connectivity... done.
Submodule path 'webthree-helpers': checked out '1faa41c425fb5376c766885b2809663b
1be9621c'

(Proceeding to the next step here)

C:\Windows\system32>cd C:\PATHTO\webthree-helpers\extdep
The system cannot find the path specified.

The only thing i can think of is that it wasn't downloaded correctly but i am not sure how to verify the download was successful?

Any help would be appreciated, Thanks.

**Comment by LefterisJP** [comment]
`PATHTO` is a variable. You should replace that with wherever you cloned the repository.

**Comment by trickybluefox** [comment]
Thank you for the response I am past this point and trying to build the solution.  Also thanks for tolerating my retarded grammar "Cannot Retrieveing Dependencies".
