### ISSUE TITLE
does not compile greeter on Windows

### ISSUE THREAD

**Issue by SCBuergel** [ethereum/webthree-umbrella#83]
cross-post from forum (https://forum.ethereum.org/discussion/3837/compiler-error-in-greeter-windows?new=1). When following your steps from the website for compiling the greeter. I get the following error during compilation:

> greeterSource
> "contract mortal { address owner; function mortal() { owner = msg.sender; } func
> tion kill() { if (msg.sender == owner) suicide(owner); } } contract greeter is m
> ortal { string greeting; function greeter(string _greeting) public { greeting =
> _greeting; } function greet() constant returns (string) { return greeting; } }"
> var greeterCompiled = web3.eth.compile.solidity(greeterSource)
> solc: exit status 1
> Exception during compilation: C:\Jenkins\sharedspace\ethrelease\label\windows-sl
> ave\webthree-umbrella\libethereum\libevmasm\ControlFlowGraph.cpp(128): Throw in
> function void __cdecl dev::eth::ControlFlowGraph::resolveNextLinks(void)
> Dynamic exception type: class boost::exception_detail::clone_impl<struct dev::et
> h::OptimizerException>
> std::exception::what: Unknown exception
> [struct dev::tag_comment \* __ptr64] = Successor block not found.
> at InvalidResponse (<anonymous>:-81662:-63)
> at send (<anonymous>:-156322:-63)
> at solidity (<anonymous>:-133322:-63)
> at <anonymous>:1:23

I'd be happy if someone could have a look on this one.

**Comment by chriseth** [comment]
This is https://github.com/ethereum/solidity/issues/82 . Could you please tell us your solidity version there? Thanks!

**Comment by SCBuergel** [comment]
I installed it yesterday from webthree, so should be up to date (if that windows release is up to date):

> solc --version
> solc, the solidity compiler commandline interface
> Version: 0.1.6-d41f8b7c/Release-Windows/msvc/JIT linked to libethereum-

Would still be happy for help?

**Comment by SCBuergel** [comment]
Could you re-open this issue or should I file a new one? I do not see any solution for this one. Would be a pity to exclude the >90% of all PCs from Ethereum even at this stage!

**Comment by chriseth** [comment]
There already is an issue: https://github.com/ethereum/solidity/issues/82 (linked above).
I will work on it as soon as I have access to a windows computer with debugger.
In the meantime, please use https://chriseth.github.io/browser-solidity

**Comment by chriseth** [comment]
Fixed in latest develop.
