### ISSUE TITLE
Incorrect develop package name in "Building on Ubuntu"

### ISSUE THREAD

**Issue by mjroncone** [ethereum/webthree-umbrella#86]
I believe that the package "libjson-rpc-cpp-dev" should be "libjsonrpccpp-dev" in the list:

```
sudo apt-get -y install build-essential git cmake libboost-all-dev libgmp-dev libleveldb-dev libminiupnpc-dev libreadline-dev libncurses5-dev libcurl4-openssl-dev libcryptopp-dev libjson-rpc-cpp-dev libmicrohttpd-dev libjsoncpp-dev libargtable2-dev llvm-3.7-dev libedit-dev mesa-common-dev ocl-icd-libopencl1 opencl-headers libgoogle-perftools-dev qtbase5-dev qt5-default qtdeclarative5-dev libqt5webkit5-dev libqt5webengine5-dev ocl-icd-dev libv8-dev libz-dev
```

The package libjson-rpc-cpp-dev is unable to be found by apt-get, however libjsonrpccpp-dev installed fine and allowed me to continue on with installation.

The page I'm referring to is here: https://github.com/ethereum/webthree-umbrella/wiki/Building-on-Ubuntu and the code is at the end of the section "Install Dependencies".

I would make the change myself but I am both new to Linux and contributing to open source, so would like to be double checked.

**Comment by bobsummerwill** [comment]
Looks like this got addressed.   Thanks for raising it!
https://github.com/ethereum/webthree-umbrella/wiki/Building-on-Ubuntu
