### ISSUE TITLE
Ethminer need connection handling code review

### ISSUE THREAD

**Issue by sammy007** [ethereum/webthree-umbrella#87]
If there is a tiny connection problem happens, ethminer can stuck forever due to

<code>std::exception::what: Exception -32003 : Client connector error: libcurl error: 56</code>

This is just one case.

JSON-RPC problem. Probably couldn't connect. Retrying in 1...
And retrying forever, after ethminer restart everything goes well.

Then "0 H/s = 0 hashes / 0.103 s" for a while, and maybe it will start to mine again, usually it's stuck forever.

**Comment by chriseth** [comment]
We should quickly recheck, but I think this might be fixed.

**Comment by winsvega** [comment]
tested on ubuntu 14_04x64 
started eth
started ethminer
paused eth
resumed eth

ethminer works well after reconnection
