### ISSUE TITLE
Can't find EthPolicy while building on OSX

### ISSUE THREAD

**Issue by ericpeters0n** [ethereum/webthree-umbrella#89]
```
$ LLVM_DIR=/usr/local/Cellar/llvm/3.6.2/share/llvm/cmake cmake ..
```

yields--

```
LLVM_DIR=/usr/local/Cellar/llvm/3.6.2/share/llvm/cmake cmake ..
CMake Error at CMakeLists.txt:13 (include):
  include could not find load file:

    EthPolicy


CMake Error at CMakeLists.txt:14 (eth_policy):
  Unknown CMake command "eth_policy".


-- Configuring incomplete, errors occurred!
```

Any hints?

**Comment by bobsummerwill** [comment]
Did you get past this @ericpeters0n?   I believe I got that at one point when I had done a "git clone" without --recursive, so had some missing files.

Could you try again now, or close the issue, please?   Thanks!

**Comment by ericpeters0n** [comment]
I will try again today. Thank you!

**Comment by bobsummerwill** [comment]
Good stuff :-)   Thank you!

**Comment by bobsummerwill** [comment]
Any joy, @ericpeters0n?
We have poured some more love into https://github.com/ethereum/webthree-umbrella/wiki/Building-on-OS-X again over the last couple of days, and would love another test-pilot :-)

**Comment by bobsummerwill** [comment]
Please can we close this, @chriseth, as per https://github.com/ethereum/webthree-umbrella/issues/117?  Thanks!

**Comment by ericpeters0n** [comment]
Looking at this now, retracing my steps. Sorry for the delay.

On January 11, 2016 at 7:19:34 PM, Bob Summerwill (notifications@github.com) wrote:

Any joy, @ericpeters0n?

**Comment by ericpeters0n** [comment]
"git clone --recursive" got me over this hurdle. Thanks!

(I've still got an Incompatible LLVM version, but that's a different story. ; )

**Comment by bobsummerwill** [comment]
Brilliant - thanks!

You know that the LLVM needs this, right?

```
brew install llvm --HEAD --with-clang
```

Or are you getting your failure purely from doing a:

```
brew install cpp-ethereum
```

Or similar?

**Comment by ericpeters0n** [comment]
Big picture, I'm drilling at 

```
brew install cpp-ethereum
```

By way of the instructions here: 
https://github.com/ethereum/webthree-umbrella/wiki/Building-on-OS-X

Unfortunately

```
LLVM_DIR=/usr/local/Cellar/llvm/HEAD/share/llvm/cmake cmake ..
```

now yeilds

```
...
------------------------------------------------------------------------

CMake Error at libethereum/evmjit/CMakeLists.txt:25 (message):
  Incompatible LLVM version 3.6.2

-- Configuring incomplete, errors occurred!
See also "/Users/ericpeters0n/Development/webthree-umbrella/build/CMakeFiles/CMakeOutput.log".
```

and yet 

```
$ cd ../..
$ brew install llvm --HEAD --with-clang
Warning: llvm-3.6.2 already installed 
```

Suggestions? (And thanks!)

**Comment by bobsummerwill** [comment]
Right.   I think that you will need to do:

```
brew reinstall llvm --HEAD --with-clang
```

Because of the way in which brew works, and is somewhat tied to https://github.com/ethereum/webthree-umbrella/issues/118.

**Comment by bobsummerwill** [comment]
You might also need to do:

```
brew update
brew upgrade
```

Before that

**Comment by bobsummerwill** [comment]
Sadly, past actions with Homebrew **really do affect** the results you get in the present, which is very regrettable.

**Comment by ericpeters0n** [comment]
Indeed. Following suggested steps yeilds

```
...
CMake Error at webthree-helpers/cmake/UseQt.cmake:30 (find_package):
  By not providing "FindQt5DBus.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5DBus", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5DBus"
  (requested version 5.4) with any of the following names:

    Qt5DBusConfig.cmake
    qt5dbus-config.cmake

  Add the installation prefix of "Qt5DBus" to CMAKE_PREFIX_PATH or set
  "Qt5DBus_DIR" to a directory containing one of the above files.  If
  "Qt5DBus" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  webthree-helpers/cmake/EthDependencies.cmake:105 (eth_apply)
  alethzero/libaleth/CMakeLists.txt:22 (eth_use)


-- Configuring incomplete, errors occurred!
```

Which gets me to about 1/3rd of the way down the page here (https://github.com/ethereum/webthree-umbrella/issues/117), I think ;)

**Comment by bobsummerwill** [comment]
Right - that is this one, I believe:

https://github.com/ethereum/webthree-umbrella/wiki/QTBUG-50155-workaround

Though you will likely need to `brew reinstall`, not `brew install`.

This step takes ages, like 4 hours or so, to rebuild Qt with DBUS support.

**Comment by ericpeters0n** [comment]
Yes, `brew reinstall --with-d-bus qt5` got over that hurdle and allowed `LLVM_DIR=/usr/local/Cellar/llvm/HEAD/share/llvm/cmake cmake ..` to succeed.

However, now `make -j6` yeilds

```
...
Generating moc_NameRegNamer.cpp
Generating moc_OtherAccounts.cpp
Generating moc_OurAccounts.cpp
Generating moc_GasPricing.cpp
Generating moc_InjectTransactions.cpp
Generating moc_Transact.cpp
Generating moc_Whisper.cpp
Generating moc_WhisperPeers.cpp
[  7%] Built target AlethZero_automoc
make: *** [all] Error 2
```

**Comment by bobsummerwill** [comment]
Hey @ericpeters0n.    The error will be higher up the log file (which might be getting truncated out of this summary e-mail).     There will be a link to the full log file, which is probably something like ~/Library/Log/Homebrew/ccp-ethereum/02.make.

Please could you get a full log, and make a Github Gist of it and share a link to that here?   https://gist.github.com

Or pastebin, or pastie, or any other service you like :-)     Thanks!

**Comment by ericpeters0n** [comment]
Sure enough @bobsummerwill! (And thanks for your continued help!)

Gist of console log here: https://gist.github.com/ericpeters0n/9fec27470e93fa8411e5

The fun starts with

```
[  6%] Building CXX object libethereum/evmjit/libevmjit/CMakeFiles/evmjit.dir/Compiler.cpp.o
/Users/ericpeters0n/Development/webthree-umbrella/libethereum/evmjit/libevmjit/Arith256.cpp:86:14: error: no member named 'getNextNode' in 'llvm::Argument'
        auto y = x->getNextNode();
```

**Comment by bobsummerwill** [comment]
Did you do:

```
brew reinstall llvm --HEAD --with-clang
```

As per the earlier message?    What you are seeing looks like a "too old LLVM" problem.

**Comment by ericpeters0n** [comment]
Yes, I did. :(

**Comment by bobsummerwill** [comment]
So ... I just did a fresh clone and OS X build, at this commit:

https://github.com/ethereum/webthree-umbrella/commit/b315d820a38a0d04064e23885b05524b9ca4e702

And am getting the same issue.    I'll keep digging.    Might be environmental.   Might be "bad commit" in one of the sub-modules.
- @chriseth @LefterisJP.

**Comment by bobsummerwill** [comment]
Add @winsvega 
See also boost changes around https://github.com/ethereum/libethereum/pull/143 and https://github.com/ethereum/webthree-umbrella/issues/108.

The odd thing is that I cannot find llvm::Argument::getnextnode() anywhere, or work out if it is something which used to be there and has been removed, or vica-versa.

**Comment by bobsummerwill** [comment]
OK - forget it :-)

So @ericpeters0n.   Doing this made it go away for me, though I'm not quite sure in what way I got into a broken state again, but please try this ...

```
brew uninstall --force llvm
rm -rf /Library/Caches/Homebrew/llvm--git
brew reinstall llvm --HEAD --with-clang
```

And then whatever you're trying to install, ie.

```
brew reinstall cpp-ethereum
```

**Comment by ericpeters0n** [comment]
Alas the `brew reinstall llvm --HEAD --with-clang` step yields:

```
[ 71%] Built target LLVMCodeGen
make: *** [all] Error 2
couldn't understand kern.osversion `14.5.0'

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
llvm 3.7.1 https://github.com/Homebrew/homebrew/pull/47824
LLVM and libc++abi https://github.com/Homebrew/homebrew/issues/47858
llvm: Add option to build Llvm dylib https://github.com/Homebrew/homebrew/pull/45690
Should clang-omp be merged into the main llvm formula? https://github.com/Homebrew/homebrew/issues/47857
llvm 3.6.2 Link to Homebrew Python. https://github.com/Homebrew/homebrew/pull/45787
More Options for LLVM's Homebrew Formula to Match Its CMake Options? https://github.com/Homebrew/homebrew/issues/47269
llvm formula's clang++ fails with -L $(brew --prefix llvm)/lib https://github.com/Homebrew/homebrew/issues/42957
MacOS.(gcc|clang|llvm)_version can return nil https://github.com/Homebrew/homebrew/issues/18781
```

**Comment by bobsummerwill** [comment]
Could you share a full log please, as a Github gist, pastie or whatever?   Thanks!

**Comment by bobsummerwill** [comment]
Maybe try, as per http://stackoverflow.com/questions/26486163/gcc-4-9-1-in-os-x-yosemite-gcc-warning-couldn-t-understand-kern-osversion-1:

```
xcode-select --install 
```

**Comment by ericpeters0n** [comment]
Here's the full makefile log from `brew reinstall llvm --HEAD --with-clang`: https://gist.github.com/ericpeters0n/496654b55dd7df6a4652

**Comment by ericpeters0n** [comment]
(Xcode command line tools are already installed.)

**Comment by ericpeters0n** [comment]
Fyi, setting env `MACOSX_DEPLOYMENT_TARGET=10.9` (I'm on Yosemite 10.10) per that StackOverflow thread got the llvm-clang install to succeed...

 --but `make -j6` subsequently complains  "(various libs) was built for newer OSX version (10.10) than being linked (10.9)"

...which isn't really surprising.

**Comment by bobsummerwill** [comment]
What is your GCC version, @ericpeters0n?
From that same Stackoverflow thread, somebody else suggested brew upgrade gcc.

Have you done this recently?

```
 brew update
 brew upgrade
```

**Comment by ericpeters0n** [comment]
```
$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.0 (clang-700.1.76)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
```

Also, brew was update/upgraded ~48 hours ago, per your suggestion.

**Comment by bobsummerwill** [comment]
Hmm.   Mine is similar.    Observation - neither of us are actually using GCC here.   Instead, it is a link or wrapper over clang.     I know that Apple dropped GCC for Clang a few years back, but it is also possible to install GCC via Homebrew, which might change what "gcc" on the command-line resolves to, though that is probably the wrong thing to do!

```
Bobs-MacBook-Air:build bob$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.2.0
Thread model: posix
```

See http://stackoverflow.com/questions/25352389/difference-between-macosx-deployment-target-and-mmacosx-version-min-compiler-op

**Comment by bobsummerwill** [comment]
Did you original error message have the "gcc: warning" bit on the front?

```
gcc: warning: couldn’t understand kern.osversion ‘14.0.0'
```

For whatever reason it just looks like you have somehow got a "bad" combination of versions on there, either of GCC, or LLVM, or whatever.

There are a few more suggestions in http://stackoverflow.com/questions/26486163/gcc-4-9-1-in-os-x-yosemite-gcc-warning-couldn-t-understand-kern-osversion-1: that you could try, eh?

**Comment by ericpeters0n** [comment]
@bobsummerwill Yup, working through those options... will keep you posted. :)

**Comment by bobsummerwill** [comment]
See also https://gist.github.com/yamaya/2924292.

**Comment by ericpeters0n** [comment]
Actually @bobsummerwill, the original error didn't have the 'gcc: warning' bit on the front, just
`couldn't understand kern.osversion `14.5.0'`

Does that change what we're looking for?

**Comment by bobsummerwill** [comment]
Maybe?  :-)    Not sure.

@caktux Might have some OSX-foo to add here ... ?

**Comment by bobsummerwill** [comment]
Any progress, @ericpeters0n?

**Comment by michaelmarks** [comment]
@bobsummerwill I followed the [instructions](https://github.com/ethereum/webthree-umbrella/wiki/Building-on-OS-X), but cmake was installed in `/usr/local/Cellar/llvm/HEAD/lib/cmake` rather than`/usr/local/Cellar/llvm/HEAD/share/llvm/cmake`, so the build command for me was`LLVM_DIR=/usr/local/Cellar/llvm/HEAD/lib/cmake cmake ..` There was no cmake binary inside of `llvm/HEAD/share`.

**Comment by bobsummerwill** [comment]
Thanks for the info, @michaelmarks!    Just doing a fresh LLVM install myself to verify I'm seeing the same as you.   I guess they changed the path :-)

Please could you confirm that you were able to build successfully after correcting the path?   Were you just doing a build-from-source on the command line with CMake/make?  Thanks.

**Comment by michaelmarks** [comment]
@bobsummerwill, correct a build from sources and make completed 100% successfully. During make install, I ran into a [qt verify_app issue](https://github.com/ethereum/webthree-umbrella/wiki/QTBUG-50155-workaround), but I didn't try to resolve it since I'm only interested in the CLI clients.

You may want to add a warning about disk space. It appeared the 3 hour long qt build might have needed 20+GB of temporary space. I didn't want to build qt again to verify the issue however

**Comment by bobsummerwill** [comment]
Yeah - I hear you on the disk space.    I actually ran out a couple of times myself, infuriatingly.
I'll add a note to the instructions when I finish working through a couple of other open OS X issues which people have raised, and I am not convinced are resolved.     Like that verify_app issue, which I got too.

See https://github.com/ethereum/homebrew-ethereum/issues/52.

**Comment by bobsummerwill** [comment]
@michaelmarks After doing a fresh LLVM install, I got the same path as you, and have updated the instructions accordingly.    Interestingly enough, I was looking at using LLVM 3.7.1 rather than HEAD a few days back, and one of the issues there was that I couldn't find the CMake files - seemingly because of this exact same change of directory.    So it might be possible for us to lock into that LLVM 3.7.1 version after all.

**Comment by bobsummerwill** [comment]
verify_app still to chase down - https://github.com/ethereum/homebrew-ethereum/issues/52.

**Comment by bobsummerwill** [comment]
Hey @ericpeters0n!
So I made a fix a while back to resolve the LLVM getNextNode() issue.
This ticket is now a horrific spawling multi-bug, and I'm just going to close it.

If you're still unable to do success following https://github.com/ethereum/webthree-umbrella/wiki/Building-on-OS-X, please could you open a new ticket describing where you get to, and I'll pick it up again.   Thanks!
