### ISSUE TITLE
Latest release just for win / mac, previous ubuntu instructions not working.

### ISSUE THREAD

**Issue by SCBuergel** [ethereum/webthree-umbrella#93]
The latest release (1.0.1) only contains installs for win and mac.

The previous version is linking [instructions](https://gavofyork.gitbooks.io/turboethereum/content/chapter1.html) which give an error in step three:

```
$ sudo apt-get update
...
W: Failed to fetch
http://ppa.launchpad.net/ethereum/ethereum/ubuntu/dists/precise/main/source/Sources  404  Not Found
W: Failed to fetch http://ppa.launchpad.net/ethereum/ethereum/ubuntu/dists/precise/main/binary-i386/Packages  404  Not Found
W: Failed to fetch http://ppa.launchpad.net/ethereum/ethereum-qt/ubuntu/dists/precise/main/source/Sources  404  Not Found
W: Failed to fetch http://ppa.launchpad.net/ethereum/ethereum-qt/ubuntu/dists/precise/main/binary-i386/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

and another one:

```
$ sudo apt-get install mix
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package mix
```

Any help would be appreciated.

**Comment by jsbranco** [comment]
Are you copying all lines and pasting them in one go on the terminal?

**Comment by SCBuergel** [comment]
I now tried it on a clean machine and it works when pasting the lines one by one. Are there any reasons why the Ubuntu instructions have been removed from the latest release? As a side-note: it was quite hard to find out that this is the only way to install solidity (or is there actually another way?), maybe spread the word about this repo.

**Comment by bobsummerwill** [comment]
I've added a PPA link to the 1.0.1 release page.   Thanks for the feedback.

That is the way to install solidity on Ubuntu, yes, unless you build your own.    I'll let @chriseth decide if there's more he'd like to do on that side-note.
