### ISSUE TITLE
AlethOne crashes when choosing private chain (1.1.0 and 1.0.0, MacOSX)

### ISSUE THREAD

**Issue by maximilliangeorge** [ethereum/webthree-umbrella#96]
After choosing "Use private chain" the program freezes and won't start again without a reinstall. This happens both in version 1.1.0 and 1.0.0.

**Comment by bobsummerwill** [comment]
Hey @maximilliangeorge!
I assume that you mean 1.0.0 and 1.0.1?   Was that installing from the DMGs?
Please could you detail exactly what you are doing when it fails?

Please could you try a Homebrew install and/or a build from source, and report back?   Thanks!

See https://github.com/ethereum/webthree-umbrella/wiki/Building-on-OS-X

**Comment by bobsummerwill** [comment]
No reply from @maximilliangeorge.   Closing.   Bugs against old builds.
