### ISSUE TITLE
Unikernel?

### ISSUE THREAD

**Issue by AndreasS2501** [ethereum/webthree-umbrella#98]
Ethereum puts a lot of effort into beeing made available on many plattforms, yet of course it is difficult to support all plattform in detail.

One alternative approach would be to make the current implemenations run as a standalone unikernel which runs only on a hypervisor:

https://en.wikipedia.org/wiki/Unikernel

There are unikernel for Go (Clive) and cpp (OSv/Rumprun)

Has the ethereum team considered/discussed the advantages/disadvantages of this approach?

**Comment by bobsummerwill** [comment]
@AndreasS2501 Have you seen ...

```
http://unikernel.org/blog/2015/includeos-is-now-open-source/
```

This line is particularly delightful ...

```
"We want to make Node++"
```

I'm looking at porting eth to a LOT of platforms (see http://github.com/doublethinkco/webthree-umbrella-cross), and I imagine that a Unikernel could be a great fit for embedded devices, router/ Ethereum nodes, etc.    Like slockit's Ethereum Computer, perhaps.

I imagine this thought has crossed ETHDEV people's minds too, but will be way down the priority list.

**Comment by bobsummerwill** [comment]
So yeah ... this is a thought, but given the recent de-resourcing of the C++ team it isn't something which is going to happen in any kind of hurry, so I'll close this issue.
