### ISSUE TITLE
eth: web3.admin.getContractInfo does not exist

### ISSUE THREAD

**Issue by colm** [ethereum/webthree-umbrella#99]
I assume there is supposed to be cross over between geth and eth. When I run create a contract and try to get teh getcontract info from address in eth it gives me an error. 

web3.admin.getContractInfo I get an error var info = web3.admin.getContractInfo(address)

(shell):1: TypeError: Object #<Object> has no method 'getContractInfo'
var info = web3.admin.getContractInfo(address)
                      ^
TypeError: Object #<Object> has no method 'getContractInfo'
    at (shell):1:23
Error: Uncaught TypeError: Object #<Object> has no method 'getContractInfo'

[multip.txt](https://github.com/ethereum/webthree-umbrella/files/60192/multip.txt)

**Comment by Nigui** [comment]
Same error on geth 1.4.0-unstable. 
Is it caused by the unstable version ? Does it occur in the previous version ?

**Comment by chriseth** [comment]
I am pretty sure the contract metadata interface will be deprecated in the future and the functionality will move to mist. This is not implemented in eth and will not for the time being.
